Darknet: shortcut_layer.h File Reference
shortcut_layer.h File Reference
#include "layer.h"
#include "network.h"
Functions
layer make_shortcut_layer (int batch, int index, int w, int h, int c, int w2, int h2, int c2)
void forward_shortcut_layer (const layer l, network net)
void backward_shortcut_layer (const layer l, network net)
Function Documentation
backward_shortcut_layer()
void backward_shortcut_layer (const layer l, network net)
Definition at line 46 of file shortcut_layer.c.
References layer::activation, axpy_cpu(), layer::batch, layer::c, network::delta, layer::delta, gradient_array(), layer::h, layer::index, network::layers, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, shortcut_cpu(), and layer::w.
Referenced by make_shortcut_layer().
 {
     gradient_array(l.output, l.outputs*l.batch, l.activation, l.delta);
     axpy_cpu(l.outputs*l.batch, 1, l.delta, 1, net.delta, 1);
     shortcut_cpu(l.batch, l.out_w, l.out_h, l.out_c, l.delta, l.w, l.h, l.c, net.layers[l.index].delta);
 }
forward_shortcut_layer()
void forward_shortcut_layer (const layer l, network net)
Definition at line 39 of file shortcut_layer.c.
References activate_array(), layer::activation, layer::batch, layer::c, copy_cpu(), layer::h, layer::index, network::input, network::layers, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, shortcut_cpu(), and layer::w.
Referenced by make_shortcut_layer().
 {
     copy_cpu(l.outputs*l.batch, net.input, 1, l.output, 1);
     shortcut_cpu(l.batch, l.w, l.h, l.c, net.layers[l.index].output, l.out_w, l.out_h, l.out_c, l.output);
     activate_array(l.output, l.outputs*l.batch, l.activation);
 }
make_shortcut_layer()
layer make_shortcut_layer (int batch, int index, int w, int h, int c, int w2, int h2, int c2)
Definition at line 7 of file shortcut_layer.c.
References layer::backward, layer::backward_gpu, backward_shortcut_layer(), layer::batch, layer::c, layer::delta, layer::forward, layer::forward_gpu, forward_shortcut_layer(), layer::h, layer::index, layer::inputs, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, SHORTCUT, layer::type, and layer::w.
Referenced by parse_shortcut().
 {
     fprintf(stderr,"Shortcut Layer: %d\n", index);
     layer l = {0};
     l.type = SHORTCUT;
     l.batch = batch;
     l.w = w2;
     l.h = h2;
     l.c = c2;
     l.out_w = w;
     l.out_h = h;
     l.out_c = c;
     l.outputs = w*h*c;
     l.inputs = l.outputs;
     l.index = index;
     l.delta =  calloc(l.outputs*batch, sizeof(float));
     l.output = calloc(l.outputs*batch, sizeof(float));;
     l.forward = forward_shortcut_layer;
     l.backward = backward_shortcut_layer;
     #ifdef GPU
     l.forward_gpu = forward_shortcut_layer_gpu;
     l.backward_gpu = backward_shortcut_layer_gpu;
     l.delta_gpu =  cuda_make_array(l.delta, l.outputs*batch);
     l.output_gpu = cuda_make_array(l.output, l.outputs*batch);
     #endif
     return l;
 }