Darknet: captcha.c File Reference
captcha.c File Reference
#include "network.h"
#include "utils.h"
#include "parser.h"
Functions
void fix_data_captcha (data d, int mask)
void train_captcha (char *cfgfile, char *weightfile)
void test_captcha (char *cfgfile, char *weightfile, char *filename)
void valid_captcha (char *cfgfile, char *weightfile, char *filename)
void run_captcha (int argc, char **argv)
Function Documentation
fix_data_captcha()
void fix_data_captcha (data d, int mask)
Definition at line 5 of file captcha.c.
References matrix::cols, matrix::rows, SECRET_NUM, matrix::vals, and data::y.
Referenced by train_captcha().
 {
     matrix labels = d.y;
     int i, j;
     for(i = 0; i < d.y.rows; ++i){
         for(j = 0; j < d.y.cols; j += 2){
             if (mask){
                 if(!labels.vals[i][j]){
                     labels.vals[i][j] = SECRET_NUM;
                     labels.vals[i][j+1] = SECRET_NUM;
                 }else if(labels.vals[i][j+1]){
                     labels.vals[i][j] = 0;
                 }
             } else{
                 if (labels.vals[i][j]) {
                     labels.vals[i][j+1] = 0;
                 } else {
                     labels.vals[i][j+1] = 1;
                 }
             }
         }
     }
 }
run_captcha()
void run_captcha (int argc, char ** argv)
Definition at line 346 of file captcha.c.
References test_captcha(), train_captcha(), and valid_captcha().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5]: 0;
     if(0==strcmp(argv[2], "train")) train_captcha(cfg, weights);
     else if(0==strcmp(argv[2], "test")) test_captcha(cfg, weights, filename);
     else if(0==strcmp(argv[2], "valid")) valid_captcha(cfg, weights, filename);
     //if(0==strcmp(argv[2], "test")) test_captcha(cfg, weights);
     //else if(0==strcmp(argv[2], "encode")) encode_captcha(cfg, weights);
     //else if(0==strcmp(argv[2], "decode")) decode_captcha(cfg, weights);
     //else if(0==strcmp(argv[2], "valid")) validate_captcha(cfg, weights);
 }
test_captcha()
void test_captcha (char * cfgfile, char * weightfile, char * filename)
Definition at line 98 of file captcha.c.
References image::data, free_image(), get_labels(), network::h, load_image_color(), load_weights(), network_predict(), parse_network_cfg(), set_batch_network(), top_predictions(), and network::w.
Referenced by run_captcha().
 {
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     int i = 0;
     char **names = get_labels("/data/captcha/reimgs.labels.list");
     char buff[256];
     char *input = buff;
     int indexes[26];
     while(1){
         if(filename){
             strncpy(input, filename, 256);
         }else{
             //printf("Enter Image Path: ");
             //fflush(stdout);
             input = fgets(input, 256, stdin);
             if(!input) return;
             strtok(input, "\n");
         }
         image im = load_image_color(input, net.w, net.h);
         float *X = im.data;
         float *predictions = network_predict(net, X);
         top_predictions(net, 26, indexes);
         //printf("%s: Predicted in %f seconds.\n", input, sec(clock()-time));
         for(i = 0; i < 26; ++i){
             int index = indexes[i];
             if(i != 0) printf(", ");
             printf("%s %f", names[index], predictions[index]);
         }
         printf("\n");
         fflush(stdout);
         free_image(im);
         if (filename) break;
     }
 }
train_captcha()
void train_captcha (char * cfgfile, char * weightfile)
Definition at line 29 of file captcha.c.
References basecfg(), load_args::classes, CLASSIFICATION_DATA, load_args::d, network::decay, fix_data_captcha(), free_data(), get_labels(), get_paths(), load_args::h, network::h, load_args::labels, network::learning_rate, list_to_array(), load_data_in_thread(), load_thread(), load_weights(), load_args::m, network::momentum, load_args::n, parse_network_cfg(), load_args::paths, save_weights(), sec(), network::seen, list::size, train_network(), load_args::type, load_args::w, and network::w.
Referenced by run_captcha().
 {
     srand(time(0));
     float avg_loss = -1;
     char *base = basecfg(cfgfile);
     printf("%s\n", base);
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     printf("Learning Rate: %g, Momentum: %g, Decay: %g\n", net.learning_rate, net.momentum, net.decay);
     int imgs = 1024;
     int i = *net.seen/imgs;
     int solved = 1;
     list *plist;
     char **labels = get_labels("/data/captcha/reimgs.labels.list");
     if (solved){
         plist = get_paths("/data/captcha/reimgs.solved.list");
     }else{
         plist = get_paths("/data/captcha/reimgs.raw.list");
     }
     char **paths = (char **)list_to_array(plist);
     printf("%d\n", plist->size);
     clock_t time;
     pthread_t load_thread;
     data train;
     data buffer;
     load_args args = {0};
     args.w = net.w;
     args.h = net.h;
     args.paths = paths;
     args.classes = 26;
     args.n = imgs;
     args.m = plist->size;
     args.labels = labels;
     args.d = &buffer;
     args.type = CLASSIFICATION_DATA;
     load_thread = load_data_in_thread(args);
     while(1){
         ++i;
         time=clock();
         pthread_join(load_thread, 0);
         train = buffer;
         fix_data_captcha(train, solved);
         /*
            image im = float_to_image(256, 256, 3, train.X.vals[114]);
            show_image(im, "training");
            cvWaitKey(0);
          */
         load_thread = load_data_in_thread(args);
         printf("Loaded: %lf seconds\n", sec(clock()-time));
         time=clock();
         float loss = train_network(net, train);
         if(avg_loss == -1) avg_loss = loss;
         avg_loss = avg_loss*.9 + loss*.1;
         printf("%d: %f, %f avg, %lf seconds, %d images\n", i, loss, avg_loss, sec(clock()-time), *net.seen);
         free_data(train);
         if(i%100==0){
             char buff[256];
             sprintf(buff, "/home/pjreddie/imagenet_backup/%s_%d.weights",base, i);
             save_weights(net, buff);
         }
     }
 }
valid_captcha()
void valid_captcha (char * cfgfile, char * weightfile, char * filename)
Definition at line 138 of file captcha.c.
References image::data, free_image(), get_labels(), get_paths(), network::h, list_to_array(), load_image_color(), load_weights(), network_predict(), network::outputs, parse_network_cfg(), set_batch_network(), list::size, and network::w.
Referenced by run_captcha().
 {
     char **labels = get_labels("/data/captcha/reimgs.labels.list");
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     list *plist = get_paths("/data/captcha/reimgs.fg.list");
     char **paths = (char **)list_to_array(plist);
     int N = plist->size;
     int outputs = net.outputs;
     set_batch_network(&net, 1);
     srand(2222222);
     int i, j;
     for(i = 0; i < N; ++i){
         if (i%100 == 0) fprintf(stderr, "%d\n", i);
         image im = load_image_color(paths[i], net.w, net.h);
         float *X = im.data;
         float *predictions = network_predict(net, X);
         //printf("%s: Predicted in %f seconds.\n", input, sec(clock()-time));
         int truth = -1;
         for(j = 0; j < 13; ++j){
             if (strstr(paths[i], labels[j])) truth = j;
         }
         if (truth == -1){
             fprintf(stderr, "bad: %s\n", paths[i]);
             return;
         }
         printf("%d, ", truth);
         for(j = 0; j < outputs; ++j){
             if (j != 0) printf(", ");
             printf("%f", predictions[j]);
         }
         printf("\n");
         fflush(stdout);
         free_image(im);
         if (filename) break;
     }
 }