Darknet: demo.h File Reference
demo.h File Reference
#include "image.h"
Functions
void demo (char *cfgfile, char *weightfile, float thresh, int cam_index, const char *filename, char **names, int classes, int frame_skip, char *prefix, int avg, float hier_thresh, int w, int h, int fps, int fullscreen)
Function Documentation
demo()
void demo (char * cfgfile, char * weightfile, float thresh, int cam_index, const char * filename, char ** names, int classes, int frame_skip, char * prefix, int avg, float hier_thresh, int w, int h, int fps, int fullscreen)
Definition at line 236 of file demo.c.
Referenced by run_coco(), run_detector(), and run_yolo().
 {
     fprintf(stderr, "Demo needs OpenCV for webcam images.\n");
 }