Darknet: gemm.c File Reference
gemm.c File Reference
#include "gemm.h"
#include "utils.h"
#include "cuda.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
Functions
void gemm_bin (int M, int N, int K, float ALPHA, char *A, int lda, float *B, int ldb, float *C, int ldc)
float * random_matrix (int rows, int cols)
void time_random_matrix (int TA, int TB, int m, int k, int n)
void gemm (int TA, int TB, int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float BETA, float *C, int ldc)
void gemm_nn (int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float *C, int ldc)
void gemm_nt (int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float *C, int ldc)
void gemm_tn (int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float *C, int ldc)
void gemm_tt (int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float *C, int ldc)
void gemm_cpu (int TA, int TB, int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float BETA, float *C, int ldc)
Function Documentation
gemm()
void gemm (int TA, int TB, int M, int N, int K, float ALPHA, float * A, int lda, float * B, int ldb, float BETA, float * C, int ldc)
Definition at line 65 of file gemm.c.
References gemm_cpu().
Referenced by backward_connected_layer(), backward_convolutional_layer(), backward_local_layer(), forward_connected_layer(), forward_convolutional_layer(), and forward_local_layer().
 {
     gemm_cpu( TA,  TB,  M, N, K, ALPHA,A,lda, B, ldb,BETA,C,ldc);
 }
gemm_bin()
void gemm_bin (int M, int N, int K, float ALPHA, char * A, int lda, float * B, int ldb, float * C, int ldc)
Definition at line 8 of file gemm.c.
 {
     int i,j,k;
     for(i = 0; i < M; ++i){
         for(k = 0; k < K; ++k){
             char A_PART = A[i*lda+k];
             if(A_PART){
                 for(j = 0; j < N; ++j){
                     C[i*ldc+j] += B[k*ldb+j];
                 }
             } else {
                 for(j = 0; j < N; ++j){
                     C[i*ldc+j] -= B[k*ldb+j];
                 }
             }
         }
     }
 }
gemm_cpu()
void gemm_cpu (int TA, int TB, int M, int N, int K, float ALPHA, float * A, int lda, float * B, int ldb, float BETA, float * C, int ldc)
Definition at line 141 of file gemm.c.
References gemm_cpu(), gemm_nn(), gemm_nt(), gemm_tn(), gemm_tt(), random_matrix(), sec(), and test_gpu_blas().
Referenced by backward_deconvolutional_layer(), forward_deconvolutional_layer(), gemm(), gemm_cpu(), and time_random_matrix().
 {
     //printf("cpu: %d %d %d %d %d %f %d %d %f %d\n",TA, TB, M, N, K, ALPHA, lda, ldb, BETA, ldc);
     int i, j;
     for(i = 0; i < M; ++i){
         for(j = 0; j < N; ++j){
             C[i*ldc + j] *= BETA;
         }
     }
     if(!TA && !TB)
         gemm_nn(M, N, K, ALPHA,A,lda, B, ldb,C,ldc);
     else if(TA && !TB)
         gemm_tn(M, N, K, ALPHA,A,lda, B, ldb,C,ldc);
     else if(!TA && TB)
         gemm_nt(M, N, K, ALPHA,A,lda, B, ldb,C,ldc);
     else
         gemm_tt(M, N, K, ALPHA,A,lda, B, ldb,C,ldc);
 }
gemm_nn()
void gemm_nn (int M, int N, int K, float ALPHA, float * A, int lda, float * B, int ldb, float * C, int ldc)
Definition at line 74 of file gemm.c.
Referenced by gemm_cpu().
 {
     int i,j,k;
     for(i = 0; i < M; ++i){
         for(k = 0; k < K; ++k){
             register float A_PART = ALPHA*A[i*lda+k];
             for(j = 0; j < N; ++j){
                 C[i*ldc+j] += A_PART*B[k*ldb+j];
             }
         }
     }
 }
gemm_nt()
void gemm_nt (int M, int N, int K, float ALPHA, float * A, int lda, float * B, int ldb, float * C, int ldc)
Definition at line 90 of file gemm.c.
Referenced by gemm_cpu().
 {
     int i,j,k;
     for(i = 0; i < M; ++i){
         for(j = 0; j < N; ++j){
             register float sum = 0;
             for(k = 0; k < K; ++k){
                 sum += ALPHA*A[i*lda+k]*B[j*ldb + k];
             }
             C[i*ldc+j] += sum;
         }
     }
 }
gemm_tn()
void gemm_tn (int M, int N, int K, float ALPHA, float * A, int lda, float * B, int ldb, float * C, int ldc)
Definition at line 107 of file gemm.c.
Referenced by gemm_cpu().
 {
     int i,j,k;
     for(i = 0; i < M; ++i){
         for(k = 0; k < K; ++k){
             register float A_PART = ALPHA*A[k*lda+i];
             for(j = 0; j < N; ++j){
                 C[i*ldc+j] += A_PART*B[k*ldb+j];
             }
         }
     }
 }
gemm_tt()
void gemm_tt (int M, int N, int K, float ALPHA, float * A, int lda, float * B, int ldb, float * C, int ldc)
Definition at line 123 of file gemm.c.
Referenced by gemm_cpu().
 {
     int i,j,k;
     for(i = 0; i < M; ++i){
         for(j = 0; j < N; ++j){
             register float sum = 0;
             for(k = 0; k < K; ++k){
                 sum += ALPHA*A[i+k*lda]*B[k+j*ldb];
             }
             C[i*ldc+j] += sum;
         }
     }
 }
random_matrix()
float* random_matrix (int rows, int cols)
Definition at line 30 of file gemm.c.
Referenced by gemm_cpu(), and time_random_matrix().
 {
     int i;
     float *m = calloc(rows*cols, sizeof(float));
     for(i = 0; i < rows*cols; ++i){
         m[i] = (float)rand()/RAND_MAX;
     }
     return m;
 }
time_random_matrix()
void time_random_matrix (int TA, int TB, int m, int k, int n)
Definition at line 40 of file gemm.c.
References gemm_cpu(), and random_matrix().
 {
     float *a;
     if(!TA) a = random_matrix(m,k);
     else a = random_matrix(k,m);
     int lda = (!TA)?k:m;
     float *b;
     if(!TB) b = random_matrix(k,n);
     else b = random_matrix(n,k);
     int ldb = (!TB)?n:k;
     float *c = random_matrix(m,n);
     int i;
     clock_t start = clock(), end;
     for(i = 0; i<10; ++i){
         gemm_cpu(TA,TB,m,n,k,1,a,lda,b,ldb,1,c,n);
     }
     end = clock();
     printf("Matrix Multiplication %dx%d * %dx%d, TA=%d, TB=%d: %lf ms\n",m,k,k,n, TA, TB, (float)(end-start)/CLOCKS_PER_SEC);
     free(a);
     free(b);
     free(c);
 }