Darknet: convolutional_layer.h File Reference
convolutional_layer.h File Reference
#include "cuda.h"
#include "image.h"
#include "activations.h"
#include "layer.h"
#include "network.h"
Typedefs
typedef layer convolutional_layer
Functions
convolutional_layer make_convolutional_layer (int batch, int h, int w, int c, int n, int size, int stride, int padding, ACTIVATION activation, int batch_normalize, int binary, int xnor, int adam)
void denormalize_convolutional_layer (convolutional_layer l)
void resize_convolutional_layer (convolutional_layer *layer, int w, int h)
void forward_convolutional_layer (const convolutional_layer layer, network net)
void update_convolutional_layer (convolutional_layer layer, int batch, float learning_rate, float momentum, float decay)
image * visualize_convolutional_layer (convolutional_layer layer, char *window, image *prev_weights)
void binarize_weights (float *weights, int n, int size, float *binary)
void swap_binary (convolutional_layer *l)
void binarize_weights2 (float *weights, int n, int size, char *binary, float *scales)
void backward_convolutional_layer (convolutional_layer layer, network net)
void add_bias (float *output, float *biases, int batch, int n, int size)
void backward_bias (float *bias_updates, float *delta, int batch, int n, int size)
image * get_weights (convolutional_layer l)
image get_convolutional_image (convolutional_layer layer)
image get_convolutional_delta (convolutional_layer layer)
image get_convolutional_weight (convolutional_layer layer, int i)
int convolutional_out_height (convolutional_layer layer)
int convolutional_out_width (convolutional_layer layer)
void rescale_weights (convolutional_layer l, float scale, float trans)
void rgbgr_weights (convolutional_layer l)
Typedef Documentation
convolutional_layer
typedef layer convolutional_layer
Definition at line 10 of file convolutional_layer.h.
Function Documentation
add_bias()
void add_bias (float * output, float * biases, int batch, int n, int size)
Definition at line 396 of file convolutional_layer.c.
Referenced by forward_batchnorm_layer(), forward_convolutional_layer(), and forward_deconvolutional_layer().
 {
     int i,j,b;
     for(b = 0; b < batch; ++b){
         for(i = 0; i < n; ++i){
             for(j = 0; j < size; ++j){
                 output[(b*n + i)*size + j] += biases[i];
             }
         }
     }
 }
backward_bias()
void backward_bias (float * bias_updates, float * delta, int batch, int n, int size)
Definition at line 420 of file convolutional_layer.c.
 {
     int i,b;
     for(b = 0; b < batch; ++b){
         for(i = 0; i < n; ++i){
             bias_updates[i] += sum_array(delta+size*(i+b*n), size);
         }
     }
 }
backward_convolutional_layer()
void backward_convolutional_layer (convolutional_layer layer, network net)
Definition at line 472 of file convolutional_layer.c.
References layer::activation, backward_batchnorm_layer(), backward_bias(), layer::batch, layer::batch_normalize, layer::bias_updates, layer::c, col2im_cpu(), network::delta, layer::delta, gemm(), gradient_array(), layer::h, im2col_cpu(), network::input, layer::n, layer::out_h, layer::out_w, layer::output, layer::pad, layer::size, layer::stride, layer::w, layer::weight_updates, layer::weights, and network::workspace.
Referenced by backward_crnn_layer(), and make_convolutional_layer().
 {
     int i;
     int m = l.n;
     int n = l.size*l.size*l.c;
     int k = l.out_w*l.out_h;
     gradient_array(l.output, m*k*l.batch, l.activation, l.delta);
     if(l.batch_normalize){
         backward_batchnorm_layer(l, net);
     } else {
         backward_bias(l.bias_updates, l.delta, l.batch, l.n, k);
     }
     for(i = 0; i < l.batch; ++i){
         float *a = l.delta + i*m*k;
         float *b = net.workspace;
         float *c = l.weight_updates;
         float *im = net.input+i*l.c*l.h*l.w;
         im2col_cpu(im, l.c, l.h, l.w,
                 l.size, l.stride, l.pad, b);
         gemm(0,1,m,n,k,1,a,k,b,k,1,c,n);
         if(net.delta){
             a = l.weights;
             b = l.delta + i*m*k;
             c = net.workspace;
             gemm(1,0,n,k,m,1,a,n,b,k,0,c,k);
             col2im_cpu(net.workspace, l.c,  l.h,  l.w,  l.size,  l.stride, l.pad, net.delta+i*l.c*l.h*l.w);
         }
     }
 }
binarize_weights()
void binarize_weights (float * weights, int n, int size, float * binary)
Definition at line 28 of file convolutional_layer.c.
Referenced by forward_convolutional_layer(), and save_convolutional_weights_binary().
 {
     int i, f;
     for(f = 0; f < n; ++f){
         float mean = 0;
         for(i = 0; i < size; ++i){
             mean += fabs(weights[f*size + i]);
         }
         mean = mean / size;
         for(i = 0; i < size; ++i){
             binary[f*size + i] = (weights[f*size + i] > 0) ? mean : -mean;
         }
     }
 }
binarize_weights2()
void binarize_weights2 (float * weights, int n, int size, char * binary, float * scales)
convolutional_out_height()
int convolutional_out_height (convolutional_layer layer)
Definition at line 66 of file convolutional_layer.c.
References layer::h, layer::pad, layer::size, and layer::stride.
Referenced by make_convolutional_layer(), and resize_convolutional_layer().
 {
     return (l.h + 2*l.pad - l.size) / l.stride + 1;
 }
convolutional_out_width()
int convolutional_out_width (convolutional_layer layer)
Definition at line 71 of file convolutional_layer.c.
References layer::pad, layer::size, layer::stride, and layer::w.
Referenced by make_convolutional_layer(), and resize_convolutional_layer().
 {
     return (l.w + 2*l.pad - l.size) / l.stride + 1;
 }
denormalize_convolutional_layer()
void denormalize_convolutional_layer (convolutional_layer l)
Definition at line 315 of file convolutional_layer.c.
References layer::biases, layer::c, layer::n, layer::rolling_mean, layer::rolling_variance, layer::scales, layer::size, and layer::weights.
Referenced by denormalize_net(), and reset_normalize_net().
 {
     int i, j;
     for(i = 0; i < l.n; ++i){
         float scale = l.scales[i]/sqrt(l.rolling_variance[i] + .00001);
         for(j = 0; j < l.c*l.size*l.size; ++j){
             l.weights[i*l.c*l.size*l.size + j] *= scale;
         }
         l.biases[i] -= l.rolling_mean[i] * scale;
         l.scales[i] = 1;
         l.rolling_mean[i] = 0;
         l.rolling_variance[i] = 1;
     }
 }
forward_convolutional_layer()
void forward_convolutional_layer (const convolutional_layer layer, network net)
Definition at line 430 of file convolutional_layer.c.
References activate_array(), layer::activation, add_bias(), layer::batch, layer::batch_normalize, layer::biases, binarize_cpu(), binarize_weights(), layer::binary, layer::binary_input, layer::binary_weights, layer::c, fill_cpu(), forward_batchnorm_layer(), gemm(), layer::h, im2col_cpu(), network::input, layer::n, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, layer::size, layer::stride, swap_binary(), layer::w, layer::weights, network::workspace, and layer::xnor.
Referenced by forward_crnn_layer(), and make_convolutional_layer().
 {
     int out_h = l.out_h;
     int out_w = l.out_w;
     int i;
     fill_cpu(l.outputs*l.batch, 0, l.output, 1);
     if(l.xnor){
         binarize_weights(l.weights, l.n, l.c*l.size*l.size, l.binary_weights);
         swap_binary(&l);
         binarize_cpu(net.input, l.c*l.h*l.w*l.batch, l.binary_input);
         net.input = l.binary_input;
     }
     int m = l.n;
     int k = l.size*l.size*l.c;
     int n = out_h*out_w;
     float *a = l.weights;
     float *b = net.workspace;
     float *c = l.output;
     for(i = 0; i < l.batch; ++i){
         im2col_cpu(net.input, l.c, l.h, l.w,
                 l.size, l.stride, l.pad, b);
         gemm(0,0,m,n,k,1,a,k,b,n,1,c,n);
         c += n*m;
         net.input += l.c*l.h*l.w;
     }
     if(l.batch_normalize){
         forward_batchnorm_layer(l, net);
     } else {
         add_bias(l.output, l.biases, l.batch, l.n, out_h*out_w);
     }
     activate_array(l.output, m*n*l.batch, l.activation);
     if(l.binary || l.xnor) swap_binary(&l);
 }
get_convolutional_delta()
image get_convolutional_delta (convolutional_layer layer)
Definition at line 81 of file convolutional_layer.c.
References layer::delta, float_to_image(), layer::out_c, layer::out_h, and layer::out_w.
 {
     return float_to_image(l.out_w,l.out_h,l.out_c,l.delta);
 }
get_convolutional_image()
image get_convolutional_image (convolutional_layer layer)
Definition at line 76 of file convolutional_layer.c.
References float_to_image(), layer::out_c, layer::out_h, layer::out_w, and layer::output.
Referenced by visualize_convolutional_layer().
 {
     return float_to_image(l.out_w,l.out_h,l.out_c,l.output);
 }
get_convolutional_weight()
image get_convolutional_weight (convolutional_layer layer, int i)
Definition at line 527 of file convolutional_layer.c.
References layer::c, float_to_image(), layer::size, and layer::weights.
Referenced by get_weights(), rescale_weights(), and rgbgr_weights().
 {
     int h = l.size;
     int w = l.size;
     int c = l.c;
     return float_to_image(w,h,c,l.weights+i*h*w*c);
 }
get_weights()
image* get_weights (convolutional_layer l)
Definition at line 559 of file convolutional_layer.c.
References copy_image(), get_convolutional_weight(), layer::n, and normalize_image().
Referenced by mkimg(), and visualize_convolutional_layer().
 {
     image *weights = calloc(l.n, sizeof(image));
     int i;
     for(i = 0; i < l.n; ++i){
         weights[i] = copy_image(get_convolutional_weight(l, i));
         normalize_image(weights[i]);
         /*
         char buff[256];
         sprintf(buff, "filter%d", i);
         save_image(weights[i], buff);
         */
     }
     //error("hey");
     return weights;
 }
make_convolutional_layer()
convolutional_layer make_convolutional_layer (int batch, int h, int w, int c, int n, int size, int stride, int padding, ACTIVATION activation, int batch_normalize, int binary, int xnor, int adam)
Definition at line 162 of file convolutional_layer.c.
References layer::activation, layer::adam, layer::backward, backward_convolutional_layer(), layer::backward_gpu, layer::batch, layer::batch_normalize, layer::bias_m, layer::bias_updates, layer::bias_v, layer::biases, layer::binary, layer::binary_input, layer::binary_weights, layer::c, CONVOLUTIONAL, convolutional_out_height(), convolutional_out_width(), layer::cweights, layer::delta, layer::forward, forward_convolutional_layer(), layer::forward_gpu, get_workspace_size(), gpu_index, layer::h, layer::inputs, layer::m, layer::mean, layer::mean_delta, layer::n, layer::nbiases, layer::nweights, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, rand_normal(), layer::rolling_mean, layer::rolling_variance, layer::scale_m, layer::scale_updates, layer::scale_v, layer::scales, layer::size, layer::stride, layer::type, layer::update, update_convolutional_layer(), layer::update_gpu, layer::v, layer::variance, layer::variance_delta, layer::w, layer::weight_updates, layer::weights, layer::workspace_size, layer::x, layer::x_norm, and layer::xnor.
Referenced by make_crnn_layer(), and parse_convolutional().
 {
     int i;
     convolutional_layer l = {0};
     l.type = CONVOLUTIONAL;
     l.h = h;
     l.w = w;
     l.c = c;
     l.n = n;
     l.binary = binary;
     l.xnor = xnor;
     l.batch = batch;
     l.stride = stride;
     l.size = size;
     l.pad = padding;
     l.batch_normalize = batch_normalize;
     l.weights = calloc(c*n*size*size, sizeof(float));
     l.weight_updates = calloc(c*n*size*size, sizeof(float));
     l.biases = calloc(n, sizeof(float));
     l.bias_updates = calloc(n, sizeof(float));
     l.nweights = c*n*size*size;
     l.nbiases = n;
     // float scale = 1./sqrt(size*size*c);
     float scale = sqrt(2./(size*size*c));
     //scale = .02;
     //for(i = 0; i < c*n*size*size; ++i) l.weights[i] = scale*rand_uniform(-1, 1);
     for(i = 0; i < c*n*size*size; ++i) l.weights[i] = scale*rand_normal();
     int out_w = convolutional_out_width(l);
     int out_h = convolutional_out_height(l);
     l.out_h = out_h;
     l.out_w = out_w;
     l.out_c = n;
     l.outputs = l.out_h * l.out_w * l.out_c;
     l.inputs = l.w * l.h * l.c;
     l.output = calloc(l.batch*l.outputs, sizeof(float));
     l.delta  = calloc(l.batch*l.outputs, sizeof(float));
     l.forward = forward_convolutional_layer;
     l.backward = backward_convolutional_layer;
     l.update = update_convolutional_layer;
     if(binary){
         l.binary_weights = calloc(c*n*size*size, sizeof(float));
         l.cweights = calloc(c*n*size*size, sizeof(char));
         l.scales = calloc(n, sizeof(float));
     }
     if(xnor){
         l.binary_weights = calloc(c*n*size*size, sizeof(float));
         l.binary_input = calloc(l.inputs*l.batch, sizeof(float));
     }
     if(batch_normalize){
         l.scales = calloc(n, sizeof(float));
         l.scale_updates = calloc(n, sizeof(float));
         for(i = 0; i < n; ++i){
             l.scales[i] = 1;
         }
         l.mean = calloc(n, sizeof(float));
         l.variance = calloc(n, sizeof(float));
         l.mean_delta = calloc(n, sizeof(float));
         l.variance_delta = calloc(n, sizeof(float));
         l.rolling_mean = calloc(n, sizeof(float));
         l.rolling_variance = calloc(n, sizeof(float));
         l.x = calloc(l.batch*l.outputs, sizeof(float));
         l.x_norm = calloc(l.batch*l.outputs, sizeof(float));
     }
     if(adam){
         l.adam = 1;
         l.m = calloc(c*n*size*size, sizeof(float));
         l.v = calloc(c*n*size*size, sizeof(float));
         l.bias_m = calloc(n, sizeof(float));
         l.scale_m = calloc(n, sizeof(float));
         l.bias_v = calloc(n, sizeof(float));
         l.scale_v = calloc(n, sizeof(float));
     }
 #ifdef GPU
     l.forward_gpu = forward_convolutional_layer_gpu;
     l.backward_gpu = backward_convolutional_layer_gpu;
     l.update_gpu = update_convolutional_layer_gpu;
     if(gpu_index >= 0){
         if (adam) {
             l.m_gpu = cuda_make_array(l.m, c*n*size*size);
             l.v_gpu = cuda_make_array(l.v, c*n*size*size);
             l.bias_m_gpu = cuda_make_array(l.bias_m, n);
             l.bias_v_gpu = cuda_make_array(l.bias_v, n);
             l.scale_m_gpu = cuda_make_array(l.scale_m, n);
             l.scale_v_gpu = cuda_make_array(l.scale_v, n);
         }
         l.weights_gpu = cuda_make_array(l.weights, c*n*size*size);
         l.weight_updates_gpu = cuda_make_array(l.weight_updates, c*n*size*size);
         l.biases_gpu = cuda_make_array(l.biases, n);
         l.bias_updates_gpu = cuda_make_array(l.bias_updates, n);
         l.delta_gpu = cuda_make_array(l.delta, l.batch*out_h*out_w*n);
         l.output_gpu = cuda_make_array(l.output, l.batch*out_h*out_w*n);
         if(binary){
             l.binary_weights_gpu = cuda_make_array(l.weights, c*n*size*size);
         }
         if(xnor){
             l.binary_weights_gpu = cuda_make_array(l.weights, c*n*size*size);
             l.binary_input_gpu = cuda_make_array(0, l.inputs*l.batch);
         }
         if(batch_normalize){
             l.mean_gpu = cuda_make_array(l.mean, n);
             l.variance_gpu = cuda_make_array(l.variance, n);
             l.rolling_mean_gpu = cuda_make_array(l.mean, n);
             l.rolling_variance_gpu = cuda_make_array(l.variance, n);
             l.mean_delta_gpu = cuda_make_array(l.mean, n);
             l.variance_delta_gpu = cuda_make_array(l.variance, n);
             l.scales_gpu = cuda_make_array(l.scales, n);
             l.scale_updates_gpu = cuda_make_array(l.scale_updates, n);
             l.x_gpu = cuda_make_array(l.output, l.batch*out_h*out_w*n);
             l.x_norm_gpu = cuda_make_array(l.output, l.batch*out_h*out_w*n);
         }
 #ifdef CUDNN
         cudnnCreateTensorDescriptor(&l.normTensorDesc);
         cudnnCreateTensorDescriptor(&l.srcTensorDesc);
         cudnnCreateTensorDescriptor(&l.dstTensorDesc);
         cudnnCreateFilterDescriptor(&l.weightDesc);
         cudnnCreateTensorDescriptor(&l.dsrcTensorDesc);
         cudnnCreateTensorDescriptor(&l.ddstTensorDesc);
         cudnnCreateFilterDescriptor(&l.dweightDesc);
         cudnnCreateConvolutionDescriptor(&l.convDesc);
         cudnn_convolutional_setup(&l);
 #endif
     }
 #endif
     l.workspace_size = get_workspace_size(l);
     l.activation = activation;
     fprintf(stderr, "conv  %5d %2d x%2d /%2d  %4d x%4d x%4d   ->  %4d x%4d x%4d\n", n, size, size, stride, w, h, c, l.out_w, l.out_h, l.out_c);
     return l;
 }
rescale_weights()
void rescale_weights (convolutional_layer l, float scale, float trans)
Definition at line 546 of file convolutional_layer.c.
References layer::biases, image::c, image::data, get_convolutional_weight(), image::h, layer::n, scale_image(), sum_array(), and image::w.
Referenced by rescale_net().
 {
     int i;
     for(i = 0; i < l.n; ++i){
         image im = get_convolutional_weight(l, i);
         if (im.c == 3) {
             scale_image(im, scale);
             float sum = sum_array(im.data, im.w*im.h*im.c);
             l.biases[i] += sum*trans;
         }
     }
 }
resize_convolutional_layer()
void resize_convolutional_layer (convolutional_layer * layer, int w, int h)
Definition at line 355 of file convolutional_layer.c.
References layer::batch, layer::batch_normalize, layer::c, convolutional_out_height(), convolutional_out_width(), layer::delta, get_workspace_size(), layer::h, layer::inputs, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::w, layer::workspace_size, layer::x, and layer::x_norm.
Referenced by resize_network().
 {
     l->w = w;
     l->h = h;
     int out_w = convolutional_out_width(*l);
     int out_h = convolutional_out_height(*l);
     l->out_w = out_w;
     l->out_h = out_h;
     l->outputs = l->out_h * l->out_w * l->out_c;
     l->inputs = l->w * l->h * l->c;
     l->output = realloc(l->output, l->batch*l->outputs*sizeof(float));
     l->delta  = realloc(l->delta,  l->batch*l->outputs*sizeof(float));
     if(l->batch_normalize){
         l->x = realloc(l->x, l->batch*l->outputs*sizeof(float));
         l->x_norm  = realloc(l->x_norm, l->batch*l->outputs*sizeof(float));
     }
 #ifdef GPU
     cuda_free(l->delta_gpu);
     cuda_free(l->output_gpu);
     l->delta_gpu =  cuda_make_array(l->delta,  l->batch*l->outputs);
     l->output_gpu = cuda_make_array(l->output, l->batch*l->outputs);
     if(l->batch_normalize){
         cuda_free(l->x_gpu);
         cuda_free(l->x_norm_gpu);
         l->x_gpu = cuda_make_array(l->output, l->batch*l->outputs);
         l->x_norm_gpu = cuda_make_array(l->output, l->batch*l->outputs);
     }
 #ifdef CUDNN
     cudnn_convolutional_setup(l);
 #endif
 #endif
     l->workspace_size = get_workspace_size(*l);
 }
rgbgr_weights()
void rgbgr_weights (convolutional_layer l)
Definition at line 535 of file convolutional_layer.c.
References image::c, get_convolutional_weight(), layer::n, and rgbgr_image().
Referenced by rgbgr_net().
 {
     int i;
     for(i = 0; i < l.n; ++i){
         image im = get_convolutional_weight(l, i);
         if (im.c == 3) {
             rgbgr_image(im);
         }
     }
 }
swap_binary()
void swap_binary (convolutional_layer * l)
Definition at line 15 of file convolutional_layer.c.
References layer::binary_weights, and layer::weights.
Referenced by forward_convolutional_layer().
 {
     float *swap = l->weights;
     l->weights = l->binary_weights;
     l->binary_weights = swap;
 #ifdef GPU
     swap = l->weights_gpu;
     l->weights_gpu = l->binary_weights_gpu;
     l->binary_weights_gpu = swap;
 #endif
 }
update_convolutional_layer()
void update_convolutional_layer (convolutional_layer layer, int batch, float learning_rate, float momentum, float decay)
Definition at line 510 of file convolutional_layer.c.
References axpy_cpu(), layer::bias_updates, layer::biases, layer::c, layer::n, scal_cpu(), layer::scale_updates, layer::scales, layer::size, layer::weight_updates, and layer::weights.
Referenced by make_convolutional_layer(), and update_crnn_layer().
 {
     int size = l.size*l.size*l.c*l.n;
     axpy_cpu(l.n, learning_rate/batch, l.bias_updates, 1, l.biases, 1);
     scal_cpu(l.n, momentum, l.bias_updates, 1);
     if(l.scales){
         axpy_cpu(l.n, learning_rate/batch, l.scale_updates, 1, l.scales, 1);
         scal_cpu(l.n, momentum, l.scale_updates, 1);
     }
     axpy_cpu(size, -decay*batch, l.weights, 1, l.weight_updates, 1);
     axpy_cpu(size, learning_rate/batch, l.weight_updates, 1, l.weights, 1);
     scal_cpu(size, momentum, l.weight_updates, 1);
 }
visualize_convolutional_layer()
image* visualize_convolutional_layer (convolutional_layer layer, char * window, image * prev_weights)
Definition at line 576 of file convolutional_layer.c.
References collapse_image_layers(), free_image(), get_convolutional_image(), get_weights(), layer::n, and show_images().
Referenced by visualize_network().
 {
     image *single_weights = get_weights(l);
     show_images(single_weights, l.n, window);
     image delta = get_convolutional_image(l);
     image dc = collapse_image_layers(delta, 1);
     char buff[256];
     sprintf(buff, "%s: Output", window);
     //show_image(dc, buff);
     //save_image(dc, buff);
     free_image(dc);
     return single_weights;
 }