Darknet: softmax_layer.c File Reference
softmax_layer.c File Reference
#include "softmax_layer.h"
#include "blas.h"
#include "cuda.h"
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
Functions
softmax_layer make_softmax_layer (int batch, int inputs, int groups)
void forward_softmax_layer (const softmax_layer l, network net)
void backward_softmax_layer (const softmax_layer l, network net)
Function Documentation
backward_softmax_layer()
void backward_softmax_layer (const softmax_layer l, network net)
Definition at line 50 of file softmax_layer.c.
References axpy_cpu(), layer::batch, network::delta, layer::delta, tree::group_size, tree::groups, layer::groups, layer::inputs, layer::output, layer::softmax_tree, and layer::temperature.
Referenced by make_softmax_layer().
 {
     axpy_cpu(l.inputs*l.batch, 1, l.delta, 1, net.delta, 1);
 }
forward_softmax_layer()
void forward_softmax_layer (const softmax_layer l, network net)
Definition at line 35 of file softmax_layer.c.
References layer::batch, tree::group_size, tree::groups, layer::groups, network::input, layer::inputs, layer::output, softmax_cpu(), layer::softmax_tree, and layer::temperature.
Referenced by make_softmax_layer().
 {
     if(l.softmax_tree){
         int i;
         int count = 0;
         for (i = 0; i < l.softmax_tree->groups; ++i) {
             int group_size = l.softmax_tree->group_size[i];
             softmax_cpu(net.input + count, group_size, l.batch, l.inputs, 1, 0, 1, l.temperature, l.output + count);
             count += group_size;
         }
     } else {
         softmax_cpu(net.input, l.inputs/l.groups, l.batch, l.inputs, l.groups, l.inputs/l.groups, 1, l.temperature, l.output);
     }
 }
make_softmax_layer()
softmax_layer make_softmax_layer (int batch, int inputs, int groups)
Definition at line 10 of file softmax_layer.c.
References layer::backward, layer::backward_gpu, backward_softmax_layer(), layer::batch, layer::delta, layer::forward, layer::forward_gpu, forward_softmax_layer(), layer::groups, layer::inputs, layer::output, layer::outputs, SOFTMAX, and layer::type.
Referenced by parse_softmax().
 {
     assert(inputs%groups == 0);
     fprintf(stderr, "softmax                                        %4d\n",  inputs);
     softmax_layer l = {0};
     l.type = SOFTMAX;
     l.batch = batch;
     l.groups = groups;
     l.inputs = inputs;
     l.outputs = inputs;
     l.output = calloc(inputs*batch, sizeof(float));
     l.delta = calloc(inputs*batch, sizeof(float));
     l.forward = forward_softmax_layer;
     l.backward = backward_softmax_layer;
     #ifdef GPU
     l.forward_gpu = forward_softmax_layer_gpu;
     l.backward_gpu = backward_softmax_layer_gpu;
     l.output_gpu = cuda_make_array(l.output, inputs*batch);
     l.delta_gpu = cuda_make_array(l.delta, inputs*batch);
     #endif
     return l;
 }