Darknet: blas.h File Reference
blas.h File Reference
Functions
void flatten (float *x, int size, int layers, int batch, int forward)
void pm (int M, int N, float *A)
float * random_matrix (int rows, int cols)
void time_random_matrix (int TA, int TB, int m, int k, int n)
void reorg_cpu (float *x, int w, int h, int c, int batch, int stride, int forward, float *out)
void test_blas ()
void const_cpu (int N, float ALPHA, float *X, int INCX)
void constrain_ongpu (int N, float ALPHA, float *X, int INCX)
void pow_cpu (int N, float ALPHA, float *X, int INCX, float *Y, int INCY)
void mul_cpu (int N, float *X, int INCX, float *Y, int INCY)
void axpy_cpu (int N, float ALPHA, float *X, int INCX, float *Y, int INCY)
void copy_cpu (int N, float *X, int INCX, float *Y, int INCY)
void scal_cpu (int N, float ALPHA, float *X, int INCX)
void fill_cpu (int N, float ALPHA, float *X, int INCX)
float dot_cpu (int N, float *X, int INCX, float *Y, int INCY)
void test_gpu_blas ()
void shortcut_cpu (int batch, int w1, int h1, int c1, float *add, int w2, int h2, int c2, float *out)
void mean_cpu (float *x, int batch, int filters, int spatial, float *mean)
void variance_cpu (float *x, float *mean, int batch, int filters, int spatial, float *variance)
void normalize_cpu (float *x, float *mean, float *variance, int batch, int filters, int spatial)
void scale_bias (float *output, float *scales, int batch, int n, int size)
void backward_scale_cpu (float *x_norm, float *delta, int batch, int n, int size, float *scale_updates)
void mean_delta_cpu (float *delta, float *variance, int batch, int filters, int spatial, float *mean_delta)
void variance_delta_cpu (float *x, float *delta, float *mean, float *variance, int batch, int filters, int spatial, float *variance_delta)
void normalize_delta_cpu (float *x, float *mean, float *variance, float *mean_delta, float *variance_delta, int batch, int filters, int spatial, float *delta)
void smooth_l1_cpu (int n, float *pred, float *truth, float *delta, float *error)
void l2_cpu (int n, float *pred, float *truth, float *delta, float *error)
void l1_cpu (int n, float *pred, float *truth, float *delta, float *error)
void weighted_sum_cpu (float *a, float *b, float *s, int num, float *c)
void softmax (float *input, int n, float temp, int stride, float *output)
void softmax_cpu (float *input, int n, int batch, int batch_offset, int groups, int group_offset, int stride, float temp, float *output)
Function Documentation
axpy_cpu()
void axpy_cpu (int N, float ALPHA, float * X, int INCX, float * Y, int INCY)
Definition at line 146 of file blas.c.
Referenced by average(), backward_connected_layer(), backward_cost_layer(), backward_crnn_layer(), backward_detection_layer(), backward_local_layer(), backward_rnn_layer(), backward_route_layer(), backward_shortcut_layer(), backward_softmax_layer(), forward_batchnorm_layer(), forward_connected_layer(), forward_crnn_layer(), forward_gru_layer(), forward_normalization_layer(), forward_rnn_layer(), optimize_picture(), predict_move(), reconstruct_picture(), test_cifar_multi(), update_connected_layer(), update_convolutional_layer(), update_deconvolutional_layer(), update_local_layer(), validate_classifier_10(), and validate_classifier_multi().
 {
     int i;
     for(i = 0; i < N; ++i) Y[i*INCY] += ALPHA*X[i*INCX];
 }
backward_scale_cpu()
void backward_scale_cpu (float * x_norm, float * delta, int batch, int n, int size, float * scale_updates)
Definition at line 72 of file batchnorm_layer.c.
Referenced by backward_batchnorm_layer(), and backward_connected_layer().
 {
     int i,b,f;
     for(f = 0; f < n; ++f){
         float sum = 0;
         for(b = 0; b < batch; ++b){
             for(i = 0; i < size; ++i){
                 int index = i + size*(f + n*b);
                 sum += delta[index] * x_norm[index];
             }
         }
         scale_updates[f] += sum;
     }
 }
const_cpu()
void const_cpu (int N, float ALPHA, float * X, int INCX)
Definition at line 128 of file blas.c.
Referenced by forward_normalization_layer().
 {
     int i;
     for(i = 0; i < N; ++i) X[i*INCX] = ALPHA;
 }
constrain_ongpu()
void constrain_ongpu (int N, float ALPHA, float * X, int INCX)
Referenced by statistics_connected_layer().
copy_cpu()
void copy_cpu (int N, float * X, int INCX, float * Y, int INCY)
Definition at line 164 of file blas.c.
Referenced by backward_activation_layer(), backward_batchnorm_layer(), backward_crnn_layer(), backward_reorg_layer(), backward_rnn_layer(), copy_matrix(), forward_activation_layer(), forward_batchnorm_layer(), forward_connected_layer(), forward_crnn_layer(), forward_gru_layer(), forward_local_layer(), forward_normalization_layer(), forward_reorg_layer(), forward_rnn_layer(), forward_route_layer(), forward_shortcut_layer(), oneoff(), optimize_picture(), predict_move(), train_colorizer(), train_dcgan(), and validate_detector_flip().
 {
     int i;
     for(i = 0; i < N; ++i) Y[i*INCY] = X[i*INCX];
 }
dot_cpu()
float dot_cpu (int N, float * X, int INCX, float * Y, int INCY)
Definition at line 207 of file blas.c.
 {
     int i;
     float dot = 0;
     for(i = 0; i < N; ++i) dot += X[i*INCX] * Y[i*INCY];
     return dot;
 }
fill_cpu()
void fill_cpu (int N, float ALPHA, float * X, int INCX)
Definition at line 158 of file blas.c.
Referenced by forward_connected_layer(), forward_convolutional_layer(), forward_crnn_layer(), forward_deconvolutional_layer(), forward_gru_layer(), forward_network(), forward_rnn_layer(), load_convolutional_weights(), and tile_images().
 {
     int i;
     for(i = 0; i < N; ++i) X[i*INCX] = ALPHA;
 }
flatten()
void flatten (float * x, int size, int layers, int batch, int forward)
Definition at line 31 of file blas.c.
Referenced by backward_reorg_layer(), forward_reorg_layer(), make_reorg_layer(), and parse_reorg().
 {
     float *swap = calloc(size*layers*batch, sizeof(float));
     int i,c,b;
     for(b = 0; b < batch; ++b){
         for(c = 0; c < layers; ++c){
             for(i = 0; i < size; ++i){
                 int i1 = b*layers*size + c*size + i;
                 int i2 = b*layers*size + i*layers + c;
                 if (forward) swap[i2] = x[i1];
                 else swap[i1] = x[i2];
             }
         }
     }
     memcpy(x, swap, size*layers*batch*sizeof(float));
     free(swap);
 }
l1_cpu()
void l1_cpu (int n, float * pred, float * truth, float * delta, float * error)
Definition at line 187 of file blas.c.
Referenced by forward_cost_layer().
 {
     int i;
     for(i = 0; i < n; ++i){
         float diff = truth[i] - pred[i];
         error[i] = fabs(diff);
         delta[i] = diff > 0 ? 1 : -1;
     }
 }
l2_cpu()
void l2_cpu (int n, float * pred, float * truth, float * delta, float * error)
Definition at line 197 of file blas.c.
Referenced by forward_cost_layer().
 {
     int i;
     for(i = 0; i < n; ++i){
         float diff = truth[i] - pred[i];
         error[i] = diff * diff;
         delta[i] = diff;
     }
 }
mean_cpu()
void mean_cpu (float * x, int batch, int filters, int spatial, float * mean)
Definition at line 83 of file blas.c.
Referenced by forward_batchnorm_layer(), and forward_connected_layer().
 {
     float scale = 1./(batch * spatial);
     int i,j,k;
     for(i = 0; i < filters; ++i){
         mean[i] = 0;
         for(j = 0; j < batch; ++j){
             for(k = 0; k < spatial; ++k){
                 int index = j*filters*spatial + i*spatial + k;
                 mean[i] += x[index];
             }
         }
         mean[i] *= scale;
     }
 }
mean_delta_cpu()
void mean_delta_cpu (float * delta, float * variance, int batch, int filters, int spatial, float * mean_delta)
Definition at line 87 of file batchnorm_layer.c.
Referenced by backward_batchnorm_layer(), and backward_connected_layer().
 {
     int i,j,k;
     for(i = 0; i < filters; ++i){
         mean_delta[i] = 0;
         for (j = 0; j < batch; ++j) {
             for (k = 0; k < spatial; ++k) {
                 int index = j*filters*spatial + i*spatial + k;
                 mean_delta[i] += delta[index];
             }
         }
         mean_delta[i] *= (-1./sqrt(variance[i] + .00001f));
     }
 }
mul_cpu()
void mul_cpu (int N, float * X, int INCX, float * Y, int INCY)
Definition at line 134 of file blas.c.
Referenced by backward_normalization_layer(), forward_gru_layer(), and forward_normalization_layer().
 {
     int i;
     for(i = 0; i < N; ++i) Y[i*INCY] *= X[i*INCX];
 }
normalize_cpu()
void normalize_cpu (float * x, float * mean, float * variance, int batch, int filters, int spatial)
Definition at line 115 of file blas.c.
Referenced by forward_batchnorm_layer(), forward_connected_layer(), and try_classifier().
 {
     int b, f, i;
     for(b = 0; b < batch; ++b){
         for(f = 0; f < filters; ++f){
             for(i = 0; i < spatial; ++i){
                 int index = b*filters*spatial + f*spatial + i;
                 x[index] = (x[index] - mean[f])/(sqrt(variance[f]) + .000001f);
             }
         }
     }
 }
normalize_delta_cpu()
void normalize_delta_cpu (float * x, float * mean, float * variance, float * mean_delta, float * variance_delta, int batch, int filters, int spatial, float * delta)
Definition at line 117 of file batchnorm_layer.c.
Referenced by backward_batchnorm_layer(), and backward_connected_layer().
 {
     int f, j, k;
     for(j = 0; j < batch; ++j){
         for(f = 0; f < filters; ++f){
             for(k = 0; k < spatial; ++k){
                 int index = j*filters*spatial + f*spatial + k;
                 delta[index] = delta[index] * 1./(sqrt(variance[f] + .00001f)) + variance_delta[f] * 2. * (x[index] - mean[f]) / (spatial * batch) + mean_delta[f]/(spatial*batch);
             }
         }
     }
 }
pm()
void pm (int M, int N, float * A)
Definition at line 163 of file utils.c.
 {
     int i,j;
     for(i =0 ; i < M; ++i){
         printf("%d ", i+1);
         for(j = 0; j < N; ++j){
             printf("%2.4f, ", A[i*N+j]);
         }
         printf("\n");
     }
     printf("\n");
 }
pow_cpu()
void pow_cpu (int N, float ALPHA, float * X, int INCX, float * Y, int INCY)
Definition at line 140 of file blas.c.
Referenced by backward_normalization_layer(), and forward_normalization_layer().
 {
     int i;
     for(i = 0; i < N; ++i) Y[i*INCY] = pow(X[i*INCX], ALPHA);
 }
random_matrix()
float* random_matrix (int rows, int cols)
Definition at line 30 of file gemm.c.
Referenced by gemm_cpu(), and time_random_matrix().
 {
     int i;
     float *m = calloc(rows*cols, sizeof(float));
     for(i = 0; i < rows*cols; ++i){
         m[i] = (float)rand()/RAND_MAX;
     }
     return m;
 }
reorg_cpu()
void reorg_cpu (float * x, int w, int h, int c, int batch, int stride, int forward, float * out)
Definition at line 8 of file blas.c.
Referenced by backward_reorg_layer(), and forward_reorg_layer().
 {
     int b,i,j,k;
     int out_c = c/(stride*stride);
     for(b = 0; b < batch; ++b){
         for(k = 0; k < c; ++k){
             for(j = 0; j < h; ++j){
                 for(i = 0; i < w; ++i){
                     int in_index  = i + w*(j + h*(k + c*b));
                     int c2 = k % out_c;
                     int offset = k / out_c;
                     int w2 = i*stride + offset % stride;
                     int h2 = j*stride + offset / stride;
                     int out_index = w2 + w*stride*(h2 + h*stride*(c2 + out_c*b));
                     if(forward) out[out_index] = x[in_index];
                     else out[in_index] = x[out_index];
                 }
             }
         }
     }
 }
scal_cpu()
void scal_cpu (int N, float ALPHA, float * X, int INCX)
Definition at line 152 of file blas.c.
Referenced by average(), forward_batchnorm_layer(), forward_connected_layer(), forward_normalization_layer(), oneoff(), predict_move(), reconstruct_picture(), update_connected_layer(), update_convolutional_layer(), update_deconvolutional_layer(), and update_local_layer().
 {
     int i;
     for(i = 0; i < N; ++i) X[i*INCX] *= ALPHA;
 }
scale_bias()
void scale_bias (float * output, float * scales, int batch, int n, int size)
Definition at line 408 of file convolutional_layer.c.
Referenced by backward_batchnorm_layer(), backward_connected_layer(), forward_batchnorm_layer(), and forward_connected_layer().
 {
     int i,j,b;
     for(b = 0; b < batch; ++b){
         for(i = 0; i < n; ++i){
             for(j = 0; j < size; ++j){
                 output[(b*n + i)*size + j] *= scales[i];
             }
         }
     }
 }
shortcut_cpu()
void shortcut_cpu (int batch, int w1, int h1, int c1, float * add, int w2, int h2, int c2, float * out)
Definition at line 57 of file blas.c.
Referenced by backward_shortcut_layer(), and forward_shortcut_layer().
 {
     int stride = w1/w2;
     int sample = w2/w1;
     assert(stride == h1/h2);
     assert(sample == h2/h1);
     if(stride < 1) stride = 1;
     if(sample < 1) sample = 1;
     int minw = (w1 < w2) ? w1 : w2;
     int minh = (h1 < h2) ? h1 : h2;
     int minc = (c1 < c2) ? c1 : c2;
     int i,j,k,b;
     for(b = 0; b < batch; ++b){
         for(k = 0; k < minc; ++k){
             for(j = 0; j < minh; ++j){
                 for(i = 0; i < minw; ++i){
                     int out_index = i*sample + w2*(j*sample + h2*(k + c2*b));
                     int add_index = i*stride + w1*(j*stride + h1*(k + c1*b));
                     out[out_index] += add[add_index];
                 }
             }
         }
     }
 }
smooth_l1_cpu()
void smooth_l1_cpu (int n, float * pred, float * truth, float * delta, float * error)
Definition at line 170 of file blas.c.
Referenced by forward_cost_layer().
 {
     int i;
     for(i = 0; i < n; ++i){
         float diff = truth[i] - pred[i];
         float abs_val = fabs(diff);
         if(abs_val < 1) {
             error[i] = diff * diff;
             delta[i] = diff;
         }
         else {
             error[i] = 2*abs_val - 1;
             delta[i] = (diff < 0) ? 1 : -1;
         }
     }
 }
softmax()
void softmax (float * input, int n, float temp, int stride, float * output)
Definition at line 215 of file blas.c.
Referenced by forward_detection_layer(), and softmax_cpu().
 {
     int i;
     float sum = 0;
     float largest = -FLT_MAX;
     for(i = 0; i < n; ++i){
         if(input[i*stride] > largest) largest = input[i*stride];
     }
     for(i = 0; i < n; ++i){
         float e = exp(input[i*stride]/temp - largest/temp);
         sum += e;
         output[i*stride] = e;
     }
     for(i = 0; i < n; ++i){
         output[i*stride] /= sum;
     }
 }
softmax_cpu()
void softmax_cpu (float * input, int n, int batch, int batch_offset, int groups, int group_offset, int stride, float temp, float * output)
Definition at line 234 of file blas.c.
References softmax().
Referenced by forward_region_layer(), and forward_softmax_layer().
 {
     int g, b;
     for(b = 0; b < batch; ++b){
         for(g = 0; g < groups; ++g){
             softmax(input + b*batch_offset + g*group_offset, n, temp, stride, output + b*batch_offset + g*group_offset);
         }
     }
 }
test_blas()
void test_blas ()
test_gpu_blas()
void test_gpu_blas ()
Referenced by gemm_cpu().
time_random_matrix()
void time_random_matrix (int TA, int TB, int m, int k, int n)
Definition at line 40 of file gemm.c.
References gemm_cpu(), and random_matrix().
 {
     float *a;
     if(!TA) a = random_matrix(m,k);
     else a = random_matrix(k,m);
     int lda = (!TA)?k:m;
     float *b;
     if(!TB) b = random_matrix(k,n);
     else b = random_matrix(n,k);
     int ldb = (!TB)?n:k;
     float *c = random_matrix(m,n);
     int i;
     clock_t start = clock(), end;
     for(i = 0; i<10; ++i){
         gemm_cpu(TA,TB,m,n,k,1,a,lda,b,ldb,1,c,n);
     }
     end = clock();
     printf("Matrix Multiplication %dx%d * %dx%d, TA=%d, TB=%d: %lf ms\n",m,k,k,n, TA, TB, (float)(end-start)/CLOCKS_PER_SEC);
     free(a);
     free(b);
     free(c);
 }
variance_cpu()
void variance_cpu (float * x, float * mean, int batch, int filters, int spatial, float * variance)
Definition at line 99 of file blas.c.
Referenced by forward_batchnorm_layer(), and forward_connected_layer().
 {
     float scale = 1./(batch * spatial - 1);
     int i,j,k;
     for(i = 0; i < filters; ++i){
         variance[i] = 0;
         for(j = 0; j < batch; ++j){
             for(k = 0; k < spatial; ++k){
                 int index = j*filters*spatial + i*spatial + k;
                 variance[i] += pow((x[index] - mean[i]), 2);
             }
         }
         variance[i] *= scale;
     }
 }
variance_delta_cpu()
void variance_delta_cpu (float * x, float * delta, float * mean, float * variance, int batch, int filters, int spatial, float * variance_delta)
Definition at line 102 of file batchnorm_layer.c.
Referenced by backward_batchnorm_layer(), and backward_connected_layer().
 {
     int i,j,k;
     for(i = 0; i < filters; ++i){
         variance_delta[i] = 0;
         for(j = 0; j < batch; ++j){
             for(k = 0; k < spatial; ++k){
                 int index = j*filters*spatial + i*spatial + k;
                 variance_delta[i] += delta[index]*(x[index] - mean[i]);
             }
         }
         variance_delta[i] *= -.5 * pow(variance[i] + .00001f, (float)(-3./2.));
     }
 }
weighted_sum_cpu()
void weighted_sum_cpu (float * a, float * b, float * s, int num, float * c)
Definition at line 49 of file blas.c.
Referenced by forward_gru_layer().
 {
     int i;
     for(i = 0; i < n; ++i){
         c[i] = s[i]*a[i] + (1-s[i])*(b ? b[i] : 0);
     }
 }