Darknet: connected_layer.h File Reference
connected_layer.h File Reference
#include "activations.h"
#include "layer.h"
#include "network.h"
Typedefs
typedef layer connected_layer
Functions
connected_layer make_connected_layer (int batch, int inputs, int outputs, ACTIVATION activation, int batch_normalize)
void forward_connected_layer (connected_layer layer, network net)
void backward_connected_layer (connected_layer layer, network net)
void update_connected_layer (connected_layer layer, int batch, float learning_rate, float momentum, float decay)
void denormalize_connected_layer (layer l)
void statistics_connected_layer (layer l)
Typedef Documentation
connected_layer
typedef layer connected_layer
Definition at line 8 of file connected_layer.h.
Function Documentation
backward_connected_layer()
void backward_connected_layer (connected_layer layer, network net)
Definition at line 163 of file connected_layer.c.
References layer::activation, axpy_cpu(), backward_scale_cpu(), layer::batch, layer::batch_normalize, layer::bias_updates, network::delta, layer::delta, gemm(), gradient_array(), network::input, layer::inputs, layer::mean, layer::mean_delta, mean_delta_cpu(), normalize_delta_cpu(), layer::output, layer::outputs, scale_bias(), layer::scale_updates, layer::scales, layer::variance, layer::variance_delta, variance_delta_cpu(), layer::weight_updates, layer::weights, layer::x, and layer::x_norm.
Referenced by backward_rnn_layer(), and make_connected_layer().
 {
     int i;
     gradient_array(l.output, l.outputs*l.batch, l.activation, l.delta);
     for(i = 0; i < l.batch; ++i){
         axpy_cpu(l.outputs, 1, l.delta + i*l.outputs, 1, l.bias_updates, 1);
     }
     if(l.batch_normalize){
         backward_scale_cpu(l.x_norm, l.delta, l.batch, l.outputs, 1, l.scale_updates);
         scale_bias(l.delta, l.scales, l.batch, l.outputs, 1);
         mean_delta_cpu(l.delta, l.variance, l.batch, l.outputs, 1, l.mean_delta);
         variance_delta_cpu(l.x, l.delta, l.mean, l.variance, l.batch, l.outputs, 1, l.variance_delta);
         normalize_delta_cpu(l.x, l.mean, l.variance, l.mean_delta, l.variance_delta, l.batch, l.outputs, 1, l.delta);
     }
     int m = l.outputs;
     int k = l.batch;
     int n = l.inputs;
     float *a = l.delta;
     float *b = net.input;
     float *c = l.weight_updates;
     gemm(1,0,m,n,k,1,a,m,b,n,1,c,n);
     m = l.batch;
     k = l.outputs;
     n = l.inputs;
     a = l.delta;
     b = l.weights;
     c = net.delta;
     if(c) gemm(0,0,m,n,k,1,a,k,b,n,1,c,n);
 }
denormalize_connected_layer()
void denormalize_connected_layer (layer l)
Definition at line 200 of file connected_layer.c.
References layer::biases, layer::inputs, layer::outputs, layer::rolling_mean, layer::rolling_variance, layer::scales, and layer::weights.
Referenced by denormalize_net(), and reset_normalize_net().
 {
     int i, j;
     for(i = 0; i < l.outputs; ++i){
         float scale = l.scales[i]/sqrt(l.rolling_variance[i] + .000001);
         for(j = 0; j < l.inputs; ++j){
             l.weights[i*l.inputs + j] *= scale;
         }
         l.biases[i] -= l.rolling_mean[i] * scale;
         l.scales[i] = 1;
         l.rolling_mean[i] = 0;
         l.rolling_variance[i] = 1;
     }
 }
forward_connected_layer()
void forward_connected_layer (connected_layer layer, network net)
Definition at line 128 of file connected_layer.c.
References activate_array(), layer::activation, axpy_cpu(), layer::batch, layer::batch_normalize, layer::biases, copy_cpu(), fill_cpu(), gemm(), network::input, layer::inputs, layer::mean, mean_cpu(), normalize_cpu(), layer::output, layer::outputs, layer::rolling_mean, layer::rolling_variance, scal_cpu(), scale_bias(), layer::scales, network::train, layer::variance, variance_cpu(), layer::weights, layer::x, and layer::x_norm.
Referenced by forward_gru_layer(), forward_rnn_layer(), and make_connected_layer().
 {
     int i;
     fill_cpu(l.outputs*l.batch, 0, l.output, 1);
     int m = l.batch;
     int k = l.inputs;
     int n = l.outputs;
     float *a = net.input;
     float *b = l.weights;
     float *c = l.output;
     gemm(0,1,m,n,k,1,a,k,b,k,1,c,n);
     if(l.batch_normalize){
         if(net.train){
             mean_cpu(l.output, l.batch, l.outputs, 1, l.mean);
             variance_cpu(l.output, l.mean, l.batch, l.outputs, 1, l.variance);
             scal_cpu(l.outputs, .95, l.rolling_mean, 1);
             axpy_cpu(l.outputs, .05, l.mean, 1, l.rolling_mean, 1);
             scal_cpu(l.outputs, .95, l.rolling_variance, 1);
             axpy_cpu(l.outputs, .05, l.variance, 1, l.rolling_variance, 1);
             copy_cpu(l.outputs*l.batch, l.output, 1, l.x, 1);
             normalize_cpu(l.output, l.mean, l.variance, l.batch, l.outputs, 1);
             copy_cpu(l.outputs*l.batch, l.output, 1, l.x_norm, 1);
         } else {
             normalize_cpu(l.output, l.rolling_mean, l.rolling_variance, l.batch, l.outputs, 1);
         }
         scale_bias(l.output, l.scales, l.batch, l.outputs, 1);
     }
     for(i = 0; i < l.batch; ++i){
         axpy_cpu(l.outputs, 1, l.biases, 1, l.output + i*l.outputs, 1);
     }
     activate_array(l.output, l.outputs*l.batch, l.activation);
 }
make_connected_layer()
connected_layer make_connected_layer (int batch, int inputs, int outputs, ACTIVATION activation, int batch_normalize)
Definition at line 13 of file connected_layer.c.
References layer::activation, layer::backward, backward_connected_layer(), layer::backward_gpu, layer::batch, layer::batch_normalize, layer::bias_updates, layer::biases, layer::c, CONNECTED, layer::delta, layer::forward, forward_connected_layer(), layer::forward_gpu, layer::h, layer::inputs, layer::mean, layer::mean_delta, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, rand_uniform(), layer::rolling_mean, layer::rolling_variance, layer::scale_updates, layer::scales, layer::type, layer::update, update_connected_layer(), layer::update_gpu, layer::variance, layer::variance_delta, layer::w, layer::weight_updates, layer::weights, layer::x, and layer::x_norm.
Referenced by make_gru_layer(), make_rnn_layer(), and parse_connected().
 {
     int i;
     connected_layer l = {0};
     l.type = CONNECTED;
     l.inputs = inputs;
     l.outputs = outputs;
     l.batch=batch;
     l.batch_normalize = batch_normalize;
     l.h = 1;
     l.w = 1;
     l.c = inputs;
     l.out_h = 1;
     l.out_w = 1;
     l.out_c = outputs;
     l.output = calloc(batch*outputs, sizeof(float));
     l.delta = calloc(batch*outputs, sizeof(float));
     l.weight_updates = calloc(inputs*outputs, sizeof(float));
     l.bias_updates = calloc(outputs, sizeof(float));
     l.weights = calloc(outputs*inputs, sizeof(float));
     l.biases = calloc(outputs, sizeof(float));
     l.forward = forward_connected_layer;
     l.backward = backward_connected_layer;
     l.update = update_connected_layer;
     //float scale = 1./sqrt(inputs);
     float scale = sqrt(2./inputs);
     for(i = 0; i < outputs*inputs; ++i){
         l.weights[i] = scale*rand_uniform(-1, 1);
     }
     for(i = 0; i < outputs; ++i){
         l.biases[i] = 0;
     }
     if(batch_normalize){
         l.scales = calloc(outputs, sizeof(float));
         l.scale_updates = calloc(outputs, sizeof(float));
         for(i = 0; i < outputs; ++i){
             l.scales[i] = 1;
         }
         l.mean = calloc(outputs, sizeof(float));
         l.mean_delta = calloc(outputs, sizeof(float));
         l.variance = calloc(outputs, sizeof(float));
         l.variance_delta = calloc(outputs, sizeof(float));
         l.rolling_mean = calloc(outputs, sizeof(float));
         l.rolling_variance = calloc(outputs, sizeof(float));
         l.x = calloc(batch*outputs, sizeof(float));
         l.x_norm = calloc(batch*outputs, sizeof(float));
     }
 #ifdef GPU
     l.forward_gpu = forward_connected_layer_gpu;
     l.backward_gpu = backward_connected_layer_gpu;
     l.update_gpu = update_connected_layer_gpu;
     l.weights_gpu = cuda_make_array(l.weights, outputs*inputs);
     l.biases_gpu = cuda_make_array(l.biases, outputs);
     l.weight_updates_gpu = cuda_make_array(l.weight_updates, outputs*inputs);
     l.bias_updates_gpu = cuda_make_array(l.bias_updates, outputs);
     l.output_gpu = cuda_make_array(l.output, outputs*batch);
     l.delta_gpu = cuda_make_array(l.delta, outputs*batch);
     if(batch_normalize){
         l.scales_gpu = cuda_make_array(l.scales, outputs);
         l.scale_updates_gpu = cuda_make_array(l.scale_updates, outputs);
         l.mean_gpu = cuda_make_array(l.mean, outputs);
         l.variance_gpu = cuda_make_array(l.variance, outputs);
         l.rolling_mean_gpu = cuda_make_array(l.mean, outputs);
         l.rolling_variance_gpu = cuda_make_array(l.variance, outputs);
         l.mean_delta_gpu = cuda_make_array(l.mean, outputs);
         l.variance_delta_gpu = cuda_make_array(l.variance, outputs);
         l.x_gpu = cuda_make_array(l.output, l.batch*outputs);
         l.x_norm_gpu = cuda_make_array(l.output, l.batch*outputs);
 #ifdef CUDNN
         cudnnCreateTensorDescriptor(&l.normTensorDesc);
         cudnnCreateTensorDescriptor(&l.dstTensorDesc);
         cudnnSetTensor4dDescriptor(l.dstTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, l.batch, l.out_c, l.out_h, l.out_w);
         cudnnSetTensor4dDescriptor(l.normTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, 1, l.out_c, 1, 1);
 #endif
     }
 #endif
     l.activation = activation;
     fprintf(stderr, "connected                            %4d  ->  %4d\n", inputs, outputs);
     return l;
 }
statistics_connected_layer()
void statistics_connected_layer (layer l)
Definition at line 216 of file connected_layer.c.
References layer::activation, layer::batch, layer::batch_normalize, layer::bias_updates, layer::biases, constrain_ongpu(), layer::inputs, layer::outputs, print_statistics(), layer::rolling_mean, layer::rolling_variance, layer::scales, layer::weight_updates, and layer::weights.
Referenced by statistics_net().
 {
     if(l.batch_normalize){
         printf("Scales ");
         print_statistics(l.scales, l.outputs);
         /*
            printf("Rolling Mean ");
            print_statistics(l.rolling_mean, l.outputs);
            printf("Rolling Variance ");
            print_statistics(l.rolling_variance, l.outputs);
          */
     }
     printf("Biases ");
     print_statistics(l.biases, l.outputs);
     printf("Weights ");
     print_statistics(l.weights, l.outputs);
 }
update_connected_layer()
void update_connected_layer (connected_layer layer, int batch, float learning_rate, float momentum, float decay)
Definition at line 113 of file connected_layer.c.
References axpy_cpu(), layer::batch_normalize, layer::bias_updates, layer::biases, layer::inputs, layer::outputs, scal_cpu(), layer::scale_updates, layer::scales, layer::weight_updates, and layer::weights.
Referenced by make_connected_layer(), update_gru_layer(), and update_rnn_layer().
 {
     axpy_cpu(l.outputs, learning_rate/batch, l.bias_updates, 1, l.biases, 1);
     scal_cpu(l.outputs, momentum, l.bias_updates, 1);
     if(l.batch_normalize){
         axpy_cpu(l.outputs, learning_rate/batch, l.scale_updates, 1, l.scales, 1);
         scal_cpu(l.outputs, momentum, l.scale_updates, 1);
     }
     axpy_cpu(l.inputs*l.outputs, -decay*batch, l.weights, 1, l.weight_updates, 1);
     axpy_cpu(l.inputs*l.outputs, learning_rate/batch, l.weight_updates, 1, l.weights, 1);
     scal_cpu(l.inputs*l.outputs, momentum, l.weight_updates, 1);
 }