Darknet: parser.h File Reference
parser.h File Reference
#include "network.h"
Functions
network parse_network_cfg (char *filename)
void save_network (network net, char *filename)
void save_weights (network net, char *filename)
void save_weights_upto (network net, char *filename, int cutoff)
void save_weights_double (network net, char *filename)
void load_weights (network *net, char *filename)
void load_weights_upto (network *net, char *filename, int start, int cutoff)
Function Documentation
load_weights()
void load_weights (network * net, char * filename)
Definition at line 1127 of file parser.c.
References load_weights_upto(), and network::n.
Referenced by average(), BattleRoyaleWithCheese(), demo_art(), demo_classifier(), demo_regressor(), denormalize_net(), engine_go(), gun_classifier(), label_classifier(), load_network(), normalize_net(), oneoff(), predict_classifier(), predict_regressor(), rescale_net(), reset_normalize_net(), rgbgr_net(), run_nightmare(), self_go(), SortMaster3000(), statistics_net(), test_captcha(), test_char_rnn(), test_cifar(), test_cifar_csv(), test_cifar_csvtrain(), test_cifar_multi(), test_classifier(), test_coco(), test_dcgan(), test_detector(), test_dice(), test_go(), test_lsd(), test_super(), test_tactic_rnn(), test_tag(), test_voxel(), test_writing(), test_yolo(), threat_classifier(), train_captcha(), train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_compare(), train_detector(), train_dice(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), try_classifier(), valid_captcha(), valid_char_rnn(), valid_go(), valid_tactic_rnn(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_compare(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_dice(), validate_yolo(), validate_yolo_recall(), vec_char_rnn(), and visualize().
 {
     load_weights_upto(net, filename, 0, net->n);
 }
load_weights_upto()
void load_weights_upto (network * net, char * filename, int start, int cutoff)
Definition at line 1059 of file parser.c.
References BATCHNORM, layer::biases, layer::c, CONNECTED, CONVOLUTIONAL, CRNN, DECONVOLUTIONAL, layer::dontload, file_error(), gpu_index, network::gpu_index, GRU, layer::input_h_layer, layer::input_layer, layer::input_r_layer, layer::input_z_layer, network::layers, load_batchnorm_weights(), load_connected_weights(), load_convolutional_weights(), LOCAL, network::n, layer::n, layer::out_h, layer::out_w, layer::output_layer, layer::outputs, RNN, network::seen, layer::self_layer, layer::size, layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, layer::type, and layer::weights.
Referenced by load_weights(), oneoff2(), and partial().
 {
 #ifdef GPU
     if(net->gpu_index >= 0){
         cuda_set_device(net->gpu_index);
     }
 #endif
     fprintf(stderr, "Loading weights from %s...", filename);
     fflush(stdout);
     FILE *fp = fopen(filename, "rb");
     if(!fp) file_error(filename);
     int major;
     int minor;
     int revision;
     fread(&major, sizeof(int), 1, fp);
     fread(&minor, sizeof(int), 1, fp);
     fread(&revision, sizeof(int), 1, fp);
     fread(net->seen, sizeof(int), 1, fp);
     int transpose = (major > 1000) || (minor > 1000);
     int i;
     for(i = start; i < net->n && i < cutoff; ++i){
         layer l = net->layers[i];
         if (l.dontload) continue;
         if(l.type == CONVOLUTIONAL || l.type == DECONVOLUTIONAL){
             load_convolutional_weights(l, fp);
         }
         if(l.type == CONNECTED){
             load_connected_weights(l, fp, transpose);
         }
         if(l.type == BATCHNORM){
             load_batchnorm_weights(l, fp);
         }
         if(l.type == CRNN){
             load_convolutional_weights(*(l.input_layer), fp);
             load_convolutional_weights(*(l.self_layer), fp);
             load_convolutional_weights(*(l.output_layer), fp);
         }
         if(l.type == RNN){
             load_connected_weights(*(l.input_layer), fp, transpose);
             load_connected_weights(*(l.self_layer), fp, transpose);
             load_connected_weights(*(l.output_layer), fp, transpose);
         }
         if(l.type == GRU){
             load_connected_weights(*(l.input_z_layer), fp, transpose);
             load_connected_weights(*(l.input_r_layer), fp, transpose);
             load_connected_weights(*(l.input_h_layer), fp, transpose);
             load_connected_weights(*(l.state_z_layer), fp, transpose);
             load_connected_weights(*(l.state_r_layer), fp, transpose);
             load_connected_weights(*(l.state_h_layer), fp, transpose);
         }
         if(l.type == LOCAL){
             int locations = l.out_w*l.out_h;
             int size = l.size*l.size*l.c*l.n*locations;
             fread(l.biases, sizeof(float), l.outputs, fp);
             fread(l.weights, sizeof(float), size, fp);
 #ifdef GPU
             if(gpu_index >= 0){
                 push_local_layer(l);
             }
 #endif
         }
     }
     fprintf(stderr, "Done!\n");
     fclose(fp);
 }
parse_network_cfg()
network parse_network_cfg (char * filename)
Definition at line 618 of file parser.c.
References ACTIVE, AVGPOOL, network::batch, size_params::batch, BATCHNORM, network::c, size_params::c, CONNECTED, CONVOLUTIONAL, COST, CRNN, CROP, DECONVOLUTIONAL, layer::delta, DETECTION, DROPOUT, error(), free_list(), free_section(), list::front, get_network_output_layer(), gpu_index, network::gpu_index, GRU, network::h, size_params::h, network::hierarchy, size_params::index, network::input, network::inputs, size_params::inputs, is_network(), network::layers, LOCAL, make_network(), MAXPOOL, network::n, size_params::net, node::next, NORMALIZATION, option_find_float_quiet(), option_find_int_quiet(), option_unused(), section::options, network::output, layer::output, network::outputs, layer::outputs, parse_activation(), parse_avgpool(), parse_batchnorm(), parse_connected(), parse_convolutional(), parse_cost(), parse_crnn(), parse_crop(), parse_deconvolutional(), parse_detection(), parse_dropout(), parse_gru(), parse_local(), parse_maxpool(), parse_net_options(), parse_normalization(), parse_region(), parse_reorg(), parse_rnn(), parse_route(), parse_shortcut(), parse_softmax(), read_cfg(), REGION, REORG, RNN, ROUTE, SHORTCUT, list::size, SOFTMAX, string_to_layer_type(), network::time_steps, size_params::time_steps, network::truth, network::truths, layer::truths, section::type, node::val, network::w, size_params::w, network::workspace, and layer::workspace_size.
Referenced by average(), BattleRoyaleWithCheese(), demo_art(), demo_classifier(), demo_regressor(), denormalize_net(), engine_go(), gun_classifier(), label_classifier(), load_network(), normalize_net(), oneoff(), oneoff2(), operations(), partial(), predict_classifier(), predict_regressor(), rescale_net(), reset_normalize_net(), rgbgr_net(), run_nightmare(), self_go(), SortMaster3000(), speed(), statistics_net(), test_captcha(), test_char_rnn(), test_cifar(), test_cifar_csv(), test_cifar_csvtrain(), test_cifar_multi(), test_classifier(), test_coco(), test_dcgan(), test_detector(), test_dice(), test_go(), test_lsd(), test_super(), test_tactic_rnn(), test_tag(), test_voxel(), test_writing(), test_yolo(), threat_classifier(), train_captcha(), train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_compare(), train_detector(), train_dice(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), try_classifier(), valid_captcha(), valid_char_rnn(), valid_go(), valid_tactic_rnn(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_compare(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_dice(), validate_yolo(), validate_yolo_recall(), vec_char_rnn(), and visualize().
 {
     list *sections = read_cfg(filename);
     node *n = sections->front;
     if(!n) error("Config file has no sections");
     network net = make_network(sections->size - 1);
     net.gpu_index = gpu_index;
     size_params params;
     section *s = (section *)n->val;
     list *options = s->options;
     if(!is_network(s)) error("First section must be [net] or [network]");
     parse_net_options(options, &net);
     params.h = net.h;
     params.w = net.w;
     params.c = net.c;
     params.inputs = net.inputs;
     params.batch = net.batch;
     params.time_steps = net.time_steps;
     params.net = net;
     size_t workspace_size = 0;
     n = n->next;
     int count = 0;
     free_section(s);
     fprintf(stderr, "layer     filters    size              input                output\n");
     while(n){
         params.index = count;
         fprintf(stderr, "%5d ", count);
         s = (section *)n->val;
         options = s->options;
         layer l = {0};
         LAYER_TYPE lt = string_to_layer_type(s->type);
         if(lt == CONVOLUTIONAL){
             l = parse_convolutional(options, params);
         }else if(lt == DECONVOLUTIONAL){
             l = parse_deconvolutional(options, params);
         }else if(lt == LOCAL){
             l = parse_local(options, params);
         }else if(lt == ACTIVE){
             l = parse_activation(options, params);
         }else if(lt == RNN){
             l = parse_rnn(options, params);
         }else if(lt == GRU){
             l = parse_gru(options, params);
         }else if(lt == CRNN){
             l = parse_crnn(options, params);
         }else if(lt == CONNECTED){
             l = parse_connected(options, params);
         }else if(lt == CROP){
             l = parse_crop(options, params);
         }else if(lt == COST){
             l = parse_cost(options, params);
         }else if(lt == REGION){
             l = parse_region(options, params);
         }else if(lt == DETECTION){
             l = parse_detection(options, params);
         }else if(lt == SOFTMAX){
             l = parse_softmax(options, params);
             net.hierarchy = l.softmax_tree;
         }else if(lt == NORMALIZATION){
             l = parse_normalization(options, params);
         }else if(lt == BATCHNORM){
             l = parse_batchnorm(options, params);
         }else if(lt == MAXPOOL){
             l = parse_maxpool(options, params);
         }else if(lt == REORG){
             l = parse_reorg(options, params);
         }else if(lt == AVGPOOL){
             l = parse_avgpool(options, params);
         }else if(lt == ROUTE){
             l = parse_route(options, params, net);
         }else if(lt == SHORTCUT){
             l = parse_shortcut(options, params, net);
         }else if(lt == DROPOUT){
             l = parse_dropout(options, params);
             l.output = net.layers[count-1].output;
             l.delta = net.layers[count-1].delta;
 #ifdef GPU
             l.output_gpu = net.layers[count-1].output_gpu;
             l.delta_gpu = net.layers[count-1].delta_gpu;
 #endif
         }else{
             fprintf(stderr, "Type not recognized: %s\n", s->type);
         }
         l.truth = option_find_int_quiet(options, "truth", 0);
         l.onlyforward = option_find_int_quiet(options, "onlyforward", 0);
         l.stopbackward = option_find_int_quiet(options, "stopbackward", 0);
         l.dontload = option_find_int_quiet(options, "dontload", 0);
         l.dontloadscales = option_find_int_quiet(options, "dontloadscales", 0);
         l.learning_rate_scale = option_find_float_quiet(options, "learning_rate", 1);
         l.smooth = option_find_float_quiet(options, "smooth", 0);
         option_unused(options);
         net.layers[count] = l;
         if (l.workspace_size > workspace_size) workspace_size = l.workspace_size;
         free_section(s);
         n = n->next;
         ++count;
         if(n){
             params.h = l.out_h;
             params.w = l.out_w;
             params.c = l.out_c;
             params.inputs = l.outputs;
         }
     }
     free_list(sections);
     layer out = get_network_output_layer(net);
     net.outputs = out.outputs;
     net.truths = out.outputs;
     if(net.layers[net.n-1].truths) net.truths = net.layers[net.n-1].truths;
     net.output = out.output;
     net.input = calloc(net.inputs*net.batch, sizeof(float));
     net.truth = calloc(net.truths*net.batch, sizeof(float));
 #ifdef GPU
     net.output_gpu = out.output_gpu;
     net.input_gpu = cuda_make_array(net.input, net.inputs*net.batch);
     net.truth_gpu = cuda_make_array(net.truth, net.truths*net.batch);
 #endif
     if(workspace_size){
         //printf("%ld\n", workspace_size);
 #ifdef GPU
         if(gpu_index >= 0){
             net.workspace = cuda_make_array(0, (workspace_size-1)/sizeof(float)+1);
         }else {
             net.workspace = calloc(1, workspace_size);
         }
 #else
         net.workspace = calloc(1, workspace_size);
 #endif
     }
     return net;
 }
save_network()
void save_network (network net, char * filename)
save_weights()
void save_weights (network net, char * filename)
Definition at line 929 of file parser.c.
References network::n, and save_weights_upto().
Referenced by average(), denormalize_net(), normalize_net(), oneoff(), rescale_net(), reset_normalize_net(), rgbgr_net(), train_captcha(), train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_go(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), and train_yolo().
 {
     save_weights_upto(net, filename, net.n);
 }
save_weights_double()
void save_weights_double (network net, char * filename)
save_weights_upto()
void save_weights_upto (network net, char * filename, int cutoff)
Definition at line 872 of file parser.c.
References BATCHNORM, layer::biases, layer::c, CONNECTED, CONVOLUTIONAL, CRNN, DECONVOLUTIONAL, file_error(), gpu_index, network::gpu_index, GRU, layer::input_h_layer, layer::input_layer, layer::input_r_layer, layer::input_z_layer, network::layers, LOCAL, network::n, layer::n, layer::out_h, layer::out_w, layer::output_layer, layer::outputs, RNN, save_batchnorm_weights(), save_connected_weights(), save_convolutional_weights(), network::seen, layer::self_layer, layer::size, layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, layer::type, and layer::weights.
Referenced by oneoff2(), partial(), and save_weights().
 {
 #ifdef GPU
     if(net.gpu_index >= 0){
         cuda_set_device(net.gpu_index);
     }
 #endif
     fprintf(stderr, "Saving weights to %s\n", filename);
     FILE *fp = fopen(filename, "wb");
     if(!fp) file_error(filename);
     int major = 0;
     int minor = 1;
     int revision = 0;
     fwrite(&major, sizeof(int), 1, fp);
     fwrite(&minor, sizeof(int), 1, fp);
     fwrite(&revision, sizeof(int), 1, fp);
     fwrite(net.seen, sizeof(int), 1, fp);
     int i;
     for(i = 0; i < net.n && i < cutoff; ++i){
         layer l = net.layers[i];
         if(l.type == CONVOLUTIONAL || l.type == DECONVOLUTIONAL){
             save_convolutional_weights(l, fp);
         } if(l.type == CONNECTED){
             save_connected_weights(l, fp);
         } if(l.type == BATCHNORM){
             save_batchnorm_weights(l, fp);
         } if(l.type == RNN){
             save_connected_weights(*(l.input_layer), fp);
             save_connected_weights(*(l.self_layer), fp);
             save_connected_weights(*(l.output_layer), fp);
         } if(l.type == GRU){
             save_connected_weights(*(l.input_z_layer), fp);
             save_connected_weights(*(l.input_r_layer), fp);
             save_connected_weights(*(l.input_h_layer), fp);
             save_connected_weights(*(l.state_z_layer), fp);
             save_connected_weights(*(l.state_r_layer), fp);
             save_connected_weights(*(l.state_h_layer), fp);
         } if(l.type == CRNN){
             save_convolutional_weights(*(l.input_layer), fp);
             save_convolutional_weights(*(l.self_layer), fp);
             save_convolutional_weights(*(l.output_layer), fp);
         } if(l.type == LOCAL){
 #ifdef GPU
             if(gpu_index >= 0){
                 pull_local_layer(l);
             }
 #endif
             int locations = l.out_w*l.out_h;
             int size = l.size*l.size*l.c*l.n*locations;
             fwrite(l.biases, sizeof(float), l.outputs, fp);
             fwrite(l.weights, sizeof(float), size, fp);
         }
     }
     fclose(fp);
 }