Darknet: route_layer.c File Reference
route_layer.c File Reference
#include "route_layer.h"
#include "cuda.h"
#include "blas.h"
#include <stdio.h>
Functions
route_layer make_route_layer (int batch, int n, int *input_layers, int *input_sizes)
void resize_route_layer (route_layer *l, network *net)
void forward_route_layer (const route_layer l, network net)
void backward_route_layer (const route_layer l, network net)
Function Documentation
backward_route_layer()
void backward_route_layer (const route_layer l, network net)
Definition at line 88 of file route_layer.c.
References axpy_cpu(), layer::batch, layer::delta, layer::input_layers, layer::input_sizes, network::layers, layer::n, and layer::outputs.
Referenced by make_route_layer().
 {
     int i, j;
     int offset = 0;
     for(i = 0; i < l.n; ++i){
         int index = l.input_layers[i];
         float *delta = net.layers[index].delta;
         int input_size = l.input_sizes[i];
         for(j = 0; j < l.batch; ++j){
             axpy_cpu(input_size, 1, l.delta + offset + j*l.outputs, 1, delta + j*input_size, 1);
         }
         offset += input_size;
     }
 }
forward_route_layer()
void forward_route_layer (const route_layer l, network net)
Definition at line 73 of file route_layer.c.
References layer::batch, copy_cpu(), layer::input_layers, layer::input_sizes, network::layers, layer::n, layer::output, and layer::outputs.
Referenced by make_route_layer().
 {
     int i, j;
     int offset = 0;
     for(i = 0; i < l.n; ++i){
         int index = l.input_layers[i];
         float *input = net.layers[index].output;
         int input_size = l.input_sizes[i];
         for(j = 0; j < l.batch; ++j){
             copy_cpu(input_size, input + j*input_size, 1, l.output + offset + j*l.outputs, 1);
         }
         offset += input_size;
     }
 }
make_route_layer()
route_layer make_route_layer (int batch, int n, int * input_layers, int * input_sizes)
Definition at line 6 of file route_layer.c.
References layer::backward, layer::backward_gpu, backward_route_layer(), layer::batch, layer::delta, layer::forward, layer::forward_gpu, forward_route_layer(), layer::input_layers, layer::input_sizes, layer::inputs, layer::n, layer::output, layer::outputs, ROUTE, and layer::type.
Referenced by parse_route().
 {
     fprintf(stderr,"route ");
     route_layer l = {0};
     l.type = ROUTE;
     l.batch = batch;
     l.n = n;
     l.input_layers = input_layers;
     l.input_sizes = input_sizes;
     int i;
     int outputs = 0;
     for(i = 0; i < n; ++i){
         fprintf(stderr," %d", input_layers[i]);
         outputs += input_sizes[i];
     }
     fprintf(stderr, "\n");
     l.outputs = outputs;
     l.inputs = outputs;
     l.delta =  calloc(outputs*batch, sizeof(float));
     l.output = calloc(outputs*batch, sizeof(float));;
     l.forward = forward_route_layer;
     l.backward = backward_route_layer;
     #ifdef GPU
     l.forward_gpu = forward_route_layer_gpu;
     l.backward_gpu = backward_route_layer_gpu;
     l.delta_gpu =  cuda_make_array(l.delta, outputs*batch);
     l.output_gpu = cuda_make_array(l.output, outputs*batch);
     #endif
     return l;
 }
resize_route_layer()
void resize_route_layer (route_layer * l, network * net)
Definition at line 39 of file route_layer.c.
References layer::batch, layer::delta, layer::input_layers, layer::input_sizes, layer::inputs, network::layers, layer::n, layer::out_c, layer::out_h, layer::out_w, layer::output, and layer::outputs.
Referenced by resize_network().
 {
     int i;
     layer first = net->layers[l->input_layers[0]];
     l->out_w = first.out_w;
     l->out_h = first.out_h;
     l->out_c = first.out_c;
     l->outputs = first.outputs;
     l->input_sizes[0] = first.outputs;
     for(i = 1; i < l->n; ++i){
         int index = l->input_layers[i];
         layer next = net->layers[index];
         l->outputs += next.outputs;
         l->input_sizes[i] = next.outputs;
         if(next.out_w == first.out_w && next.out_h == first.out_h){
             l->out_c += next.out_c;
         }else{
             printf("%d %d, %d %d\n", next.out_w, next.out_h, first.out_w, first.out_h);
             l->out_h = l->out_w = l->out_c = 0;
         }
     }
     l->inputs = l->outputs;
     l->delta =  realloc(l->delta, l->outputs*l->batch*sizeof(float));
     l->output = realloc(l->output, l->outputs*l->batch*sizeof(float));
 #ifdef GPU
     cuda_free(l->output_gpu);
     cuda_free(l->delta_gpu);
     l->output_gpu  = cuda_make_array(l->output, l->outputs*l->batch);
     l->delta_gpu   = cuda_make_array(l->delta,  l->outputs*l->batch);
 #endif
 }