Darknet: avgpool_layer.c File Reference
avgpool_layer.c File Reference
#include "avgpool_layer.h"
#include "cuda.h"
#include <stdio.h>
Functions
avgpool_layer make_avgpool_layer (int batch, int w, int h, int c)
void resize_avgpool_layer (avgpool_layer *l, int w, int h)
void forward_avgpool_layer (const avgpool_layer l, network net)
void backward_avgpool_layer (const avgpool_layer l, network net)
Function Documentation
backward_avgpool_layer()
void backward_avgpool_layer (const avgpool_layer l, network net)
Definition at line 57 of file avgpool_layer.c.
References layer::batch, layer::c, network::delta, layer::delta, layer::h, and layer::w.
Referenced by make_avgpool_layer().
 {
     int b,i,k;
     for(b = 0; b < l.batch; ++b){
         for(k = 0; k < l.c; ++k){
             int out_index = k + b*l.c;
             for(i = 0; i < l.h*l.w; ++i){
                 int in_index = i + l.h*l.w*(k + b*l.c);
                 net.delta[in_index] += l.delta[out_index] / (l.h*l.w);
             }
         }
     }
 }
forward_avgpool_layer()
void forward_avgpool_layer (const avgpool_layer l, network net)
Definition at line 40 of file avgpool_layer.c.
References layer::batch, layer::c, layer::h, network::input, layer::output, and layer::w.
Referenced by make_avgpool_layer().
 {
     int b,i,k;
     for(b = 0; b < l.batch; ++b){
         for(k = 0; k < l.c; ++k){
             int out_index = k + b*l.c;
             l.output[out_index] = 0;
             for(i = 0; i < l.h*l.w; ++i){
                 int in_index = i + l.h*l.w*(k + b*l.c);
                 l.output[out_index] += net.input[in_index];
             }
             l.output[out_index] /= l.h*l.w;
         }
     }
 }
make_avgpool_layer()
avgpool_layer make_avgpool_layer (int batch, int w, int h, int c)
Definition at line 5 of file avgpool_layer.c.
References AVGPOOL, layer::backward, backward_avgpool_layer(), layer::backward_gpu, layer::batch, layer::c, layer::delta, layer::forward, forward_avgpool_layer(), layer::forward_gpu, layer::h, layer::inputs, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::type, and layer::w.
Referenced by parse_avgpool().
 {
     fprintf(stderr, "avg                     %4d x%4d x%4d   ->  %4d\n",  w, h, c, c);
     avgpool_layer l = {0};
     l.type = AVGPOOL;
     l.batch = batch;
     l.h = h;
     l.w = w;
     l.c = c;
     l.out_w = 1;
     l.out_h = 1;
     l.out_c = c;
     l.outputs = l.out_c;
     l.inputs = h*w*c;
     int output_size = l.outputs * batch;
     l.output =  calloc(output_size, sizeof(float));
     l.delta =   calloc(output_size, sizeof(float));
     l.forward = forward_avgpool_layer;
     l.backward = backward_avgpool_layer;
     #ifdef GPU
     l.forward_gpu = forward_avgpool_layer_gpu;
     l.backward_gpu = backward_avgpool_layer_gpu;
     l.output_gpu  = cuda_make_array(l.output, output_size);
     l.delta_gpu   = cuda_make_array(l.delta, output_size);
     #endif
     return l;
 }
resize_avgpool_layer()
void resize_avgpool_layer (avgpool_layer * l, int w, int h)
Definition at line 33 of file avgpool_layer.c.
References layer::c, layer::h, layer::inputs, and layer::w.
Referenced by resize_network().
 {
     l->w = w;
     l->h = h;
     l->inputs = h*w*l->c;
 }