Darknet: activations.h File Reference
activations.h File Reference
#include "cuda.h"
#include "math.h"
Enumerations
enum ACTIVATION {
LOGISTIC, RELU, RELIE, LINEAR,
RAMP, TANH, PLSE, LEAKY,
ELU, LOGGY, STAIR, HARDTAN,
LHTAN
}
Functions
ACTIVATION get_activation (char *s)
char * get_activation_string (ACTIVATION a)
float activate (float x, ACTIVATION a)
float gradient (float x, ACTIVATION a)
void gradient_array (const float *x, const int n, const ACTIVATION a, float *delta)
void activate_array (float *x, const int n, const ACTIVATION a)
static float stair_activate (float x)
static float hardtan_activate (float x)
static float linear_activate (float x)
static float logistic_activate (float x)
static float loggy_activate (float x)
static float relu_activate (float x)
static float elu_activate (float x)
static float relie_activate (float x)
static float ramp_activate (float x)
static float leaky_activate (float x)
static float tanh_activate (float x)
static float plse_activate (float x)
static float lhtan_activate (float x)
static float lhtan_gradient (float x)
static float hardtan_gradient (float x)
static float linear_gradient (float x)
static float logistic_gradient (float x)
static float loggy_gradient (float x)
static float stair_gradient (float x)
static float relu_gradient (float x)
static float elu_gradient (float x)
static float relie_gradient (float x)
static float ramp_gradient (float x)
static float leaky_gradient (float x)
static float tanh_gradient (float x)
static float plse_gradient (float x)
Enumeration Type Documentation
ACTIVATION
enum ACTIVATION
Enumerator
LOGISTIC
RELU
RELIE
LINEAR
RAMP
TANH
PLSE
LEAKY
ELU
LOGGY
STAIR
HARDTAN
LHTAN
Definition at line 6 of file activations.h.
             {
     LOGISTIC, RELU, RELIE, LINEAR, RAMP, TANH, PLSE, LEAKY, ELU, LOGGY, STAIR, HARDTAN, LHTAN
 }ACTIVATION;
Function Documentation
activate()
float activate (float x, ACTIVATION a)
Definition at line 62 of file activations.c.
References ELU, elu_activate(), HARDTAN, hardtan_activate(), LEAKY, leaky_activate(), LHTAN, lhtan_activate(), LINEAR, linear_activate(), LOGGY, loggy_activate(), LOGISTIC, logistic_activate(), PLSE, plse_activate(), RAMP, ramp_activate(), RELIE, relie_activate(), RELU, relu_activate(), STAIR, stair_activate(), TANH, and tanh_activate().
Referenced by activate_array().
 {
     switch(a){
         case LINEAR:
             return linear_activate(x);
         case LOGISTIC:
             return logistic_activate(x);
         case LOGGY:
             return loggy_activate(x);
         case RELU:
             return relu_activate(x);
         case ELU:
             return elu_activate(x);
         case RELIE:
             return relie_activate(x);
         case RAMP:
             return ramp_activate(x);
         case LEAKY:
             return leaky_activate(x);
         case TANH:
             return tanh_activate(x);
         case PLSE:
             return plse_activate(x);
         case STAIR:
             return stair_activate(x);
         case HARDTAN:
             return hardtan_activate(x);
         case LHTAN:
             return lhtan_activate(x);
     }
     return 0;
 }
activate_array()
void activate_array (float * x, const int n, const ACTIVATION a)
Definition at line 95 of file activations.c.
References activate().
Referenced by forward_activation_layer(), forward_connected_layer(), forward_convolutional_layer(), forward_deconvolutional_layer(), forward_gru_layer(), forward_local_layer(), forward_region_layer(), and forward_shortcut_layer().
 {
     int i;
     for(i = 0; i < n; ++i){
         x[i] = activate(x[i], a);
     }
 }
elu_activate()
static float elu_activate (float x) inline static
Definition at line 38 of file activations.h.
Referenced by activate().
 {return (x >= 0)*x + (x < 0)*(exp(x)-1);}
elu_gradient()
static float elu_gradient (float x) inline static
Definition at line 80 of file activations.h.
Referenced by gradient().
 {return (x >= 0) + (x < 0)*(x + 1);}
get_activation()
ACTIVATION get_activation (char * s)
Definition at line 43 of file activations.c.
References ELU, HARDTAN, LEAKY, LHTAN, LINEAR, LOGGY, LOGISTIC, PLSE, RAMP, RELIE, RELU, STAIR, and TANH.
Referenced by parse_activation(), parse_connected(), parse_convolutional(), parse_crnn(), parse_deconvolutional(), parse_local(), parse_rnn(), and parse_shortcut().
 {
     if (strcmp(s, "logistic")==0) return LOGISTIC;
     if (strcmp(s, "loggy")==0) return LOGGY;
     if (strcmp(s, "relu")==0) return RELU;
     if (strcmp(s, "elu")==0) return ELU;
     if (strcmp(s, "relie")==0) return RELIE;
     if (strcmp(s, "plse")==0) return PLSE;
     if (strcmp(s, "hardtan")==0) return HARDTAN;
     if (strcmp(s, "lhtan")==0) return LHTAN;
     if (strcmp(s, "linear")==0) return LINEAR;
     if (strcmp(s, "ramp")==0) return RAMP;
     if (strcmp(s, "leaky")==0) return LEAKY;
     if (strcmp(s, "tanh")==0) return TANH;
     if (strcmp(s, "stair")==0) return STAIR;
     fprintf(stderr, "Couldn't find activation function %s, going with ReLU\n", s);
     return RELU;
 }
get_activation_string()
char* get_activation_string (ACTIVATION a)
Definition at line 8 of file activations.c.
References ELU, HARDTAN, LEAKY, LHTAN, LINEAR, LOGGY, LOGISTIC, PLSE, RAMP, RELIE, RELU, STAIR, and TANH.
 {
     switch(a){
         case LOGISTIC:
             return "logistic";
         case LOGGY:
             return "loggy";
         case RELU:
             return "relu";
         case ELU:
             return "elu";
         case RELIE:
             return "relie";
         case RAMP:
             return "ramp";
         case LINEAR:
             return "linear";
         case TANH:
             return "tanh";
         case PLSE:
             return "plse";
         case LEAKY:
             return "leaky";
         case STAIR:
             return "stair";
         case HARDTAN:
             return "hardtan";
         case LHTAN:
             return "lhtan";
         default:
             break;
     }
     return "relu";
 }
gradient()
float gradient (float x, ACTIVATION a)
Definition at line 103 of file activations.c.
References ELU, elu_gradient(), HARDTAN, hardtan_gradient(), LEAKY, leaky_gradient(), LHTAN, lhtan_gradient(), LINEAR, linear_gradient(), LOGGY, loggy_gradient(), LOGISTIC, logistic_gradient(), PLSE, plse_gradient(), RAMP, ramp_gradient(), RELIE, relie_gradient(), RELU, relu_gradient(), STAIR, stair_gradient(), TANH, and tanh_gradient().
Referenced by gradient_array().
 {
     switch(a){
         case LINEAR:
             return linear_gradient(x);
         case LOGISTIC:
             return logistic_gradient(x);
         case LOGGY:
             return loggy_gradient(x);
         case RELU:
             return relu_gradient(x);
         case ELU:
             return elu_gradient(x);
         case RELIE:
             return relie_gradient(x);
         case RAMP:
             return ramp_gradient(x);
         case LEAKY:
             return leaky_gradient(x);
         case TANH:
             return tanh_gradient(x);
         case PLSE:
             return plse_gradient(x);
         case STAIR:
             return stair_gradient(x);
         case HARDTAN:
             return hardtan_gradient(x);
         case LHTAN:
             return lhtan_gradient(x);
     }
     return 0;
 }
gradient_array()
void gradient_array (const float * x, const int n, const ACTIVATION a, float * delta)
Definition at line 136 of file activations.c.
References gradient().
Referenced by backward_activation_layer(), backward_connected_layer(), backward_convolutional_layer(), backward_deconvolutional_layer(), backward_local_layer(), and backward_shortcut_layer().
 {
     int i;
     for(i = 0; i < n; ++i){
         delta[i] *= gradient(x[i], a);
     }
 }
hardtan_activate()
static float hardtan_activate (float x) inline static
Definition at line 28 of file activations.h.
Referenced by activate().
 {
     if (x < -1) return -1;
     if (x > 1) return 1;
     return x;
 }
hardtan_gradient()
static float hardtan_gradient (float x) inline static
Definition at line 62 of file activations.h.
Referenced by gradient().
 {
     if (x > -1 && x < 1) return 1;
     return 0;
 }
leaky_activate()
static float leaky_activate (float x) inline static
Definition at line 41 of file activations.h.
Referenced by activate().
 {return (x>0) ? x : .1*x;}
leaky_gradient()
static float leaky_gradient (float x) inline static
Definition at line 83 of file activations.h.
Referenced by gradient().
 {return (x>0) ? 1 : .1;}
lhtan_activate()
static float lhtan_activate (float x) inline static
Definition at line 50 of file activations.h.
Referenced by activate().
 {
     if(x < 0) return .001*x;
     if(x > 1) return .001*(x-1) + 1;
     return x;
 }
lhtan_gradient()
static float lhtan_gradient (float x) inline static
Definition at line 56 of file activations.h.
Referenced by gradient().
 {
     if(x > 0 && x < 1) return 1;
     return .001;
 }
linear_activate()
static float linear_activate (float x) inline static
Definition at line 34 of file activations.h.
Referenced by activate().
 {return x;}
linear_gradient()
static float linear_gradient (float x) inline static
Definition at line 67 of file activations.h.
Referenced by gradient().
 {return 1;}
loggy_activate()
static float loggy_activate (float x) inline static
Definition at line 36 of file activations.h.
Referenced by activate().
 {return 2./(1. + exp(-x)) - 1;}
loggy_gradient()
static float loggy_gradient (float x) inline static
Definition at line 69 of file activations.h.
Referenced by gradient().
 {
     float y = (x+1.)/2.;
     return 2*(1-y)*y;
 }
logistic_activate()
static float logistic_activate (float x) inline static
Definition at line 35 of file activations.h.
Referenced by activate().
 {return 1./(1. + exp(-x));}
logistic_gradient()
static float logistic_gradient (float x) inline static
Definition at line 68 of file activations.h.
Referenced by gradient().
 {return (1-x)*x;}
plse_activate()
static float plse_activate (float x) inline static
Definition at line 43 of file activations.h.
Referenced by activate().
 {
     if(x < -4) return .01 * (x + 4);
     if(x > 4)  return .01 * (x - 4) + 1;
     return .125*x + .5;
 }
plse_gradient()
static float plse_gradient (float x) inline static
Definition at line 85 of file activations.h.
Referenced by gradient().
 {return (x < 0 || x > 1) ? .01 : .125;}
ramp_activate()
static float ramp_activate (float x) inline static
Definition at line 40 of file activations.h.
Referenced by activate().
 {return x*(x>0)+.1*x;}
ramp_gradient()
static float ramp_gradient (float x) inline static
Definition at line 82 of file activations.h.
Referenced by gradient().
 {return (x>0)+.1;}
relie_activate()
static float relie_activate (float x) inline static
Definition at line 39 of file activations.h.
Referenced by activate().
 {return (x>0) ? x : .01*x;}
relie_gradient()
static float relie_gradient (float x) inline static
Definition at line 81 of file activations.h.
Referenced by gradient().
 {return (x>0) ? 1 : .01;}
relu_activate()
static float relu_activate (float x) inline static
Definition at line 37 of file activations.h.
Referenced by activate().
 {return x*(x>0);}
relu_gradient()
static float relu_gradient (float x) inline static
Definition at line 79 of file activations.h.
Referenced by gradient().
 {return (x>0);}
stair_activate()
static float stair_activate (float x) inline static
Definition at line 22 of file activations.h.
Referenced by activate().
 {
     int n = floor(x);
     if (n%2 == 0) return floor(x/2.);
     else return (x - n) + floor(x/2.);
 }
stair_gradient()
static float stair_gradient (float x) inline static
Definition at line 74 of file activations.h.
Referenced by gradient().
 {
     if (floor(x) == x) return 0;
     return 1;
 }
tanh_activate()
static float tanh_activate (float x) inline static
Definition at line 42 of file activations.h.
Referenced by activate().
 {return (exp(2*x)-1)/(exp(2*x)+1);}
tanh_gradient()
static float tanh_gradient (float x) inline static
Definition at line 84 of file activations.h.
Referenced by gradient().
 {return 1-x*x;}