Darknet: darknet.c File Reference
darknet.c File Reference
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include "parser.h"
#include "utils.h"
#include "cuda.h"
#include "blas.h"
#include "connected_layer.h"
#include "convolutional_layer.h"
Functions
void predict_classifier (char *datacfg, char *cfgfile, char *weightfile, char *filename, int top)
void test_detector (char *datacfg, char *cfgfile, char *weightfile, char *filename, float thresh, float hier_thresh, char *outfile, int fullscreen)
void run_voxel (int argc, char **argv)
void run_yolo (int argc, char **argv)
void run_detector (int argc, char **argv)
void run_coco (int argc, char **argv)
void run_writing (int argc, char **argv)
void run_captcha (int argc, char **argv)
void run_nightmare (int argc, char **argv)
void run_dice (int argc, char **argv)
void run_compare (int argc, char **argv)
void run_classifier (int argc, char **argv)
void run_regressor (int argc, char **argv)
void run_char_rnn (int argc, char **argv)
void run_vid_rnn (int argc, char **argv)
void run_tag (int argc, char **argv)
void run_cifar (int argc, char **argv)
void run_go (int argc, char **argv)
void run_art (int argc, char **argv)
void run_super (int argc, char **argv)
void run_lsd (int argc, char **argv)
void average (int argc, char *argv[])
void speed (char *cfgfile, int tics)
void operations (char *cfgfile)
void oneoff (char *cfgfile, char *weightfile, char *outfile)
void oneoff2 (char *cfgfile, char *weightfile, char *outfile, int l)
void partial (char *cfgfile, char *weightfile, char *outfile, int max)
void rescale_net (char *cfgfile, char *weightfile, char *outfile)
void rgbgr_net (char *cfgfile, char *weightfile, char *outfile)
void reset_normalize_net (char *cfgfile, char *weightfile, char *outfile)
layer normalize_layer (layer l, int n)
void normalize_net (char *cfgfile, char *weightfile, char *outfile)
void statistics_net (char *cfgfile, char *weightfile)
void denormalize_net (char *cfgfile, char *weightfile, char *outfile)
void mkimg (char *cfgfile, char *weightfile, int h, int w, int num, char *prefix)
void visualize (char *cfgfile, char *weightfile)
int main (int argc, char **argv)
Function Documentation
average()
void average (int argc, char * argv[])
Definition at line 33 of file darknet.c.
References axpy_cpu(), layer::batch_normalize, layer::biases, layer::c, CONNECTED, CONVOLUTIONAL, gpu_index, layer::inputs, network::layers, load_weights(), network::n, layer::n, layer::outputs, parse_network_cfg(), layer::rolling_mean, layer::rolling_variance, save_weights(), scal_cpu(), layer::scales, layer::size, layer::type, and layer::weights.
Referenced by main().
 {
     char *cfgfile = argv[2];
     char *outfile = argv[3];
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     network sum = parse_network_cfg(cfgfile);
     char *weightfile = argv[4];
     load_weights(&sum, weightfile);
     int i, j;
     int n = argc - 5;
     for(i = 0; i < n; ++i){
         weightfile = argv[i+5];
         load_weights(&net, weightfile);
         for(j = 0; j < net.n; ++j){
             layer l = net.layers[j];
             layer out = sum.layers[j];
             if(l.type == CONVOLUTIONAL){
                 int num = l.n*l.c*l.size*l.size;
                 axpy_cpu(l.n, 1, l.biases, 1, out.biases, 1);
                 axpy_cpu(num, 1, l.weights, 1, out.weights, 1);
                 if(l.batch_normalize){
                     axpy_cpu(l.n, 1, l.scales, 1, out.scales, 1);
                     axpy_cpu(l.n, 1, l.rolling_mean, 1, out.rolling_mean, 1);
                     axpy_cpu(l.n, 1, l.rolling_variance, 1, out.rolling_variance, 1);
                 }
             }
             if(l.type == CONNECTED){
                 axpy_cpu(l.outputs, 1, l.biases, 1, out.biases, 1);
                 axpy_cpu(l.outputs*l.inputs, 1, l.weights, 1, out.weights, 1);
             }
         }
     }
     n = n+1;
     for(j = 0; j < net.n; ++j){
         layer l = sum.layers[j];
         if(l.type == CONVOLUTIONAL){
             int num = l.n*l.c*l.size*l.size;
             scal_cpu(l.n, 1./n, l.biases, 1);
             scal_cpu(num, 1./n, l.weights, 1);
                 if(l.batch_normalize){
                     scal_cpu(l.n, 1./n, l.scales, 1);
                     scal_cpu(l.n, 1./n, l.rolling_mean, 1);
                     scal_cpu(l.n, 1./n, l.rolling_variance, 1);
                 }
         }
         if(l.type == CONNECTED){
             scal_cpu(l.outputs, 1./n, l.biases, 1);
             scal_cpu(l.outputs*l.inputs, 1./n, l.weights, 1);
         }
     }
     save_weights(sum, outfile);
 }
denormalize_net()
void denormalize_net (char * cfgfile, char * weightfile, char * outfile)
Definition at line 314 of file darknet.c.
References layer::batch_normalize, CONNECTED, CONVOLUTIONAL, denormalize_connected_layer(), denormalize_convolutional_layer(), gpu_index, GRU, layer::input_h_layer, layer::input_r_layer, layer::input_z_layer, network::layers, load_weights(), network::n, parse_network_cfg(), save_weights(), layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, and layer::type.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     if (weightfile) {
         load_weights(&net, weightfile);
     }
     int i;
     for (i = 0; i < net.n; ++i) {
         layer l = net.layers[i];
         if (l.type == CONVOLUTIONAL && l.batch_normalize) {
             denormalize_convolutional_layer(l);
             net.layers[i].batch_normalize=0;
         }
         if (l.type == CONNECTED && l.batch_normalize) {
             denormalize_connected_layer(l);
             net.layers[i].batch_normalize=0;
         }
         if (l.type == GRU && l.batch_normalize) {
             denormalize_connected_layer(*l.input_z_layer);
             denormalize_connected_layer(*l.input_r_layer);
             denormalize_connected_layer(*l.input_h_layer);
             denormalize_connected_layer(*l.state_z_layer);
             denormalize_connected_layer(*l.state_r_layer);
             denormalize_connected_layer(*l.state_h_layer);
             l.input_z_layer->batch_normalize = 0;
             l.input_r_layer->batch_normalize = 0;
             l.input_h_layer->batch_normalize = 0;
             l.state_z_layer->batch_normalize = 0;
             l.state_r_layer->batch_normalize = 0;
             l.state_h_layer->batch_normalize = 0;
             net.layers[i].batch_normalize=0;
         }
     }
     save_weights(net, outfile);
 }
main()
int main (int argc, char ** argv)
Definition at line 389 of file darknet.c.
References average(), composite_3d(), denormalize_net(), find_arg(), find_char_arg(), find_float_arg(), find_int_arg(), gpu_index, mkimg(), normalize_net(), oneoff(), oneoff2(), operations(), partial(), predict_classifier(), rescale_net(), reset_normalize_net(), rgbgr_net(), run_art(), run_captcha(), run_char_rnn(), run_cifar(), run_classifier(), run_coco(), run_compare(), run_detector(), run_dice(), run_go(), run_lsd(), run_nightmare(), run_regressor(), run_super(), run_tag(), run_vid_rnn(), run_voxel(), run_writing(), run_yolo(), speed(), statistics_net(), test_detector(), test_resize(), and visualize().
 {
     //test_resize("data/bad.jpg");
     //test_box();
     //test_convolutional_layer();
     if(argc < 2){
         fprintf(stderr, "usage: %s <function>\n", argv[0]);
         return 0;
     }
     gpu_index = find_int_arg(argc, argv, "-i", 0);
     if(find_arg(argc, argv, "-nogpu")) {
         gpu_index = -1;
     }
 #ifndef GPU
     gpu_index = -1;
 #else
     if(gpu_index >= 0){
         cuda_set_device(gpu_index);
     }
 #endif
     if (0 == strcmp(argv[1], "average")){
         average(argc, argv);
     } else if (0 == strcmp(argv[1], "yolo")){
         run_yolo(argc, argv);
     } else if (0 == strcmp(argv[1], "voxel")){
         run_voxel(argc, argv);
     } else if (0 == strcmp(argv[1], "super")){
         run_super(argc, argv);
     } else if (0 == strcmp(argv[1], "lsd")){
         run_lsd(argc, argv);
     } else if (0 == strcmp(argv[1], "detector")){
         run_detector(argc, argv);
     } else if (0 == strcmp(argv[1], "detect")){
         float thresh = find_float_arg(argc, argv, "-thresh", .24);
         char *filename = (argc > 4) ? argv[4]: 0;
         char *outfile = find_char_arg(argc, argv, "-out", 0);
         int fullscreen = find_arg(argc, argv, "-fullscreen");
         test_detector("cfg/coco.data", argv[2], argv[3], filename, thresh, .5, outfile, fullscreen);
     } else if (0 == strcmp(argv[1], "cifar")){
         run_cifar(argc, argv);
     } else if (0 == strcmp(argv[1], "go")){
         run_go(argc, argv);
     } else if (0 == strcmp(argv[1], "rnn")){
         run_char_rnn(argc, argv);
     } else if (0 == strcmp(argv[1], "vid")){
         run_vid_rnn(argc, argv);
     } else if (0 == strcmp(argv[1], "coco")){
         run_coco(argc, argv);
     } else if (0 == strcmp(argv[1], "classify")){
         predict_classifier("cfg/imagenet1k.data", argv[2], argv[3], argv[4], 5);
     } else if (0 == strcmp(argv[1], "classifier")){
         run_classifier(argc, argv);
     } else if (0 == strcmp(argv[1], "regressor")){
         run_regressor(argc, argv);
     } else if (0 == strcmp(argv[1], "art")){
         run_art(argc, argv);
     } else if (0 == strcmp(argv[1], "tag")){
         run_tag(argc, argv);
     } else if (0 == strcmp(argv[1], "compare")){
         run_compare(argc, argv);
     } else if (0 == strcmp(argv[1], "dice")){
         run_dice(argc, argv);
     } else if (0 == strcmp(argv[1], "writing")){
         run_writing(argc, argv);
     } else if (0 == strcmp(argv[1], "3d")){
         composite_3d(argv[2], argv[3], argv[4], (argc > 5) ? atof(argv[5]) : 0);
     } else if (0 == strcmp(argv[1], "test")){
         test_resize(argv[2]);
     } else if (0 == strcmp(argv[1], "captcha")){
         run_captcha(argc, argv);
     } else if (0 == strcmp(argv[1], "nightmare")){
         run_nightmare(argc, argv);
     } else if (0 == strcmp(argv[1], "rgbgr")){
         rgbgr_net(argv[2], argv[3], argv[4]);
     } else if (0 == strcmp(argv[1], "reset")){
         reset_normalize_net(argv[2], argv[3], argv[4]);
     } else if (0 == strcmp(argv[1], "denormalize")){
         denormalize_net(argv[2], argv[3], argv[4]);
     } else if (0 == strcmp(argv[1], "statistics")){
         statistics_net(argv[2], argv[3]);
     } else if (0 == strcmp(argv[1], "normalize")){
         normalize_net(argv[2], argv[3], argv[4]);
     } else if (0 == strcmp(argv[1], "rescale")){
         rescale_net(argv[2], argv[3], argv[4]);
     } else if (0 == strcmp(argv[1], "ops")){
         operations(argv[2]);
     } else if (0 == strcmp(argv[1], "speed")){
         speed(argv[2], (argc > 3 && argv[3]) ? atoi(argv[3]) : 0);
     } else if (0 == strcmp(argv[1], "oneoff")){
         oneoff(argv[2], argv[3], argv[4]);
     } else if (0 == strcmp(argv[1], "oneoff2")){
         oneoff2(argv[2], argv[3], argv[4], atoi(argv[5]));
     } else if (0 == strcmp(argv[1], "partial")){
         partial(argv[2], argv[3], argv[4], atoi(argv[5]));
     } else if (0 == strcmp(argv[1], "average")){
         average(argc, argv);
     } else if (0 == strcmp(argv[1], "visualize")){
         visualize(argv[2], (argc > 3) ? argv[3] : 0);
     } else if (0 == strcmp(argv[1], "mkimg")){
         mkimg(argv[2], argv[3], atoi(argv[4]), atoi(argv[5]), atoi(argv[6]), argv[7]);
     } else if (0 == strcmp(argv[1], "imtest")){
         test_resize(argv[2]);
     } else {
         fprintf(stderr, "Not an option: %s\n", argv[1]);
     }
     return 0;
 }
mkimg()
void mkimg (char * cfgfile, char * weightfile, int h, int w, int num, char * prefix)
Definition at line 351 of file darknet.c.
References copy_image(), fill_image(), free_image(), get_weights(), ghost_image(), image::h, network::layers, load_network(), make_image(), layer::n, random_distort_image(), rotate_image_cw(), save_image(), and image::w.
Referenced by main().
 {
     network net = load_network(cfgfile, weightfile, 0);
     image *ims = get_weights(net.layers[0]);
     int n = net.layers[0].n;
     int z;
     for(z = 0; z < num; ++z){
         image im = make_image(h, w, 3);
         fill_image(im, .5);
         int i;
         for(i = 0; i < 100; ++i){
             image r = copy_image(ims[rand()%n]);
             rotate_image_cw(r, rand()%4);
             random_distort_image(r, 1, 1.5, 1.5);
             int dx = rand()%(w-r.w);
             int dy = rand()%(h-r.h);
             ghost_image(r, im, dx, dy);
             free_image(r);
         }
         char buff[256];
         sprintf(buff, "%s/gen_%d", prefix, z);
         save_image(im, buff);
         free_image(im);
     }
 }
normalize_layer()
layer normalize_layer (layer l, int n)
Definition at line 239 of file darknet.c.
References layer::batch_normalize, layer::rolling_mean, layer::rolling_variance, and layer::scales.
Referenced by normalize_net().
 {
     int j;
     l.batch_normalize=1;
     l.scales = calloc(n, sizeof(float));
     for(j = 0; j < n; ++j){
         l.scales[j] = 1;
     }
     l.rolling_mean = calloc(n, sizeof(float));
     l.rolling_variance = calloc(n, sizeof(float));
     return l;
 }
normalize_net()
void normalize_net (char * cfgfile, char * weightfile, char * outfile)
Definition at line 252 of file darknet.c.
References layer::batch_normalize, CONNECTED, CONVOLUTIONAL, gpu_index, GRU, layer::input_h_layer, layer::input_r_layer, layer::input_z_layer, network::layers, load_weights(), network::n, layer::n, normalize_layer(), layer::outputs, parse_network_cfg(), save_weights(), layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, and layer::type.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     int i;
     for(i = 0; i < net.n; ++i){
         layer l = net.layers[i];
         if(l.type == CONVOLUTIONAL && !l.batch_normalize){
             net.layers[i] = normalize_layer(l, l.n);
         }
         if (l.type == CONNECTED && !l.batch_normalize) {
             net.layers[i] = normalize_layer(l, l.outputs);
         }
         if (l.type == GRU && l.batch_normalize) {
             *l.input_z_layer = normalize_layer(*l.input_z_layer, l.input_z_layer->outputs);
             *l.input_r_layer = normalize_layer(*l.input_r_layer, l.input_r_layer->outputs);
             *l.input_h_layer = normalize_layer(*l.input_h_layer, l.input_h_layer->outputs);
             *l.state_z_layer = normalize_layer(*l.state_z_layer, l.state_z_layer->outputs);
             *l.state_r_layer = normalize_layer(*l.state_r_layer, l.state_r_layer->outputs);
             *l.state_h_layer = normalize_layer(*l.state_h_layer, l.state_h_layer->outputs);
             net.layers[i].batch_normalize=1;
         }
     }
     save_weights(net, outfile);
 }
oneoff()
void oneoff (char * cfgfile, char * weightfile, char * outfile)
Definition at line 124 of file darknet.c.
References layer::biases, layer::c, copy_cpu(), gpu_index, network::layers, load_weights(), network::n, layer::n, parse_network_cfg(), save_weights(), scal_cpu(), network::seen, and layer::weights.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     int oldn = net.layers[net.n - 2].n;
     int c = net.layers[net.n - 2].c;
     scal_cpu(oldn*c, .1, net.layers[net.n - 2].weights, 1);
     scal_cpu(oldn, 0, net.layers[net.n - 2].biases, 1);
     net.layers[net.n - 2].n = 9418;
     net.layers[net.n - 2].biases += 5;
     net.layers[net.n - 2].weights += 5*c;
     if(weightfile){
         load_weights(&net, weightfile);
     }
     net.layers[net.n - 2].biases -= 5;
     net.layers[net.n - 2].weights -= 5*c;
     net.layers[net.n - 2].n = oldn;
     printf("%d\n", oldn);
     layer l = net.layers[net.n - 2];
     copy_cpu(l.n/3, l.biases, 1, l.biases +   l.n/3, 1);
     copy_cpu(l.n/3, l.biases, 1, l.biases + 2*l.n/3, 1);
     copy_cpu(l.n/3*l.c, l.weights, 1, l.weights +   l.n/3*l.c, 1);
     copy_cpu(l.n/3*l.c, l.weights, 1, l.weights + 2*l.n/3*l.c, 1);
     *net.seen = 0;
     save_weights(net, outfile);
 }
oneoff2()
void oneoff2 (char * cfgfile, char * weightfile, char * outfile, int l)
Definition at line 151 of file darknet.c.
References gpu_index, load_weights_upto(), network::n, parse_network_cfg(), save_weights_upto(), and network::seen.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights_upto(&net, weightfile, 0, net.n);
         load_weights_upto(&net, weightfile, l, net.n);
     }
     *net.seen = 0;
     save_weights_upto(net, outfile, net.n);
 }
operations()
void operations (char * cfgfile)
Definition at line 106 of file darknet.c.
References layer::c, CONNECTED, CONVOLUTIONAL, gpu_index, layer::inputs, network::layers, network::n, layer::n, layer::out_h, layer::out_w, layer::outputs, parse_network_cfg(), layer::size, and layer::type.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     int i;
     long ops = 0;
     for(i = 0; i < net.n; ++i){
         layer l = net.layers[i];
         if(l.type == CONVOLUTIONAL){
             ops += 2l * l.n * l.size*l.size*l.c * l.out_h*l.out_w;
         } else if(l.type == CONNECTED){
             ops += 2l * l.inputs * l.outputs;
         }
     }
     printf("Floating Point Operations: %ld\n", ops);
     printf("Floating Point Operations: %.2f Bn\n", (float)ops/1000000000.);
 }
partial()
void partial (char * cfgfile, char * weightfile, char * outfile, int max)
Definition at line 163 of file darknet.c.
References gpu_index, load_weights_upto(), parse_network_cfg(), save_weights_upto(), and network::seen.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights_upto(&net, weightfile, 0, max);
     }
     *net.seen = 0;
     save_weights_upto(net, outfile, max);
 }
predict_classifier()
void predict_classifier (char * datacfg, char * cfgfile, char * weightfile, char * filename, int top)
Definition at line 661 of file classifier.c.
References image::data, free_image(), get_labels(), image::h, network::hierarchy, hierarchy_predictions(), load_image_color(), load_weights(), network_predict(), option_find_int(), option_find_str(), network::outputs, parse_network_cfg(), read_data_cfg(), resize_min(), resize_network(), sec(), set_batch_network(), top_k(), image::w, and network::w.
Referenced by main(), and run_classifier().
 {
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     list *options = read_data_cfg(datacfg);
     char *name_list = option_find_str(options, "names", 0);
     if(!name_list) name_list = option_find_str(options, "labels", "data/labels.list");
     if(top == 0) top = option_find_int(options, "top", 1);
     int i = 0;
     char **names = get_labels(name_list);
     clock_t time;
     int *indexes = calloc(top, sizeof(int));
     char buff[256];
     char *input = buff;
     int size = net.w;
     while(1){
         if(filename){
             strncpy(input, filename, 256);
         }else{
             printf("Enter Image Path: ");
             fflush(stdout);
             input = fgets(input, 256, stdin);
             if(!input) return;
             strtok(input, "\n");
         }
         image im = load_image_color(input, 0, 0);
         image r = resize_min(im, size);
         resize_network(&net, r.w, r.h);
         //printf("%d %d\n", r.w, r.h);
         float *X = r.data;
         time=clock();
         float *predictions = network_predict(net, X);
         if(net.hierarchy) hierarchy_predictions(predictions, net.outputs, net.hierarchy, 1, 1);
         top_k(predictions, net.outputs, top, indexes);
         printf("%s: Predicted in %f seconds.\n", input, sec(clock()-time));
         for(i = 0; i < top; ++i){
             int index = indexes[i];
             //if(net.hierarchy) printf("%d, %s: %f, parent: %s \n",index, names[index], predictions[index], (net.hierarchy->parent[index] >= 0) ? names[net.hierarchy->parent[index]] : "Root");
             //else printf("%s: %f\n",names[index], predictions[index]);
             printf("%5.2f%%: %s\n", predictions[index]*100, names[index]);
         }
         if(r.data != im.data) free_image(r);
         free_image(im);
         if (filename) break;
     }
 }
rescale_net()
void rescale_net (char * cfgfile, char * weightfile, char * outfile)
Definition at line 175 of file darknet.c.
References CONVOLUTIONAL, gpu_index, network::layers, load_weights(), network::n, parse_network_cfg(), rescale_weights(), save_weights(), and layer::type.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     int i;
     for(i = 0; i < net.n; ++i){
         layer l = net.layers[i];
         if(l.type == CONVOLUTIONAL){
             rescale_weights(l, 2, -.5);
             break;
         }
     }
     save_weights(net, outfile);
 }
reset_normalize_net()
void reset_normalize_net (char * cfgfile, char * weightfile, char * outfile)
Definition at line 211 of file darknet.c.
References layer::batch_normalize, CONNECTED, CONVOLUTIONAL, denormalize_connected_layer(), denormalize_convolutional_layer(), gpu_index, GRU, layer::input_h_layer, layer::input_r_layer, layer::input_z_layer, network::layers, load_weights(), network::n, parse_network_cfg(), save_weights(), layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, and layer::type.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     if (weightfile) {
         load_weights(&net, weightfile);
     }
     int i;
     for (i = 0; i < net.n; ++i) {
         layer l = net.layers[i];
         if (l.type == CONVOLUTIONAL && l.batch_normalize) {
             denormalize_convolutional_layer(l);
         }
         if (l.type == CONNECTED && l.batch_normalize) {
             denormalize_connected_layer(l);
         }
         if (l.type == GRU && l.batch_normalize) {
             denormalize_connected_layer(*l.input_z_layer);
             denormalize_connected_layer(*l.input_r_layer);
             denormalize_connected_layer(*l.input_h_layer);
             denormalize_connected_layer(*l.state_z_layer);
             denormalize_connected_layer(*l.state_r_layer);
             denormalize_connected_layer(*l.state_h_layer);
         }
     }
     save_weights(net, outfile);
 }
rgbgr_net()
void rgbgr_net (char * cfgfile, char * weightfile, char * outfile)
Definition at line 193 of file darknet.c.
References CONVOLUTIONAL, gpu_index, network::layers, load_weights(), network::n, parse_network_cfg(), rgbgr_weights(), save_weights(), and layer::type.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     int i;
     for(i = 0; i < net.n; ++i){
         layer l = net.layers[i];
         if(l.type == CONVOLUTIONAL){
             rgbgr_weights(l);
             break;
         }
     }
     save_weights(net, outfile);
 }
run_art()
void run_art (int argc, char ** argv)
Definition at line 64 of file art.c.
References demo_art(), and find_int_arg().
Referenced by main().
 {
     int cam_index = find_int_arg(argc, argv, "-c", 0);
     char *cfg = argv[2];
     char *weights = argv[3];
     demo_art(cfg, weights, cam_index);
 }
run_captcha()
void run_captcha (int argc, char ** argv)
Definition at line 346 of file captcha.c.
References test_captcha(), train_captcha(), and valid_captcha().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5]: 0;
     if(0==strcmp(argv[2], "train")) train_captcha(cfg, weights);
     else if(0==strcmp(argv[2], "test")) test_captcha(cfg, weights, filename);
     else if(0==strcmp(argv[2], "valid")) valid_captcha(cfg, weights, filename);
     //if(0==strcmp(argv[2], "test")) test_captcha(cfg, weights);
     //else if(0==strcmp(argv[2], "encode")) encode_captcha(cfg, weights);
     //else if(0==strcmp(argv[2], "decode")) decode_captcha(cfg, weights);
     //else if(0==strcmp(argv[2], "valid")) validate_captcha(cfg, weights);
 }
run_char_rnn()
void run_char_rnn (int argc, char ** argv)
Definition at line 467 of file rnn.c.
References find_arg(), find_char_arg(), find_float_arg(), find_int_arg(), test_char_rnn(), test_tactic_rnn(), train_char_rnn(), valid_char_rnn(), valid_tactic_rnn(), and vec_char_rnn().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *filename = find_char_arg(argc, argv, "-file", "data/shakespeare.txt");
     char *seed = find_char_arg(argc, argv, "-seed", "\n\n");
     int len = find_int_arg(argc, argv, "-len", 1000);
     float temp = find_float_arg(argc, argv, "-temp", .7);
     int rseed = find_int_arg(argc, argv, "-srand", time(0));
     int clear = find_arg(argc, argv, "-clear");
     int tokenized = find_arg(argc, argv, "-tokenized");
     char *tokens = find_char_arg(argc, argv, "-tokens", 0);
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     if(0==strcmp(argv[2], "train")) train_char_rnn(cfg, weights, filename, clear, tokenized);
     else if(0==strcmp(argv[2], "valid")) valid_char_rnn(cfg, weights, seed);
     else if(0==strcmp(argv[2], "validtactic")) valid_tactic_rnn(cfg, weights, seed);
     else if(0==strcmp(argv[2], "vec")) vec_char_rnn(cfg, weights, seed);
     else if(0==strcmp(argv[2], "generate")) test_char_rnn(cfg, weights, len, seed, temp, rseed, tokens);
     else if(0==strcmp(argv[2], "generatetactic")) test_tactic_rnn(cfg, weights, len, temp, rseed, tokens);
 }
run_cifar()
void run_cifar (int argc, char ** argv)
Definition at line 254 of file cifar.c.
References eval_cifar_csv(), extract_cifar(), test_cifar(), test_cifar_csv(), test_cifar_csvtrain(), test_cifar_multi(), train_cifar(), and train_cifar_distill().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     if(0==strcmp(argv[2], "train")) train_cifar(cfg, weights);
     else if(0==strcmp(argv[2], "extract")) extract_cifar();
     else if(0==strcmp(argv[2], "distill")) train_cifar_distill(cfg, weights);
     else if(0==strcmp(argv[2], "test")) test_cifar(cfg, weights);
     else if(0==strcmp(argv[2], "multi")) test_cifar_multi(cfg, weights);
     else if(0==strcmp(argv[2], "csv")) test_cifar_csv(cfg, weights);
     else if(0==strcmp(argv[2], "csvtrain")) test_cifar_csvtrain(cfg, weights);
     else if(0==strcmp(argv[2], "eval")) eval_cifar_csv();
 }
run_classifier()
void run_classifier (int argc, char ** argv)
Definition at line 1109 of file classifier.c.
References demo_classifier(), find_arg(), find_char_arg(), find_int_arg(), gpu_index, gun_classifier(), label_classifier(), predict_classifier(), read_intlist(), test_classifier(), threat_classifier(), train_classifier(), try_classifier(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), and validate_classifier_single().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *gpu_list = find_char_arg(argc, argv, "-gpus", 0);
     int ngpus;
     int *gpus = read_intlist(gpu_list, &ngpus, gpu_index);
     int cam_index = find_int_arg(argc, argv, "-c", 0);
     int top = find_int_arg(argc, argv, "-t", 0);
     int clear = find_arg(argc, argv, "-clear");
     char *data = argv[3];
     char *cfg = argv[4];
     char *weights = (argc > 5) ? argv[5] : 0;
     char *filename = (argc > 6) ? argv[6]: 0;
     char *layer_s = (argc > 7) ? argv[7]: 0;
     int layer = layer_s ? atoi(layer_s) : -1;
     if(0==strcmp(argv[2], "predict")) predict_classifier(data, cfg, weights, filename, top);
     else if(0==strcmp(argv[2], "try")) try_classifier(data, cfg, weights, filename, atoi(layer_s));
     else if(0==strcmp(argv[2], "train")) train_classifier(data, cfg, weights, gpus, ngpus, clear);
     else if(0==strcmp(argv[2], "demo")) demo_classifier(data, cfg, weights, cam_index, filename);
     else if(0==strcmp(argv[2], "gun")) gun_classifier(data, cfg, weights, cam_index, filename);
     else if(0==strcmp(argv[2], "threat")) threat_classifier(data, cfg, weights, cam_index, filename);
     else if(0==strcmp(argv[2], "test")) test_classifier(data, cfg, weights, layer);
     else if(0==strcmp(argv[2], "label")) label_classifier(data, cfg, weights);
     else if(0==strcmp(argv[2], "valid")) validate_classifier_single(data, cfg, weights);
     else if(0==strcmp(argv[2], "validmulti")) validate_classifier_multi(data, cfg, weights);
     else if(0==strcmp(argv[2], "valid10")) validate_classifier_10(data, cfg, weights);
     else if(0==strcmp(argv[2], "validcrop")) validate_classifier_crop(data, cfg, weights);
     else if(0==strcmp(argv[2], "validfull")) validate_classifier_full(data, cfg, weights);
 }
run_coco()
void run_coco (int argc, char ** argv)
Definition at line 364 of file coco.c.
References coco_classes, demo(), find_char_arg(), find_float_arg(), find_int_arg(), test_coco(), train_coco(), validate_coco(), and validate_coco_recall().
Referenced by main().
 {
     char *prefix = find_char_arg(argc, argv, "-prefix", 0);
     float thresh = find_float_arg(argc, argv, "-thresh", .2);
     int cam_index = find_int_arg(argc, argv, "-c", 0);
     int frame_skip = find_int_arg(argc, argv, "-s", 0);
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5]: 0;
     int avg = find_int_arg(argc, argv, "-avg", 1);
     if(0==strcmp(argv[2], "test")) test_coco(cfg, weights, filename, thresh);
     else if(0==strcmp(argv[2], "train")) train_coco(cfg, weights);
     else if(0==strcmp(argv[2], "valid")) validate_coco(cfg, weights);
     else if(0==strcmp(argv[2], "recall")) validate_coco_recall(cfg, weights);
     else if(0==strcmp(argv[2], "demo")) demo(cfg, weights, thresh, cam_index, filename, coco_classes, 80, frame_skip, prefix, avg, .5, 0,0,0,0);
 }
run_compare()
void run_compare (int argc, char ** argv)
Definition at line 333 of file compare.c.
References BattleRoyaleWithCheese(), SortMaster3000(), train_compare(), and validate_compare().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     //char *filename = (argc > 5) ? argv[5]: 0;
     if(0==strcmp(argv[2], "train")) train_compare(cfg, weights);
     else if(0==strcmp(argv[2], "valid")) validate_compare(cfg, weights);
     else if(0==strcmp(argv[2], "sort")) SortMaster3000(cfg, weights);
     else if(0==strcmp(argv[2], "battle")) BattleRoyaleWithCheese(cfg, weights);
     /*
        else if(0==strcmp(argv[2], "train")) train_coco(cfg, weights);
        else if(0==strcmp(argv[2], "extract")) extract_boxes(cfg, weights);
        else if(0==strcmp(argv[2], "valid")) validate_recall(cfg, weights);
      */
 }
run_detector()
void run_detector (int argc, char ** argv)
Definition at line 663 of file detector.c.
References demo(), find_arg(), find_char_arg(), find_float_arg(), find_int_arg(), get_labels(), gpu_index, option_find_int(), option_find_str(), read_data_cfg(), test_detector(), train_detector(), validate_detector(), validate_detector_flip(), and validate_detector_recall().
Referenced by main().
 {
     char *prefix = find_char_arg(argc, argv, "-prefix", 0);
     float thresh = find_float_arg(argc, argv, "-thresh", .24);
     float hier_thresh = find_float_arg(argc, argv, "-hier", .5);
     int cam_index = find_int_arg(argc, argv, "-c", 0);
     int frame_skip = find_int_arg(argc, argv, "-s", 0);
     int avg = find_int_arg(argc, argv, "-avg", 3);
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *gpu_list = find_char_arg(argc, argv, "-gpus", 0);
     char *outfile = find_char_arg(argc, argv, "-out", 0);
     int *gpus = 0;
     int gpu = 0;
     int ngpus = 0;
     if(gpu_list){
         printf("%s\n", gpu_list);
         int len = strlen(gpu_list);
         ngpus = 1;
         int i;
         for(i = 0; i < len; ++i){
             if (gpu_list[i] == ',') ++ngpus;
         }
         gpus = calloc(ngpus, sizeof(int));
         for(i = 0; i < ngpus; ++i){
             gpus[i] = atoi(gpu_list);
             gpu_list = strchr(gpu_list, ',')+1;
         }
     } else {
         gpu = gpu_index;
         gpus = &gpu;
         ngpus = 1;
     }
     int clear = find_arg(argc, argv, "-clear");
     int fullscreen = find_arg(argc, argv, "-fullscreen");
     int width = find_int_arg(argc, argv, "-w", 0);
     int height = find_int_arg(argc, argv, "-h", 0);
     int fps = find_int_arg(argc, argv, "-fps", 0);
     char *datacfg = argv[3];
     char *cfg = argv[4];
     char *weights = (argc > 5) ? argv[5] : 0;
     char *filename = (argc > 6) ? argv[6]: 0;
     if(0==strcmp(argv[2], "test")) test_detector(datacfg, cfg, weights, filename, thresh, hier_thresh, outfile, fullscreen);
     else if(0==strcmp(argv[2], "train")) train_detector(datacfg, cfg, weights, gpus, ngpus, clear);
     else if(0==strcmp(argv[2], "valid")) validate_detector(datacfg, cfg, weights, outfile);
     else if(0==strcmp(argv[2], "valid2")) validate_detector_flip(datacfg, cfg, weights, outfile);
     else if(0==strcmp(argv[2], "recall")) validate_detector_recall(cfg, weights);
     else if(0==strcmp(argv[2], "demo")) {
         list *options = read_data_cfg(datacfg);
         int classes = option_find_int(options, "classes", 20);
         char *name_list = option_find_str(options, "names", "data/names.list");
         char **names = get_labels(name_list);
         demo(cfg, weights, thresh, cam_index, filename, names, classes, frame_skip, prefix, avg, hier_thresh, width, height, fps, fullscreen);
     }
 }
run_dice()
void run_dice (int argc, char ** argv)
Definition at line 104 of file dice.c.
References test_dice(), train_dice(), and validate_dice().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5]: 0;
     if(0==strcmp(argv[2], "test")) test_dice(cfg, weights, filename);
     else if(0==strcmp(argv[2], "train")) train_dice(cfg, weights);
     else if(0==strcmp(argv[2], "valid")) validate_dice(cfg, weights);
 }
run_go()
void run_go (int argc, char ** argv)
Definition at line 871 of file go.c.
References engine_go(), find_arg(), find_char_arg(), gpu_index, self_go(), test_go(), train_go(), and valid_go().
Referenced by main().
 {
     //boards_go();
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *gpu_list = find_char_arg(argc, argv, "-gpus", 0);
     int *gpus = 0;
     int gpu = 0;
     int ngpus = 0;
     if(gpu_list){
         printf("%s\n", gpu_list);
         int len = strlen(gpu_list);
         ngpus = 1;
         int i;
         for(i = 0; i < len; ++i){
             if (gpu_list[i] == ',') ++ngpus;
         }
         gpus = calloc(ngpus, sizeof(int));
         for(i = 0; i < ngpus; ++i){
             gpus[i] = atoi(gpu_list);
             gpu_list = strchr(gpu_list, ',')+1;
         }
     } else {
         gpu = gpu_index;
         gpus = &gpu;
         ngpus = 1;
     }
     int clear = find_arg(argc, argv, "-clear");
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *c2 = (argc > 5) ? argv[5] : 0;
     char *w2 = (argc > 6) ? argv[6] : 0;
     int multi = find_arg(argc, argv, "-multi");
     if(0==strcmp(argv[2], "train")) train_go(cfg, weights, c2, gpus, ngpus, clear);
     else if(0==strcmp(argv[2], "valid")) valid_go(cfg, weights, multi, c2);
     else if(0==strcmp(argv[2], "self")) self_go(cfg, weights, c2, w2, multi);
     else if(0==strcmp(argv[2], "test")) test_go(cfg, weights, multi);
     else if(0==strcmp(argv[2], "engine")) engine_go(cfg, weights, multi);
 }
run_lsd()
void run_lsd (int argc, char ** argv)
Definition at line 1111 of file lsd.c.
References find_arg(), find_char_arg(), test_dcgan(), test_lsd(), train_colorizer(), and train_dcgan().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     int clear = find_arg(argc, argv, "-clear");
     int display = find_arg(argc, argv, "-display");
     char *file = find_char_arg(argc, argv, "-file", "/home/pjreddie/data/imagenet/imagenet1k.train.list");
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5] : 0;
     char *acfg = argv[5];
     char *aweights = (argc > 6) ? argv[6] : 0;
     //if(0==strcmp(argv[2], "train")) train_lsd(cfg, weights, clear);
     //else if(0==strcmp(argv[2], "train2")) train_lsd2(cfg, weights, acfg, aweights, clear);
     //else if(0==strcmp(argv[2], "traincolor")) train_colorizer(cfg, weights, acfg, aweights, clear);
     //else if(0==strcmp(argv[2], "train3")) train_lsd3(argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], clear);
     if(0==strcmp(argv[2], "traingan")) train_dcgan(cfg, weights, acfg, aweights, clear, display, file);
     else if(0==strcmp(argv[2], "traincolor")) train_colorizer(cfg, weights, acfg, aweights, clear, display);
     else if(0==strcmp(argv[2], "gan")) test_dcgan(cfg, weights);
     else if(0==strcmp(argv[2], "test")) test_lsd(cfg, weights, filename, 0);
     else if(0==strcmp(argv[2], "color")) test_lsd(cfg, weights, filename, 1);
     /*
        else if(0==strcmp(argv[2], "valid")) validate_lsd(cfg, weights);
      */
 }
run_nightmare()
void run_nightmare (int argc, char ** argv)
Definition at line 285 of file nightmare.c.
References basecfg(), image::c, copy_image(), crop_image(), image::data, find_arg(), find_char_arg(), find_float_arg(), find_int_arg(), free_image(), get_network_image(), grayscale_image(), image::h, network::h, network::layers, letterbox_image(), load_image_color(), load_weights(), make_image(), network::n, network_predict(), optimize_picture(), parse_network_cfg(), reconstruct_picture(), REGION, resize_image(), rotate_image(), save_image(), set_batch_network(), show_image(), layer::type, image::w, network::w, and zero_objectness().
Referenced by main().
 {
     srand(0);
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [cfg] [weights] [image] [layer] [options! (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[2];
     char *weights = argv[3];
     char *input = argv[4];
     int max_layer = atoi(argv[5]);
     int range = find_int_arg(argc, argv, "-range", 1);
     int norm = find_int_arg(argc, argv, "-norm", 1);
     int rounds = find_int_arg(argc, argv, "-rounds", 1);
     int iters = find_int_arg(argc, argv, "-iters", 10);
     int octaves = find_int_arg(argc, argv, "-octaves", 4);
     float zoom = find_float_arg(argc, argv, "-zoom", 1.);
     float rate = find_float_arg(argc, argv, "-rate", .04);
     float thresh = find_float_arg(argc, argv, "-thresh", 1.);
     float rotate = find_float_arg(argc, argv, "-rotate", 0);
     float momentum = find_float_arg(argc, argv, "-momentum", .9);
     float lambda = find_float_arg(argc, argv, "-lambda", .01);
     char *prefix = find_char_arg(argc, argv, "-prefix", 0);
     int reconstruct = find_arg(argc, argv, "-reconstruct");
     int smooth_size = find_int_arg(argc, argv, "-smooth", 1);
     network net = parse_network_cfg(cfg);
     load_weights(&net, weights);
     char *cfgbase = basecfg(cfg);
     char *imbase = basecfg(input);
     set_batch_network(&net, 1);
     image im = load_image_color(input, 0, 0);
     if(0){
         float scale = 1;
         if(im.w > 512 || im.h > 512){
             if(im.w > im.h) scale = 512.0/im.w;
             else scale = 512.0/im.h;
         }
         image resized = resize_image(im, scale*im.w, scale*im.h);
         free_image(im);
         im = resized;
     }
     //im = letterbox_image(im, net.w, net.h);
     float *features = 0;
     image update;
     if (reconstruct){
         net.n = max_layer;
         im = letterbox_image(im, net.w, net.h);
         //resize_network(&net, im.w, im.h);
         network_predict(net, im.data);
         if(net.layers[net.n-1].type == REGION){
             printf("region!\n");
             zero_objectness(net.layers[net.n-1]);
         }
         image out_im = copy_image(get_network_image(net));
         /*
            image crop = crop_image(out_im, zz, zz, out_im.w-2*zz, out_im.h-2*zz);
         //flip_image(crop);
         image f_im = resize_image(crop, out_im.w, out_im.h);
         free_image(crop);
          */
         printf("%d features\n", out_im.w*out_im.h*out_im.c);
         features = out_im.data;
         /*
         int i;
            for(i = 0; i < 14*14*512; ++i){
         //features[i] += rand_uniform(-.19, .19);
         }
         free_image(im);
         im = make_random_image(im.w, im.h, im.c);
          */
         update = make_image(im.w, im.h, im.c);
     }
     int e;
     int n;
     for(e = 0; e < rounds; ++e){
         fprintf(stderr, "Iteration: ");
         fflush(stderr);
         for(n = 0; n < iters; ++n){
             fprintf(stderr, "%d, ", n);
             fflush(stderr);
             if(reconstruct){
                 reconstruct_picture(net, features, im, update, rate, momentum, lambda, smooth_size, 1);
                 //if ((n+1)%30 == 0) rate *= .5;
                 show_image(im, "reconstruction");
 #ifdef OPENCV
                 cvWaitKey(10);
 #endif
             }else{
                 int layer = max_layer + rand()%range - range/2;
                 int octave = rand()%octaves;
                 optimize_picture(&net, im, layer, 1/pow(1.33333333, octave), rate, thresh, norm);
             }
         }
         fprintf(stderr, "done\n");
         if(0){
             image g = grayscale_image(im);
             free_image(im);
             im = g;
         }
         char buff[256];
         if (prefix){
             sprintf(buff, "%s/%s_%s_%d_%06d",prefix, imbase, cfgbase, max_layer, e);
         }else{
             sprintf(buff, "%s_%s_%d_%06d",imbase, cfgbase, max_layer, e);
         }
         printf("%d %s\n", e, buff);
         save_image(im, buff);
         //show_image(im, buff);
         //cvWaitKey(0);
         if(rotate){
             image rot = rotate_image(im, rotate);
             free_image(im);
             im = rot;
         }
         image crop = crop_image(im, im.w * (1. - zoom)/2., im.h * (1.-zoom)/2., im.w*zoom, im.h*zoom);
         image resized = resize_image(crop, im.w, im.h);
         free_image(im);
         free_image(crop);
         im = resized;
     }
 }
run_regressor()
void run_regressor (int argc, char ** argv)
Definition at line 214 of file regressor.c.
References demo_regressor(), find_arg(), find_char_arg(), find_int_arg(), gpu_index, predict_regressor(), and train_regressor().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *gpu_list = find_char_arg(argc, argv, "-gpus", 0);
     int *gpus = 0;
     int gpu = 0;
     int ngpus = 0;
     if(gpu_list){
         printf("%s\n", gpu_list);
         int len = strlen(gpu_list);
         ngpus = 1;
         int i;
         for(i = 0; i < len; ++i){
             if (gpu_list[i] == ',') ++ngpus;
         }
         gpus = calloc(ngpus, sizeof(int));
         for(i = 0; i < ngpus; ++i){
             gpus[i] = atoi(gpu_list);
             gpu_list = strchr(gpu_list, ',')+1;
         }
     } else {
         gpu = gpu_index;
         gpus = &gpu;
         ngpus = 1;
     }
     int cam_index = find_int_arg(argc, argv, "-c", 0);
     int clear = find_arg(argc, argv, "-clear");
     char *data = argv[3];
     char *cfg = argv[4];
     char *weights = (argc > 5) ? argv[5] : 0;
     char *filename = (argc > 6) ? argv[6]: 0;
     if(0==strcmp(argv[2], "test")) predict_regressor(data, cfg, weights);
     else if(0==strcmp(argv[2], "train")) train_regressor(data, cfg, weights, gpus, ngpus, clear);
     else if(0==strcmp(argv[2], "demo")) demo_regressor(data, cfg, weights, cam_index, filename);
 }
run_super()
void run_super (int argc, char ** argv)
Definition at line 113 of file super.c.
References find_arg(), test_super(), and train_super().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5] : 0;
     int clear = find_arg(argc, argv, "-clear");
     if(0==strcmp(argv[2], "train")) train_super(cfg, weights, clear);
     else if(0==strcmp(argv[2], "test")) test_super(cfg, weights, filename);
     /*
     else if(0==strcmp(argv[2], "valid")) validate_super(cfg, weights);
     */
 }
run_tag()
void run_tag (int argc, char ** argv)
Definition at line 135 of file tag.c.
References find_arg(), test_tag(), and train_tag().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     int clear = find_arg(argc, argv, "-clear");
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5] : 0;
     if(0==strcmp(argv[2], "train")) train_tag(cfg, weights, clear);
     else if(0==strcmp(argv[2], "test")) test_tag(cfg, weights, filename);
 }
run_vid_rnn()
void run_vid_rnn (int argc, char ** argv)
Definition at line 210 of file rnn_vid.c.
Referenced by main().
 {}
run_voxel()
void run_voxel (int argc, char ** argv)
Definition at line 148 of file voxel.c.
References extract_voxel(), test_voxel(), and train_voxel().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5] : 0;
     if(0==strcmp(argv[2], "train")) train_voxel(cfg, weights);
     else if(0==strcmp(argv[2], "test")) test_voxel(cfg, weights, filename);
     else if(0==strcmp(argv[2], "extract")) extract_voxel(argv[3], argv[4], argv[5]);
     /*
        else if(0==strcmp(argv[2], "valid")) validate_voxel(cfg, weights);
      */
 }
run_writing()
void run_writing (int argc, char ** argv)
Definition at line 133 of file writing.c.
References test_writing(), and train_writing().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5] : 0;
     if(0==strcmp(argv[2], "train")) train_writing(cfg, weights);
     else if(0==strcmp(argv[2], "test")) test_writing(cfg, weights, filename);
 }
run_yolo()
void run_yolo (int argc, char ** argv)
Definition at line 332 of file yolo.c.
References demo(), find_char_arg(), find_float_arg(), find_int_arg(), test_yolo(), train_yolo(), validate_yolo(), validate_yolo_recall(), and voc_names.
Referenced by main().
 {
     char *prefix = find_char_arg(argc, argv, "-prefix", 0);
     float thresh = find_float_arg(argc, argv, "-thresh", .2);
     int cam_index = find_int_arg(argc, argv, "-c", 0);
     int frame_skip = find_int_arg(argc, argv, "-s", 0);
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     int avg = find_int_arg(argc, argv, "-avg", 1);
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5]: 0;
     if(0==strcmp(argv[2], "test")) test_yolo(cfg, weights, filename, thresh);
     else if(0==strcmp(argv[2], "train")) train_yolo(cfg, weights);
     else if(0==strcmp(argv[2], "valid")) validate_yolo(cfg, weights);
     else if(0==strcmp(argv[2], "recall")) validate_yolo_recall(cfg, weights);
     else if(0==strcmp(argv[2], "demo")) demo(cfg, weights, thresh, cam_index, filename, voc_names, 20, frame_skip, prefix, avg, .5, 0,0,0,0);
 }
speed()
void speed (char * cfgfile, int tics)
Definition at line 89 of file darknet.c.
References network::batch, network::c, image::data, network::h, make_image(), network_predict(), parse_network_cfg(), set_batch_network(), and network::w.
Referenced by main().
 {
     if (tics == 0) tics = 1000;
     network net = parse_network_cfg(cfgfile);
     set_batch_network(&net, 1);
     int i;
     time_t start = time(0);
     image im = make_image(net.w, net.h, net.c*net.batch);
     for(i = 0; i < tics; ++i){
         network_predict(net, im.data);
     }
     double t = difftime(time(0), start);
     printf("\n%d evals, %f Seconds\n", tics, t);
     printf("Speed: %f sec/eval\n", t/tics);
     printf("Speed: %f Hz\n", tics/t);
 }
statistics_net()
void statistics_net (char * cfgfile, char * weightfile)
Definition at line 281 of file darknet.c.
References layer::batch_normalize, CONNECTED, gpu_index, GRU, layer::input_h_layer, layer::input_r_layer, layer::input_z_layer, network::layers, load_weights(), network::n, parse_network_cfg(), layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, statistics_connected_layer(), and layer::type.
Referenced by main().
 {
     gpu_index = -1;
     network net = parse_network_cfg(cfgfile);
     if (weightfile) {
         load_weights(&net, weightfile);
     }
     int i;
     for (i = 0; i < net.n; ++i) {
         layer l = net.layers[i];
         if (l.type == CONNECTED && l.batch_normalize) {
             printf("Connected Layer %d\n", i);
             statistics_connected_layer(l);
         }
         if (l.type == GRU && l.batch_normalize) {
             printf("GRU Layer %d\n", i);
             printf("Input Z\n");
             statistics_connected_layer(*l.input_z_layer);
             printf("Input R\n");
             statistics_connected_layer(*l.input_r_layer);
             printf("Input H\n");
             statistics_connected_layer(*l.input_h_layer);
             printf("State Z\n");
             statistics_connected_layer(*l.state_z_layer);
             printf("State R\n");
             statistics_connected_layer(*l.state_r_layer);
             printf("State H\n");
             statistics_connected_layer(*l.state_h_layer);
         }
         printf("\n");
     }
 }
test_detector()
void test_detector (char * datacfg, char * cfgfile, char * weightfile, char * filename, float thresh, float hier_thresh, char * outfile, int fullscreen)
Definition at line 591 of file detector.c.
References layer::classes, image::data, do_nms_obj(), draw_detections(), free_image(), free_ptrs(), get_labels(), get_region_boxes(), image::h, network::h, layer::h, network::layers, letterbox_image(), load_alphabet(), load_image_color(), load_weights(), network::n, layer::n, network_predict(), option_find_str(), parse_network_cfg(), read_data_cfg(), save_image(), sec(), set_batch_network(), show_image(), image::w, network::w, and layer::w.
Referenced by main(), and run_detector().
 {
     list *options = read_data_cfg(datacfg);
     char *name_list = option_find_str(options, "names", "data/names.list");
     char **names = get_labels(name_list);
     image **alphabet = load_alphabet();
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     clock_t time;
     char buff[256];
     char *input = buff;
     int j;
     float nms=.4;
     while(1){
         if(filename){
             strncpy(input, filename, 256);
         } else {
             printf("Enter Image Path: ");
             fflush(stdout);
             input = fgets(input, 256, stdin);
             if(!input) return;
             strtok(input, "\n");
         }
         image im = load_image_color(input,0,0);
         image sized = letterbox_image(im, net.w, net.h);
         //image sized = resize_image(im, net.w, net.h);
         //image sized2 = resize_max(im, net.w);
         //image sized = crop_image(sized2, -((net.w - sized2.w)/2), -((net.h - sized2.h)/2), net.w, net.h);
         //resize_network(&net, sized.w, sized.h);
         layer l = net.layers[net.n-1];
         box *boxes = calloc(l.w*l.h*l.n, sizeof(box));
         float **probs = calloc(l.w*l.h*l.n, sizeof(float *));
         for(j = 0; j < l.w*l.h*l.n; ++j) probs[j] = calloc(l.classes + 1, sizeof(float *));
         float *X = sized.data;
         time=clock();
         network_predict(net, X);
         printf("%s: Predicted in %f seconds.\n", input, sec(clock()-time));
         get_region_boxes(l, im.w, im.h, net.w, net.h, thresh, probs, boxes, 0, 0, hier_thresh, 1);
         if (nms) do_nms_obj(boxes, probs, l.w*l.h*l.n, l.classes, nms);
         //else if (nms) do_nms_sort(boxes, probs, l.w*l.h*l.n, l.classes, nms);
         draw_detections(im, l.w*l.h*l.n, thresh, boxes, probs, names, alphabet, l.classes);
         if(outfile){
             save_image(im, outfile);
         }
         else{
             save_image(im, "predictions");
 #ifdef OPENCV
             cvNamedWindow("predictions", CV_WINDOW_NORMAL);
             if(fullscreen){
                 cvSetWindowProperty("predictions", CV_WND_PROP_FULLSCREEN, CV_WINDOW_FULLSCREEN);
             }
             show_image(im, "predictions");
             cvWaitKey(0);
             cvDestroyAllWindows();
 #endif
         }
         free_image(im);
         free_image(sized);
         free(boxes);
         free_ptrs((void **)probs, l.w*l.h*l.n);
         if (filename) break;
     }
 }
visualize()
void visualize (char * cfgfile, char * weightfile)
Definition at line 377 of file darknet.c.
References load_weights(), parse_network_cfg(), and visualize_network().
Referenced by main().
 {
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     visualize_network(net);
 #ifdef OPENCV
     cvWaitKey(0);
 #endif
 }