Darknet: crnn_layer.c File Reference
crnn_layer.c File Reference
#include "crnn_layer.h"
#include "convolutional_layer.h"
#include "utils.h"
#include "cuda.h"
#include "blas.h"
#include "gemm.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static void increment_layer (layer *l, int steps)
layer make_crnn_layer (int batch, int h, int w, int c, int hidden_filters, int output_filters, int steps, ACTIVATION activation, int batch_normalize)
void update_crnn_layer (layer l, int batch, float learning_rate, float momentum, float decay)
void forward_crnn_layer (layer l, network net)
void backward_crnn_layer (layer l, network net)
Function Documentation
backward_crnn_layer()
void backward_crnn_layer (layer l, network net)
Definition at line 132 of file crnn_layer.c.
References axpy_cpu(), backward_convolutional_layer(), layer::batch, copy_cpu(), network::delta, layer::delta, layer::hidden, increment_layer(), network::input, layer::input_layer, layer::inputs, layer::output, layer::output_layer, layer::outputs, layer::self_layer, layer::shortcut, layer::state, layer::steps, and network::train.
Referenced by make_crnn_layer().
 {
     network s = net;
     int i;
     layer input_layer = *(l.input_layer);
     layer self_layer = *(l.self_layer);
     layer output_layer = *(l.output_layer);
     increment_layer(&input_layer, l.steps-1);
     increment_layer(&self_layer, l.steps-1);
     increment_layer(&output_layer, l.steps-1);
     l.state += l.hidden*l.batch*l.steps;
     for (i = l.steps-1; i >= 0; --i) {
         copy_cpu(l.hidden * l.batch, input_layer.output, 1, l.state, 1);
         axpy_cpu(l.hidden * l.batch, 1, self_layer.output, 1, l.state, 1);
         s.input = l.state;
         s.delta = self_layer.delta;
         backward_convolutional_layer(output_layer, s);
         l.state -= l.hidden*l.batch;
         /*
            if(i > 0){
            copy_cpu(l.hidden * l.batch, input_layer.output - l.hidden*l.batch, 1, l.state, 1);
            axpy_cpu(l.hidden * l.batch, 1, self_layer.output - l.hidden*l.batch, 1, l.state, 1);
            }else{
            fill_cpu(l.hidden * l.batch, 0, l.state, 1);
            }
          */
         s.input = l.state;
         s.delta = self_layer.delta - l.hidden*l.batch;
         if (i == 0) s.delta = 0;
         backward_convolutional_layer(self_layer, s);
         copy_cpu(l.hidden*l.batch, self_layer.delta, 1, input_layer.delta, 1);
         if (i > 0 && l.shortcut) axpy_cpu(l.hidden*l.batch, 1, self_layer.delta, 1, self_layer.delta - l.hidden*l.batch, 1);
         s.input = net.input + i*l.inputs*l.batch;
         if(net.delta) s.delta = net.delta + i*l.inputs*l.batch;
         else s.delta = 0;
         backward_convolutional_layer(input_layer, s);
         increment_layer(&input_layer, -1);
         increment_layer(&self_layer, -1);
         increment_layer(&output_layer, -1);
     }
 }
forward_crnn_layer()
void forward_crnn_layer (layer l, network net)
Definition at line 91 of file crnn_layer.c.
References axpy_cpu(), layer::batch, copy_cpu(), layer::delta, fill_cpu(), forward_convolutional_layer(), layer::hidden, increment_layer(), network::input, layer::input_layer, layer::inputs, layer::output, layer::output_layer, layer::outputs, layer::self_layer, layer::shortcut, layer::state, layer::steps, and network::train.
Referenced by make_crnn_layer().
 {
     network s = net;
     s.train = net.train;
     int i;
     layer input_layer = *(l.input_layer);
     layer self_layer = *(l.self_layer);
     layer output_layer = *(l.output_layer);
     fill_cpu(l.outputs * l.batch * l.steps, 0, output_layer.delta, 1);
     fill_cpu(l.hidden * l.batch * l.steps, 0, self_layer.delta, 1);
     fill_cpu(l.hidden * l.batch * l.steps, 0, input_layer.delta, 1);
     if(net.train) fill_cpu(l.hidden * l.batch, 0, l.state, 1);
     for (i = 0; i < l.steps; ++i) {
         s.input = net.input;
         forward_convolutional_layer(input_layer, s);
         s.input = l.state;
         forward_convolutional_layer(self_layer, s);
         float *old_state = l.state;
         if(net.train) l.state += l.hidden*l.batch;
         if(l.shortcut){
             copy_cpu(l.hidden * l.batch, old_state, 1, l.state, 1);
         }else{
             fill_cpu(l.hidden * l.batch, 0, l.state, 1);
         }
         axpy_cpu(l.hidden * l.batch, 1, input_layer.output, 1, l.state, 1);
         axpy_cpu(l.hidden * l.batch, 1, self_layer.output, 1, l.state, 1);
         s.input = l.state;
         forward_convolutional_layer(output_layer, s);
         net.input += l.inputs*l.batch;
         increment_layer(&input_layer, 1);
         increment_layer(&self_layer, 1);
         increment_layer(&output_layer, 1);
     }
 }
increment_layer()
static void increment_layer (layer * l, int steps) static
Definition at line 13 of file crnn_layer.c.
References layer::batch, layer::delta, layer::output, layer::outputs, layer::x, and layer::x_norm.
Referenced by backward_crnn_layer(), and forward_crnn_layer().
 {
     int num = l->outputs*l->batch*steps;
     l->output += num;
     l->delta += num;
     l->x += num;
     l->x_norm += num;
 #ifdef GPU
     l->output_gpu += num;
     l->delta_gpu += num;
     l->x_gpu += num;
     l->x_norm_gpu += num;
 #endif
 }
make_crnn_layer()
layer make_crnn_layer (int batch, int h, int w, int c, int hidden_filters, int output_filters, int steps, ACTIVATION activation, int batch_normalize)
Definition at line 29 of file crnn_layer.c.
References layer::backward, backward_crnn_layer(), layer::backward_gpu, layer::batch, layer::c, CRNN, layer::delta, layer::forward, forward_crnn_layer(), layer::forward_gpu, layer::h, layer::hidden, layer::input_layer, layer::inputs, make_convolutional_layer(), layer::out_c, layer::out_h, layer::out_w, layer::output, layer::output_layer, layer::outputs, layer::self_layer, layer::state, layer::steps, layer::type, layer::update, update_crnn_layer(), layer::update_gpu, and layer::w.
Referenced by parse_crnn().
 {
     fprintf(stderr, "CRNN Layer: %d x %d x %d image, %d filters\n", h,w,c,output_filters);
     batch = batch / steps;
     layer l = {0};
     l.batch = batch;
     l.type = CRNN;
     l.steps = steps;
     l.h = h;
     l.w = w;
     l.c = c;
     l.out_h = h;
     l.out_w = w;
     l.out_c = output_filters;
     l.inputs = h*w*c;
     l.hidden = h * w * hidden_filters;
     l.outputs = l.out_h * l.out_w * l.out_c;
     l.state = calloc(l.hidden*batch*(steps+1), sizeof(float));
     l.input_layer = malloc(sizeof(layer));
     fprintf(stderr, "\t\t");
     *(l.input_layer) = make_convolutional_layer(batch*steps, h, w, c, hidden_filters, 3, 1, 1,  activation, batch_normalize, 0, 0, 0);
     l.input_layer->batch = batch;
     l.self_layer = malloc(sizeof(layer));
     fprintf(stderr, "\t\t");
     *(l.self_layer) = make_convolutional_layer(batch*steps, h, w, hidden_filters, hidden_filters, 3, 1, 1,  activation, batch_normalize, 0, 0, 0);
     l.self_layer->batch = batch;
     l.output_layer = malloc(sizeof(layer));
     fprintf(stderr, "\t\t");
     *(l.output_layer) = make_convolutional_layer(batch*steps, h, w, hidden_filters, output_filters, 3, 1, 1,  activation, batch_normalize, 0, 0, 0);
     l.output_layer->batch = batch;
     l.output = l.output_layer->output;
     l.delta = l.output_layer->delta;
     l.forward = forward_crnn_layer;
     l.backward = backward_crnn_layer;
     l.update = update_crnn_layer;
 #ifdef GPU
     l.forward_gpu = forward_crnn_layer_gpu;
     l.backward_gpu = backward_crnn_layer_gpu;
     l.update_gpu = update_crnn_layer_gpu;
     l.state_gpu = cuda_make_array(l.state, l.hidden*batch*(steps+1));
     l.output_gpu = l.output_layer->output_gpu;
     l.delta_gpu = l.output_layer->delta_gpu;
 #endif
     return l;
 }
update_crnn_layer()
void update_crnn_layer (layer l, int batch, float learning_rate, float momentum, float decay)
Definition at line 84 of file crnn_layer.c.
References layer::input_layer, layer::output_layer, layer::self_layer, and update_convolutional_layer().
Referenced by make_crnn_layer().
 {
     update_convolutional_layer(*(l.input_layer), batch, learning_rate, momentum, decay);
     update_convolutional_layer(*(l.self_layer), batch, learning_rate, momentum, decay);
     update_convolutional_layer(*(l.output_layer), batch, learning_rate, momentum, decay);
 }