Darknet: deconvolutional_layer.h File Reference
deconvolutional_layer.h File Reference
#include "cuda.h"
#include "image.h"
#include "activations.h"
#include "layer.h"
#include "network.h"
Functions
layer make_deconvolutional_layer (int batch, int h, int w, int c, int n, int size, int stride, int padding, ACTIVATION activation, int batch_normalize, int adam)
void resize_deconvolutional_layer (layer *l, int h, int w)
void forward_deconvolutional_layer (const layer l, network net)
void update_deconvolutional_layer (layer l, int batch, float learning_rate, float momentum, float decay)
void backward_deconvolutional_layer (layer l, network net)
Function Documentation
backward_deconvolutional_layer()
void backward_deconvolutional_layer (layer l, network net)
Definition at line 213 of file deconvolutional_layer.c.
References layer::activation, backward_batchnorm_layer(), backward_bias(), layer::batch, layer::batch_normalize, layer::bias_updates, layer::c, network::delta, layer::delta, gemm_cpu(), gradient_array(), layer::h, im2col_cpu(), network::input, layer::n, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, layer::size, layer::stride, layer::w, layer::weight_updates, layer::weights, and network::workspace.
Referenced by make_deconvolutional_layer().
 {
     int i;
     gradient_array(l.output, l.outputs*l.batch, l.activation, l.delta);
     if(l.batch_normalize){
         backward_batchnorm_layer(l, net);
     } else {
         backward_bias(l.bias_updates, l.delta, l.batch, l.n, l.out_w*l.out_h);
     }
     //if(net.delta) memset(net.delta, 0, l.batch*l.h*l.w*l.c*sizeof(float));
     for(i = 0; i < l.batch; ++i){
         int m = l.c;
         int n = l.size*l.size*l.n;
         int k = l.h*l.w;
         float *a = net.input + i*m*k;
         float *b = net.workspace;
         float *c = l.weight_updates;
         im2col_cpu(l.delta + i*l.outputs, l.out_c, l.out_h, l.out_w,
                 l.size, l.stride, l.pad, b);
         gemm_cpu(0,1,m,n,k,1,a,k,b,k,1,c,n);
         if(net.delta){
             int m = l.c;
             int n = l.h*l.w;
             int k = l.size*l.size*l.n;
             float *a = l.weights;
             float *b = net.workspace;
             float *c = net.delta + i*n*m;
             gemm_cpu(0,0,m,n,k,1,a,k,b,n,1,c,n);
         }
     }
 }
forward_deconvolutional_layer()
void forward_deconvolutional_layer (const layer l, network net)
Definition at line 186 of file deconvolutional_layer.c.
References activate_array(), layer::activation, add_bias(), layer::batch, layer::batch_normalize, layer::biases, layer::c, col2im_cpu(), fill_cpu(), forward_batchnorm_layer(), gemm_cpu(), layer::h, network::input, layer::n, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, layer::size, layer::stride, layer::w, layer::weights, and network::workspace.
Referenced by make_deconvolutional_layer().
 {
     int i;
     int m = l.size*l.size*l.n;
     int n = l.h*l.w;
     int k = l.c;
     fill_cpu(l.outputs*l.batch, 0, l.output, 1);
     for(i = 0; i < l.batch; ++i){
         float *a = l.weights;
         float *b = net.input + i*l.c*l.h*l.w;
         float *c = net.workspace;
         gemm_cpu(1,0,m,n,k,1,a,m,b,n,0,c,n);
         col2im_cpu(net.workspace, l.out_c, l.out_h, l.out_w, l.size, l.stride, l.pad, l.output+i*l.outputs);
     }
     if (l.batch_normalize) {
         forward_batchnorm_layer(l, net);
     } else {
         add_bias(l.output, l.biases, l.batch, l.n, l.out_w*l.out_h);
     }
     activate_array(l.output, l.batch*l.n*l.out_w*l.out_h, l.activation);
 }
make_deconvolutional_layer()
layer make_deconvolutional_layer (int batch, int h, int w, int c, int n, int size, int stride, int padding, ACTIVATION activation, int batch_normalize, int adam)
Definition at line 18 of file deconvolutional_layer.c.
References layer::activation, layer::adam, layer::backward, backward_deconvolutional_layer(), layer::backward_gpu, layer::batch, layer::batch_normalize, layer::bias_m, layer::bias_updates, layer::bias_v, layer::biases, layer::c, DECONVOLUTIONAL, layer::delta, layer::forward, forward_deconvolutional_layer(), layer::forward_gpu, get_workspace_size(), gpu_index, layer::h, layer::inputs, layer::m, layer::mean, layer::mean_delta, layer::n, layer::nbiases, layer::nweights, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, rand_normal(), layer::rolling_mean, layer::rolling_variance, layer::scale_m, layer::scale_updates, layer::scale_v, layer::scales, layer::size, layer::stride, layer::type, layer::update, update_deconvolutional_layer(), layer::update_gpu, layer::v, layer::variance, layer::variance_delta, layer::w, layer::weight_updates, layer::weights, layer::workspace_size, layer::x, and layer::x_norm.
Referenced by parse_deconvolutional().
 {
     int i;
     layer l = {0};
     l.type = DECONVOLUTIONAL;
     l.h = h;
     l.w = w;
     l.c = c;
     l.n = n;
     l.batch = batch;
     l.stride = stride;
     l.size = size;
     l.nweights = c*n*size*size;
     l.nbiases = n;
     l.weights = calloc(c*n*size*size, sizeof(float));
     l.weight_updates = calloc(c*n*size*size, sizeof(float));
     l.biases = calloc(n, sizeof(float));
     l.bias_updates = calloc(n, sizeof(float));
     float scale = .02;
     for(i = 0; i < c*n*size*size; ++i) l.weights[i] = scale*rand_normal();
     for(i = 0; i < n; ++i){
         l.biases[i] = 0;
     }
     l.pad = padding;
     l.out_h = (l.h - 1) * l.stride + l.size - 2*l.pad;
     l.out_w = (l.w - 1) * l.stride + l.size - 2*l.pad;
     l.out_c = n;
     l.outputs = l.out_w * l.out_h * l.out_c;
     l.inputs = l.w * l.h * l.c;
     l.output = calloc(l.batch*l.outputs, sizeof(float));
     l.delta  = calloc(l.batch*l.outputs, sizeof(float));
     l.forward = forward_deconvolutional_layer;
     l.backward = backward_deconvolutional_layer;
     l.update = update_deconvolutional_layer;
     l.batch_normalize = batch_normalize;
     if(batch_normalize){
         l.scales = calloc(n, sizeof(float));
         l.scale_updates = calloc(n, sizeof(float));
         for(i = 0; i < n; ++i){
             l.scales[i] = 1;
         }
         l.mean = calloc(n, sizeof(float));
         l.variance = calloc(n, sizeof(float));
         l.mean_delta = calloc(n, sizeof(float));
         l.variance_delta = calloc(n, sizeof(float));
         l.rolling_mean = calloc(n, sizeof(float));
         l.rolling_variance = calloc(n, sizeof(float));
         l.x = calloc(l.batch*l.outputs, sizeof(float));
         l.x_norm = calloc(l.batch*l.outputs, sizeof(float));
     }
     if(adam){
         l.adam = 1;
         l.m = calloc(c*n*size*size, sizeof(float));
         l.v = calloc(c*n*size*size, sizeof(float));
         l.bias_m = calloc(n, sizeof(float));
         l.scale_m = calloc(n, sizeof(float));
         l.bias_v = calloc(n, sizeof(float));
         l.scale_v = calloc(n, sizeof(float));
     }
 #ifdef GPU
     l.forward_gpu = forward_deconvolutional_layer_gpu;
     l.backward_gpu = backward_deconvolutional_layer_gpu;
     l.update_gpu = update_deconvolutional_layer_gpu;
     if(gpu_index >= 0){
         if (adam) {
             l.m_gpu = cuda_make_array(l.m, c*n*size*size);
             l.v_gpu = cuda_make_array(l.v, c*n*size*size);
             l.bias_m_gpu = cuda_make_array(l.bias_m, n);
             l.bias_v_gpu = cuda_make_array(l.bias_v, n);
             l.scale_m_gpu = cuda_make_array(l.scale_m, n);
             l.scale_v_gpu = cuda_make_array(l.scale_v, n);
         }
         l.weights_gpu = cuda_make_array(l.weights, c*n*size*size);
         l.weight_updates_gpu = cuda_make_array(l.weight_updates, c*n*size*size);
         l.biases_gpu = cuda_make_array(l.biases, n);
         l.bias_updates_gpu = cuda_make_array(l.bias_updates, n);
         l.delta_gpu = cuda_make_array(l.delta, l.batch*l.out_h*l.out_w*n);
         l.output_gpu = cuda_make_array(l.output, l.batch*l.out_h*l.out_w*n);
         if(batch_normalize){
             l.mean_gpu = cuda_make_array(l.mean, n);
             l.variance_gpu = cuda_make_array(l.variance, n);
             l.rolling_mean_gpu = cuda_make_array(l.mean, n);
             l.rolling_variance_gpu = cuda_make_array(l.variance, n);
             l.mean_delta_gpu = cuda_make_array(l.mean, n);
             l.variance_delta_gpu = cuda_make_array(l.variance, n);
             l.scales_gpu = cuda_make_array(l.scales, n);
             l.scale_updates_gpu = cuda_make_array(l.scale_updates, n);
             l.x_gpu = cuda_make_array(l.output, l.batch*l.out_h*l.out_w*n);
             l.x_norm_gpu = cuda_make_array(l.output, l.batch*l.out_h*l.out_w*n);
         }
     }
     #ifdef CUDNN
         cudnnCreateTensorDescriptor(&l.dstTensorDesc);
         cudnnCreateTensorDescriptor(&l.normTensorDesc);
         cudnnSetTensor4dDescriptor(l.dstTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, l.batch, l.out_c, l.out_h, l.out_w);
         cudnnSetTensor4dDescriptor(l.normTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, 1, l.out_c, 1, 1);
     #endif
 #endif
     l.activation = activation;
     l.workspace_size = get_workspace_size(l);
     fprintf(stderr, "deconv%5d %2d x%2d /%2d  %4d x%4d x%4d   ->  %4d x%4d x%4d\n", n, size, size, stride, w, h, c, l.out_w, l.out_h, l.out_c);
     return l;
 }
resize_deconvolutional_layer()
void resize_deconvolutional_layer (layer * l, int h, int w)
Definition at line 147 of file deconvolutional_layer.c.
References layer::batch, layer::batch_normalize, layer::c, layer::delta, get_workspace_size(), layer::h, layer::inputs, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, layer::size, layer::stride, layer::w, layer::workspace_size, layer::x, and layer::x_norm.
 {
     l->h = h;
     l->w = w;
     l->out_h = (l->h - 1) * l->stride + l->size - 2*l->pad;
     l->out_w = (l->w - 1) * l->stride + l->size - 2*l->pad;
     l->outputs = l->out_h * l->out_w * l->out_c;
     l->inputs = l->w * l->h * l->c;
     l->output = realloc(l->output, l->batch*l->outputs*sizeof(float));
     l->delta  = realloc(l->delta,  l->batch*l->outputs*sizeof(float));
     if(l->batch_normalize){
         l->x = realloc(l->x, l->batch*l->outputs*sizeof(float));
         l->x_norm  = realloc(l->x_norm, l->batch*l->outputs*sizeof(float));
     }
 #ifdef GPU
     cuda_free(l->delta_gpu);
     cuda_free(l->output_gpu);
     l->delta_gpu =  cuda_make_array(l->delta,  l->batch*l->outputs);
     l->output_gpu = cuda_make_array(l->output, l->batch*l->outputs);
     if(l->batch_normalize){
         cuda_free(l->x_gpu);
         cuda_free(l->x_norm_gpu);
         l->x_gpu = cuda_make_array(l->output, l->batch*l->outputs);
         l->x_norm_gpu = cuda_make_array(l->output, l->batch*l->outputs);
     }
     #ifdef CUDNN
         cudnnSetTensor4dDescriptor(l->dstTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, l->batch, l->out_c, l->out_h, l->out_w);
         cudnnSetTensor4dDescriptor(l->normTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, 1, l->out_c, 1, 1);
     #endif
 #endif
     l->workspace_size = get_workspace_size(*l);
 }
update_deconvolutional_layer()
void update_deconvolutional_layer (layer l, int batch, float learning_rate, float momentum, float decay)
Definition at line 254 of file deconvolutional_layer.c.
References axpy_cpu(), layer::bias_updates, layer::biases, layer::c, layer::n, scal_cpu(), layer::scale_updates, layer::scales, layer::size, layer::weight_updates, and layer::weights.
Referenced by make_deconvolutional_layer().
 {
     int size = l.size*l.size*l.c*l.n;
     axpy_cpu(l.n, learning_rate/batch, l.bias_updates, 1, l.biases, 1);
     scal_cpu(l.n, momentum, l.bias_updates, 1);
     if(l.scales){
         axpy_cpu(l.n, learning_rate/batch, l.scale_updates, 1, l.scales, 1);
         scal_cpu(l.n, momentum, l.scale_updates, 1);
     }
     axpy_cpu(size, -decay*batch, l.weights, 1, l.weight_updates, 1);
     axpy_cpu(size, learning_rate/batch, l.weight_updates, 1, l.weights, 1);
     scal_cpu(size, momentum, l.weight_updates, 1);
 }