Darknet: maxpool_layer.h File Reference
maxpool_layer.h File Reference
#include "image.h"
#include "cuda.h"
#include "layer.h"
#include "network.h"
Typedefs
typedef layer maxpool_layer
Functions
image get_maxpool_image (maxpool_layer l)
maxpool_layer make_maxpool_layer (int batch, int h, int w, int c, int size, int stride, int padding)
void resize_maxpool_layer (maxpool_layer *l, int w, int h)
void forward_maxpool_layer (const maxpool_layer l, network net)
void backward_maxpool_layer (const maxpool_layer l, network net)
Typedef Documentation
maxpool_layer
typedef layer maxpool_layer
Definition at line 9 of file maxpool_layer.h.
Function Documentation
backward_maxpool_layer()
void backward_maxpool_layer (const maxpool_layer l, network net)
Definition at line 116 of file maxpool_layer.c.
References layer::batch, layer::c, network::delta, layer::delta, layer::indexes, layer::out_h, and layer::out_w.
Referenced by make_maxpool_layer().
 {
     int i;
     int h = l.out_h;
     int w = l.out_w;
     int c = l.c;
     for(i = 0; i < h*w*c*l.batch; ++i){
         int index = l.indexes[i];
         net.delta[index] += l.delta[i];
     }
 }
forward_maxpool_layer()
void forward_maxpool_layer (const maxpool_layer l, network net)
Definition at line 79 of file maxpool_layer.c.
References layer::batch, layer::c, layer::h, layer::indexes, network::input, layer::out_h, layer::out_w, layer::output, layer::pad, layer::size, layer::stride, and layer::w.
Referenced by make_maxpool_layer().
 {
     int b,i,j,k,m,n;
     int w_offset = -l.pad;
     int h_offset = -l.pad;
     int h = l.out_h;
     int w = l.out_w;
     int c = l.c;
     for(b = 0; b < l.batch; ++b){
         for(k = 0; k < c; ++k){
             for(i = 0; i < h; ++i){
                 for(j = 0; j < w; ++j){
                     int out_index = j + w*(i + h*(k + c*b));
                     float max = -FLT_MAX;
                     int max_i = -1;
                     for(n = 0; n < l.size; ++n){
                         for(m = 0; m < l.size; ++m){
                             int cur_h = h_offset + i*l.stride + n;
                             int cur_w = w_offset + j*l.stride + m;
                             int index = cur_w + l.w*(cur_h + l.h*(k + b*l.c));
                             int valid = (cur_h >= 0 && cur_h < l.h &&
                                          cur_w >= 0 && cur_w < l.w);
                             float val = (valid != 0) ? net.input[index] : -FLT_MAX;
                             max_i = (val > max) ? index : max_i;
                             max   = (val > max) ? val   : max;
                         }
                     }
                     l.output[out_index] = max;
                     l.indexes[out_index] = max_i;
                 }
             }
         }
     }
 }
get_maxpool_image()
image get_maxpool_image (maxpool_layer l)
Definition at line 5 of file maxpool_layer.c.
References layer::c, float_to_image(), layer::out_h, layer::out_w, and layer::output.
 {
     int h = l.out_h;
     int w = l.out_w;
     int c = l.c;
     return float_to_image(w,h,c,l.output);
 }
make_maxpool_layer()
maxpool_layer make_maxpool_layer (int batch, int h, int w, int c, int size, int stride, int padding)
Definition at line 21 of file maxpool_layer.c.
References layer::backward, layer::backward_gpu, backward_maxpool_layer(), layer::batch, layer::c, layer::delta, layer::forward, layer::forward_gpu, forward_maxpool_layer(), layer::h, layer::indexes, layer::inputs, MAXPOOL, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, layer::size, layer::stride, layer::type, and layer::w.
Referenced by parse_maxpool().
 {
     maxpool_layer l = {0};
     l.type = MAXPOOL;
     l.batch = batch;
     l.h = h;
     l.w = w;
     l.c = c;
     l.pad = padding;
     l.out_w = (w + 2*padding)/stride;
     l.out_h = (h + 2*padding)/stride;
     l.out_c = c;
     l.outputs = l.out_h * l.out_w * l.out_c;
     l.inputs = h*w*c;
     l.size = size;
     l.stride = stride;
     int output_size = l.out_h * l.out_w * l.out_c * batch;
     l.indexes = calloc(output_size, sizeof(int));
     l.output =  calloc(output_size, sizeof(float));
     l.delta =   calloc(output_size, sizeof(float));
     l.forward = forward_maxpool_layer;
     l.backward = backward_maxpool_layer;
     #ifdef GPU
     l.forward_gpu = forward_maxpool_layer_gpu;
     l.backward_gpu = backward_maxpool_layer_gpu;
     l.indexes_gpu = cuda_make_int_array(output_size);
     l.output_gpu  = cuda_make_array(l.output, output_size);
     l.delta_gpu   = cuda_make_array(l.delta, output_size);
     #endif
     fprintf(stderr, "max          %d x %d / %d  %4d x%4d x%4d   ->  %4d x%4d x%4d\n", size, size, stride, w, h, c, l.out_w, l.out_h, l.out_c);
     return l;
 }
resize_maxpool_layer()
void resize_maxpool_layer (maxpool_layer * l, int w, int h)
Definition at line 54 of file maxpool_layer.c.
References layer::batch, layer::c, layer::delta, layer::h, layer::indexes, layer::inputs, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, layer::stride, and layer::w.
Referenced by resize_network().
 {
     l->h = h;
     l->w = w;
     l->inputs = h*w*l->c;
     l->out_w = (w + 2*l->pad)/l->stride;
     l->out_h = (h + 2*l->pad)/l->stride;
     l->outputs = l->out_w * l->out_h * l->c;
     int output_size = l->outputs * l->batch;
     l->indexes = realloc(l->indexes, output_size * sizeof(int));
     l->output = realloc(l->output, output_size * sizeof(float));
     l->delta = realloc(l->delta, output_size * sizeof(float));
     #ifdef GPU
     cuda_free((float *)l->indexes_gpu);
     cuda_free(l->output_gpu);
     cuda_free(l->delta_gpu);
     l->indexes_gpu = cuda_make_int_array(output_size);
     l->output_gpu  = cuda_make_array(l->output, output_size);
     l->delta_gpu   = cuda_make_array(l->delta,  output_size);
     #endif
 }