Darknet: demo.c File Reference
demo.c File Reference
#include "network.h"
#include "detection_layer.h"
#include "region_layer.h"
#include "cost_layer.h"
#include "utils.h"
#include "parser.h"
#include "box.h"
#include "image.h"
#include "demo.h"
#include <sys/time.h>
Macros
#define DEMO 1
Functions
void demo (char *cfgfile, char *weightfile, float thresh, int cam_index, const char *filename, char **names, int classes, int delay, char *prefix, int avg, float hier, int w, int h, int frames, int fullscreen)
Macro Definition Documentation
DEMO
#define DEMO 1
Definition at line 12 of file demo.c.
Function Documentation
demo()
void demo (char * cfgfile, char * weightfile, float thresh, int cam_index, const char * filename, char ** names, int classes, int delay, char * prefix, int avg, float hier, int w, int h, int frames, int fullscreen)
Definition at line 236 of file demo.c.
Referenced by run_coco(), run_detector(), and run_yolo().
 {
     fprintf(stderr, "Demo needs OpenCV for webcam images.\n");
 }