Darknet: local_layer.h File Reference
local_layer.h File Reference
#include "cuda.h"
#include "image.h"
#include "activations.h"
#include "layer.h"
#include "network.h"
Typedefs
typedef layer local_layer
Functions
local_layer make_local_layer (int batch, int h, int w, int c, int n, int size, int stride, int pad, ACTIVATION activation)
void forward_local_layer (const local_layer layer, network net)
void backward_local_layer (local_layer layer, network net)
void update_local_layer (local_layer layer, int batch, float learning_rate, float momentum, float decay)
void bias_output (float *output, float *biases, int batch, int n, int size)
void backward_bias (float *bias_updates, float *delta, int batch, int n, int size)
Typedef Documentation
local_layer
typedef layer local_layer
Definition at line 10 of file local_layer.h.
Function Documentation
backward_bias()
void backward_bias (float * bias_updates, float * delta, int batch, int n, int size)
Definition at line 420 of file convolutional_layer.c.
References sum_array().
Referenced by backward_batchnorm_layer(), backward_convolutional_layer(), and backward_deconvolutional_layer().
 {
     int i,b;
     for(b = 0; b < batch; ++b){
         for(i = 0; i < n; ++i){
             bias_updates[i] += sum_array(delta+size*(i+b*n), size);
         }
     }
 }
backward_local_layer()
void backward_local_layer (local_layer layer, network net)
Definition at line 122 of file local_layer.c.
References layer::activation, axpy_cpu(), layer::batch, layer::bias_updates, layer::c, col2im_cpu(), network::delta, layer::delta, gemm(), gradient_array(), layer::h, im2col_cpu(), network::input, layer::n, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, layer::size, layer::stride, layer::w, layer::weight_updates, layer::weights, and network::workspace.
Referenced by make_local_layer().
 {
     int i, j;
     int locations = l.out_w*l.out_h;
     gradient_array(l.output, l.outputs*l.batch, l.activation, l.delta);
     for(i = 0; i < l.batch; ++i){
         axpy_cpu(l.outputs, 1, l.delta + i*l.outputs, 1, l.bias_updates, 1);
     }
     for(i = 0; i < l.batch; ++i){
         float *input = net.input + i*l.w*l.h*l.c;
         im2col_cpu(input, l.c, l.h, l.w,
                 l.size, l.stride, l.pad, net.workspace);
         for(j = 0; j < locations; ++j){
             float *a = l.delta + i*l.outputs + j;
             float *b = net.workspace + j;
             float *c = l.weight_updates + j*l.size*l.size*l.c*l.n;
             int m = l.n;
             int n = l.size*l.size*l.c;
             int k = 1;
             gemm(0,1,m,n,k,1,a,locations,b,locations,1,c,n);
         }
         if(net.delta){
             for(j = 0; j < locations; ++j){
                 float *a = l.weights + j*l.size*l.size*l.c*l.n;
                 float *b = l.delta + i*l.outputs + j;
                 float *c = net.workspace + j;
                 int m = l.size*l.size*l.c;
                 int n = 1;
                 int k = l.n;
                 gemm(1,0,m,n,k,1,a,m,b,locations,0,c,locations);
             }
             col2im_cpu(net.workspace, l.c,  l.h,  l.w,  l.size,  l.stride, l.pad, net.delta+i*l.c*l.h*l.w);
         }
     }
 }
bias_output()
void bias_output (float * output, float * biases, int batch, int n, int size)
forward_local_layer()
void forward_local_layer (const local_layer layer, network net)
Definition at line 91 of file local_layer.c.
References activate_array(), layer::activation, layer::batch, layer::biases, layer::c, copy_cpu(), gemm(), layer::h, im2col_cpu(), network::input, local_out_height(), local_out_width(), layer::n, layer::output, layer::outputs, layer::pad, layer::size, layer::stride, layer::w, layer::weights, and network::workspace.
Referenced by make_local_layer().
 {
     int out_h = local_out_height(l);
     int out_w = local_out_width(l);
     int i, j;
     int locations = out_h * out_w;
     for(i = 0; i < l.batch; ++i){
         copy_cpu(l.outputs, l.biases, 1, l.output + i*l.outputs, 1);
     }
     for(i = 0; i < l.batch; ++i){
         float *input = net.input + i*l.w*l.h*l.c;
         im2col_cpu(input, l.c, l.h, l.w,
                 l.size, l.stride, l.pad, net.workspace);
         float *output = l.output + i*l.outputs;
         for(j = 0; j < locations; ++j){
             float *a = l.weights + j*l.size*l.size*l.c*l.n;
             float *b = net.workspace + j;
             float *c = output + j;
             int m = l.n;
             int n = 1;
             int k = l.size*l.size*l.c;
             gemm(0,0,m,n,k,1,a,k,b,locations,1,c,locations);
         }
     }
     activate_array(l.output, l.outputs*l.batch, l.activation);
 }
make_local_layer()
local_layer make_local_layer (int batch, int h, int w, int c, int n, int size, int stride, int pad, ACTIVATION activation)
Definition at line 26 of file local_layer.c.
References layer::activation, layer::backward, layer::backward_gpu, backward_local_layer(), layer::batch, layer::bias_updates, layer::biases, layer::c, layer::delta, layer::forward, layer::forward_gpu, forward_local_layer(), layer::h, layer::inputs, LOCAL, local_out_height(), local_out_width(), layer::n, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::pad, rand_uniform(), layer::size, layer::stride, layer::type, layer::update, layer::update_gpu, update_local_layer(), layer::w, layer::weight_updates, layer::weights, and layer::workspace_size.
Referenced by parse_local().
 {
     int i;
     local_layer l = {0};
     l.type = LOCAL;
     l.h = h;
     l.w = w;
     l.c = c;
     l.n = n;
     l.batch = batch;
     l.stride = stride;
     l.size = size;
     l.pad = pad;
     int out_h = local_out_height(l);
     int out_w = local_out_width(l);
     int locations = out_h*out_w;
     l.out_h = out_h;
     l.out_w = out_w;
     l.out_c = n;
     l.outputs = l.out_h * l.out_w * l.out_c;
     l.inputs = l.w * l.h * l.c;
     l.weights = calloc(c*n*size*size*locations, sizeof(float));
     l.weight_updates = calloc(c*n*size*size*locations, sizeof(float));
     l.biases = calloc(l.outputs, sizeof(float));
     l.bias_updates = calloc(l.outputs, sizeof(float));
     // float scale = 1./sqrt(size*size*c);
     float scale = sqrt(2./(size*size*c));
     for(i = 0; i < c*n*size*size; ++i) l.weights[i] = scale*rand_uniform(-1,1);
     l.output = calloc(l.batch*out_h * out_w * n, sizeof(float));
     l.delta  = calloc(l.batch*out_h * out_w * n, sizeof(float));
     l.workspace_size = out_h*out_w*size*size*c;
     l.forward = forward_local_layer;
     l.backward = backward_local_layer;
     l.update = update_local_layer;
 #ifdef GPU
     l.forward_gpu = forward_local_layer_gpu;
     l.backward_gpu = backward_local_layer_gpu;
     l.update_gpu = update_local_layer_gpu;
     l.weights_gpu = cuda_make_array(l.weights, c*n*size*size*locations);
     l.weight_updates_gpu = cuda_make_array(l.weight_updates, c*n*size*size*locations);
     l.biases_gpu = cuda_make_array(l.biases, l.outputs);
     l.bias_updates_gpu = cuda_make_array(l.bias_updates, l.outputs);
     l.delta_gpu = cuda_make_array(l.delta, l.batch*out_h*out_w*n);
     l.output_gpu = cuda_make_array(l.output, l.batch*out_h*out_w*n);
 #endif
     l.activation = activation;
     fprintf(stderr, "Local Layer: %d x %d x %d image, %d filters -> %d x %d x %d image\n", h,w,c,n, out_h, out_w, n);
     return l;
 }
update_local_layer()
void update_local_layer (local_layer layer, int batch, float learning_rate, float momentum, float decay)
Definition at line 167 of file local_layer.c.
References layer::activation, axpy_cpu(), layer::batch, layer::bias_updates, layer::biases, layer::c, layer::h, local_out_height(), local_out_width(), layer::n, layer::out_h, layer::out_w, layer::outputs, layer::pad, scal_cpu(), layer::size, layer::stride, layer::w, layer::weight_updates, layer::weights, and network::workspace.
Referenced by make_local_layer().
 {
     int locations = l.out_w*l.out_h;
     int size = l.size*l.size*l.c*l.n*locations;
     axpy_cpu(l.outputs, learning_rate/batch, l.bias_updates, 1, l.biases, 1);
     scal_cpu(l.outputs, momentum, l.bias_updates, 1);
     axpy_cpu(size, -decay*batch, l.weights, 1, l.weight_updates, 1);
     axpy_cpu(size, learning_rate/batch, l.weight_updates, 1, l.weights, 1);
     scal_cpu(size, momentum, l.weight_updates, 1);
 }