Darknet: option_list.h File Reference
option_list.h File Reference
#include "list.h"
Data Structures
struct kvp
Functions
list * read_data_cfg (char *filename)
int read_option (char *s, list *options)
void option_insert (list *l, char *key, char *val)
char * option_find (list *l, char *key)
char * option_find_str (list *l, char *key, char *def)
int option_find_int (list *l, char *key, int def)
int option_find_int_quiet (list *l, char *key, int def)
float option_find_float (list *l, char *key, float def)
float option_find_float_quiet (list *l, char *key, float def)
void option_unused (list *l)
Function Documentation
option_find()
char* option_find (list * l, char * key)
Definition at line 74 of file option_list.c.
References list::front, kvp::key, node::next, kvp::used, node::val, and kvp::val.
Referenced by option_find_float(), option_find_float_quiet(), option_find_int(), option_find_int_quiet(), option_find_str(), parse_net_options(), parse_route(), and parse_shortcut().
 {
     node *n = l->front;
     while(n){
         kvp *p = (kvp *)n->val;
         if(strcmp(p->key, key) == 0){
             p->used = 1;
             return p->val;
         }
         n = n->next;
     }
     return 0;
 }
option_find_float()
float option_find_float (list * l, char * key, float def)
Definition at line 117 of file option_list.c.
References option_find().
Referenced by parse_crop(), parse_detection(), parse_dropout(), parse_net_options(), parse_normalization(), and parse_region().
 {
     char *v = option_find(l, key);
     if(v) return atof(v);
     fprintf(stderr, "%s: Using default '%lf'\n", key, def);
     return def;
 }
option_find_float_quiet()
float option_find_float_quiet (list * l, char * key, float def)
Definition at line 110 of file option_list.c.
References option_find().
Referenced by parse_convolutional(), parse_cost(), parse_net_options(), parse_network_cfg(), and parse_softmax().
 {
     char *v = option_find(l, key);
     if(v) return atof(v);
     return def;
 }
option_find_int()
int option_find_int (list * l, char * key, int def)
Definition at line 95 of file option_list.c.
References option_find().
Referenced by demo_classifier(), gun_classifier(), label_classifier(), parse_connected(), parse_convolutional(), parse_crnn(), parse_crop(), parse_deconvolutional(), parse_detection(), parse_gru(), parse_local(), parse_maxpool(), parse_net_options(), parse_normalization(), parse_region(), parse_reorg(), parse_rnn(), predict_classifier(), run_detector(), test_classifier(), threat_classifier(), train_classifier(), try_classifier(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), and validate_classifier_single().
 {
     char *v = option_find(l, key);
     if(v) return atoi(v);
     fprintf(stderr, "%s: Using default '%d'\n", key, def);
     return def;
 }
option_find_int_quiet()
int option_find_int_quiet (list * l, char * key, int def)
Definition at line 103 of file option_list.c.
References option_find().
Referenced by parse_connected(), parse_convolutional(), parse_crnn(), parse_crop(), parse_deconvolutional(), parse_detection(), parse_gru(), parse_maxpool(), parse_net_options(), parse_network_cfg(), parse_region(), parse_reorg(), parse_rnn(), and parse_softmax().
 {
     char *v = option_find(l, key);
     if(v) return atoi(v);
     return def;
 }
option_find_str()
char* option_find_str (list * l, char * key, char * def)
Definition at line 87 of file option_list.c.
References option_find().
Referenced by demo_classifier(), gun_classifier(), label_classifier(), parse_activation(), parse_connected(), parse_convolutional(), parse_cost(), parse_crnn(), parse_deconvolutional(), parse_local(), parse_net_options(), parse_region(), parse_rnn(), parse_shortcut(), parse_softmax(), predict_classifier(), run_detector(), test_classifier(), test_detector(), threat_classifier(), train_classifier(), train_detector(), train_regressor(), try_classifier(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_detector(), and validate_detector_flip().
 {
     char *v = option_find(l, key);
     if(v) return v;
     if(def) fprintf(stderr, "%s: Using default '%s'\n", key, def);
     return def;
 }
option_insert()
void option_insert (list * l, char * key, char * val)
Definition at line 53 of file option_list.c.
References kvp::key, list_insert(), kvp::used, and kvp::val.
Referenced by read_option().
 {
     kvp *p = malloc(sizeof(kvp));
     p->key = key;
     p->val = val;
     p->used = 0;
     list_insert(l, p);
 }
option_unused()
void option_unused (list * l)
Definition at line 62 of file option_list.c.
References list::front, kvp::key, node::next, kvp::used, node::val, and kvp::val.
Referenced by parse_network_cfg().
 {
     node *n = l->front;
     while(n){
         kvp *p = (kvp *)n->val;
         if(!p->used){
             fprintf(stderr, "Unused field: '%s = %s'\n", p->key, p->val);
         }
         n = n->next;
     }
 }
read_data_cfg()
list* read_data_cfg (char * filename)
Definition at line 7 of file option_list.c.
References fgetl(), file_error(), make_list(), read_option(), and strip().
 {
     FILE *file = fopen(filename, "r");
     if(file == 0) file_error(filename);
     char *line;
     int nu = 0;
     list *options = make_list();
     while((line=fgetl(file)) != 0){
         ++ nu;
         strip(line);
         switch(line[0]){
             case '\0':
             case '#':
             case ';':
                 free(line);
                 break;
             default:
                 if(!read_option(line, options)){
                     fprintf(stderr, "Config file error line %d, could parse: %s\n", nu, line);
                     free(line);
                 }
                 break;
         }
     }
     fclose(file);
     return options;
 }
read_option()
int read_option (char * s, list * options)
Definition at line 35 of file option_list.c.
References option_insert().
Referenced by read_cfg(), and read_data_cfg().
 {
     size_t i;
     size_t len = strlen(s);
     char *val = 0;
     for(i = 0; i < len; ++i){
         if(s[i] == '='){
             s[i] = '\0';
             val = s+i+1;
             break;
         }
     }
     if(i == len-1) return 0;
     char *key = s;
     option_insert(options, key, val);
     return 1;
 }