Darknet: list.c File Reference
list.c File Reference
#include <stdlib.h>
#include <string.h>
#include "list.h"
Functions
list * make_list ()
void * list_pop (list *l)
void list_insert (list *l, void *val)
void free_node (node *n)
void free_list (list *l)
void free_list_contents (list *l)
void ** list_to_array (list *l)
Function Documentation
free_list()
void free_list (list * l)
Definition at line 67 of file list.c.
References free_node(), and list::front.
Referenced by BattleRoyaleWithCheese(), get_labels(), label_classifier(), parse_network_cfg(), SortMaster3000(), test_classifier(), train_classifier(), train_compare(), train_regressor(), train_tag(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_compare(), and validate_dice().
 {
     free_node(l->front);
     free(l);
 }
free_list_contents()
void free_list_contents (list * l)
Definition at line 73 of file list.c.
References list::front, layer::n, node::next, and node::val.
 {
     node *n = l->front;
     while(n){
         free(n->val);
         n = n->next;
     }
 }
free_node()
void free_node (node * n)
Definition at line 57 of file list.c.
References node::next.
Referenced by free_list().
 {
     node *next;
     while(n) {
         next = n->next;
         free(n);
         n = next;
     }
 }
list_insert()
void list_insert (list * l, void * val)
Definition at line 40 of file list.c.
References list::back, list::front, node::next, node::prev, and list::size.
Referenced by get_paths(), option_insert(), parse_csv_line(), read_cfg(), and split_str().
 {
     node *new = malloc(sizeof(node));
     new->val = val;
     new->next = 0;
     if(!l->back){
         l->front = new;
         new->prev = 0;
     }else{
         l->back->next = new;
         new->prev = l->back;
     }
     l->back = new;
     ++l->size;
 }
list_pop()
void* list_pop (list * l)
Definition at line 28 of file list.c.
References list::back, node::next, node::prev, list::size, and node::val.
{
     if(!l->back) return 0;
     node *b = l->back;
     void *val = b->val;
     l->back = b->prev;
     if(l->back) l->back->next = 0;
     free(b);
     --l->size;
     return val;
 }
list_to_array()
void** list_to_array (list * l)
Definition at line 82 of file list.c.
References list::front, layer::n, node::next, list::size, and node::val.
Referenced by BattleRoyaleWithCheese(), change_leaves(), get_labels(), label_classifier(), SortMaster3000(), test_classifier(), train_captcha(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), valid_captcha(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_compare(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_dice(), validate_yolo(), and validate_yolo_recall().
 {
     void **a = calloc(l->size, sizeof(void*));
     int count = 0;
     node *n = l->front;
     while(n){
         a[count++] = n->val;
         n = n->next;
     }
     return a;
 }
make_list()
list* make_list ()
Definition at line 5 of file list.c.
References list::back, list::front, and list::size.
Referenced by get_paths(), parse_csv_line(), read_cfg(), read_data_cfg(), and split_str().
 {
     list *l = malloc(sizeof(list));
     l->size = 0;
     l->front = 0;
     l->back = 0;
     return l;
 }