Darknet: data.h File Reference
data.h File Reference
#include <pthread.h>
#include "matrix.h"
#include "list.h"
#include "image.h"
#include "tree.h"
Data Structures
struct data
struct load_args
struct box_label
Typedefs
typedef struct load_args load_args
Enumerations
enum data_type {
CLASSIFICATION_DATA, DETECTION_DATA, CAPTCHA_DATA, REGION_DATA,
IMAGE_DATA, COMPARE_DATA, WRITING_DATA, SWAG_DATA,
TAG_DATA, OLD_CLASSIFICATION_DATA, STUDY_DATA, DET_DATA,
SUPER_DATA, LETTERBOX_DATA, REGRESSION_DATA
}
Functions
static float distance_from_edge (int x, int max)
void free_data (data d)
pthread_t load_data (load_args args)
pthread_t load_data_in_thread (load_args args)
void print_letters (float *pred, int n)
data load_data_captcha (char **paths, int n, int m, int k, int w, int h)
data load_data_captcha_encode (char **paths, int n, int m, int w, int h)
data load_data_old (char **paths, int n, int m, char **labels, int k, int w, int h)
data load_data_detection (int n, char **paths, int m, int w, int h, int boxes, int classes, float jitter, float hue, float saturation, float exposure)
data load_data_tag (char **paths, int n, int m, int k, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure)
matrix load_image_augment_paths (char **paths, int n, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure, int center)
data load_data_super (char **paths, int n, int m, int w, int h, int scale)
data load_data_augment (char **paths, int n, int m, char **labels, int k, tree *hierarchy, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure, int center)
data load_data_regression (char **paths, int n, int m, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure)
data load_go (char *filename)
box_label * read_boxes (char *filename, int *n)
data load_cifar10_data (char *filename)
data load_all_cifar10 ()
data load_data_writing (char **paths, int n, int m, int w, int h, int out_w, int out_h)
list * get_paths (char *filename)
char ** get_labels (char *filename)
void get_random_batch (data d, int n, float *X, float *y)
data get_data_part (data d, int part, int total)
data get_random_data (data d, int num)
void get_next_batch (data d, int n, int offset, float *X, float *y)
data load_categorical_data_csv (char *filename, int target, int k)
void normalize_data_rows (data d)
void scale_data_rows (data d, float s)
void translate_data_rows (data d, float s)
void randomize_data (data d)
data * split_data (data d, int part, int total)
data concat_data (data d1, data d2)
data concat_datas (data *d, int n)
void fill_truth (char *path, char **labels, int k, float *truth)
data copy_data (data d)
Typedef Documentation
load_args
typedef struct load_args load_args
Enumeration Type Documentation
data_type
enum data_type
Enumerator
CLASSIFICATION_DATA
DETECTION_DATA
CAPTCHA_DATA
REGION_DATA
IMAGE_DATA
COMPARE_DATA
WRITING_DATA
SWAG_DATA
TAG_DATA
OLD_CLASSIFICATION_DATA
STUDY_DATA
DET_DATA
SUPER_DATA
LETTERBOX_DATA
REGRESSION_DATA
Definition at line 30 of file data.h.
              {
     CLASSIFICATION_DATA, DETECTION_DATA, CAPTCHA_DATA, REGION_DATA, IMAGE_DATA, COMPARE_DATA, WRITING_DATA, SWAG_DATA, TAG_DATA, OLD_CLASSIFICATION_DATA, STUDY_DATA, DET_DATA, SUPER_DATA, LETTERBOX_DATA, REGRESSION_DATA
 } data_type;
Function Documentation
concat_data()
data concat_data (data d1, data d2)
Definition at line 944 of file data.c.
References concat_matrix(), load_args::d, data::shallow, data::X, and data::y.
Referenced by concat_datas(), train_colorizer(), and train_dcgan().
 {
     data d = {0};
     d.shallow = 1;
     d.X = concat_matrix(d1.X, d2.X);
     d.y = concat_matrix(d1.y, d2.y);
     return d;
 }
concat_datas()
data concat_datas (data * d, int n)
Definition at line 953 of file data.c.
References concat_data(), free_data(), and load_args::n.
Referenced by load_threads().
 {
     int i;
     data out = {0};
     for(i = 0; i < n; ++i){
         data new = concat_data(d[i], out);
         free_data(out);
         out = new;
     }
     return out;
 }
copy_data()
data copy_data (data d)
Definition at line 1152 of file data.c.
References data::boxes, copy_matrix(), data::h, data::num_boxes, data::shallow, data::w, data::X, and data::y.
Referenced by train_colorizer(), and train_dcgan().
 {
     data c = {0};
     c.w = d.w;
     c.h = d.h;
     c.shallow = 0;
     c.num_boxes = d.num_boxes;
     c.boxes = d.boxes;
     c.X = copy_matrix(d.X);
     c.y = copy_matrix(d.y);
     return c;
 }
distance_from_edge()
static float distance_from_edge (int x, int max) inline static
Definition at line 10 of file data.h.
 {
     int dx = (max/2) - x;
     if (dx < 0) dx = -dx;
     dx = (max/2) + 1 - dx;
     dx *= 2;
     float dist = (float)dx/max;
     if (dist > 1) dist = 1;
     return dist;
 }
fill_truth()
void fill_truth (char * path, char ** labels, int k, float * truth)
Definition at line 390 of file data.c.
Referenced by load_labels_paths().
 {
     int i;
     memset(truth, 0, k*sizeof(float));
     int count = 0;
     for(i = 0; i < k; ++i){
         if(strstr(path, labels[i])){
             truth[i] = 1;
             ++count;
         }
     }
     if(count != 1 && (k != 1 || count != 0)) printf("Too many or too few labels: %d, %s\n", count, path);
 }
free_data()
void free_data (data d)
Definition at line 503 of file data.c.
References free_matrix(), data::shallow, matrix::vals, data::X, and data::y.
Referenced by concat_datas(), eval_cifar_csv(), load_threads(), test_cifar(), test_cifar_csv(), test_cifar_csvtrain(), test_classifier(), train_captcha(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_go(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), validate_classifier_crop(), validate_compare(), and validate_dice().
 {
     if(!d.shallow){
         free_matrix(d.X);
         free_matrix(d.y);
     }else{
         free(d.X.vals);
         free(d.y.vals);
     }
 }
get_data_part()
data get_data_part (data d, int part, int total)
Definition at line 1173 of file data.c.
References matrix::cols, matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     data p = {0};
     p.shallow = 1;
     p.X.rows = d.X.rows * (part + 1) / total - d.X.rows * part / total;
     p.y.rows = d.y.rows * (part + 1) / total - d.y.rows * part / total;
     p.X.cols = d.X.cols;
     p.y.cols = d.y.cols;
     p.X.vals = d.X.vals + d.X.rows * part / total;
     p.y.vals = d.y.vals + d.y.rows * part / total;
     return p;
 }
get_labels()
char** get_labels (char * filename)
Definition at line 495 of file data.c.
References free_list(), get_paths(), and list_to_array().
Referenced by demo_classifier(), gun_classifier(), label_classifier(), predict_classifier(), run_detector(), test_captcha(), test_detector(), test_tag(), threat_classifier(), train_captcha(), train_cifar(), train_cifar_distill(), train_classifier(), try_classifier(), valid_captcha(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_detector(), and validate_detector_flip().
 {
     list *plist = get_paths(filename);
     char **labels = (char **)list_to_array(plist);
     free_list(plist);
     return labels;
 }
get_next_batch()
void get_next_batch (data d, int n, int offset, float * X, float * y)
Definition at line 1019 of file data.c.
References matrix::cols, matrix::vals, data::X, and data::y.
Referenced by train_colorizer(), train_dcgan(), and train_network().
 {
     int j;
     for(j = 0; j < n; ++j){
         int index = offset + j;
         memcpy(X+j*d.X.cols, d.X.vals[index], d.X.cols*sizeof(float));
         if(y) memcpy(y+j*d.y.cols, d.y.vals[index], d.y.cols*sizeof(float));
     }
 }
get_paths()
list* get_paths (char * filename)
Definition at line 12 of file data.c.
References fgetl(), file_error(), list_insert(), and make_list().
Referenced by BattleRoyaleWithCheese(), change_leaves(), get_labels(), label_classifier(), SortMaster3000(), test_classifier(), train_captcha(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), valid_captcha(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_compare(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_dice(), validate_yolo(), and validate_yolo_recall().
 {
     char *path;
     FILE *file = fopen(filename, "r");
     if(!file) file_error(filename);
     list *lines = make_list();
     while((path=fgetl(file))){
         list_insert(lines, path);
     }
     fclose(file);
     return lines;
 }
get_random_batch()
void get_random_batch (data d, int n, float * X, float * y)
Definition at line 1009 of file data.c.
References matrix::cols, matrix::rows, matrix::vals, data::X, and data::y.
Referenced by train_network_sgd().
 {
     int j;
     for(j = 0; j < n; ++j){
         int index = rand()%d.X.rows;
         memcpy(X+j*d.X.cols, d.X.vals[index], d.X.cols*sizeof(float));
         memcpy(y+j*d.y.cols, d.y.vals[index], d.y.cols*sizeof(float));
     }
 }
get_random_data()
data get_random_data (data d, int num)
Definition at line 1186 of file data.c.
References matrix::cols, matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     data r = {0};
     r.shallow = 1;
     r.X.rows = num;
     r.y.rows = num;
     r.X.cols = d.X.cols;
     r.y.cols = d.y.cols;
     r.X.vals = calloc(num, sizeof(float *));
     r.y.vals = calloc(num, sizeof(float *));
     int i;
     for(i = 0; i < num; ++i){
         int index = rand()%d.X.rows;
         r.X.vals[i] = d.X.vals[index];
         r.y.vals[i] = d.y.vals[index];
     }
     return r;
 }
load_all_cifar10()
data load_all_cifar10 ()
Definition at line 1041 of file data.c.
References matrix::cols, file_error(), make_matrix(), scale_data_rows(), data::shallow, smooth_data(), matrix::vals, data::X, and data::y.
Referenced by extract_cifar(), test_cifar_csvtrain(), train_cifar(), and train_cifar_distill().
 {
     data d = {0};
     d.shallow = 0;
     int i,j,b;
     matrix X = make_matrix(50000, 3072);
     matrix y = make_matrix(50000, 10);
     d.X = X;
     d.y = y;
     for(b = 0; b < 5; ++b){
         char buff[256];
         sprintf(buff, "data/cifar/cifar-10-batches-bin/data_batch_%d.bin", b+1);
         FILE *fp = fopen(buff, "rb");
         if(!fp) file_error(buff);
         for(i = 0; i < 10000; ++i){
             unsigned char bytes[3073];
             fread(bytes, 1, 3073, fp);
             int class = bytes[0];
             y.vals[i+b*10000][class] = 1;
             for(j = 0; j < X.cols; ++j){
                 X.vals[i+b*10000][j] = (double)bytes[j+1];
             }
         }
         fclose(fp);
     }
     //normalize_data_rows(d);
     scale_data_rows(d, 1./255);
     smooth_data(d);
     return d;
 }
load_categorical_data_csv()
data load_categorical_data_csv (char * filename, int target, int k)
Definition at line 965 of file data.c.
References matrix::cols, csv_to_matrix(), load_args::d, one_hot_encode(), pop_column(), matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     data d = {0};
     d.shallow = 0;
     matrix X = csv_to_matrix(filename);
     float *truth_1d = pop_column(&X, target);
     float **truth = one_hot_encode(truth_1d, X.rows, k);
     matrix y;
     y.rows = X.rows;
     y.cols = k;
     y.vals = truth;
     d.X = X;
     d.y = y;
     free(truth_1d);
     return d;
 }
load_cifar10_data()
data load_cifar10_data (char * filename)
Definition at line 982 of file data.c.
References matrix::cols, load_args::d, file_error(), make_matrix(), scale_data_rows(), data::shallow, matrix::vals, data::X, and data::y.
Referenced by eval_cifar_csv(), extract_cifar(), test_cifar(), test_cifar_csv(), and test_cifar_multi().
 {
     data d = {0};
     d.shallow = 0;
     long i,j;
     matrix X = make_matrix(10000, 3072);
     matrix y = make_matrix(10000, 10);
     d.X = X;
     d.y = y;
     FILE *fp = fopen(filename, "rb");
     if(!fp) file_error(filename);
     for(i = 0; i < 10000; ++i){
         unsigned char bytes[3073];
         fread(bytes, 1, 3073, fp);
         int class = bytes[0];
         y.vals[i][class] = 1;
         for(j = 0; j < X.cols; ++j){
             X.vals[i][j] = (double)bytes[j+1];
         }
     }
     scale_data_rows(d, 1./255);
     //normalize_data_rows(d);
     fclose(fp);
     return d;
 }
load_data()
pthread_t load_data (load_args args)
Definition at line 814 of file data.c.
References error(), and load_threads().
Referenced by train_classifier(), train_detector(), and train_regressor().
 {
     pthread_t thread;
     struct load_args *ptr = calloc(1, sizeof(struct load_args));
     *ptr = args;
     if(pthread_create(&thread, 0, load_threads, ptr)) error("Thread creation failed");
     return thread;
 }
load_data_augment()
data load_data_augment (char ** paths, int n, int m, char ** labels, int k, tree * hierarchy, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure, int center)
Definition at line 904 of file data.c.
References load_args::d, get_random_paths(), load_image_augment_paths(), load_labels_paths(), data::shallow, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_augment_paths(paths, n, min, max, size, angle, aspect, hue, saturation, exposure, center);
     d.y = load_labels_paths(paths, n, labels, k, hierarchy);
     if(m) free(paths);
     return d;
 }
load_data_captcha()
data load_data_captcha (char ** paths, int n, int m, int k, int w, int h)
Definition at line 363 of file data.c.
References fill_truth_captcha(), get_random_paths(), load_image_paths(), make_matrix(), NUMCHARS, data::shallow, matrix::vals, data::X, and data::y.
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_paths(paths, n, w, h);
     d.y = make_matrix(n, k*NUMCHARS);
     int i;
     for(i = 0; i < n; ++i){
         fill_truth_captcha(paths[i], k, d.y.vals[i]);
     }
     if(m) free(paths);
     return d;
 }
load_data_captcha_encode()
data load_data_captcha_encode (char ** paths, int n, int m, int w, int h)
Definition at line 378 of file data.c.
References matrix::cols, get_random_paths(), load_image_paths(), data::shallow, data::X, and data::y.
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_paths(paths, n, w, h);
     d.X.cols = 17100;
     d.y = d.X;
     if(m) free(paths);
     return d;
 }
load_data_detection()
data load_data_detection (int n, char ** paths, int m, int w, int h, int boxes, int classes, float jitter, float hue, float saturation, float exposure)
Definition at line 685 of file data.c.
References image::c, matrix::cols, image::data, fill_image(), fill_truth_detection(), flip_image(), free_image(), get_random_paths(), image::h, load_image_color(), make_image(), make_matrix(), place_image(), rand_uniform(), random_distort_image(), matrix::rows, data::shallow, matrix::vals, image::w, data::X, and data::y.
Referenced by load_thread().
 {
     char **random_paths = get_random_paths(paths, n, m);
     int i;
     data d = {0};
     d.shallow = 0;
     d.X.rows = n;
     d.X.vals = calloc(d.X.rows, sizeof(float*));
     d.X.cols = h*w*3;
     d.y = make_matrix(n, 5*boxes);
     for(i = 0; i < n; ++i){
         image orig = load_image_color(random_paths[i], 0, 0);
         image sized = make_image(w, h, orig.c);
         fill_image(sized, .5);
         float dw = jitter * orig.w;
         float dh = jitter * orig.h;
         float new_ar = (orig.w + rand_uniform(-dw, dw)) / (orig.h + rand_uniform(-dh, dh));
         float scale = rand_uniform(.25, 2);
         float nw, nh;
         if(new_ar < 1){
             nh = scale * h;
             nw = nh * new_ar;
         } else {
             nw = scale * w;
             nh = nw / new_ar;
         }
         float dx = rand_uniform(0, w - nw);
         float dy = rand_uniform(0, h - nh);
         place_image(orig, nw, nh, dx, dy, sized);
         random_distort_image(sized, hue, saturation, exposure);
         int flip = rand()%2;
         if(flip) flip_image(sized);
         d.X.vals[i] = sized.data;
         fill_truth_detection(random_paths[i], boxes, d.y.vals[i], classes, flip, -dx/w, -dy/h, nw/w, nh/h);
         free_image(orig);
     }
     free(random_paths);
     return d;
 }
load_data_in_thread()
pthread_t load_data_in_thread (load_args args)
Definition at line 776 of file data.c.
References error(), and load_thread().
Referenced by load_threads(), test_classifier(), train_captcha(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), validate_classifier_crop(), validate_coco(), validate_compare(), validate_detector(), validate_detector_flip(), and validate_yolo().
 {
     pthread_t thread;
     struct load_args *ptr = calloc(1, sizeof(struct load_args));
     *ptr = args;
     if(pthread_create(&thread, 0, load_thread, ptr)) error("Thread creation failed");
     return thread;
 }
load_data_old()
data load_data_old (char ** paths, int n, int m, char ** labels, int k, int w, int h)
Definition at line 838 of file data.c.
References load_args::d, get_random_paths(), load_image_paths(), load_labels_paths(), data::shallow, data::X, and data::y.
Referenced by load_thread(), train_dice(), and validate_dice().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_paths(paths, n, w, h);
     d.y = load_labels_paths(paths, n, labels, k, 0);
     if(m) free(paths);
     return d;
 }
load_data_regression()
data load_data_regression (char ** paths, int n, int m, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure)
Definition at line 893 of file data.c.
References load_args::d, get_random_paths(), load_image_augment_paths(), load_regression_labels_paths(), data::shallow, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_augment_paths(paths, n, min, max, size, angle, aspect, hue, saturation, exposure, 0);
     d.y = load_regression_labels_paths(paths, n);
     if(m) free(paths);
     return d;
 }
load_data_super()
data load_data_super (char ** paths, int n, int m, int w, int h, int scale)
Definition at line 863 of file data.c.
References matrix::cols, load_args::d, image::data, flip_image(), free_image(), get_random_paths(), load_args::im, load_image_color(), load_args::n, random_crop_image(), resize_image(), matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     int i;
     d.X.rows = n;
     d.X.vals = calloc(n, sizeof(float*));
     d.X.cols = w*h*3;
     d.y.rows = n;
     d.y.vals = calloc(n, sizeof(float*));
     d.y.cols = w*scale * h*scale * 3;
     for(i = 0; i < n; ++i){
         image im = load_image_color(paths[i], 0, 0);
         image crop = random_crop_image(im, w*scale, h*scale);
         int flip = rand()%2;
         if (flip) flip_image(crop);
         image resize = resize_image(crop, w, h);
         d.X.vals[i] = resize.data;
         d.y.vals[i] = crop.data;
         free_image(im);
     }
     if(m) free(paths);
     return d;
 }
load_data_tag()
data load_data_tag (char ** paths, int n, int m, int k, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure)
Definition at line 915 of file data.c.
References load_args::d, get_random_paths(), data::h, load_image_augment_paths(), load_tags_paths(), data::shallow, load_args::size, data::w, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.w = size;
     d.h = size;
     d.shallow = 0;
     d.X = load_image_augment_paths(paths, n, min, max, size, angle, aspect, hue, saturation, exposure, 0);
     d.y = load_tags_paths(paths, n, k);
     if(m) free(paths);
     return d;
 }
load_data_writing()
data load_data_writing (char ** paths, int n, int m, int w, int h, int out_w, int out_h)
Definition at line 823 of file data.c.
References load_args::d, find_replace_paths(), get_random_paths(), load_image_paths(), load_image_paths_gray(), load_args::n, data::shallow, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     char **replace_paths = find_replace_paths(paths, n, ".png", "-label.png");
     data d = {0};
     d.shallow = 0;
     d.X = load_image_paths(paths, n, w, h);
     d.y = load_image_paths_gray(replace_paths, n, out_w, out_h);
     if(m) free(paths);
     int i;
     for(i = 0; i < n; ++i) free(replace_paths[i]);
     free(replace_paths);
     return d;
 }
load_go()
data load_go (char * filename)
Definition at line 1074 of file data.c.
References fgetl(), file_error(), make_matrix(), resize_matrix(), matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     FILE *fp = fopen(filename, "rb");
     matrix X = make_matrix(3363059, 361);
     matrix y = make_matrix(3363059, 361);
     int row, col;
     if(!fp) file_error(filename);
     char *label;
     int count = 0;
     while((label = fgetl(fp))){
         int i;
         if(count == X.rows){
             X = resize_matrix(X, count*2);
             y = resize_matrix(y, count*2);
         }
         sscanf(label, "%d %d", &row, &col);
         char *board = fgetl(fp);
         int index = row*19 + col;
         y.vals[count][index] = 1;
         for(i = 0; i < 19*19; ++i){
             float val = 0;
             if(board[i] == '1') val = 1;
             else if(board[i] == '2') val = -1;
             X.vals[count][i] = val;
         }
         ++count;
         free(label);
         free(board);
     }
     X = resize_matrix(X, count);
     y = resize_matrix(y, count);
     data d = {0};
     d.shallow = 0;
     d.X = X;
     d.y = y;
     fclose(fp);
     return d;
 }
load_image_augment_paths()
matrix load_image_augment_paths (char ** paths, int n, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure, int center)
Definition at line 105 of file data.c.
References image::c, center_crop_image(), matrix::cols, image::data, flip_image(), free_image(), image::h, load_image_color(), random_augment_image(), random_distort_image(), matrix::rows, matrix::vals, and image::w.
Referenced by load_data_augment(), load_data_regression(), and load_data_tag().
 {
     int i;
     matrix X;
     X.rows = n;
     X.vals = calloc(X.rows, sizeof(float*));
     X.cols = 0;
     for(i = 0; i < n; ++i){
         image im = load_image_color(paths[i], 0, 0);
         image crop;
         if(center){
             crop = center_crop_image(im, size, size);
         } else {
             crop = random_augment_image(im, angle, aspect, min, max, size);
         }
         int flip = rand()%2;
         if (flip) flip_image(crop);
         random_distort_image(crop, hue, saturation, exposure);
         /*
         show_image(im, "orig");
         show_image(crop, "crop");
         cvWaitKey(0);
         */
         free_image(im);
         X.vals[i] = crop.data;
         X.cols = crop.h*crop.w*crop.c;
     }
     return X;
 }
normalize_data_rows()
void normalize_data_rows (data d)
Definition at line 1165 of file data.c.
References matrix::cols, normalize_array(), matrix::rows, matrix::vals, and data::X.
 {
     int i;
     for(i = 0; i < d.X.rows; ++i){
         normalize_array(d.X.vals[i], d.X.cols);
     }
 }
print_letters()
void print_letters (float * pred, int n)
Definition at line 338 of file data.c.
References int_to_alphanum(), max_index(), and NUMCHARS.
 {
     int i;
     for(i = 0; i < n; ++i){
         int index = max_index(pred+i*NUMCHARS, NUMCHARS);
         printf("%c", int_to_alphanum(index));
     }
     printf("\n");
 }
randomize_data()
void randomize_data (data d)
Definition at line 1121 of file data.c.
References matrix::rows, matrix::vals, data::X, and data::y.
 {
     int i;
     for(i = d.X.rows-1; i > 0; --i){
         int index = rand()%i;
         float *swap = d.X.vals[index];
         d.X.vals[index] = d.X.vals[i];
         d.X.vals[i] = swap;
         swap = d.y.vals[index];
         d.y.vals[index] = d.y.vals[i];
         d.y.vals[i] = swap;
     }
 }
read_boxes()
box_label* read_boxes (char * filename, int * n)
Definition at line 138 of file data.c.
References box_label::bottom, file_error(), box_label::h, box_label::id, box_label::left, box_label::right, box_label::top, box_label::w, box_label::x, and box_label::y.
Referenced by fill_truth_detection(), fill_truth_region(), fill_truth_swag(), validate_coco_recall(), validate_detector_recall(), and validate_yolo_recall().
 {
     box_label *boxes = calloc(1, sizeof(box_label));
     FILE *file = fopen(filename, "r");
     if(!file) file_error(filename);
     float x, y, h, w;
     int id;
     int count = 0;
     while(fscanf(file, "%d %f %f %f %f", &id, &x, &y, &w, &h) == 5){
         boxes = realloc(boxes, (count+1)*sizeof(box_label));
         boxes[count].id = id;
         boxes[count].x = x;
         boxes[count].y = y;
         boxes[count].h = h;
         boxes[count].w = w;
         boxes[count].left   = x - w/2;
         boxes[count].right  = x + w/2;
         boxes[count].top    = y - h/2;
         boxes[count].bottom = y + h/2;
         ++count;
     }
     fclose(file);
     *n = count;
     return boxes;
 }
scale_data_rows()
void scale_data_rows (data d, float s)
Definition at line 1136 of file data.c.
References matrix::cols, matrix::rows, scale_array(), matrix::vals, and data::X.
Referenced by load_all_cifar10(), and load_cifar10_data().
 {
     int i;
     for(i = 0; i < d.X.rows; ++i){
         scale_array(d.X.vals[i], d.X.cols, s);
     }
 }
split_data()
data* split_data (data d, int part, int total)
Definition at line 1209 of file data.c.
References matrix::cols, matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     data *split = calloc(2, sizeof(data));
     int i;
     int start = part*d.X.rows/total;
     int end = (part+1)*d.X.rows/total;
     data train;
     data test;
     train.shallow = test.shallow = 1;
     test.X.rows = test.y.rows = end-start;
     train.X.rows = train.y.rows = d.X.rows - (end-start);
     train.X.cols = test.X.cols = d.X.cols;
     train.y.cols = test.y.cols = d.y.cols;
     train.X.vals = calloc(train.X.rows, sizeof(float*));
     test.X.vals = calloc(test.X.rows, sizeof(float*));
     train.y.vals = calloc(train.y.rows, sizeof(float*));
     test.y.vals = calloc(test.y.rows, sizeof(float*));
     for(i = 0; i < start; ++i){
         train.X.vals[i] = d.X.vals[i];
         train.y.vals[i] = d.y.vals[i];
     }
     for(i = start; i < end; ++i){
         test.X.vals[i-start] = d.X.vals[i];
         test.y.vals[i-start] = d.y.vals[i];
     }
     for(i = end; i < d.X.rows; ++i){
         train.X.vals[i-(end-start)] = d.X.vals[i];
         train.y.vals[i-(end-start)] = d.y.vals[i];
     }
     split[0] = train;
     split[1] = test;
     return split;
 }
translate_data_rows()
void translate_data_rows (data d, float s)
Definition at line 1144 of file data.c.
References matrix::cols, matrix::rows, translate_array(), matrix::vals, and data::X.
 {
     int i;
     for(i = 0; i < d.X.rows; ++i){
         translate_array(d.X.vals[i], d.X.cols, s);
     }
 }