Darknet: normalization_layer.h File Reference
normalization_layer.h File Reference
#include "image.h"
#include "layer.h"
#include "network.h"
Functions
layer make_normalization_layer (int batch, int w, int h, int c, int size, float alpha, float beta, float kappa)
void resize_normalization_layer (layer *layer, int h, int w)
void forward_normalization_layer (const layer layer, network net)
void backward_normalization_layer (const layer layer, network net)
void visualize_normalization_layer (layer layer, char *window)
Function Documentation
backward_normalization_layer()
void backward_normalization_layer (const layer layer, network net)
Definition at line 96 of file normalization_layer.c.
References layer::alpha, layer::batch, layer::beta, layer::c, network::delta, layer::delta, layer::h, layer::kappa, mul_cpu(), layer::norms, pow_cpu(), layer::size, and layer::w.
Referenced by make_normalization_layer().
 {
     // TODO This is approximate ;-)
     // Also this should add in to delta instead of overwritting.
     int w = layer.w;
     int h = layer.h;
     int c = layer.c;
     pow_cpu(w*h*c*layer.batch, -layer.beta, layer.norms, 1, net.delta, 1);
     mul_cpu(w*h*c*layer.batch, layer.delta, 1, net.delta, 1);
 }
forward_normalization_layer()
void forward_normalization_layer (const layer layer, network net)
Definition at line 65 of file normalization_layer.c.
References layer::alpha, axpy_cpu(), layer::batch, layer::beta, layer::c, const_cpu(), copy_cpu(), layer::h, network::input, layer::kappa, mul_cpu(), layer::norms, layer::output, pow_cpu(), scal_cpu(), layer::size, layer::squared, and layer::w.
Referenced by make_normalization_layer().
 {
     int k,b;
     int w = layer.w;
     int h = layer.h;
     int c = layer.c;
     scal_cpu(w*h*c*layer.batch, 0, layer.squared, 1);
     for(b = 0; b < layer.batch; ++b){
         float *squared = layer.squared + w*h*c*b;
         float *norms   = layer.norms + w*h*c*b;
         float *input   = net.input + w*h*c*b;
         pow_cpu(w*h*c, 2, input, 1, squared, 1);
         const_cpu(w*h, layer.kappa, norms, 1);
         for(k = 0; k < layer.size/2; ++k){
             axpy_cpu(w*h, layer.alpha, squared + w*h*k, 1, norms, 1);
         }
         for(k = 1; k < layer.c; ++k){
             copy_cpu(w*h, norms + w*h*(k-1), 1, norms + w*h*k, 1);
             int prev = k - ((layer.size-1)/2) - 1;
             int next = k + (layer.size/2);
             if(prev >= 0)      axpy_cpu(w*h, -layer.alpha, squared + w*h*prev, 1, norms + w*h*k, 1);
             if(next < layer.c) axpy_cpu(w*h,  layer.alpha, squared + w*h*next, 1, norms + w*h*k, 1);
         }
     }
     pow_cpu(w*h*c*layer.batch, -layer.beta, layer.norms, 1, layer.output, 1);
     mul_cpu(w*h*c*layer.batch, net.input, 1, layer.output, 1);
 }
make_normalization_layer()
layer make_normalization_layer (int batch, int w, int h, int c, int size, float alpha, float beta, float kappa)
Definition at line 5 of file normalization_layer.c.
References layer::alpha, layer::backward, layer::backward_gpu, backward_normalization_layer(), layer::batch, layer::beta, layer::c, layer::delta, layer::forward, layer::forward_gpu, forward_normalization_layer(), layer::h, layer::inputs, layer::kappa, NORMALIZATION, layer::norms, layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::size, layer::squared, layer::type, and layer::w.
Referenced by parse_normalization().
 {
     fprintf(stderr, "Local Response Normalization Layer: %d x %d x %d image, %d size\n", w,h,c,size);
     layer layer = {0};
     layer.type = NORMALIZATION;
     layer.batch = batch;
     layer.h = layer.out_h = h;
     layer.w = layer.out_w = w;
     layer.c = layer.out_c = c;
     layer.kappa = kappa;
     layer.size = size;
     layer.alpha = alpha;
     layer.beta = beta;
     layer.output = calloc(h * w * c * batch, sizeof(float));
     layer.delta = calloc(h * w * c * batch, sizeof(float));
     layer.squared = calloc(h * w * c * batch, sizeof(float));
     layer.norms = calloc(h * w * c * batch, sizeof(float));
     layer.inputs = w*h*c;
     layer.outputs = layer.inputs;
     layer.forward = forward_normalization_layer;
     layer.backward = backward_normalization_layer;
     #ifdef GPU
     layer.forward_gpu = forward_normalization_layer_gpu;
     layer.backward_gpu = backward_normalization_layer_gpu;
     layer.output_gpu =  cuda_make_array(layer.output, h * w * c * batch);
     layer.delta_gpu =   cuda_make_array(layer.delta, h * w * c * batch);
     layer.squared_gpu = cuda_make_array(layer.squared, h * w * c * batch);
     layer.norms_gpu =   cuda_make_array(layer.norms, h * w * c * batch);
     #endif
     return layer;
 }
resize_normalization_layer()
void resize_normalization_layer (layer * layer, int h, int w)
Definition at line 39 of file normalization_layer.c.
References layer::batch, layer::c, layer::delta, layer::h, layer::inputs, layer::norms, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::squared, and layer::w.
Referenced by resize_network().
 {
     int c = layer->c;
     int batch = layer->batch;
     layer->h = h;
     layer->w = w;
     layer->out_h = h;
     layer->out_w = w;
     layer->inputs = w*h*c;
     layer->outputs = layer->inputs;
     layer->output = realloc(layer->output, h * w * c * batch * sizeof(float));
     layer->delta = realloc(layer->delta, h * w * c * batch * sizeof(float));
     layer->squared = realloc(layer->squared, h * w * c * batch * sizeof(float));
     layer->norms = realloc(layer->norms, h * w * c * batch * sizeof(float));
 #ifdef GPU
     cuda_free(layer->output_gpu);
     cuda_free(layer->delta_gpu);
     cuda_free(layer->squared_gpu);
     cuda_free(layer->norms_gpu);
     layer->output_gpu =  cuda_make_array(layer->output, h * w * c * batch);
     layer->delta_gpu =   cuda_make_array(layer->delta, h * w * c * batch);
     layer->squared_gpu = cuda_make_array(layer->squared, h * w * c * batch);
     layer->norms_gpu =   cuda_make_array(layer->norms, h * w * c * batch);
 #endif
 }
visualize_normalization_layer()
void visualize_normalization_layer (layer layer, char * window)