Darknet: image.c File Reference
image.c File Reference
#include "image.h"
#include "utils.h"
#include "blas.h"
#include "cuda.h"
#include <stdio.h>
#include <math.h>
#include "stb_image.h"
#include "stb_image_write.h"
Macros
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
Functions
float get_color (int c, int x, int max)
void composite_image (image source, image dest, int dx, int dy)
image border_image (image a, int border)
image tile_images (image a, image b, int dx)
image get_label (image **characters, char *string, int size)
void draw_label (image a, int r, int c, image label, const float *rgb)
void draw_box (image a, int x1, int y1, int x2, int y2, float r, float g, float b)
void draw_box_width (image a, int x1, int y1, int x2, int y2, int w, float r, float g, float b)
void draw_bbox (image a, box bbox, int w, float r, float g, float b)
image ** load_alphabet ()
void draw_detections (image im, int num, float thresh, box *boxes, float **probs, char **names, image **alphabet, int classes)
void transpose_image (image im)
void rotate_image_cw (image im, int times)
void flip_image (image a)
image image_distance (image a, image b)
void ghost_image (image source, image dest, int dx, int dy)
void embed_image (image source, image dest, int dx, int dy)
image collapse_image_layers (image source, int border)
void constrain_image (image im)
void normalize_image (image p)
void normalize_image2 (image p)
void copy_image_into (image src, image dest)
image copy_image (image p)
void rgbgr_image (image im)
void show_image (image p, const char *name)
void save_image_png (image im, const char *name)
void save_image (image im, const char *name)
void show_image_layers (image p, char *name)
void show_image_collapsed (image p, char *name)
image make_empty_image (int w, int h, int c)
image make_image (int w, int h, int c)
image make_random_image (int w, int h, int c)
image float_to_image (int w, int h, int c, float *data)
void place_image (image im, int w, int h, int dx, int dy, image canvas)
image center_crop_image (image im, int w, int h)
image rotate_crop_image (image im, float rad, float s, int w, int h, float dx, float dy, float aspect)
image rotate_image (image im, float rad)
void fill_image (image m, float s)
void translate_image (image m, float s)
void scale_image (image m, float s)
image crop_image (image im, int dx, int dy, int w, int h)
int best_3d_shift_r (image a, image b, int min, int max)
int best_3d_shift (image a, image b, int min, int max)
void composite_3d (char *f1, char *f2, char *out, int delta)
void letterbox_image_into (image im, int w, int h, image boxed)
image letterbox_image (image im, int w, int h)
image resize_max (image im, int max)
image resize_min (image im, int min)
image random_crop_image (image im, int w, int h)
image random_augment_image (image im, float angle, float aspect, int low, int high, int size)
float three_way_max (float a, float b, float c)
float three_way_min (float a, float b, float c)
void yuv_to_rgb (image im)
void rgb_to_yuv (image im)
void rgb_to_hsv (image im)
void hsv_to_rgb (image im)
void grayscale_image_3c (image im)
image grayscale_image (image im)
image threshold_image (image im, float thresh)
image blend_image (image fore, image back, float alpha)
void scale_image_channel (image im, int c, float v)
void translate_image_channel (image im, int c, float v)
image binarize_image (image im)
void saturate_image (image im, float sat)
void hue_image (image im, float hue)
void exposure_image (image im, float sat)
void distort_image (image im, float hue, float sat, float val)
void random_distort_image (image im, float hue, float saturation, float exposure)
void saturate_exposure_image (image im, float sat, float exposure)
float bilinear_interpolate (image im, float x, float y, int c)
image resize_image (image im, int w, int h)
void test_resize (char *filename)
image load_image_stb (char *filename, int channels)
image load_image (char *filename, int w, int h, int c)
image load_image_color (char *filename, int w, int h)
image get_image_layer (image m, int l)
float get_pixel (image m, int x, int y, int c)
float get_pixel_extend (image m, int x, int y, int c)
void set_pixel (image m, int x, int y, int c, float val)
void add_pixel (image m, int x, int y, int c, float val)
void print_image (image m)
image collapse_images_vert (image *ims, int n)
image collapse_images_horz (image *ims, int n)
void show_image_normalized (image im, const char *name)
void show_images (image *ims, int n, char *window)
void free_image (image m)
Variables
int windows = 0
float colors [6][3] = { {1,0,1}, {0,0,1},{0,1,1},{0,1,0},{1,1,0},{1,0,0} }
Macro Definition Documentation
STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
Definition at line 8 of file image.c.
STB_IMAGE_WRITE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
Definition at line 10 of file image.c.
Function Documentation
add_pixel()
void add_pixel (image m, int x, int y, int c, float val)
Definition at line 1403 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by resize_image().
 {
     assert(x < m.w && y < m.h && c < m.c);
     m.data[c*m.h*m.w + y*m.w + x] += val;
 }
best_3d_shift()
int best_3d_shift (image a, image b, int min, int max)
Definition at line 775 of file image.c.
References image::c, crop_image(), image::data, dist_array(), free_image(), image::h, and image::w.
 {
     int i;
     int best = 0;
     float best_distance = FLT_MAX;
     for(i = min; i <= max; i += 2){
         image c = crop_image(b, 0, i, b.w, b.h);
         float d = dist_array(c.data, a.data, a.w*a.h*a.c, 100);
         if(d < best_distance){
             best_distance = d;
             best = i;
         }
         printf("%d %f\n", i, d);
         free_image(c);
     }
     return best;
 }
best_3d_shift_r()
int best_3d_shift_r (image a, image b, int min, int max)
Definition at line 761 of file image.c.
References best_3d_shift_r(), image::c, crop_image(), image::data, dist_array(), free_image(), image::h, and image::w.
Referenced by best_3d_shift_r(), composite_3d(), and extract_voxel().
 {
     if(min == max) return min;
     int mid = floor((min + max) / 2.);
     image c1 = crop_image(b, 0, mid, b.w, b.h);
     image c2 = crop_image(b, 0, mid+1, b.w, b.h);
     float d1 = dist_array(c1.data, a.data, a.w*a.h*a.c, 10);
     float d2 = dist_array(c2.data, a.data, a.w*a.h*a.c, 10);
     free_image(c1);
     free_image(c2);
     if(d1 < d2) return best_3d_shift_r(a, b, min, mid);
     else return best_3d_shift_r(a, b, mid+1, max);
 }
bilinear_interpolate()
float bilinear_interpolate (image im, float x, float y, int c)
Definition at line 1218 of file image.c.
References get_pixel_extend().
Referenced by place_image(), rotate_crop_image(), and rotate_image().
 {
     int ix = (int) floorf(x);
     int iy = (int) floorf(y);
     float dx = x - ix;
     float dy = y - iy;
     float val = (1-dy) * (1-dx) * get_pixel_extend(im, ix, iy, c) +
         dy     * (1-dx) * get_pixel_extend(im, ix, iy+1, c) +
         (1-dy) *   dx   * get_pixel_extend(im, ix+1, iy, c) +
         dy     *   dx   * get_pixel_extend(im, ix+1, iy+1, c);
     return val;
 }
binarize_image()
image binarize_image (image im)
Definition at line 1146 of file image.c.
References image::c, copy_image(), image::data, image::h, and image::w.
 {
     image c = copy_image(im);
     int i;
     for(i = 0; i < im.w * im.h * im.c; ++i){
         if(c.data[i] > .5) c.data[i] = 1;
         else c.data[i] = 0;
     }
     return c;
 }
blend_image()
image blend_image (image fore, image back, float alpha)
Definition at line 1105 of file image.c.
References image::c, get_pixel(), image::h, make_image(), set_pixel(), and image::w.
 {
     assert(fore.w == back.w && fore.h == back.h && fore.c == back.c);
     image blend = make_image(fore.w, fore.h, fore.c);
     int i, j, k;
     for(k = 0; k < fore.c; ++k){
         for(j = 0; j < fore.h; ++j){
             for(i = 0; i < fore.w; ++i){
                 float val = alpha * get_pixel(fore, i, j, k) +
                     (1 - alpha)* get_pixel(back, i, j, k);
                 set_pixel(blend, i, j, k, val);
             }
         }
     }
     return blend;
 }
border_image()
image border_image (image a, int border)
Definition at line 42 of file image.c.
References image::c, get_pixel_extend(), image::h, make_image(), set_pixel(), and image::w.
Referenced by get_label().
 {
     image b = make_image(a.w + 2*border, a.h + 2*border, a.c);
     int x,y,k;
     for(k = 0; k < b.c; ++k){
         for(y = 0; y < b.h; ++y){
             for(x = 0; x < b.w; ++x){
                 float val = get_pixel_extend(a, x - border, y - border, k);
                 if(x - border < 0 || x - border >= a.w || y - border < 0 || y - border >= a.h) val = 1;
                 set_pixel(b, x, y, k, val);
             }
         }
     }
     return b;
 }
center_crop_image()
image center_crop_image (image im, int w, int h)
Definition at line 676 of file image.c.
References crop_image(), free_image(), image::h, resize_image(), and image::w.
Referenced by load_image_augment_paths().
 {
     int m = (im.w < im.h) ? im.w : im.h;
     image c = crop_image(im, (im.w - m) / 2, (im.h - m)/2, m, m);
     image r = resize_image(c, w, h);
     free_image(c);
     return r;
 }
collapse_image_layers()
image collapse_image_layers (image source, int border)
Definition at line 325 of file image.c.
References image::c, embed_image(), free_image(), get_image_layer(), image::h, make_image(), and image::w.
Referenced by show_image_collapsed(), and visualize_convolutional_layer().
 {
     int h = source.h;
     h = (h+border)*source.c - border;
     image dest = make_image(source.w, h, 1);
     int i;
     for(i = 0; i < source.c; ++i){
         image layer = get_image_layer(source, i);
         int h_offset = i*(source.h+border);
         embed_image(layer, dest, 0, h_offset);
         free_image(layer);
     }
     return dest;
 }
collapse_images_horz()
image collapse_images_horz (image * ims, int n)
Definition at line 1461 of file image.c.
References image::c, copy_image(), embed_image(), free_image(), get_image_layer(), image::h, make_image(), and image::w.
 {
     int color = 1;
     int border = 1;
     int h,w,c;
     int size = ims[0].h;
     h = size;
     w = (ims[0].w + border) * n - border;
     c = ims[0].c;
     if(c != 3 || !color){
         h = (h+border)*c - border;
         c = 1;
     }
     image filters = make_image(w, h, c);
     int i,j;
     for(i = 0; i < n; ++i){
         int w_offset = i*(size+border);
         image copy = copy_image(ims[i]);
         //normalize_image(copy);
         if(c == 3 && color){
             embed_image(copy, filters, w_offset, 0);
         }
         else{
             for(j = 0; j < copy.c; ++j){
                 int h_offset = j*(size+border);
                 image layer = get_image_layer(copy, j);
                 embed_image(layer, filters, w_offset, h_offset);
                 free_image(layer);
             }
         }
         free_image(copy);
     }
     return filters;
 }
collapse_images_vert()
image collapse_images_vert (image * ims, int n)
Definition at line 1426 of file image.c.
References image::c, copy_image(), embed_image(), free_image(), get_image_layer(), image::h, make_image(), and image::w.
Referenced by show_images().
 {
     int color = 1;
     int border = 1;
     int h,w,c;
     w = ims[0].w;
     h = (ims[0].h + border) * n - border;
     c = ims[0].c;
     if(c != 3 || !color){
         w = (w+border)*c - border;
         c = 1;
     }
     image filters = make_image(w, h, c);
     int i,j;
     for(i = 0; i < n; ++i){
         int h_offset = i*(ims[0].h+border);
         image copy = copy_image(ims[i]);
         //normalize_image(copy);
         if(c == 3 && color){
             embed_image(copy, filters, 0, h_offset);
         }
         else{
             for(j = 0; j < copy.c; ++j){
                 int w_offset = j*(ims[0].w+border);
                 image layer = get_image_layer(copy, j);
                 embed_image(layer, filters, w_offset, h_offset);
                 free_image(layer);
             }
         }
         free_image(copy);
     }
     return filters;
 }
composite_3d()
void composite_3d (char * f1, char * f2, char * out, int delta)
Definition at line 793 of file image.c.
References best_3d_shift_r(), image::c, crop_image(), image::data, dist_array(), image::h, load_image(), save_image(), and image::w.
Referenced by main().
 {
     if(!out) out = "out";
     image a = load_image(f1, 0,0,0);
     image b = load_image(f2, 0,0,0);
     int shift = best_3d_shift_r(a, b, -a.h/100, a.h/100);
     image c1 = crop_image(b, 10, shift, b.w, b.h);
     float d1 = dist_array(c1.data, a.data, a.w*a.h*a.c, 100);
     image c2 = crop_image(b, -10, shift, b.w, b.h);
     float d2 = dist_array(c2.data, a.data, a.w*a.h*a.c, 100);
     if(d2 < d1 && 0){
         image swap = a;
         a = b;
         b = swap;
         shift = -shift;
         printf("swapped, %d\n", shift);
     }
     else{
         printf("%d\n", shift);
     }
     image c = crop_image(b, delta, shift, a.w, a.h);
     int i;
     for(i = 0; i < c.w*c.h; ++i){
         c.data[i] = a.data[i];
     }
 #ifdef OPENCV
     save_image_jpg(c, out);
 #else
     save_image(c, out);
 #endif
 }
composite_image()
void composite_image (image source, image dest, int dx, int dy)
Definition at line 28 of file image.c.
References image::c, get_pixel(), get_pixel_extend(), image::h, set_pixel(), and image::w.
Referenced by tile_images().
 {
     int x,y,k;
     for(k = 0; k < source.c; ++k){
         for(y = 0; y < source.h; ++y){
             for(x = 0; x < source.w; ++x){
                 float val = get_pixel(source, x, y, k);
                 float val2 = get_pixel_extend(dest, dx+x, dy+y, k);
                 set_pixel(dest, dx+x, dy+y, k, val * val2);
             }
         }
     }
 }
constrain_image()
void constrain_image (image im)
Definition at line 340 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by distort_image(), exposure_image(), hue_image(), optimize_picture(), reconstruct_picture(), saturate_exposure_image(), saturate_image(), show_image(), and test_lsd().
 {
     int i;
     for(i = 0; i < im.w*im.h*im.c; ++i){
         if(im.data[i] < 0) im.data[i] = 0;
         if(im.data[i] > 1) im.data[i] = 1;
     }
 }
copy_image()
image copy_image (image p)
Definition at line 403 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by binarize_image(), collapse_images_horz(), collapse_images_vert(), get_weights(), mkimg(), run_nightmare(), show_image(), show_image_normalized(), test_resize(), and tile_images().
 {
     image copy = p;
     copy.data = calloc(p.h*p.w*p.c, sizeof(float));
     memcpy(copy.data, p.data, p.h*p.w*p.c*sizeof(float));
     return copy;
 }
copy_image_into()
void copy_image_into (image src, image dest)
Definition at line 398 of file image.c.
References image::c, image::data, image::h, and image::w.
 {
     memcpy(dest.data, src.data, src.h*src.w*src.c*sizeof(float));
 }
crop_image()
image crop_image (image im, int dx, int dy, int w, int h)
Definition at line 741 of file image.c.
References image::c, constrain_int(), get_pixel(), image::h, make_image(), set_pixel(), and image::w.
Referenced by best_3d_shift(), best_3d_shift_r(), center_crop_image(), composite_3d(), extract_voxel(), label_classifier(), load_data_region(), load_data_swag(), optimize_picture(), random_crop_image(), run_nightmare(), test_lsd(), try_classifier(), validate_classifier_10(), and validate_classifier_single().
 {
     image cropped = make_image(w, h, im.c);
     int i, j, k;
     for(k = 0; k < im.c; ++k){
         for(j = 0; j < h; ++j){
             for(i = 0; i < w; ++i){
                 int r = j + dy;
                 int c = i + dx;
                 float val = 0;
                 r = constrain_int(r, 0, im.h-1);
                 c = constrain_int(c, 0, im.w-1);
                 val = get_pixel(im, c, r, k);
                 set_pixel(cropped, i, j, k, val);
             }
         }
     }
     return cropped;
 }
distort_image()
void distort_image (image im, float hue, float sat, float val)
Definition at line 1186 of file image.c.
References constrain_image(), image::data, image::h, hsv_to_rgb(), rgb_to_hsv(), scale_image_channel(), and image::w.
Referenced by random_distort_image(), and test_resize().
 {
     rgb_to_hsv(im);
     scale_image_channel(im, 1, sat);
     scale_image_channel(im, 2, val);
     int i;
     for(i = 0; i < im.w*im.h; ++i){
         im.data[i] = im.data[i] + hue;
         if (im.data[i] > 1) im.data[i] -= 1;
         if (im.data[i] < 0) im.data[i] += 1;
     }
     hsv_to_rgb(im);
     constrain_image(im);
 }
draw_bbox()
void draw_bbox (image a, box bbox, int w, float r, float g, float b)
Definition at line 145 of file image.c.
References draw_box(), box::h, image::h, box::w, image::w, box::x, and box::y.
 {
     int left  = (bbox.x-bbox.w/2)*a.w;
     int right = (bbox.x+bbox.w/2)*a.w;
     int top   = (bbox.y-bbox.h/2)*a.h;
     int bot   = (bbox.y+bbox.h/2)*a.h;
     int i;
     for(i = 0; i < w; ++i){
         draw_box(a, left+i, top+i, right-i, bot-i, r, g, b);
     }
 }
draw_box()
void draw_box (image a, int x1, int y1, int x2, int y2, float r, float g, float b)
Definition at line 101 of file image.c.
References image::data, image::h, and image::w.
Referenced by draw_bbox(), and draw_box_width().
 {
     //normalize_image(a);
     int i;
     if(x1 < 0) x1 = 0;
     if(x1 >= a.w) x1 = a.w-1;
     if(x2 < 0) x2 = 0;
     if(x2 >= a.w) x2 = a.w-1;
     if(y1 < 0) y1 = 0;
     if(y1 >= a.h) y1 = a.h-1;
     if(y2 < 0) y2 = 0;
     if(y2 >= a.h) y2 = a.h-1;
     for(i = x1; i <= x2; ++i){
         a.data[i + y1*a.w + 0*a.w*a.h] = r;
         a.data[i + y2*a.w + 0*a.w*a.h] = r;
         a.data[i + y1*a.w + 1*a.w*a.h] = g;
         a.data[i + y2*a.w + 1*a.w*a.h] = g;
         a.data[i + y1*a.w + 2*a.w*a.h] = b;
         a.data[i + y2*a.w + 2*a.w*a.h] = b;
     }
     for(i = y1; i <= y2; ++i){
         a.data[x1 + i*a.w + 0*a.w*a.h] = r;
         a.data[x2 + i*a.w + 0*a.w*a.h] = r;
         a.data[x1 + i*a.w + 1*a.w*a.h] = g;
         a.data[x2 + i*a.w + 1*a.w*a.h] = g;
         a.data[x1 + i*a.w + 2*a.w*a.h] = b;
         a.data[x2 + i*a.w + 2*a.w*a.h] = b;
     }
 }
draw_box_width()
void draw_box_width (image a, int x1, int y1, int x2, int y2, int w, float r, float g, float b)
Definition at line 137 of file image.c.
References draw_box().
Referenced by draw_detections(), and threat_classifier().
 {
     int i;
     for(i = 0; i < w; ++i){
         draw_box(a, x1+i, y1+i, x2-i, y2-i, r, g, b);
     }
 }
draw_detections()
void draw_detections (image im, int num, float thresh, box * boxes, float ** probs, char ** names, image ** alphabet, int classes)
Definition at line 174 of file image.c.
References draw_box_width(), draw_label(), free_image(), get_color(), get_label(), box::h, image::h, max_index(), box::w, image::w, box::x, and box::y.
Referenced by test_coco(), test_detector(), and test_yolo().
 {
     int i;
     for(i = 0; i < num; ++i){
         int class = max_index(probs[i], classes);
         float prob = probs[i][class];
         if(prob > thresh){
             int width = im.h * .012;
             if(0){
                 width = pow(prob, 1./2.)*10+1;
                 alphabet = 0;
             }
             //printf("%d %s: %.0f%%\n", i, names[class], prob*100);
             printf("%s: %.0f%%\n", names[class], prob*100);
             int offset = class*123457 % classes;
             float red = get_color(2,offset,classes);
             float green = get_color(1,offset,classes);
             float blue = get_color(0,offset,classes);
             float rgb[3];
             //width = prob*20+2;
             rgb[0] = red;
             rgb[1] = green;
             rgb[2] = blue;
             box b = boxes[i];
             int left  = (b.x-b.w/2.)*im.w;
             int right = (b.x+b.w/2.)*im.w;
             int top   = (b.y-b.h/2.)*im.h;
             int bot   = (b.y+b.h/2.)*im.h;
             if(left < 0) left = 0;
             if(right > im.w-1) right = im.w-1;
             if(top < 0) top = 0;
             if(bot > im.h-1) bot = im.h-1;
             draw_box_width(im, left, top, right, bot, width, red, green, blue);
             if (alphabet) {
                 image label = get_label(alphabet, names[class], (im.h*.03)/10);
                 draw_label(im, top + width, left, label, rgb);
                 free_image(label);
             }
         }
     }
 }
draw_label()
void draw_label (image a, int r, int c, image label, const float * rgb)
Definition at line 84 of file image.c.
References image::c, get_pixel(), image::h, set_pixel(), and image::w.
Referenced by draw_detections().
 {
     int w = label.w;
     int h = label.h;
     if (r - h >= 0) r = r - h;
     int i, j, k;
     for(j = 0; j < h && j + r < a.h; ++j){
         for(i = 0; i < w && i + c < a.w; ++i){
             for(k = 0; k < label.c; ++k){
                 float val = get_pixel(label, i, j, k);
                 set_pixel(a, i+c, j+r, k, rgb[k] * val);
             }
         }
     }
 }
embed_image()
void embed_image (image source, image dest, int dx, int dy)
Definition at line 312 of file image.c.
References image::c, get_pixel(), image::h, set_pixel(), and image::w.
Referenced by collapse_image_layers(), collapse_images_horz(), collapse_images_vert(), letterbox_image(), letterbox_image_into(), and tile_images().
 {
     int x,y,k;
     for(k = 0; k < source.c; ++k){
         for(y = 0; y < source.h; ++y){
             for(x = 0; x < source.w; ++x){
                 float val = get_pixel(source, x,y,k);
                 set_pixel(dest, dx+x, dy+y, k, val);
             }
         }
     }
 }
exposure_image()
void exposure_image (image im, float sat)
Definition at line 1178 of file image.c.
References constrain_image(), hsv_to_rgb(), rgb_to_hsv(), and scale_image_channel().
 {
     rgb_to_hsv(im);
     scale_image_channel(im, 2, sat);
     hsv_to_rgb(im);
     constrain_image(im);
 }
fill_image()
void fill_image (image m, float s)
Definition at line 723 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by letterbox_image(), load_data_detection(), and mkimg().
 {
     int i;
     for(i = 0; i < m.h*m.w*m.c; ++i) m.data[i] = s;
 }
flip_image()
void flip_image (image a)
Definition at line 262 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by load_data_detection(), load_data_region(), load_data_super(), load_data_swag(), load_image_augment_paths(), optimize_picture(), predict_move(), random_go_moves(), test_cifar_csv(), test_cifar_csvtrain(), test_cifar_multi(), validate_classifier_10(), validate_classifier_multi(), and validate_detector_flip().
 {
     int i,j,k;
     for(k = 0; k < a.c; ++k){
         for(i = 0; i < a.h; ++i){
             for(j = 0; j < a.w/2; ++j){
                 int index = j + a.w*(i + a.h*(k));
                 int flip = (a.w - j - 1) + a.w*(i + a.h*(k));
                 float swap = a.data[flip];
                 a.data[flip] = a.data[index];
                 a.data[index] = swap;
             }
         }
     }
 }
float_to_image()
image float_to_image (int w, int h, int c, float * data)
Definition at line 654 of file image.c.
References image::data, and make_empty_image().
Referenced by extract_cifar(), get_convolutional_delta(), get_convolutional_image(), get_convolutional_weight(), get_crop_image(), get_maxpool_delta(), get_maxpool_image(), get_network_image_layer(), predict_move(), random_go_moves(), test_cifar_csv(), test_cifar_csvtrain(), test_cifar_multi(), train_colorizer(), and train_dcgan().
 {
     image out = make_empty_image(w,h,c);
     out.data = data;
     return out;
 }
free_image()
void free_image (image m)
Definition at line 1523 of file image.c.
References image::data.
Referenced by bbox_comparator(), bbox_fight(), best_3d_shift(), best_3d_shift_r(), center_crop_image(), collapse_image_layers(), collapse_images_horz(), collapse_images_vert(), demo_art(), demo_classifier(), demo_regressor(), draw_detections(), extract_voxel(), get_label(), gun_classifier(), label_classifier(), letterbox_image(), letterbox_image_into(), load_data_compare(), load_data_detection(), load_data_region(), load_data_super(), load_data_swag(), load_image(), load_image_augment_paths(), load_image_paths_gray(), mkimg(), optimize_picture(), predict_classifier(), predict_regressor(), reconstruct_picture(), resize_image(), run_nightmare(), show_image(), show_image_collapsed(), show_image_layers(), show_image_normalized(), show_images(), test_captcha(), test_cifar_multi(), test_coco(), test_dcgan(), test_detector(), test_dice(), test_lsd(), test_resize(), test_super(), test_tag(), test_voxel(), test_writing(), test_yolo(), threat_classifier(), try_classifier(), valid_captcha(), validate_classifier_10(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_yolo(), validate_yolo_recall(), and visualize_convolutional_layer().
 {
     if(m.data){
         free(m.data);
     }
 }
get_color()
float get_color (int c, int x, int max)
Definition at line 17 of file image.c.
References colors.
Referenced by draw_detections().
 {
     float ratio = ((float)x/max)*5;
     int i = floor(ratio);
     int j = ceil(ratio);
     ratio -= i;
     float r = (1-ratio) * colors[i][c] + ratio*colors[j][c];
     //printf("%f\n", r);
     return r;
 }
get_image_layer()
image get_image_layer (image m, int l)
Definition at line 1373 of file image.c.
References image::data, image::h, make_image(), and image::w.
Referenced by collapse_image_layers(), collapse_images_horz(), collapse_images_vert(), and show_image_layers().
 {
     image out = make_image(m.w, m.h, 1);
     int i;
     for(i = 0; i < m.h*m.w; ++i){
         out.data[i] = m.data[i+l*m.h*m.w];
     }
     return out;
 }
get_label()
image get_label (image ** characters, char * string, int size)
Definition at line 68 of file image.c.
References border_image(), free_image(), image::h, make_empty_image(), and tile_images().
Referenced by draw_detections().
 {
     if(size > 7) size = 7;
     image label = make_empty_image(0,0,0);
     while(*string){
         image l = characters[size][(int)*string];
         image n = tile_images(label, l, -size - 1 + (size+1)/2);
         free_image(label);
         label = n;
         ++string;
     }
     image b = border_image(label, label.h*.25);
     free_image(label);
     return b;
 }
get_pixel()
float get_pixel (image m, int x, int y, int c)
Definition at line 1383 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by blend_image(), composite_image(), crop_image(), draw_label(), embed_image(), get_pixel_extend(), ghost_image(), grayscale_image(), grayscale_image_3c(), hsv_to_rgb(), resize_image(), rgb_to_hsv(), rgb_to_yuv(), rgbgr_image(), scale_image_channel(), show_image(), translate_image_channel(), and yuv_to_rgb().
 {
     assert(x < m.w && y < m.h && c < m.c);
     return m.data[c*m.h*m.w + y*m.w + x];
 }
get_pixel_extend()
float get_pixel_extend (image m, int x, int y, int c)
Definition at line 1388 of file image.c.
References image::c, get_pixel(), image::h, and image::w.
Referenced by bilinear_interpolate(), border_image(), and composite_image().
 {
     if(x < 0) x = 0;
     if(x >= m.w) x = m.w-1;
     if(y < 0) y = 0;
     if(y >= m.h) y = m.h-1;
     if(c < 0 || c >= m.c) return 0;
     return get_pixel(m, x, y, c);
 }
ghost_image()
void ghost_image (image source, image dest, int dx, int dy)
Definition at line 293 of file image.c.
References image::c, get_pixel(), image::h, set_pixel(), and image::w.
Referenced by mkimg().
 {
     int x,y,k;
     float max_dist = sqrt((-source.w/2. + .5)*(-source.w/2. + .5));
     for(k = 0; k < source.c; ++k){
         for(y = 0; y < source.h; ++y){
             for(x = 0; x < source.w; ++x){
                 float dist = sqrt((x - source.w/2. + .5)*(x - source.w/2. + .5) + (y - source.h/2. + .5)*(y - source.h/2. + .5));
                 float alpha = (1 - dist/max_dist);
                 if(alpha < 0) alpha = 0;
                 float v1 = get_pixel(source, x,y,k);
                 float v2 = get_pixel(dest, dx+x,dy+y,k);
                 float val = alpha*v1 + (1-alpha)*v2;
                 set_pixel(dest, dx+x, dy+y, k, val);
             }
         }
     }
 }
grayscale_image()
image grayscale_image (image im)
Definition at line 1079 of file image.c.
References image::c, image::data, get_pixel(), image::h, make_image(), and image::w.
Referenced by load_image_paths_gray(), run_nightmare(), and test_resize().
 {
     assert(im.c == 3);
     int i, j, k;
     image gray = make_image(im.w, im.h, 1);
     float scale[] = {0.299, 0.587, 0.114};
     for(k = 0; k < im.c; ++k){
         for(j = 0; j < im.h; ++j){
             for(i = 0; i < im.w; ++i){
                 gray.data[i+im.w*j] += scale[k]*get_pixel(im, i, j, k);
             }
         }
     }
     return gray;
 }
grayscale_image_3c()
void grayscale_image_3c (image im)
Definition at line 1061 of file image.c.
References image::c, image::data, get_pixel(), image::h, and image::w.
Referenced by test_lsd(), and train_colorizer().
 {
     assert(im.c == 3);
     int i, j, k;
     float scale[] = {0.299, 0.587, 0.114};
     for(j = 0; j < im.h; ++j){
         for(i = 0; i < im.w; ++i){
             float val = 0;
             for(k = 0; k < 3; ++k){
                 val += scale[k]*get_pixel(im, i, j, k);
             }
             im.data[0*im.h*im.w + im.w*j + i] = val;
             im.data[1*im.h*im.w + im.w*j + i] = val;
             im.data[2*im.h*im.w + im.w*j + i] = val;
         }
     }
 }
hsv_to_rgb()
void hsv_to_rgb (image im)
Definition at line 1020 of file image.c.
References image::c, get_pixel(), image::h, set_pixel(), and image::w.
Referenced by distort_image(), exposure_image(), hue_image(), saturate_exposure_image(), and saturate_image().
 {
     assert(im.c == 3);
     int i, j;
     float r, g, b;
     float h, s, v;
     float f, p, q, t;
     for(j = 0; j < im.h; ++j){
         for(i = 0; i < im.w; ++i){
             h = 6 * get_pixel(im, i , j, 0);
             s = get_pixel(im, i , j, 1);
             v = get_pixel(im, i , j, 2);
             if (s == 0) {
                 r = g = b = v;
             } else {
                 int index = floor(h);
                 f = h - index;
                 p = v*(1-s);
                 q = v*(1-s*f);
                 t = v*(1-s*(1-f));
                 if(index == 0){
                     r = v; g = t; b = p;
                 } else if(index == 1){
                     r = q; g = v; b = p;
                 } else if(index == 2){
                     r = p; g = v; b = t;
                 } else if(index == 3){
                     r = p; g = q; b = v;
                 } else if(index == 4){
                     r = t; g = p; b = v;
                 } else {
                     r = v; g = p; b = q;
                 }
             }
             set_pixel(im, i, j, 0, r);
             set_pixel(im, i, j, 1, g);
             set_pixel(im, i, j, 2, b);
         }
     }
 }
hue_image()
void hue_image (image im, float hue)
Definition at line 1165 of file image.c.
References constrain_image(), image::data, image::h, hsv_to_rgb(), rgb_to_hsv(), and image::w.
 {
     rgb_to_hsv(im);
     int i;
     for(i = 0; i < im.w*im.h; ++i){
         im.data[i] = im.data[i] + hue;
         if (im.data[i] > 1) im.data[i] -= 1;
         if (im.data[i] < 0) im.data[i] += 1;
     }
     hsv_to_rgb(im);
     constrain_image(im);
 }
image_distance()
image image_distance (image a, image b)
Definition at line 278 of file image.c.
References image::c, image::data, image::h, make_image(), and image::w.
 {
     int i,j;
     image dist = make_image(a.w, a.h, 1);
     for(i = 0; i < a.c; ++i){
         for(j = 0; j < a.h*a.w; ++j){
             dist.data[j] += pow(a.data[i*a.h*a.w+j]-b.data[i*a.h*a.w+j],2);
         }
     }
     for(j = 0; j < a.h*a.w; ++j){
         dist.data[j] = sqrt(dist.data[j]);
     }
     return dist;
 }
letterbox_image()
image letterbox_image (image im, int w, int h)
Definition at line 844 of file image.c.
References image::c, embed_image(), fill_image(), free_image(), image::h, make_image(), resize_image(), and image::w.
Referenced by demo_regressor(), load_thread(), predict_regressor(), run_nightmare(), and test_detector().
 {
     int new_w = im.w;
     int new_h = im.h;
     if (((float)w/im.w) < ((float)h/im.h)) {
         new_w = w;
         new_h = (im.h * w)/im.w;
     } else {
         new_h = h;
         new_w = (im.w * h)/im.h;
     }
     image resized = resize_image(im, new_w, new_h);
     image boxed = make_image(w, h, im.c);
     fill_image(boxed, .5);
     //int i;
     //for(i = 0; i < boxed.w*boxed.h*boxed.c; ++i) boxed.data[i] = 0;
     embed_image(resized, boxed, (w-new_w)/2, (h-new_h)/2);
     free_image(resized);
     return boxed;
 }
letterbox_image_into()
void letterbox_image_into (image im, int w, int h, image boxed)
Definition at line 828 of file image.c.
References embed_image(), free_image(), image::h, resize_image(), and image::w.
 {
     int new_w = im.w;
     int new_h = im.h;
     if (((float)w/im.w) < ((float)h/im.h)) {
         new_w = w;
         new_h = (im.h * w)/im.w;
     } else {
         new_h = h;
         new_w = (im.w * h)/im.h;
     }
     image resized = resize_image(im, new_w, new_h);
     embed_image(resized, boxed, (w-new_w)/2, (h-new_h)/2);
     free_image(resized);
 }
load_alphabet()
image** load_alphabet ()
Definition at line 158 of file image.c.
References load_image_color().
Referenced by test_coco(), test_detector(), and test_yolo().
 {
     int i, j;
     const int nsize = 8;
     image **alphabets = calloc(nsize, sizeof(image));
     for(j = 0; j < nsize; ++j){
         alphabets[j] = calloc(128, sizeof(image));
         for(i = 32; i < 127; ++i){
             char buff[256];
             sprintf(buff, "data/labels/%d_%d.png", i, j);
             alphabets[j][i] = load_image_color(buff, 0, 0);
         }
     }
     return alphabets;
 }
load_image()
image load_image (char * filename, int w, int h, int c)
Definition at line 1352 of file image.c.
References free_image(), image::h, load_image_stb(), resize_image(), and image::w.
Referenced by composite_3d(), load_image_color(), load_image_paths_gray(), and test_resize().
 {
 #ifdef OPENCV
     image out = load_image_cv(filename, c);
 #else
     image out = load_image_stb(filename, c);
 #endif
     if((h && w) && (h != out.h || w != out.w)){
         image resized = resize_image(out, w, h);
         free_image(out);
         out = resized;
     }
     return out;
 }
load_image_color()
image load_image_color (char * filename, int w, int h)
Definition at line 1368 of file image.c.
References load_image().
Referenced by bbox_comparator(), bbox_fight(), label_classifier(), load_alphabet(), load_data_compare(), load_data_detection(), load_data_region(), load_data_super(), load_data_swag(), load_image_augment_paths(), load_image_paths(), load_thread(), predict_classifier(), predict_regressor(), run_nightmare(), test_captcha(), test_coco(), test_detector(), test_dice(), test_lsd(), test_super(), test_tag(), test_voxel(), test_writing(), test_yolo(), try_classifier(), valid_captcha(), validate_classifier_10(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco_recall(), validate_detector_recall(), and validate_yolo_recall().
 {
     return load_image(filename, w, h, 3);
 }
load_image_stb()
image load_image_stb (char * filename, int channels)
Definition at line 1328 of file image.c.
References image::data, make_image(), stbi_failure_reason(), and stbi_load().
Referenced by load_image().
 {
     int w, h, c;
     unsigned char *data = stbi_load(filename, &w, &h, &c, channels);
     if (!data) {
         fprintf(stderr, "Cannot load image \"%s\"\nSTB Reason: %s\n", filename, stbi_failure_reason());
         exit(0);
     }
     if(channels) c = channels;
     int i,j,k;
     image im = make_image(w, h, c);
     for(k = 0; k < c; ++k){
         for(j = 0; j < h; ++j){
             for(i = 0; i < w; ++i){
                 int dst_index = i + w*j + w*h*k;
                 int src_index = k + c*i + c*w*j;
                 im.data[dst_index] = (float)data[src_index]/255.;
             }
         }
     }
     free(data);
     return im;
 }
make_empty_image()
image make_empty_image (int w, int h, int c)
Definition at line 626 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by float_to_image(), get_label(), make_image(), make_random_image(), and show_image().
 {
     image out;
     out.data = 0;
     out.h = h;
     out.w = w;
     out.c = c;
     return out;
 }
make_image()
image make_image (int w, int h, int c)
Definition at line 636 of file image.c.
References image::data, and make_empty_image().
Referenced by blend_image(), border_image(), collapse_image_layers(), collapse_images_horz(), collapse_images_vert(), crop_image(), get_image_layer(), grayscale_image(), image_distance(), letterbox_image(), load_data_detection(), load_image_stb(), mkimg(), optimize_picture(), reconstruct_picture(), resize_image(), rotate_crop_image(), rotate_image(), run_nightmare(), show_image(), speed(), test_dcgan(), threshold_image(), tile_images(), and validate_detector_flip().
 {
     image out = make_empty_image(w,h,c);
     out.data = calloc(h*w*c, sizeof(float));
     return out;
 }
make_random_image()
image make_random_image (int w, int h, int c)
Definition at line 643 of file image.c.
References image::data, make_empty_image(), and rand_normal().
 {
     image out = make_empty_image(w,h,c);
     out.data = calloc(h*w*c, sizeof(float));
     int i;
     for(i = 0; i < w*h*c; ++i){
         out.data[i] = (rand_normal() * .25) + .5;
     }
     return out;
 }
normalize_image()
void normalize_image (image p)
Definition at line 349 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by get_weights(), show_image_normalized(), show_images(), and test_dcgan().
 {
     int i;
     float min = 9999999;
     float max = -999999;
     for(i = 0; i < p.h*p.w*p.c; ++i){
         float v = p.data[i];
         if(v < min) min = v;
         if(v > max) max = v;
     }
     if(max - min < .000000001){
         min = 0;
         max = 1;
     }
     for(i = 0; i < p.c*p.w*p.h; ++i){
         p.data[i] = (p.data[i] - min)/(max-min);
     }
 }
normalize_image2()
void normalize_image2 (image p)
Definition at line 369 of file image.c.
References image::c, image::data, image::h, and image::w.
 {
     float *min = calloc(p.c, sizeof(float));
     float *max = calloc(p.c, sizeof(float));
     int i,j;
     for(i = 0; i < p.c; ++i) min[i] = max[i] = p.data[i*p.h*p.w];
     for(j = 0; j < p.c; ++j){
         for(i = 0; i < p.h*p.w; ++i){
             float v = p.data[i+j*p.h*p.w];
             if(v < min[j]) min[j] = v;
             if(v > max[j]) max[j] = v;
         }
     }
     for(i = 0; i < p.c; ++i){
         if(max[i] - min[i] < .000000001){
             min[i] = 0;
             max[i] = 1;
         }
     }
     for(j = 0; j < p.c; ++j){
         for(i = 0; i < p.w*p.h; ++i){
             p.data[i+j*p.h*p.w] = (p.data[i+j*p.h*p.w] - min[j])/(max[j]-min[j]);
         }
     }
     free(min);
     free(max);
 }
place_image()
void place_image (image im, int w, int h, int dx, int dy, image canvas)
Definition at line 661 of file image.c.
References bilinear_interpolate(), image::c, image::h, set_pixel(), and image::w.
Referenced by load_data_detection().
 {
     int x, y, c;
     for(c = 0; c < im.c; ++c){
         for(y = 0; y < h; ++y){
             for(x = 0; x < w; ++x){
                 int rx = ((float)x / w) * im.w;
                 int ry = ((float)y / h) * im.h;
                 float val = bilinear_interpolate(im, rx, ry, c);
                 set_pixel(canvas, x + dx, y + dy, c, val);
             }
         }
     }
 }
print_image()
void print_image (image m)
Definition at line 1409 of file image.c.
References image::c, image::data, image::h, and image::w.
 {
     int i, j, k;
     for(i =0 ; i < m.c; ++i){
         for(j =0 ; j < m.h; ++j){
             for(k = 0; k < m.w; ++k){
                 printf("%.2lf, ", m.data[i*m.h*m.w + j*m.w + k]);
                 if(k > 30) break;
             }
             printf("\n");
             if(j > 30) break;
         }
         printf("\n");
     }
     printf("\n");
 }
random_augment_image()
image random_augment_image (image im, float angle, float aspect, int low, int high, int size)
Definition at line 905 of file image.c.
References image::h, rand_int(), rand_scale(), rand_uniform(), rotate_crop_image(), TWO_PI, and image::w.
Referenced by load_image_augment_paths(), and test_resize().
 {
     aspect = rand_scale(aspect);
     int r = rand_int(low, high);
     int min = (im.h < im.w*aspect) ? im.h : im.w*aspect;
     float scale = (float)r / min;
     float rad = rand_uniform(-angle, angle) * TWO_PI / 360.;
     float dx = (im.w*scale/aspect - size) / 2.;
     float dy = (im.h*scale - size) / 2.;
     if(dx < 0) dx = 0;
     if(dy < 0) dy = 0;
     dx = rand_uniform(-dx, dx);
     dy = rand_uniform(-dy, dy);
     image crop = rotate_crop_image(im, rad, scale, size, size, dx, dy, aspect);
     return crop;
 }
random_crop_image()
image random_crop_image (image im, int w, int h)
Definition at line 897 of file image.c.
References crop_image(), image::h, rand_int(), and image::w.
Referenced by load_data_super().
 {
     int dx = rand_int(0, im.w - w);
     int dy = rand_int(0, im.h - h);
     image crop = crop_image(im, dx, dy, w, h);
     return crop;
 }
random_distort_image()
void random_distort_image (image im, float hue, float saturation, float exposure)
Definition at line 1201 of file image.c.
References distort_image(), rand_scale(), and rand_uniform().
Referenced by load_data_detection(), load_data_region(), load_image_augment_paths(), and mkimg().
 {
     float dhue = rand_uniform(-hue, hue);
     float dsat = rand_scale(saturation);
     float dexp = rand_scale(exposure);
     distort_image(im, dhue, dsat, dexp);
 }
resize_image()
image resize_image (image im, int w, int h)
Definition at line 1233 of file image.c.
References add_pixel(), image::c, free_image(), get_pixel(), image::h, make_image(), set_pixel(), and image::w.
Referenced by center_crop_image(), demo_art(), demo_classifier(), gun_classifier(), letterbox_image(), letterbox_image_into(), load_data_region(), load_data_super(), load_data_swag(), load_image(), load_thread(), optimize_picture(), resize_max(), resize_min(), run_nightmare(), test_coco(), test_writing(), test_yolo(), threat_classifier(), validate_coco_recall(), validate_detector_recall(), and validate_yolo_recall().
 {
     image resized = make_image(w, h, im.c);
     image part = make_image(w, im.h, im.c);
     int r, c, k;
     float w_scale = (float)(im.w - 1) / (w - 1);
     float h_scale = (float)(im.h - 1) / (h - 1);
     for(k = 0; k < im.c; ++k){
         for(r = 0; r < im.h; ++r){
             for(c = 0; c < w; ++c){
                 float val = 0;
                 if(c == w-1 || im.w == 1){
                     val = get_pixel(im, im.w-1, r, k);
                 } else {
                     float sx = c*w_scale;
                     int ix = (int) sx;
                     float dx = sx - ix;
                     val = (1 - dx) * get_pixel(im, ix, r, k) + dx * get_pixel(im, ix+1, r, k);
                 }
                 set_pixel(part, c, r, k, val);
             }
         }
     }
     for(k = 0; k < im.c; ++k){
         for(r = 0; r < h; ++r){
             float sy = r*h_scale;
             int iy = (int) sy;
             float dy = sy - iy;
             for(c = 0; c < w; ++c){
                 float val = (1-dy) * get_pixel(part, c, iy, k);
                 set_pixel(resized, c, r, k, val);
             }
             if(r == h-1 || im.h == 1) continue;
             for(c = 0; c < w; ++c){
                 float val = dy * get_pixel(part, c, iy+1, k);
                 add_pixel(resized, c, r, k, val);
             }
         }
     }
     free_image(part);
     return resized;
 }
resize_max()
image resize_max (image im, int max)
Definition at line 865 of file image.c.
References image::h, resize_image(), and image::w.
 {
     int w = im.w;
     int h = im.h;
     if(w > h){
         h = (h * max) / w;
         w = max;
     } else {
         w = (w * max) / h;
         h = max;
     }
     if(w == im.w && h == im.h) return im;
     image resized = resize_image(im, w, h);
     return resized;
 }
resize_min()
image resize_min (image im, int min)
Definition at line 881 of file image.c.
References image::h, resize_image(), and image::w.
Referenced by label_classifier(), predict_classifier(), test_lsd(), test_tag(), try_classifier(), validate_classifier_full(), validate_classifier_multi(), and validate_classifier_single().
 {
     int w = im.w;
     int h = im.h;
     if(w < h){
         h = (h * min) / w;
         w = min;
     } else {
         w = (w * min) / h;
         h = min;
     }
     if(w == im.w && h == im.h) return im;
     image resized = resize_image(im, w, h);
     return resized;
 }
rgb_to_hsv()
void rgb_to_hsv (image im)
Definition at line 983 of file image.c.
References image::c, get_pixel(), image::h, set_pixel(), three_way_max(), three_way_min(), and image::w.
Referenced by distort_image(), exposure_image(), hue_image(), saturate_exposure_image(), and saturate_image().
 {
     assert(im.c == 3);
     int i, j;
     float r, g, b;
     float h, s, v;
     for(j = 0; j < im.h; ++j){
         for(i = 0; i < im.w; ++i){
             r = get_pixel(im, i , j, 0);
             g = get_pixel(im, i , j, 1);
             b = get_pixel(im, i , j, 2);
             float max = three_way_max(r,g,b);
             float min = three_way_min(r,g,b);
             float delta = max - min;
             v = max;
             if(max == 0){
                 s = 0;
                 h = 0;
             }else{
                 s = delta/max;
                 if(r == max){
                     h = (g - b) / delta;
                 } else if (g == max) {
                     h = 2 + (b - r) / delta;
                 } else {
                     h = 4 + (r - g) / delta;
                 }
                 if (h < 0) h += 6;
                 h = h/6.;
             }
             set_pixel(im, i, j, 0, h);
             set_pixel(im, i, j, 1, s);
             set_pixel(im, i, j, 2, v);
         }
     }
 }
rgb_to_yuv()
void rgb_to_yuv (image im)
Definition at line 959 of file image.c.
References image::c, get_pixel(), image::h, set_pixel(), and image::w.
 {
     assert(im.c == 3);
     int i, j;
     float r, g, b;
     float y, u, v;
     for(j = 0; j < im.h; ++j){
         for(i = 0; i < im.w; ++i){
             r = get_pixel(im, i , j, 0);
             g = get_pixel(im, i , j, 1);
             b = get_pixel(im, i , j, 2);
             y = .299*r + .587*g + .114*b;
             u = -.14713*r + -.28886*g + .436*b;
             v = .615*r + -.51499*g + -.10001*b;
             set_pixel(im, i, j, 0, y);
             set_pixel(im, i, j, 1, u);
             set_pixel(im, i, j, 2, v);
         }
     }
 }
rgbgr_image()
void rgbgr_image (image im)
Definition at line 411 of file image.c.
References image::c, image::data, get_pixel(), image::h, rgbgr_image(), image::w, and windows.
Referenced by rgbgr_image(), rgbgr_weights(), and show_image().
 {
     int i;
     for(i = 0; i < im.w*im.h; ++i){
         float swap = im.data[i];
         im.data[i] = im.data[i+im.w*im.h*2];
         im.data[i+im.w*im.h*2] = swap;
     }
 }
rotate_crop_image()
image rotate_crop_image (image im, float rad, float s, int w, int h, float dx, float dy, float aspect)
Definition at line 685 of file image.c.
References bilinear_interpolate(), image::c, image::h, make_image(), set_pixel(), and image::w.
Referenced by random_augment_image().
 {
     int x, y, c;
     float cx = im.w/2.;
     float cy = im.h/2.;
     image rot = make_image(w, h, im.c);
     for(c = 0; c < im.c; ++c){
         for(y = 0; y < h; ++y){
             for(x = 0; x < w; ++x){
                 float rx = cos(rad)*((x - w/2.)/s*aspect + dx/s*aspect) - sin(rad)*((y - h/2.)/s + dy/s) + cx;
                 float ry = sin(rad)*((x - w/2.)/s*aspect + dx/s*aspect) + cos(rad)*((y - h/2.)/s + dy/s) + cy;
                 float val = bilinear_interpolate(im, rx, ry, c);
                 set_pixel(rot, x, y, c, val);
             }
         }
     }
     return rot;
 }
rotate_image()
image rotate_image (image im, float rad)
Definition at line 704 of file image.c.
References bilinear_interpolate(), image::c, image::h, make_image(), set_pixel(), and image::w.
Referenced by run_nightmare().
 {
     int x, y, c;
     float cx = im.w/2.;
     float cy = im.h/2.;
     image rot = make_image(im.w, im.h, im.c);
     for(c = 0; c < im.c; ++c){
         for(y = 0; y < im.h; ++y){
             for(x = 0; x < im.w; ++x){
                 float rx = cos(rad)*(x-cx) - sin(rad)*(y-cy) + cx;
                 float ry = sin(rad)*(x-cx) + cos(rad)*(y-cy) + cy;
                 float val = bilinear_interpolate(im, rx, ry, c);
                 set_pixel(rot, x, y, c, val);
             }
         }
     }
     return rot;
 }
rotate_image_cw()
void rotate_image_cw (image im, int times)
Definition at line 241 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by mkimg(), predict_move(), and random_go_moves().
 {
     assert(im.w == im.h);
     times = (times + 400) % 4;
     int i, x, y, c;
     int n = im.w;
     for(i = 0; i < times; ++i){
         for(c = 0; c < im.c; ++c){
             for(x = 0; x < n/2; ++x){
                 for(y = 0; y < (n-1)/2 + 1; ++y){
                     float temp = im.data[y + im.w*(x + im.h*c)];
                     im.data[y + im.w*(x + im.h*c)] = im.data[n-1-x + im.w*(y + im.h*c)];
                     im.data[n-1-x + im.w*(y + im.h*c)] = im.data[n-1-y + im.w*(n-1-x + im.h*c)];
                     im.data[n-1-y + im.w*(n-1-x + im.h*c)] = im.data[x + im.w*(n-1-y + im.h*c)];
                     im.data[x + im.w*(n-1-y + im.h*c)] = temp;
                 }
             }
         }
     }
 }
saturate_exposure_image()
void saturate_exposure_image (image im, float sat, float exposure)
Definition at line 1209 of file image.c.
References constrain_image(), hsv_to_rgb(), rgb_to_hsv(), and scale_image_channel().
 {
     rgb_to_hsv(im);
     scale_image_channel(im, 1, sat);
     scale_image_channel(im, 2, exposure);
     hsv_to_rgb(im);
     constrain_image(im);
 }
saturate_image()
void saturate_image (image im, float sat)
Definition at line 1157 of file image.c.
References constrain_image(), hsv_to_rgb(), rgb_to_hsv(), and scale_image_channel().
 {
     rgb_to_hsv(im);
     scale_image_channel(im, 1, sat);
     hsv_to_rgb(im);
     constrain_image(im);
 }
save_image()
void save_image (image im, const char * name)
Definition at line 597 of file image.c.
References save_image_png().
Referenced by composite_3d(), extract_voxel(), mkimg(), run_nightmare(), show_image(), show_images(), test_coco(), test_dcgan(), test_detector(), test_lsd(), test_super(), test_voxel(), and test_yolo().
 {
 #ifdef OPENCV
     save_image_jpg(im, name);
 #else
     save_image_png(im, name);
 #endif
 }
save_image_png()
void save_image_png (image im, const char * name)
Definition at line 580 of file image.c.
References image::c, image::data, image::h, stbi_write_png(), and image::w.
Referenced by extract_cifar(), and save_image().
 {
     char buff[256];
     //sprintf(buff, "%s (%d)", name, windows);
     sprintf(buff, "%s.png", name);
     unsigned char *data = calloc(im.w*im.h*im.c, sizeof(char));
     int i,k;
     for(k = 0; k < im.c; ++k){
         for(i = 0; i < im.w*im.h; ++i){
             data[i*im.c+k] = (unsigned char) (255*im.data[i + k*im.w*im.h]);
         }
     }
     int success = stbi_write_png(buff, im.w, im.h, im.c, data, im.w*im.c);
     free(data);
     if(!success) fprintf(stderr, "Failed to write image %s\n", buff);
 }
scale_image()
void scale_image (image m, float s)
Definition at line 735 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by rescale_weights().
 {
     int i;
     for(i = 0; i < m.h*m.w*m.c; ++i) m.data[i] *= s;
 }
scale_image_channel()
void scale_image_channel (image im, int c, float v)
Definition at line 1122 of file image.c.
References get_pixel(), image::h, set_pixel(), and image::w.
Referenced by distort_image(), exposure_image(), saturate_exposure_image(), and saturate_image().
 {
     int i, j;
     for(j = 0; j < im.h; ++j){
         for(i = 0; i < im.w; ++i){
             float pix = get_pixel(im, i, j, c);
             pix = pix*v;
             set_pixel(im, i, j, c, pix);
         }
     }
 }
set_pixel()
void set_pixel (image m, int x, int y, int c, float val)
Definition at line 1397 of file image.c.
References image::c, image::data, image::h, and image::w.
Referenced by blend_image(), border_image(), composite_image(), crop_image(), draw_label(), embed_image(), ghost_image(), hsv_to_rgb(), place_image(), resize_image(), rgb_to_hsv(), rgb_to_yuv(), rotate_crop_image(), rotate_image(), scale_image_channel(), translate_image_channel(), and yuv_to_rgb().
 {
     if (x < 0 || y < 0 || c < 0 || x >= m.w || y >= m.h || c >= m.c) return;
     assert(x < m.w && y < m.h && c < m.c);
     m.data[c*m.h*m.w + y*m.w + x] = val;
 }
show_image()
void show_image (image p, const char * name)
Definition at line 459 of file image.c.
References image::c, constrain_image(), copy_image(), image::data, free_image(), get_pixel(), image::h, make_empty_image(), make_image(), rgbgr_image(), save_image(), and image::w.
Referenced by demo_art(), demo_classifier(), demo_regressor(), gun_classifier(), run_nightmare(), show_image_collapsed(), show_image_layers(), show_image_normalized(), show_images(), test_coco(), test_dcgan(), test_detector(), test_lsd(), test_resize(), test_writing(), test_yolo(), threat_classifier(), train_colorizer(), and train_dcgan().
 {
 #ifdef OPENCV
     IplImage *disp = cvCreateImage(cvSize(p.w,p.h), IPL_DEPTH_8U, p.c);
     image copy = copy_image(p);
     constrain_image(copy);
     show_image_cv(copy, name, disp);
     free_image(copy);
     cvReleaseImage(&disp);
 #else
     fprintf(stderr, "Not compiled with OpenCV, saving to %s.png instead\n", name);
     save_image(p, name);
 #endif
 }
show_image_collapsed()
void show_image_collapsed (image p, char * name)
Definition at line 619 of file image.c.
References collapse_image_layers(), free_image(), and show_image().
 {
     image c = collapse_image_layers(p, 1);
     show_image(c, name);
     free_image(c);
 }
show_image_layers()
void show_image_layers (image p, char * name)
Definition at line 607 of file image.c.
References image::c, free_image(), get_image_layer(), and show_image().
 {
     int i;
     char buff[256];
     for(i = 0; i < p.c; ++i){
         sprintf(buff, "%s - Layer %d", name, i);
         image layer = get_image_layer(p, i);
         show_image(layer, buff);
         free_image(layer);
     }
 }
show_image_normalized()
void show_image_normalized (image im, const char * name)
Definition at line 1497 of file image.c.
References copy_image(), free_image(), normalize_image(), and show_image().
 {
     image c = copy_image(im);
     normalize_image(c);
     show_image(c, name);
     free_image(c);
 }
show_images()
void show_images (image * ims, int n, char * window)
Definition at line 1505 of file image.c.
References collapse_images_vert(), free_image(), normalize_image(), save_image(), and show_image().
Referenced by visualize_convolutional_layer().
 {
     image m = collapse_images_vert(ims, n);
     /*
        int w = 448;
        int h = ((float)m.h/m.w) * 448;
        if(h > 896){
        h = 896;
        w = ((float)m.w/m.h) * 896;
        }
        image sized = resize_image(m, w, h);
      */
     normalize_image(m);
     save_image(m, window);
     show_image(m, window);
     free_image(m);
 }
test_resize()
void test_resize (char * filename)
Definition at line 1278 of file image.c.
References image::c, copy_image(), image::data, distort_image(), free_image(), grayscale_image(), image::h, load_image(), mag_array(), rand_scale(), rand_uniform(), random_augment_image(), show_image(), and image::w.
Referenced by main().
 {
     image im = load_image(filename, 0,0, 3);
     float mag = mag_array(im.data, im.w*im.h*im.c);
     printf("L2 Norm: %f\n", mag);
     image gray = grayscale_image(im);
     image c1 = copy_image(im);
     image c2 = copy_image(im);
     image c3 = copy_image(im);
     image c4 = copy_image(im);
     distort_image(c1, .1, 1.5, 1.5);
     distort_image(c2, -.1, .66666, .66666);
     distort_image(c3, .1, 1.5, .66666);
     distort_image(c4, .1, .66666, 1.5);
     show_image(im,   "Original");
     show_image(gray, "Gray");
     show_image(c1, "C1");
     show_image(c2, "C2");
     show_image(c3, "C3");
     show_image(c4, "C4");
 #ifdef OPENCV
     while(1){
         image aug = random_augment_image(im, 0, .75, 320, 448, 320);
         show_image(aug, "aug");
         free_image(aug);
         float exposure = 1.15;
         float saturation = 1.15;
         float hue = .05;
         image c = copy_image(im);
         float dexp = rand_scale(exposure);
         float dsat = rand_scale(saturation);
         float dhue = rand_uniform(-hue, hue);
         distort_image(c, dhue, dsat, dexp);
         show_image(c, "rand");
         printf("%f %f %f\n", dhue, dsat, dexp);
         free_image(c);
         cvWaitKey(0);
     }
 #endif
 }
three_way_max()
float three_way_max (float a, float b, float c)
Definition at line 926 of file image.c.
Referenced by rgb_to_hsv().
 {
     return (a > b) ? ( (a > c) ? a : c) : ( (b > c) ? b : c) ;
 }
three_way_min()
float three_way_min (float a, float b, float c)
Definition at line 931 of file image.c.
Referenced by rgb_to_hsv().
 {
     return (a < b) ? ( (a < c) ? a : c) : ( (b < c) ? b : c) ;
 }
threshold_image()
image threshold_image (image im, float thresh)
Definition at line 1095 of file image.c.
References image::c, image::data, image::h, make_image(), and image::w.
Referenced by test_writing().
 {
     int i;
     image t = make_image(im.w, im.h, im.c);
     for(i = 0; i < im.w*im.h*im.c; ++i){
         t.data[i] = im.data[i]>thresh ? 1 : 0;
     }
     return t;
 }
tile_images()
image tile_images (image a, image b, int dx)
Definition at line 58 of file image.c.
References image::c, composite_image(), copy_image(), image::data, embed_image(), fill_cpu(), image::h, make_image(), and image::w.
Referenced by get_label().
 {
     if(a.w == 0) return copy_image(b);
     image c = make_image(a.w + b.w + dx, (a.h > b.h) ? a.h : b.h, (a.c > b.c) ? a.c : b.c);
     fill_cpu(c.w*c.h*c.c, 1, c.data, 1);
     embed_image(a, c, 0, 0);
     composite_image(b, c, a.w + dx, 0);
     return c;
 }
translate_image()
void translate_image (image m, float s)
Definition at line 729 of file image.c.
References image::c, image::data, image::h, and image::w.
 {
     int i;
     for(i = 0; i < m.h*m.w*m.c; ++i) m.data[i] += s;
 }
translate_image_channel()
void translate_image_channel (image im, int c, float v)
Definition at line 1134 of file image.c.
References get_pixel(), image::h, set_pixel(), and image::w.
 {
     int i, j;
     for(j = 0; j < im.h; ++j){
         for(i = 0; i < im.w; ++i){
             float pix = get_pixel(im, i, j, c);
             pix = pix+v;
             set_pixel(im, i, j, c, pix);
         }
     }
 }
transpose_image()
void transpose_image (image im)
Definition at line 225 of file image.c.
References image::c, image::data, image::h, and image::w.
 {
     assert(im.w == im.h);
     int n, m;
     int c;
     for(c = 0; c < im.c; ++c){
         for(n = 0; n < im.w-1; ++n){
             for(m = n + 1; m < im.w; ++m){
                 float swap = im.data[m + im.w*(n + im.h*c)];
                 im.data[m + im.w*(n + im.h*c)] = im.data[n + im.w*(m + im.h*c)];
                 im.data[n + im.w*(m + im.h*c)] = swap;
             }
         }
     }
 }
yuv_to_rgb()
void yuv_to_rgb (image im)
Definition at line 936 of file image.c.
References image::c, get_pixel(), image::h, set_pixel(), and image::w.
 {
     assert(im.c == 3);
     int i, j;
     float r, g, b;
     float y, u, v;
     for(j = 0; j < im.h; ++j){
         for(i = 0; i < im.w; ++i){
             y = get_pixel(im, i , j, 0);
             u = get_pixel(im, i , j, 1);
             v = get_pixel(im, i , j, 2);
             r = y + 1.13983*v;
             g = y + -.39465*u + -.58060*v;
             b = y + 2.03211*u;
             set_pixel(im, i, j, 0, r);
             set_pixel(im, i, j, 1, g);
             set_pixel(im, i, j, 2, b);
         }
     }
 }
Variable Documentation
colors
float colors[6][3] = { {1,0,1}, {0,0,1},{0,1,1},{0,1,0},{1,1,0},{1,0,0} }
Definition at line 15 of file image.c.
Referenced by get_color().
windows
int windows = 0
Definition at line 13 of file image.c.
Referenced by rgbgr_image().