Darknet: matrix.h File Reference
matrix.h File Reference
Data Structures
struct matrix
Typedefs
typedef struct matrix matrix
Functions
matrix make_matrix (int rows, int cols)
matrix copy_matrix (matrix m)
void free_matrix (matrix m)
void print_matrix (matrix m)
matrix csv_to_matrix (char *filename)
void matrix_to_csv (matrix m)
matrix hold_out_matrix (matrix *m, int n)
float matrix_topk_accuracy (matrix truth, matrix guess, int k)
void matrix_add_matrix (matrix from, matrix to)
void scale_matrix (matrix m, float scale)
matrix resize_matrix (matrix m, int size)
float * pop_column (matrix *m, int c)
Typedef Documentation
matrix
typedef struct matrix matrix
Function Documentation
copy_matrix()
matrix copy_matrix (matrix m)
Definition at line 77 of file matrix.c.
References matrix::cols, copy_cpu(), matrix::rows, and matrix::vals.
Referenced by copy_data().
 {
     matrix c = {0};
     c.rows = m.rows;
     c.cols = m.cols;
     c.vals = calloc(c.rows, sizeof(float *));
     int i;
     for(i = 0; i < c.rows; ++i){
         c.vals[i] = calloc(c.cols, sizeof(float));
         copy_cpu(c.cols, m.vals[i], 1, c.vals[i], 1);
     }
     return c;
 }
csv_to_matrix()
matrix csv_to_matrix (char * filename)
Definition at line 133 of file matrix.c.
References matrix::cols, count_fields(), fgetl(), file_error(), parse_fields(), matrix::rows, and matrix::vals.
Referenced by eval_cifar_csv(), load_categorical_data_csv(), and train_cifar_distill().
 {
     FILE *fp = fopen(filename, "r");
     if(!fp) file_error(filename);
     matrix m;
     m.cols = -1;
     char *line;
     int n = 0;
     int size = 1024;
     m.vals = calloc(size, sizeof(float*));
     while((line = fgetl(fp))){
         if(m.cols == -1) m.cols = count_fields(line);
         if(n == size){
             size *= 2;
             m.vals = realloc(m.vals, size*sizeof(float*));
         }
         m.vals[n] = parse_fields(line, m.cols);
         free(line);
         ++n;
     }
     m.vals = realloc(m.vals, n*sizeof(float*));
     m.rows = n;
     return m;
 }
free_matrix()
void free_matrix (matrix m)
Definition at line 10 of file matrix.c.
References matrix::rows, and matrix::vals.
Referenced by eval_cifar_csv(), free_data(), network_accuracies(), network_accuracy(), network_accuracy_multi(), test_classifier(), and validate_compare().
 {
     int i;
     for(i = 0; i < m.rows; ++i) free(m.vals[i]);
     free(m.vals);
 }
hold_out_matrix()
matrix hold_out_matrix (matrix * m, int n)
Definition at line 104 of file matrix.c.
References matrix::cols, matrix::rows, and matrix::vals.
 {
     int i;
     matrix h;
     h.rows = n;
     h.cols = m->cols;
     h.vals = calloc(h.rows, sizeof(float *));
     for(i = 0; i < n; ++i){
         int index = rand()%m->rows;
         h.vals[i] = m->vals[index];
         m->vals[index] = m->vals[--(m->rows)];
     }
     return h;
 }
make_matrix()
matrix make_matrix (int rows, int cols)
Definition at line 91 of file matrix.c.
References matrix::cols, matrix::rows, and matrix::vals.
Referenced by load_all_cifar10(), load_cifar10_data(), load_data_captcha(), load_data_compare(), load_data_detection(), load_data_region(), load_data_swag(), load_go(), load_labels_paths(), load_regression_labels_paths(), load_tags_paths(), network_predict_data(), network_predict_data_multi(), and random_go_moves().
 {
     int i;
     matrix m;
     m.rows = rows;
     m.cols = cols;
     m.vals = calloc(m.rows, sizeof(float *));
     for(i = 0; i < m.rows; ++i){
         m.vals[i] = calloc(m.cols, sizeof(float));
     }
     return m;
 }
matrix_add_matrix()
void matrix_add_matrix (matrix from, matrix to)
Definition at line 66 of file matrix.c.
References matrix::cols, matrix::rows, and matrix::vals.
Referenced by test_cifar_csv(), test_cifar_csvtrain(), and train_cifar_distill().
 {
     assert(from.rows == to.rows && from.cols == to.cols);
     int i,j;
     for(i = 0; i < from.rows; ++i){
         for(j = 0; j < from.cols; ++j){
             to.vals[i][j] += from.vals[i][j];
         }
     }
 }
matrix_to_csv()
void matrix_to_csv (matrix m)
Definition at line 161 of file matrix.c.
References matrix::cols, matrix::rows, and matrix::vals.
Referenced by test_cifar_csv(), and test_cifar_csvtrain().
 {
     int i, j;
     for(i = 0; i < m.rows; ++i){
         for(j = 0; j < m.cols; ++j){
             if(j > 0) printf(",");
             printf("%.17g", m.vals[i][j]);
         }
         printf("\n");
     }
 }
matrix_topk_accuracy()
float matrix_topk_accuracy (matrix truth, matrix guess, int k)
Definition at line 17 of file matrix.c.
References matrix::cols, matrix::rows, top_k(), and matrix::vals.
Referenced by eval_cifar_csv(), network_accuracies(), network_accuracy(), network_accuracy_multi(), test_cifar_csv(), and test_cifar_csvtrain().
 {
     int *indexes = calloc(k, sizeof(int));
     int n = truth.cols;
     int i,j;
     int correct = 0;
     for(i = 0; i < truth.rows; ++i){
         top_k(guess.vals[i], n, k, indexes);
         for(j = 0; j < k; ++j){
             int class = indexes[j];
             if(truth.vals[i][class]){
                 ++correct;
                 break;
             }
         }
     }
     free(indexes);
     return (float)correct/truth.rows;
 }
pop_column()
float* pop_column (matrix * m, int c)
Definition at line 119 of file matrix.c.
References matrix::cols, matrix::rows, and matrix::vals.
Referenced by load_categorical_data_csv().
 {
     float *col = calloc(m->rows, sizeof(float));
     int i, j;
     for(i = 0; i < m->rows; ++i){
         col[i] = m->vals[i][c];
         for(j = c; j < m->cols-1; ++j){
             m->vals[i][j] = m->vals[i][j+1];
         }
     }
     --m->cols;
     return col;
 }
print_matrix()
void print_matrix (matrix m)
Definition at line 174 of file matrix.c.
References matrix::cols, matrix::rows, and matrix::vals.
 {
     int i, j;
     printf("%d X %d Matrix:\n",m.rows, m.cols);
     printf(" __");
     for(j = 0; j < 16*m.cols-1; ++j) printf(" ");
     printf("__ \n");
     printf("|  ");
     for(j = 0; j < 16*m.cols-1; ++j) printf(" ");
     printf("  |\n");
     for(i = 0; i < m.rows; ++i){
         printf("|  ");
         for(j = 0; j < m.cols; ++j){
             printf("%15.7f ", m.vals[i][j]);
         }
         printf(" |\n");
     }
     printf("|__");
     for(j = 0; j < 16*m.cols-1; ++j) printf(" ");
     printf("__|\n");
 }
resize_matrix()
matrix resize_matrix (matrix m, int size)
Definition at line 47 of file matrix.c.
References matrix::cols, matrix::rows, and matrix::vals.
Referenced by load_go().
 {
     int i;
     if (m.rows == size) return m;
     if (m.rows < size) {
         m.vals = realloc(m.vals, size*sizeof(float*));
         for (i = m.rows; i < size; ++i) {
             m.vals[i] = calloc(m.cols, sizeof(float));
         }
     } else if (m.rows > size) {
         for (i = size; i < m.rows; ++i) {
             free(m.vals[i]);
         }
         m.vals = realloc(m.vals, size*sizeof(float*));
     }
     m.rows = size;
     return m;
 }
scale_matrix()
void scale_matrix (matrix m, float scale)
Definition at line 37 of file matrix.c.
References matrix::cols, matrix::rows, and matrix::vals.
Referenced by test_cifar_csv(), test_cifar_csvtrain(), and train_cifar_distill().
 {
     int i,j;
     for(i = 0; i < m.rows; ++i){
         for(j = 0; j < m.cols; ++j){
             m.vals[i][j] *= scale;
         }
     }
 }