Darknet: box.h File Reference
box.h File Reference
Data Structures
struct box
struct dbox
Functions
box float_to_box (float *f, int stride)
float box_iou (box a, box b)
float box_rmse (box a, box b)
dbox diou (box a, box b)
void do_nms (box *boxes, float **probs, int total, int classes, float thresh)
void do_nms_sort (box *boxes, float **probs, int total, int classes, float thresh)
void do_nms_obj (box *boxes, float **probs, int total, int classes, float thresh)
box decode_box (box b, box anchor)
box encode_box (box b, box anchor)
Function Documentation
box_iou()
float box_iou (box a, box b)
Definition at line 94 of file box.c.
References box_intersection(), and box_union().
Referenced by delta_region_box(), do_nms(), do_nms_obj(), do_nms_sort(), forward_detection_layer(), forward_region_layer(), test_box(), validate_coco_recall(), validate_detector_recall(), and validate_yolo_recall().
 {
     return box_intersection(a, b)/box_union(a, b);
 }
box_rmse()
float box_rmse (box a, box b)
Definition at line 99 of file box.c.
References box::h, box::w, box::x, and box::y.
Referenced by forward_detection_layer().
 {
     return sqrt(pow(a.x-b.x, 2) +
                 pow(a.y-b.y, 2) +
                 pow(a.w-b.w, 2) +
                 pow(a.h-b.h, 2));
 }
decode_box()
box decode_box (box b, box anchor)
Definition at line 337 of file box.c.
References box::h, box::w, box::x, and box::y.
 {
     box decode;
     decode.x = b.x * anchor.w + anchor.x;
     decode.y = b.y * anchor.h + anchor.y;
     decode.w = pow(2., b.w) * anchor.w;
     decode.h = pow(2., b.h) * anchor.h;
     return decode;
 }
diou()
dbox diou (box a, box b)
Definition at line 210 of file box.c.
References box_intersection(), box_union(), dbox::dh, dintersect(), dunion(), dbox::dw, dbox::dx, dbox::dy, box::h, box::w, box::x, and box::y.
Referenced by test_box().
 {
     float u = box_union(a,b);
     float i = box_intersection(a,b);
     dbox di = dintersect(a,b);
     dbox du = dunion(a,b);
     dbox dd = {0,0,0,0};
     if(i <= 0 || 1) {
         dd.dx = b.x - a.x;
         dd.dy = b.y - a.y;
         dd.dw = b.w - a.w;
         dd.dh = b.h - a.h;
         return dd;
     }
     dd.dx = 2*pow((1-(i/u)),1)*(di.dx*u - du.dx*i)/(u*u);
     dd.dy = 2*pow((1-(i/u)),1)*(di.dy*u - du.dy*i)/(u*u);
     dd.dw = 2*pow((1-(i/u)),1)*(di.dw*u - du.dw*i)/(u*u);
     dd.dh = 2*pow((1-(i/u)),1)*(di.dh*u - du.dh*i)/(u*u);
     return dd;
 }
do_nms()
void do_nms (box * boxes, float ** probs, int total, int classes, float thresh)
Definition at line 307 of file box.c.
References box_iou().
Referenced by validate_coco_recall(), validate_detector_recall(), and validate_yolo_recall().
 {
     int i, j, k;
     for(i = 0; i < total; ++i){
         int any = 0;
         for(k = 0; k < classes; ++k) any = any || (probs[i][k] > 0);
         if(!any) {
             continue;
         }
         for(j = i+1; j < total; ++j){
             if (box_iou(boxes[i], boxes[j]) > thresh){
                 for(k = 0; k < classes; ++k){
                     if (probs[i][k] < probs[j][k]) probs[i][k] = 0;
                     else probs[j][k] = 0;
                 }
             }
         }
     }
 }
do_nms_obj()
void do_nms_obj (box * boxes, float ** probs, int total, int classes, float thresh)
Definition at line 249 of file box.c.
References box_iou(), sortable_bbox::class, sortable_bbox::index, nms_comparator(), and sortable_bbox::probs.
Referenced by test_detector().
 {
     int i, j, k;
     sortable_bbox *s = calloc(total, sizeof(sortable_bbox));
     for(i = 0; i < total; ++i){
         s[i].index = i;
         s[i].class = classes;
         s[i].probs = probs;
     }
     qsort(s, total, sizeof(sortable_bbox), nms_comparator);
     for(i = 0; i < total; ++i){
         if(probs[s[i].index][classes] == 0) continue;
         box a = boxes[s[i].index];
         for(j = i+1; j < total; ++j){
             box b = boxes[s[j].index];
             if (box_iou(a, b) > thresh){
                 for(k = 0; k < classes+1; ++k){
                     probs[s[j].index][k] = 0;
                 }
             }
         }
     }
     free(s);
 }
do_nms_sort()
void do_nms_sort (box * boxes, float ** probs, int total, int classes, float thresh)
Definition at line 277 of file box.c.
References box_iou(), sortable_bbox::class, sortable_bbox::index, nms_comparator(), and sortable_bbox::probs.
Referenced by test_coco(), test_yolo(), validate_coco(), validate_detector(), validate_detector_flip(), and validate_yolo().
 {
     int i, j, k;
     sortable_bbox *s = calloc(total, sizeof(sortable_bbox));
     for(i = 0; i < total; ++i){
         s[i].index = i;
         s[i].class = 0;
         s[i].probs = probs;
     }
     for(k = 0; k < classes; ++k){
         for(i = 0; i < total; ++i){
             s[i].class = k;
         }
         qsort(s, total, sizeof(sortable_bbox), nms_comparator);
         for(i = 0; i < total; ++i){
             if(probs[s[i].index][k] == 0) continue;
             box a = boxes[s[i].index];
             for(j = i+1; j < total; ++j){
                 box b = boxes[s[j].index];
                 if (box_iou(a, b) > thresh){
                     probs[s[j].index][k] = 0;
                 }
             }
         }
     }
     free(s);
 }
encode_box()
box encode_box (box b, box anchor)
Definition at line 327 of file box.c.
References box::h, box::w, box::x, and box::y.
 {
     box encode;
     encode.x = (b.x - anchor.x) / anchor.w;
     encode.y = (b.y - anchor.y) / anchor.h;
     encode.w = log2(b.w / anchor.w);
     encode.h = log2(b.h / anchor.h);
     return encode;
 }
float_to_box()
box float_to_box (float * f, int stride)
Definition at line 6 of file box.c.
References box::h, box::w, box::x, and box::y.
Referenced by forward_detection_layer(), and forward_region_layer().
 {
     box b;
     b.x = f[0];
     b.y = f[1*stride];
     b.w = f[2*stride];
     b.h = f[3*stride];
     return b;
 }