Darknet: network.c File Reference
network.c File Reference
#include <stdio.h>
#include <time.h>
#include <assert.h>
#include "network.h"
#include "image.h"
#include "data.h"
#include "utils.h"
#include "blas.h"
#include "crop_layer.h"
#include "connected_layer.h"
#include "gru_layer.h"
#include "rnn_layer.h"
#include "crnn_layer.h"
#include "local_layer.h"
#include "convolutional_layer.h"
#include "activation_layer.h"
#include "detection_layer.h"
#include "region_layer.h"
#include "normalization_layer.h"
#include "batchnorm_layer.h"
#include "maxpool_layer.h"
#include "reorg_layer.h"
#include "avgpool_layer.h"
#include "cost_layer.h"
#include "softmax_layer.h"
#include "dropout_layer.h"
#include "route_layer.h"
#include "shortcut_layer.h"
#include "parser.h"
Functions
load_args get_base_args (network net)
network load_network (char *cfg, char *weights, int clear)
int get_current_batch (network net)
void reset_momentum (network net)
float get_current_rate (network net)
char * get_layer_string (LAYER_TYPE a)
network make_network (int n)
void forward_network (network net)
void update_network (network net)
void calc_network_cost (network net)
int get_predicted_class_network (network net)
void backward_network (network net)
float train_network_datum (network net)
float train_network_sgd (network net, data d, int n)
float train_network (network net, data d)
void set_batch_network (network *net, int b)
int resize_network (network *net, int w, int h)
detection_layer get_network_detection_layer (network net)
image get_network_image_layer (network net, int i)
image get_network_image (network net)
void visualize_network (network net)
void top_predictions (network net, int k, int *index)
float * network_predict (network net, float *input)
matrix network_predict_data_multi (network net, data test, int n)
matrix network_predict_data (network net, data test)
void print_network (network net)
void compare_networks (network n1, network n2, data test)
float network_accuracy (network net, data d)
float * network_accuracies (network net, data d, int n)
layer get_network_output_layer (network net)
float network_accuracy_multi (network net, data d, int n)
void free_network (network net)
layer network_output_layer (network net)
int network_inputs (network net)
int network_outputs (network net)
float * network_output (network net)
Function Documentation
backward_network()
void backward_network (network net)
Definition at line 222 of file network.c.
References layer::backward, network::delta, layer::delta, network::index, network::input, network::layers, network::n, layer::output, and layer::stopbackward.
Referenced by optimize_picture(), reconstruct_picture(), and train_network_datum().
 {
     int i;
     network orig = net;
     for(i = net.n-1; i >= 0; --i){
         layer l = net.layers[i];
         if(l.stopbackward) break;
         if(i == 0){
             net = orig;
         }else{
             layer prev = net.layers[i-1];
             net.input = prev.output;
             net.delta = prev.delta;
         }
         net.index = i;
         l.backward(l, net);
     }
 }
calc_network_cost()
void calc_network_cost (network net)
Definition at line 203 of file network.c.
References network::cost, layer::cost, network::layers, and network::n.
Referenced by forward_network().
 {
     int i;
     float sum = 0;
     int count = 0;
     for(i = 0; i < net.n; ++i){
         if(net.layers[i].cost){
             sum += net.layers[i].cost[0];
             ++count;
         }
     }
     *net.cost = sum/count;
 }
compare_networks()
void compare_networks (network n1, network n2, data test)
Definition at line 507 of file network.c.
References matrix::cols, max_index(), network_predict_data(), matrix::rows, matrix::vals, and data::y.
 {
     matrix g1 = network_predict_data(n1, test);
     matrix g2 = network_predict_data(n2, test);
     int i;
     int a,b,c,d;
     a = b = c = d = 0;
     for(i = 0; i < g1.rows; ++i){
         int truth = max_index(test.y.vals[i], test.y.cols);
         int p1 = max_index(g1.vals[i], g1.cols);
         int p2 = max_index(g2.vals[i], g2.cols);
         if(p1 == truth){
             if(p2 == truth) ++d;
             else ++c;
         }else{
             if(p2 == truth) ++b;
             else ++a;
         }
     }
     printf("%5d %5d\n%5d %5d\n", a, b, c, d);
     float num = pow((abs(b - c) - 1.), 2.);
     float den = b + c;
     printf("%f\n", num/den);
 }
forward_network()
void forward_network (network net)
Definition at line 172 of file network.c.
References layer::batch, calc_network_cost(), layer::delta, fill_cpu(), layer::forward, network::index, network::input, network::layers, network::n, layer::output, layer::outputs, network::truth, and layer::truth.
Referenced by network_predict(), optimize_picture(), reconstruct_picture(), and train_network_datum().
 {
     int i;
     for(i = 0; i < net.n; ++i){
         net.index = i;
         layer l = net.layers[i];
         if(l.delta){
             fill_cpu(l.outputs * l.batch, 0, l.delta, 1);
         }
         l.forward(l, net);
         net.input = l.output;
         if(l.truth) {
             net.truth = l.output;
         }
     }
     calc_network_cost(net);
 }
free_network()
void free_network (network net)
Definition at line 567 of file network.c.
References free_layer(), network::input, network::layers, network::n, and network::truth.
Referenced by train_cifar(), train_cifar_distill(), train_classifier(), train_compare(), train_go(), train_regressor(), and train_tag().
 {
     int i;
     for(i = 0; i < net.n; ++i){
         free_layer(net.layers[i]);
     }
     free(net.layers);
     if(net.input) free(net.input);
     if(net.truth) free(net.truth);
 #ifdef GPU
     if(net.input_gpu) cuda_free(net.input_gpu);
     if(net.truth_gpu) cuda_free(net.truth_gpu);
 #endif
 }
get_base_args()
load_args get_base_args (network net)
Definition at line 33 of file network.c.
References network::angle, load_args::angle, network::aspect, load_args::aspect, network::center, load_args::center, network::exposure, load_args::exposure, load_args::h, network::h, network::hue, load_args::hue, load_args::max, network::max_crop, load_args::min, network::min_crop, network::saturation, load_args::saturation, load_args::size, load_args::w, and network::w.
Referenced by train_colorizer(), and train_dcgan().
 {
     load_args args = {0};
     args.w = net.w;
     args.h = net.h;
     args.size = net.w;
     args.min = net.min_crop;
     args.max = net.max_crop;
     args.angle = net.angle;
     args.aspect = net.aspect;
     args.exposure = net.exposure;
     args.center = net.center;
     args.saturation = net.saturation;
     args.hue = net.hue;
     return args;
 }
get_current_batch()
int get_current_batch (network net)
Definition at line 61 of file network.c.
References network::batch, network::seen, and network::subdivisions.
Referenced by get_current_rate(), train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_colorizer(), train_dcgan(), train_detector(), train_go(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), and train_yolo().
 {
     int batch_num = (*net.seen)/(net.batch*net.subdivisions);
     return batch_num;
 }
get_current_rate()
float get_current_rate (network net)
Definition at line 78 of file network.c.
References network::burn_in, CONSTANT, EXP, network::gamma, get_current_batch(), network::learning_rate, network::max_batches, network::num_steps, network::policy, POLY, network::power, rand_uniform(), RANDOM, network::scale, network::scales, SIG, STEP, network::step, STEPS, and network::steps.
Referenced by train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_colorizer(), train_dcgan(), train_detector(), train_go(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), and update_network().
 {
     int batch_num = get_current_batch(net);
     int i;
     float rate;
     if (batch_num < net.burn_in) return net.learning_rate * pow((float)batch_num / net.burn_in, net.power);
     switch (net.policy) {
         case CONSTANT:
             return net.learning_rate;
         case STEP:
             return net.learning_rate * pow(net.scale, batch_num/net.step);
         case STEPS:
             rate = net.learning_rate;
             for(i = 0; i < net.num_steps; ++i){
                 if(net.steps[i] > batch_num) return rate;
                 rate *= net.scales[i];
                 //if(net.steps[i] > batch_num - 1 && net.scales[i] > 1) reset_momentum(net);
             }
             return rate;
         case EXP:
             return net.learning_rate * pow(net.gamma, batch_num);
         case POLY:
             return net.learning_rate * pow(1 - (float)batch_num / net.max_batches, net.power);
         case RANDOM:
             return net.learning_rate * pow(rand_uniform(0,1), net.power);
         case SIG:
             return net.learning_rate * (1./(1.+exp(net.gamma*(batch_num - net.step))));
         default:
             fprintf(stderr, "Policy is weird!\n");
             return net.learning_rate;
     }
 }
get_layer_string()
char* get_layer_string (LAYER_TYPE a)
Definition at line 111 of file network.c.
References ACTIVE, AVGPOOL, BATCHNORM, CONNECTED, CONVOLUTIONAL, COST, CRNN, CROP, DECONVOLUTIONAL, DETECTION, DROPOUT, GRU, LOCAL, MAXPOOL, NORMALIZATION, REGION, REORG, RNN, ROUTE, SHORTCUT, and SOFTMAX.
 {
     switch(a){
         case CONVOLUTIONAL:
             return "convolutional";
         case ACTIVE:
             return "activation";
         case LOCAL:
             return "local";
         case DECONVOLUTIONAL:
             return "deconvolutional";
         case CONNECTED:
             return "connected";
         case RNN:
             return "rnn";
         case GRU:
             return "gru";
         case CRNN:
             return "crnn";
         case MAXPOOL:
             return "maxpool";
         case REORG:
             return "reorg";
         case AVGPOOL:
             return "avgpool";
         case SOFTMAX:
             return "softmax";
         case DETECTION:
             return "detection";
         case REGION:
             return "region";
         case DROPOUT:
             return "dropout";
         case CROP:
             return "crop";
         case COST:
             return "cost";
         case ROUTE:
             return "route";
         case SHORTCUT:
             return "shortcut";
         case NORMALIZATION:
             return "normalization";
         case BATCHNORM:
             return "batchnorm";
         default:
             break;
     }
     return "none";
 }
get_network_detection_layer()
detection_layer get_network_detection_layer (network net)
Definition at line 372 of file network.c.
References DETECTION, network::layers, network::n, and layer::type.
 {
     int i;
     for(i = 0; i < net.n; ++i){
         if(net.layers[i].type == DETECTION){
             return net.layers[i];
         }
     }
     fprintf(stderr, "Detection layer not found!!\n");
     detection_layer l = {0};
     return l;
 }
get_network_image()
image get_network_image (network net)
Definition at line 398 of file network.c.
References get_network_image_layer(), image::h, and network::n.
Referenced by run_nightmare(), test_super(), test_voxel(), test_writing(), and train_writing().
 {
     int i;
     for(i = net.n-1; i >= 0; --i){
         image m = get_network_image_layer(net, i);
         if(m.h != 0) return m;
     }
     image def = {0};
     return def;
 }
get_network_image_layer()
image get_network_image_layer (network net, int i)
Definition at line 385 of file network.c.
References float_to_image(), network::layers, layer::out_c, layer::out_h, layer::out_w, and layer::output.
Referenced by get_network_image(), test_dcgan(), and test_lsd().
 {
     layer l = net.layers[i];
 #ifdef GPU
     //cuda_pull_array(l.output_gpu, l.output, l.outputs);
 #endif
     if (l.out_w && l.out_h && l.out_c){
         return float_to_image(l.out_w, l.out_h, l.out_c, l.output);
     }
     image def = {0};
     return def;
 }
get_network_output_layer()
layer get_network_output_layer (network net)
Definition at line 550 of file network.c.
References COST, network::layers, network::n, and layer::type.
Referenced by parse_network_cfg(), reconstruct_picture(), and resize_network().
 {
     int i;
     for(i = net.n - 1; i >= 0; --i){
         if(net.layers[i].type != COST) break;
     }
     return net.layers[i];
 }
get_predicted_class_network()
int get_predicted_class_network (network net)
Definition at line 217 of file network.c.
References max_index(), network::output, and network::outputs.
 {
     return max_index(net.output, net.outputs);
 }
load_network()
network load_network (char * cfg, char * weights, int clear)
Definition at line 51 of file network.c.
References load_weights(), parse_network_cfg(), and network::seen.
Referenced by mkimg(), train_colorizer(), train_dcgan(), and train_go().
 {
     network net = parse_network_cfg(cfg);
     if(weights && weights[0] != 0){
         load_weights(&net, weights);
     }
     if(clear) *net.seen = 0;
     return net;
 }
make_network()
network make_network (int n)
Definition at line 162 of file network.c.
References network::cost, network::layers, network::n, and network::seen.
Referenced by parse_network_cfg().
 {
     network net = {0};
     net.n = n;
     net.layers = calloc(net.n, sizeof(layer));
     net.seen = calloc(1, sizeof(int));
     net.cost = calloc(1, sizeof(float));
     return net;
 }
network_accuracies()
float* network_accuracies (network net, data d, int n)
Definition at line 540 of file network.c.
References free_matrix(), matrix_topk_accuracy(), network_predict_data(), and data::y.
Referenced by test_cifar(), validate_classifier_crop(), and validate_dice().
 {
     static float acc[2];
     matrix guess = network_predict_data(net, d);
     acc[0] = matrix_topk_accuracy(d.y, guess, 1);
     acc[1] = matrix_topk_accuracy(d.y, guess, n);
     free_matrix(guess);
     return acc;
 }
network_accuracy()
float network_accuracy (network net, data d)
Definition at line 532 of file network.c.
References free_matrix(), matrix_topk_accuracy(), network_predict_data(), and data::y.
 {
     matrix guess = network_predict_data(net, d);
     float acc = matrix_topk_accuracy(d.y, guess,1);
     free_matrix(guess);
     return acc;
 }
network_accuracy_multi()
float network_accuracy_multi (network net, data d, int n)
Definition at line 559 of file network.c.
References free_matrix(), matrix_topk_accuracy(), network_predict_data_multi(), and data::y.
 {
     matrix guess = network_predict_data_multi(net, d, n);
     float acc = matrix_topk_accuracy(d.y, guess,1);
     free_matrix(guess);
     return acc;
 }
network_inputs()
int network_inputs (network net)
Definition at line 594 of file network.c.
References layer::inputs, and network::layers.
 {
     return net.layers[0].inputs;
 }
network_output()
float* network_output (network net)
Definition at line 604 of file network.c.
References network_output_layer(), and layer::output.
 {
     return network_output_layer(net).output;
 }
network_output_layer()
layer network_output_layer (network net)
Definition at line 585 of file network.c.
References COST, network::layers, network::n, and layer::type.
Referenced by network_output(), and network_outputs().
 {
     int i;
     for(i = net.n - 1; i >= 0; --i){
         if(net.layers[i].type != COST) break;
     }
     return net.layers[i];
 }
network_outputs()
int network_outputs (network net)
Definition at line 599 of file network.c.
References network_output_layer(), and layer::outputs.
 {
     return network_output_layer(net).outputs;
 }
network_predict()
float* network_predict (network net, float * input)
Definition at line 429 of file network.c.
References network::delta, forward_network(), gpu_index, network::input, network::output, network::train, and network::truth.
Referenced by bbox_comparator(), bbox_fight(), demo_art(), demo_classifier(), demo_regressor(), gun_classifier(), label_classifier(), network_predict_data(), network_predict_data_multi(), predict_classifier(), predict_move(), predict_regressor(), run_nightmare(), speed(), test_captcha(), test_char_rnn(), test_cifar_multi(), test_coco(), test_dcgan(), test_detector(), test_dice(), test_lsd(), test_super(), test_tactic_rnn(), test_tag(), test_voxel(), test_writing(), test_yolo(), threat_classifier(), try_classifier(), valid_captcha(), valid_char_rnn(), valid_tactic_rnn(), validate_classifier_10(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_yolo(), validate_yolo_recall(), and vec_char_rnn().
 {
 #ifdef GPU
     if(gpu_index >= 0)  return network_predict_gpu(net, input);
 #endif
     net.input = input;
     net.truth = 0;
     net.train = 0;
     net.delta = 0;
     forward_network(net);
     return net.output;
 }
network_predict_data()
matrix network_predict_data (network net, data test)
Definition at line 467 of file network.c.
References network::batch, matrix::cols, make_matrix(), network_predict(), network::outputs, matrix::rows, matrix::vals, and data::X.
Referenced by compare_networks(), network_accuracies(), network_accuracy(), test_cifar_csv(), test_cifar_csvtrain(), test_classifier(), and validate_compare().
 {
     int i,j,b;
     int k = net.outputs;
     matrix pred = make_matrix(test.X.rows, k);
     float *X = calloc(net.batch*test.X.cols, sizeof(float));
     for(i = 0; i < test.X.rows; i += net.batch){
         for(b = 0; b < net.batch; ++b){
             if(i+b == test.X.rows) break;
             memcpy(X+b*test.X.cols, test.X.vals[i+b], test.X.cols*sizeof(float));
         }
         float *out = network_predict(net, X);
         for(b = 0; b < net.batch; ++b){
             if(i+b == test.X.rows) break;
             for(j = 0; j < k; ++j){
                 pred.vals[i+b][j] = out[j+b*k];
             }
         }
     }
     free(X);
     return pred;
 }
network_predict_data_multi()
matrix network_predict_data_multi (network net, data test, int n)
Definition at line 442 of file network.c.
References network::batch, matrix::cols, make_matrix(), network_predict(), network::outputs, matrix::rows, matrix::vals, and data::X.
Referenced by network_accuracy_multi().
 {
     int i,j,b,m;
     int k = net.outputs;
     matrix pred = make_matrix(test.X.rows, k);
     float *X = calloc(net.batch*test.X.rows, sizeof(float));
     for(i = 0; i < test.X.rows; i += net.batch){
         for(b = 0; b < net.batch; ++b){
             if(i+b == test.X.rows) break;
             memcpy(X+b*test.X.cols, test.X.vals[i+b], test.X.cols*sizeof(float));
         }
         for(m = 0; m < n; ++m){
             float *out = network_predict(net, X);
             for(b = 0; b < net.batch; ++b){
                 if(i+b == test.X.rows) break;
                 for(j = 0; j < k; ++j){
                     pred.vals[i+b][j] += out[j+b*k]/n;
                 }
             }
         }
     }
     free(X);
     return pred;
 }
print_network()
void print_network (network net)
Definition at line 490 of file network.c.
References network::layers, mean_array(), network::n, layer::output, layer::outputs, and variance_array().
 {
     int i,j;
     for(i = 0; i < net.n; ++i){
         layer l = net.layers[i];
         float *output = l.output;
         int n = l.outputs;
         float mean = mean_array(output, n);
         float vari = variance_array(output, n);
         fprintf(stderr, "Layer %d - Mean: %f, Variance: %f\n",i,mean, vari);
         if(n > 100) n = 100;
         for(j = 0; j < n; ++j) fprintf(stderr, "%f, ", output[j]);
         if(n == 100)fprintf(stderr,".....\n");
         fprintf(stderr, "\n");
     }
 }
reset_momentum()
void reset_momentum (network net)
Definition at line 67 of file network.c.
References network::decay, network::learning_rate, and network::momentum.
 {
     if (net.momentum == 0) return;
     net.learning_rate = 0;
     net.momentum = 0;
     net.decay = 0;
     #ifdef GPU
         //if(net.gpu_index >= 0) update_network_gpu(net);
     #endif
 }
resize_network()
int resize_network (network * net, int w, int h)
Definition at line 299 of file network.c.
References AVGPOOL, network::batch, CONVOLUTIONAL, COST, CROP, error(), get_network_output_layer(), gpu_index, network::gpu_index, network::h, network::input, network::inputs, layer::inputs, network::layers, MAXPOOL, network::n, NORMALIZATION, layer::out_h, layer::out_w, network::output, layer::output, network::outputs, layer::outputs, REGION, REORG, resize_avgpool_layer(), resize_convolutional_layer(), resize_cost_layer(), resize_crop_layer(), resize_maxpool_layer(), resize_normalization_layer(), resize_region_layer(), resize_reorg_layer(), resize_route_layer(), ROUTE, network::truth, network::truths, layer::truths, layer::type, network::w, network::workspace, and layer::workspace_size.
Referenced by optimize_picture(), predict_classifier(), test_super(), test_tag(), test_voxel(), test_writing(), train_detector(), validate_classifier_full(), and validate_classifier_multi().
 {
 #ifdef GPU
     cuda_set_device(net->gpu_index);
     cuda_free(net->workspace);
 #endif
     int i;
     //if(w == net->w && h == net->h) return 0;
     net->w = w;
     net->h = h;
     int inputs = 0;
     size_t workspace_size = 0;
     //fprintf(stderr, "Resizing to %d x %d...\n", w, h);
     //fflush(stderr);
     for (i = 0; i < net->n; ++i){
         layer l = net->layers[i];
         if(l.type == CONVOLUTIONAL){
             resize_convolutional_layer(&l, w, h);
         }else if(l.type == CROP){
             resize_crop_layer(&l, w, h);
         }else if(l.type == MAXPOOL){
             resize_maxpool_layer(&l, w, h);
         }else if(l.type == REGION){
             resize_region_layer(&l, w, h);
         }else if(l.type == ROUTE){
             resize_route_layer(&l, net);
         }else if(l.type == REORG){
             resize_reorg_layer(&l, w, h);
         }else if(l.type == AVGPOOL){
             resize_avgpool_layer(&l, w, h);
         }else if(l.type == NORMALIZATION){
             resize_normalization_layer(&l, w, h);
         }else if(l.type == COST){
             resize_cost_layer(&l, inputs);
         }else{
             error("Cannot resize this type of layer");
         }
         if(l.workspace_size > workspace_size) workspace_size = l.workspace_size;
         inputs = l.outputs;
         net->layers[i] = l;
         w = l.out_w;
         h = l.out_h;
         if(l.type == AVGPOOL) break;
     }
     layer out = get_network_output_layer(*net);
     net->inputs = net->layers[0].inputs;
     net->outputs = out.outputs;
     net->truths = out.outputs;
     if(net->layers[net->n-1].truths) net->truths = net->layers[net->n-1].truths;
     net->output = out.output;
     free(net->input);
     free(net->truth);
     net->input = calloc(net->inputs*net->batch, sizeof(float));
     net->truth = calloc(net->truths*net->batch, sizeof(float));
 #ifdef GPU
     if(gpu_index >= 0){
         cuda_free(net->input_gpu);
         cuda_free(net->truth_gpu);
         net->input_gpu = cuda_make_array(net->input, net->inputs*net->batch);
         net->truth_gpu = cuda_make_array(net->truth, net->truths*net->batch);
         net->workspace = cuda_make_array(0, (workspace_size-1)/sizeof(float)+1);
     }else {
         free(net->workspace);
         net->workspace = calloc(1, workspace_size);
     }
 #else
     free(net->workspace);
     net->workspace = calloc(1, workspace_size);
 #endif
     //fprintf(stderr, " Done!\n");
     return 0;
 }
set_batch_network()
void set_batch_network (network * net, int b)
Definition at line 285 of file network.c.
References network::batch, layer::batch, CONVOLUTIONAL, network::layers, network::n, and layer::type.
Referenced by BattleRoyaleWithCheese(), demo_art(), demo_classifier(), demo_regressor(), engine_go(), gun_classifier(), label_classifier(), predict_classifier(), predict_regressor(), run_nightmare(), self_go(), SortMaster3000(), speed(), test_captcha(), test_cifar_multi(), test_coco(), test_dcgan(), test_detector(), test_dice(), test_go(), test_lsd(), test_super(), test_tag(), test_voxel(), test_writing(), test_yolo(), threat_classifier(), try_classifier(), valid_captcha(), valid_go(), validate_classifier_10(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_yolo(), and validate_yolo_recall().
 {
     net->batch = b;
     int i;
     for(i = 0; i < net->n; ++i){
         net->layers[i].batch = b;
 #ifdef CUDNN
         if(net->layers[i].type == CONVOLUTIONAL){
             cudnn_convolutional_setup(net->layers + i);
         }
 #endif
     }
 }
top_predictions()
void top_predictions (network net, int k, int * index)
Definition at line 423 of file network.c.
References network::output, network::outputs, and top_k().
Referenced by demo_classifier(), gun_classifier(), test_captcha(), test_dice(), test_tag(), threat_classifier(), and try_classifier().
 {
     top_k(net.output, net.outputs, k, index);
 }
train_network()
float train_network (network net, data d)
Definition at line 269 of file network.c.
References network::batch, get_next_batch(), network::input, matrix::rows, train_network_datum(), network::truth, and data::X.
Referenced by train_captcha(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_go(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), and train_yolo().
 {
     assert(d.X.rows % net.batch == 0);
     int batch = net.batch;
     int n = d.X.rows / batch;
     int i;
     float sum = 0;
     for(i = 0; i < n; ++i){
         get_next_batch(d, batch, i*batch, net.input, net.truth);
         float err = train_network_datum(net);
         sum += err;
     }
     return (float)sum/(n*batch);
 }
train_network_datum()
float train_network_datum (network net)
Definition at line 241 of file network.c.
References backward_network(), network::batch, network::cost, error(), forward_network(), gpu_index, network::seen, network::subdivisions, network::train, and update_network().
Referenced by train_char_rnn(), train_network(), and train_network_sgd().
 {
 #ifdef GPU
     if(gpu_index >= 0) return train_network_datum_gpu(net);
 #endif
     *net.seen += net.batch;
     net.train = 1;
     forward_network(net);
     backward_network(net);
     float error = *net.cost;
     if(((*net.seen)/net.batch)%net.subdivisions == 0) update_network(net);
     return error;
 }
train_network_sgd()
float train_network_sgd (network net, data d, int n)
Definition at line 255 of file network.c.
References network::batch, get_random_batch(), network::input, train_network_datum(), and network::truth.
Referenced by train_cifar(), and train_cifar_distill().
 {
     int batch = net.batch;
     int i;
     float sum = 0;
     for(i = 0; i < n; ++i){
         get_random_batch(d, batch, net.input, net.truth);
         float err = train_network_datum(net);
         sum += err;
     }
     return (float)sum/(n*batch);
 }
update_network()
void update_network (network net)
Definition at line 190 of file network.c.
References network::batch, network::decay, get_current_rate(), network::layers, layer::learning_rate_scale, network::momentum, network::n, network::subdivisions, and layer::update.
Referenced by train_network_datum().
 {
     int i;
     int update_batch = net.batch*net.subdivisions;
     float rate = get_current_rate(net);
     for(i = 0; i < net.n; ++i){
         layer l = net.layers[i];
         if(l.update){
             l.update(l, update_batch, rate*l.learning_rate_scale, net.momentum, net.decay);
         }
     }
 }
visualize_network()
void visualize_network (network net)
Definition at line 409 of file network.c.
References CONVOLUTIONAL, network::layers, network::n, layer::type, and visualize_convolutional_layer().
Referenced by visualize().
 {
     image *prev = 0;
     int i;
     char buff[256];
     for(i = 0; i < net.n; ++i){
         sprintf(buff, "Layer %d", i);
         layer l = net.layers[i];
         if(l.type == CONVOLUTIONAL){
             prev = visualize_convolutional_layer(l, buff, prev);
         }
     }
 }