Darknet: tag.c File Reference
tag.c File Reference
#include "network.h"
#include "utils.h"
#include "parser.h"
Functions
void train_tag (char *cfgfile, char *weightfile, int clear)
void test_tag (char *cfgfile, char *weightfile, char *filename)
void run_tag (int argc, char **argv)
Function Documentation
run_tag()
void run_tag (int argc, char ** argv)
Definition at line 135 of file tag.c.
References find_arg(), test_tag(), and train_tag().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     int clear = find_arg(argc, argv, "-clear");
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5] : 0;
     if(0==strcmp(argv[2], "train")) train_tag(cfg, weights, clear);
     else if(0==strcmp(argv[2], "test")) test_tag(cfg, weights, filename);
 }
test_tag()
void test_tag (char * cfgfile, char * weightfile, char * filename)
Definition at line 89 of file tag.c.
References image::data, free_image(), get_labels(), image::h, load_image_color(), load_weights(), network_predict(), parse_network_cfg(), resize_min(), resize_network(), sec(), set_batch_network(), top_predictions(), image::w, and network::w.
Referenced by run_tag().
 {
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     int i = 0;
     char **names = get_labels("data/tags.txt");
     clock_t time;
     int indexes[10];
     char buff[256];
     char *input = buff;
     int size = net.w;
     while(1){
         if(filename){
             strncpy(input, filename, 256);
         }else{
             printf("Enter Image Path: ");
             fflush(stdout);
             input = fgets(input, 256, stdin);
             if(!input) return;
             strtok(input, "\n");
         }
         image im = load_image_color(input, 0, 0);
         image r = resize_min(im, size);
         resize_network(&net, r.w, r.h);
         printf("%d %d\n", r.w, r.h);
         float *X = r.data;
         time=clock();
         float *predictions = network_predict(net, X);
         top_predictions(net, 10, indexes);
         printf("%s: Predicted in %f seconds.\n", input, sec(clock()-time));
         for(i = 0; i < 10; ++i){
             int index = indexes[i];
             printf("%.1f%%: %s\n", predictions[index]*100, names[index]);
         }
         if(r.data != im.data) free_image(r);
         free_image(im);
         if (filename) break;
     }
 }
train_tag()
void train_tag (char * cfgfile, char * weightfile, int clear)
Definition at line 5 of file tag.c.
References network::angle, load_args::angle, basecfg(), load_args::classes, load_args::d, network::decay, network::exposure, load_args::exposure, free_data(), free_list(), free_network(), free_ptrs(), get_current_batch(), get_current_rate(), get_paths(), load_args::h, network::h, network::hue, load_args::hue, network::learning_rate, list_to_array(), load_data_in_thread(), load_thread(), load_weights(), load_args::m, load_args::max, network::max_batches, network::max_crop, load_args::min, network::momentum, load_args::n, network::outputs, parse_network_cfg(), load_args::paths, network::saturation, load_args::saturation, save_weights(), sec(), network::seen, list::size, load_args::size, TAG_DATA, train_network(), load_args::type, load_args::w, and network::w.
Referenced by run_tag().
 {
     srand(time(0));
     float avg_loss = -1;
     char *base = basecfg(cfgfile);
     char *backup_directory = "/home/pjreddie/backup/";
     printf("%s\n", base);
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     if(clear) *net.seen = 0;
     printf("Learning Rate: %g, Momentum: %g, Decay: %g\n", net.learning_rate, net.momentum, net.decay);
     int imgs = 1024;
     list *plist = get_paths("/home/pjreddie/tag/train.list");
     char **paths = (char **)list_to_array(plist);
     printf("%d\n", plist->size);
     int N = plist->size;
     clock_t time;
     pthread_t load_thread;
     data train;
     data buffer;
     load_args args = {0};
     args.w = net.w;
     args.h = net.h;
     args.min = net.w;
     args.max = net.max_crop;
     args.size = net.w;
     args.paths = paths;
     args.classes = net.outputs;
     args.n = imgs;
     args.m = N;
     args.d = &buffer;
     args.type = TAG_DATA;
     args.angle = net.angle;
     args.exposure = net.exposure;
     args.saturation = net.saturation;
     args.hue = net.hue;
     fprintf(stderr, "%d classes\n", net.outputs);
     load_thread = load_data_in_thread(args);
     int epoch = (*net.seen)/N;
     while(get_current_batch(net) < net.max_batches || net.max_batches == 0){
         time=clock();
         pthread_join(load_thread, 0);
         train = buffer;
         load_thread = load_data_in_thread(args);
         printf("Loaded: %lf seconds\n", sec(clock()-time));
         time=clock();
         float loss = train_network(net, train);
         if(avg_loss == -1) avg_loss = loss;
         avg_loss = avg_loss*.9 + loss*.1;
         printf("%d, %.3f: %f, %f avg, %f rate, %lf seconds, %d images\n", get_current_batch(net), (float)(*net.seen)/N, loss, avg_loss, get_current_rate(net), sec(clock()-time), *net.seen);
         free_data(train);
         if(*net.seen/N > epoch){
             epoch = *net.seen/N;
             char buff[256];
             sprintf(buff, "%s/%s_%d.weights",backup_directory,base, epoch);
             save_weights(net, buff);
         }
         if(get_current_batch(net)%100 == 0){
             char buff[256];
             sprintf(buff, "%s/%s.backup",backup_directory,base);
             save_weights(net, buff);
         }
     }
     char buff[256];
     sprintf(buff, "%s/%s.weights", backup_directory, base);
     save_weights(net, buff);
     pthread_join(load_thread, 0);
     free_data(buffer);
     free_network(net);
     free_ptrs((void**)paths, plist->size);
     free_list(plist);
     free(base);
 }