Darknet: gemm.h File Reference
gemm.h File Reference
Functions
void gemm_bin (int M, int N, int K, float ALPHA, char *A, int lda, float *B, int ldb, float *C, int ldc)
void gemm (int TA, int TB, int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float BETA, float *C, int ldc)
void gemm_cpu (int TA, int TB, int M, int N, int K, float ALPHA, float *A, int lda, float *B, int ldb, float BETA, float *C, int ldc)
Function Documentation
gemm()
void gemm (int TA, int TB, int M, int N, int K, float ALPHA, float * A, int lda, float * B, int ldb, float BETA, float * C, int ldc)
Definition at line 65 of file gemm.c.
References gemm_cpu().
Referenced by backward_connected_layer(), backward_convolutional_layer(), backward_local_layer(), forward_connected_layer(), forward_convolutional_layer(), and forward_local_layer().
 {
     gemm_cpu( TA,  TB,  M, N, K, ALPHA,A,lda, B, ldb,BETA,C,ldc);
 }
gemm_bin()
void gemm_bin (int M, int N, int K, float ALPHA, char * A, int lda, float * B, int ldb, float * C, int ldc)
Definition at line 8 of file gemm.c.
 {
     int i,j,k;
     for(i = 0; i < M; ++i){
         for(k = 0; k < K; ++k){
             char A_PART = A[i*lda+k];
             if(A_PART){
                 for(j = 0; j < N; ++j){
                     C[i*ldc+j] += B[k*ldb+j];
                 }
             } else {
                 for(j = 0; j < N; ++j){
                     C[i*ldc+j] -= B[k*ldb+j];
                 }
             }
         }
     }
 }
gemm_cpu()
void gemm_cpu (int TA, int TB, int M, int N, int K, float ALPHA, float * A, int lda, float * B, int ldb, float BETA, float * C, int ldc)
Definition at line 141 of file gemm.c.
References gemm_cpu(), gemm_nn(), gemm_nt(), gemm_tn(), gemm_tt(), random_matrix(), sec(), and test_gpu_blas().
Referenced by backward_deconvolutional_layer(), forward_deconvolutional_layer(), gemm(), gemm_cpu(), and time_random_matrix().
 {
     //printf("cpu: %d %d %d %d %d %f %d %d %f %d\n",TA, TB, M, N, K, ALPHA, lda, ldb, BETA, ldc);
     int i, j;
     for(i = 0; i < M; ++i){
         for(j = 0; j < N; ++j){
             C[i*ldc + j] *= BETA;
         }
     }
     if(!TA && !TB)
         gemm_nn(M, N, K, ALPHA,A,lda, B, ldb,C,ldc);
     else if(TA && !TB)
         gemm_tn(M, N, K, ALPHA,A,lda, B, ldb,C,ldc);
     else if(!TA && TB)
         gemm_nt(M, N, K, ALPHA,A,lda, B, ldb,C,ldc);
     else
         gemm_tt(M, N, K, ALPHA,A,lda, B, ldb,C,ldc);
 }