Darknet: activation_layer.c File Reference
activation_layer.c File Reference
#include "activation_layer.h"
#include "utils.h"
#include "cuda.h"
#include "blas.h"
#include "gemm.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
layer make_activation_layer (int batch, int inputs, ACTIVATION activation)
void forward_activation_layer (layer l, network net)
void backward_activation_layer (layer l, network net)
Function Documentation
backward_activation_layer()
void backward_activation_layer (layer l, network net)
Definition at line 44 of file activation_layer.c.
References layer::activation, layer::batch, copy_cpu(), network::delta, layer::delta, gradient_array(), layer::output, and layer::outputs.
Referenced by make_activation_layer().
 {
     gradient_array(l.output, l.outputs*l.batch, l.activation, l.delta);
     copy_cpu(l.outputs*l.batch, l.delta, 1, net.delta, 1);
 }
forward_activation_layer()
void forward_activation_layer (layer l, network net)
Definition at line 38 of file activation_layer.c.
References activate_array(), layer::activation, layer::batch, copy_cpu(), network::input, layer::output, and layer::outputs.
Referenced by make_activation_layer().
 {
     copy_cpu(l.outputs*l.batch, net.input, 1, l.output, 1);
     activate_array(l.output, l.outputs*l.batch, l.activation);
 }
make_activation_layer()
layer make_activation_layer (int batch, int inputs, ACTIVATION activation)
Definition at line 12 of file activation_layer.c.
References layer::activation, ACTIVE, layer::backward, backward_activation_layer(), layer::backward_gpu, layer::batch, layer::delta, layer::forward, forward_activation_layer(), layer::forward_gpu, layer::inputs, layer::output, layer::outputs, and layer::type.
Referenced by parse_activation().
 {
     layer l = {0};
     l.type = ACTIVE;
     l.inputs = inputs;
     l.outputs = inputs;
     l.batch=batch;
     l.output = calloc(batch*inputs, sizeof(float*));
     l.delta = calloc(batch*inputs, sizeof(float*));
     l.forward = forward_activation_layer;
     l.backward = backward_activation_layer;
 #ifdef GPU
     l.forward_gpu = forward_activation_layer_gpu;
     l.backward_gpu = backward_activation_layer_gpu;
     l.output_gpu = cuda_make_array(l.output, inputs*batch);
     l.delta_gpu = cuda_make_array(l.delta, inputs*batch);
 #endif
     l.activation = activation;
     fprintf(stderr, "Activation Layer: %d inputs\n", inputs);
     return l;
 }