Darknet: activations.c File Reference
activations.c File Reference
#include "activations.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
char * get_activation_string (ACTIVATION a)
ACTIVATION get_activation (char *s)
float activate (float x, ACTIVATION a)
void activate_array (float *x, const int n, const ACTIVATION a)
float gradient (float x, ACTIVATION a)
void gradient_array (const float *x, const int n, const ACTIVATION a, float *delta)
Function Documentation
activate()
float activate (float x, ACTIVATION a)
Definition at line 62 of file activations.c.
References ELU, elu_activate(), HARDTAN, hardtan_activate(), LEAKY, leaky_activate(), LHTAN, lhtan_activate(), LINEAR, linear_activate(), LOGGY, loggy_activate(), LOGISTIC, logistic_activate(), PLSE, plse_activate(), RAMP, ramp_activate(), RELIE, relie_activate(), RELU, relu_activate(), STAIR, stair_activate(), TANH, and tanh_activate().
Referenced by activate_array().
 {
     switch(a){
         case LINEAR:
             return linear_activate(x);
         case LOGISTIC:
             return logistic_activate(x);
         case LOGGY:
             return loggy_activate(x);
         case RELU:
             return relu_activate(x);
         case ELU:
             return elu_activate(x);
         case RELIE:
             return relie_activate(x);
         case RAMP:
             return ramp_activate(x);
         case LEAKY:
             return leaky_activate(x);
         case TANH:
             return tanh_activate(x);
         case PLSE:
             return plse_activate(x);
         case STAIR:
             return stair_activate(x);
         case HARDTAN:
             return hardtan_activate(x);
         case LHTAN:
             return lhtan_activate(x);
     }
     return 0;
 }
activate_array()
void activate_array (float * x, const int n, const ACTIVATION a)
Definition at line 95 of file activations.c.
References activate().
Referenced by forward_activation_layer(), forward_connected_layer(), forward_convolutional_layer(), forward_deconvolutional_layer(), forward_gru_layer(), forward_local_layer(), forward_region_layer(), and forward_shortcut_layer().
 {
     int i;
     for(i = 0; i < n; ++i){
         x[i] = activate(x[i], a);
     }
 }
get_activation()
ACTIVATION get_activation (char * s)
Definition at line 43 of file activations.c.
References ELU, HARDTAN, LEAKY, LHTAN, LINEAR, LOGGY, LOGISTIC, PLSE, RAMP, RELIE, RELU, STAIR, and TANH.
Referenced by parse_activation(), parse_connected(), parse_convolutional(), parse_crnn(), parse_deconvolutional(), parse_local(), parse_rnn(), and parse_shortcut().
 {
     if (strcmp(s, "logistic")==0) return LOGISTIC;
     if (strcmp(s, "loggy")==0) return LOGGY;
     if (strcmp(s, "relu")==0) return RELU;
     if (strcmp(s, "elu")==0) return ELU;
     if (strcmp(s, "relie")==0) return RELIE;
     if (strcmp(s, "plse")==0) return PLSE;
     if (strcmp(s, "hardtan")==0) return HARDTAN;
     if (strcmp(s, "lhtan")==0) return LHTAN;
     if (strcmp(s, "linear")==0) return LINEAR;
     if (strcmp(s, "ramp")==0) return RAMP;
     if (strcmp(s, "leaky")==0) return LEAKY;
     if (strcmp(s, "tanh")==0) return TANH;
     if (strcmp(s, "stair")==0) return STAIR;
     fprintf(stderr, "Couldn't find activation function %s, going with ReLU\n", s);
     return RELU;
 }
get_activation_string()
char* get_activation_string (ACTIVATION a)
Definition at line 8 of file activations.c.
References ELU, HARDTAN, LEAKY, LHTAN, LINEAR, LOGGY, LOGISTIC, PLSE, RAMP, RELIE, RELU, STAIR, and TANH.
 {
     switch(a){
         case LOGISTIC:
             return "logistic";
         case LOGGY:
             return "loggy";
         case RELU:
             return "relu";
         case ELU:
             return "elu";
         case RELIE:
             return "relie";
         case RAMP:
             return "ramp";
         case LINEAR:
             return "linear";
         case TANH:
             return "tanh";
         case PLSE:
             return "plse";
         case LEAKY:
             return "leaky";
         case STAIR:
             return "stair";
         case HARDTAN:
             return "hardtan";
         case LHTAN:
             return "lhtan";
         default:
             break;
     }
     return "relu";
 }
gradient()
float gradient (float x, ACTIVATION a)
Definition at line 103 of file activations.c.
References ELU, elu_gradient(), HARDTAN, hardtan_gradient(), LEAKY, leaky_gradient(), LHTAN, lhtan_gradient(), LINEAR, linear_gradient(), LOGGY, loggy_gradient(), LOGISTIC, logistic_gradient(), PLSE, plse_gradient(), RAMP, ramp_gradient(), RELIE, relie_gradient(), RELU, relu_gradient(), STAIR, stair_gradient(), TANH, and tanh_gradient().
Referenced by gradient_array().
 {
     switch(a){
         case LINEAR:
             return linear_gradient(x);
         case LOGISTIC:
             return logistic_gradient(x);
         case LOGGY:
             return loggy_gradient(x);
         case RELU:
             return relu_gradient(x);
         case ELU:
             return elu_gradient(x);
         case RELIE:
             return relie_gradient(x);
         case RAMP:
             return ramp_gradient(x);
         case LEAKY:
             return leaky_gradient(x);
         case TANH:
             return tanh_gradient(x);
         case PLSE:
             return plse_gradient(x);
         case STAIR:
             return stair_gradient(x);
         case HARDTAN:
             return hardtan_gradient(x);
         case LHTAN:
             return lhtan_gradient(x);
     }
     return 0;
 }
gradient_array()
void gradient_array (const float * x, const int n, const ACTIVATION a, float * delta)
Definition at line 136 of file activations.c.
References gradient().
Referenced by backward_activation_layer(), backward_connected_layer(), backward_convolutional_layer(), backward_deconvolutional_layer(), backward_local_layer(), and backward_shortcut_layer().
 {
     int i;
     for(i = 0; i < n; ++i){
         delta[i] *= gradient(x[i], a);
     }
 }