Darknet: data.c File Reference
data.c File Reference
#include "data.h"
#include "utils.h"
#include "image.h"
#include "cuda.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define NUMCHARS 37
Functions
list * get_paths (char *filename)
char ** get_random_paths (char **paths, int n, int m)
char ** find_replace_paths (char **paths, int n, char *find, char *replace)
matrix load_image_paths_gray (char **paths, int n, int w, int h)
matrix load_image_paths (char **paths, int n, int w, int h)
matrix load_image_augment_paths (char **paths, int n, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure, int center)
box_label * read_boxes (char *filename, int *n)
void randomize_boxes (box_label *b, int n)
void correct_boxes (box_label *boxes, int n, float dx, float dy, float sx, float sy, int flip)
void fill_truth_swag (char *path, float *truth, int classes, int flip, float dx, float dy, float sx, float sy)
void fill_truth_region (char *path, float *truth, int classes, int num_boxes, int flip, float dx, float dy, float sx, float sy)
void fill_truth_detection (char *path, int num_boxes, float *truth, int classes, int flip, float dx, float dy, float sx, float sy)
void print_letters (float *pred, int n)
void fill_truth_captcha (char *path, int n, float *truth)
data load_data_captcha (char **paths, int n, int m, int k, int w, int h)
data load_data_captcha_encode (char **paths, int n, int m, int w, int h)
void fill_truth (char *path, char **labels, int k, float *truth)
void fill_hierarchy (float *truth, int k, tree *hierarchy)
matrix load_regression_labels_paths (char **paths, int n)
matrix load_labels_paths (char **paths, int n, char **labels, int k, tree *hierarchy)
matrix load_tags_paths (char **paths, int n, int k)
char ** get_labels (char *filename)
void free_data (data d)
data load_data_region (int n, char **paths, int m, int w, int h, int size, int classes, float jitter, float hue, float saturation, float exposure)
data load_data_compare (int n, char **paths, int m, int classes, int w, int h)
data load_data_swag (char **paths, int n, int classes, float jitter)
data load_data_detection (int n, char **paths, int m, int w, int h, int boxes, int classes, float jitter, float hue, float saturation, float exposure)
void * load_thread (void *ptr)
pthread_t load_data_in_thread (load_args args)
void * load_threads (void *ptr)
pthread_t load_data (load_args args)
data load_data_writing (char **paths, int n, int m, int w, int h, int out_w, int out_h)
data load_data_old (char **paths, int n, int m, char **labels, int k, int w, int h)
data load_data_super (char **paths, int n, int m, int w, int h, int scale)
data load_data_regression (char **paths, int n, int m, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure)
data load_data_augment (char **paths, int n, int m, char **labels, int k, tree *hierarchy, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure, int center)
data load_data_tag (char **paths, int n, int m, int k, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure)
matrix concat_matrix (matrix m1, matrix m2)
data concat_data (data d1, data d2)
data concat_datas (data *d, int n)
data load_categorical_data_csv (char *filename, int target, int k)
data load_cifar10_data (char *filename)
void get_random_batch (data d, int n, float *X, float *y)
void get_next_batch (data d, int n, int offset, float *X, float *y)
void smooth_data (data d)
data load_all_cifar10 ()
data load_go (char *filename)
void randomize_data (data d)
void scale_data_rows (data d, float s)
void translate_data_rows (data d, float s)
data copy_data (data d)
void normalize_data_rows (data d)
data get_data_part (data d, int part, int total)
data get_random_data (data d, int num)
data * split_data (data d, int part, int total)
Variables
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
NUMCHARS
#define NUMCHARS 37
Definition at line 336 of file data.c.
Referenced by fill_truth_captcha(), load_data_captcha(), and print_letters().
Function Documentation
concat_data()
data concat_data (data d1, data d2)
Definition at line 944 of file data.c.
References concat_matrix(), load_args::d, data::shallow, data::X, and data::y.
Referenced by concat_datas(), train_colorizer(), and train_dcgan().
 {
     data d = {0};
     d.shallow = 1;
     d.X = concat_matrix(d1.X, d2.X);
     d.y = concat_matrix(d1.y, d2.y);
     return d;
 }
concat_datas()
data concat_datas (data * d, int n)
Definition at line 953 of file data.c.
References concat_data(), free_data(), and load_args::n.
Referenced by load_threads().
 {
     int i;
     data out = {0};
     for(i = 0; i < n; ++i){
         data new = concat_data(d[i], out);
         free_data(out);
         out = new;
     }
     return out;
 }
concat_matrix()
matrix concat_matrix (matrix m1, matrix m2)
Definition at line 928 of file data.c.
References matrix::cols, load_args::m, matrix::rows, and matrix::vals.
Referenced by concat_data().
 {
     int i, count = 0;
     matrix m;
     m.cols = m1.cols;
     m.rows = m1.rows+m2.rows;
     m.vals = calloc(m1.rows + m2.rows, sizeof(float*));
     for(i = 0; i < m1.rows; ++i){
         m.vals[count++] = m1.vals[i];
     }
     for(i = 0; i < m2.rows; ++i){
         m.vals[count++] = m2.vals[i];
     }
     return m;
 }
copy_data()
data copy_data (data d)
Definition at line 1152 of file data.c.
References data::boxes, copy_matrix(), data::h, data::num_boxes, data::shallow, data::w, data::X, and data::y.
Referenced by train_colorizer(), and train_dcgan().
 {
     data c = {0};
     c.w = d.w;
     c.h = d.h;
     c.shallow = 0;
     c.num_boxes = d.num_boxes;
     c.boxes = d.boxes;
     c.X = copy_matrix(d.X);
     c.y = copy_matrix(d.y);
     return c;
 }
correct_boxes()
void correct_boxes (box_label * boxes, int n, float dx, float dy, float sx, float sy, int flip)
Definition at line 175 of file data.c.
References box_label::bottom, constrain(), box_label::h, box_label::left, box_label::right, box_label::top, box_label::w, box_label::x, and box_label::y.
Referenced by fill_truth_detection(), fill_truth_region(), and fill_truth_swag().
 {
     int i;
     for(i = 0; i < n; ++i){
         if(boxes[i].x == 0 && boxes[i].y == 0) {
             boxes[i].x = 999999;
             boxes[i].y = 999999;
             boxes[i].w = 999999;
             boxes[i].h = 999999;
             continue;
         }
         boxes[i].left   = boxes[i].left  * sx - dx;
         boxes[i].right  = boxes[i].right * sx - dx;
         boxes[i].top    = boxes[i].top   * sy - dy;
         boxes[i].bottom = boxes[i].bottom* sy - dy;
         if(flip){
             float swap = boxes[i].left;
             boxes[i].left = 1. - boxes[i].right;
             boxes[i].right = 1. - swap;
         }
         boxes[i].left =  constrain(0, 1, boxes[i].left);
         boxes[i].right = constrain(0, 1, boxes[i].right);
         boxes[i].top =   constrain(0, 1, boxes[i].top);
         boxes[i].bottom =   constrain(0, 1, boxes[i].bottom);
         boxes[i].x = (boxes[i].left+boxes[i].right)/2;
         boxes[i].y = (boxes[i].top+boxes[i].bottom)/2;
         boxes[i].w = (boxes[i].right - boxes[i].left);
         boxes[i].h = (boxes[i].bottom - boxes[i].top);
         boxes[i].w = constrain(0, 1, boxes[i].w);
         boxes[i].h = constrain(0, 1, boxes[i].h);
     }
 }
fill_hierarchy()
void fill_hierarchy (float * truth, int k, tree * hierarchy)
Definition at line 404 of file data.c.
References tree::group_size, tree::groups, tree::parent, and SECRET_NUM.
Referenced by load_labels_paths().
 {
     int j;
     for(j = 0; j < k; ++j){
         if(truth[j]){
             int parent = hierarchy->parent[j];
             while(parent >= 0){
                 truth[parent] = 1;
                 parent = hierarchy->parent[parent];
             }
         }
     }
     int i;
     int count = 0;
     for(j = 0; j < hierarchy->groups; ++j){
         //printf("%d\n", count);
         int mask = 1;
         for(i = 0; i < hierarchy->group_size[j]; ++i){
             if(truth[count + i]){
                 mask = 0;
                 break;
             }
         }
         if (mask) {
             for(i = 0; i < hierarchy->group_size[j]; ++i){
                 truth[count + i] = SECRET_NUM;
             }
         }
         count += hierarchy->group_size[j];
     }
 }
fill_truth()
void fill_truth (char * path, char ** labels, int k, float * truth)
Definition at line 390 of file data.c.
Referenced by load_labels_paths().
 {
     int i;
     memset(truth, 0, k*sizeof(float));
     int count = 0;
     for(i = 0; i < k; ++i){
         if(strstr(path, labels[i])){
             truth[i] = 1;
             ++count;
         }
     }
     if(count != 1 && (k != 1 || count != 0)) printf("Too many or too few labels: %d, %s\n", count, path);
 }
fill_truth_captcha()
void fill_truth_captcha (char * path, int n, float * truth)
Definition at line 348 of file data.c.
References alphanum_to_int(), and NUMCHARS.
Referenced by load_data_captcha().
 {
     char *begin = strrchr(path, '/');
     ++begin;
     int i;
     for(i = 0; i < strlen(begin) && i < n && begin[i] != '.'; ++i){
         int index = alphanum_to_int(begin[i]);
         if(index > 35) printf("Bad %c\n", begin[i]);
         truth[i*NUMCHARS+index] = 1;
     }
     for(;i < n; ++i){
         truth[i*NUMCHARS + NUMCHARS-1] = 1;
     }
 }
fill_truth_detection()
void fill_truth_detection (char * path, int num_boxes, float * truth, int classes, int flip, float dx, float dy, float sx, float sy)
Definition at line 298 of file data.c.
References correct_boxes(), find_replace(), box_label::h, box_label::id, randomize_boxes(), read_boxes(), box_label::w, box_label::x, and box_label::y.
Referenced by load_data_detection().
 {
     char labelpath[4096];
     find_replace(path, "images", "labels", labelpath);
     find_replace(labelpath, "JPEGImages", "labels", labelpath);
     find_replace(labelpath, "raw", "labels", labelpath);
     find_replace(labelpath, ".jpg", ".txt", labelpath);
     find_replace(labelpath, ".png", ".txt", labelpath);
     find_replace(labelpath, ".JPG", ".txt", labelpath);
     find_replace(labelpath, ".JPEG", ".txt", labelpath);
     int count = 0;
     box_label *boxes = read_boxes(labelpath, &count);
     randomize_boxes(boxes, count);
     correct_boxes(boxes, count, dx, dy, sx, sy, flip);
     if(count > num_boxes) count = num_boxes;
     float x,y,w,h;
     int id;
     int i;
     for (i = 0; i < count; ++i) {
         x =  boxes[i].x;
         y =  boxes[i].y;
         w =  boxes[i].w;
         h =  boxes[i].h;
         id = boxes[i].id;
         if ((w < .001 || h < .001)) continue;
         truth[i*5+0] = x;
         truth[i*5+1] = y;
         truth[i*5+2] = w;
         truth[i*5+3] = h;
         truth[i*5+4] = id;
     }
     free(boxes);
 }
fill_truth_region()
void fill_truth_region (char * path, float * truth, int classes, int num_boxes, int flip, float dx, float dy, float sx, float sy)
Definition at line 250 of file data.c.
References correct_boxes(), find_replace(), box_label::h, box_label::id, randomize_boxes(), read_boxes(), box_label::w, box_label::x, and box_label::y.
Referenced by load_data_region().
 {
     char labelpath[4096];
     find_replace(path, "images", "labels", labelpath);
     find_replace(labelpath, "JPEGImages", "labels", labelpath);
     find_replace(labelpath, ".jpg", ".txt", labelpath);
     find_replace(labelpath, ".png", ".txt", labelpath);
     find_replace(labelpath, ".JPG", ".txt", labelpath);
     find_replace(labelpath, ".JPEG", ".txt", labelpath);
     int count = 0;
     box_label *boxes = read_boxes(labelpath, &count);
     randomize_boxes(boxes, count);
     correct_boxes(boxes, count, dx, dy, sx, sy, flip);
     float x,y,w,h;
     int id;
     int i;
     for (i = 0; i < count; ++i) {
         x =  boxes[i].x;
         y =  boxes[i].y;
         w =  boxes[i].w;
         h =  boxes[i].h;
         id = boxes[i].id;
         if (w < .005 || h < .005) continue;
         int col = (int)(x*num_boxes);
         int row = (int)(y*num_boxes);
         x = x*num_boxes - col;
         y = y*num_boxes - row;
         int index = (col+row*num_boxes)*(5+classes);
         if (truth[index]) continue;
         truth[index++] = 1;
         if (id < classes) truth[index+id] = 1;
         index += classes;
         truth[index++] = x;
         truth[index++] = y;
         truth[index++] = w;
         truth[index++] = h;
     }
     free(boxes);
 }
fill_truth_swag()
void fill_truth_swag (char * path, float * truth, int classes, int flip, float dx, float dy, float sx, float sy)
Definition at line 212 of file data.c.
References correct_boxes(), find_replace(), box_label::h, box_label::id, randomize_boxes(), read_boxes(), box_label::w, box_label::x, and box_label::y.
Referenced by load_data_swag().
 {
     char labelpath[4096];
     find_replace(path, "images", "labels", labelpath);
     find_replace(labelpath, "JPEGImages", "labels", labelpath);
     find_replace(labelpath, ".jpg", ".txt", labelpath);
     find_replace(labelpath, ".JPG", ".txt", labelpath);
     find_replace(labelpath, ".JPEG", ".txt", labelpath);
     int count = 0;
     box_label *boxes = read_boxes(labelpath, &count);
     randomize_boxes(boxes, count);
     correct_boxes(boxes, count, dx, dy, sx, sy, flip);
     float x,y,w,h;
     int id;
     int i;
     for (i = 0; i < count && i < 30; ++i) {
         x =  boxes[i].x;
         y =  boxes[i].y;
         w =  boxes[i].w;
         h =  boxes[i].h;
         id = boxes[i].id;
         if (w < .0 || h < .0) continue;
         int index = (4+classes) * i;
         truth[index++] = x;
         truth[index++] = y;
         truth[index++] = w;
         truth[index++] = h;
         if (id < classes) truth[index+id] = 1;
     }
     free(boxes);
 }
find_replace_paths()
char** find_replace_paths (char ** paths, int n, char * find, char * replace)
Definition at line 56 of file data.c.
References copy_string(), and find_replace().
Referenced by load_data_writing().
 {
     char **replace_paths = calloc(n, sizeof(char*));
     int i;
     for(i = 0; i < n; ++i){
         char replaced[4096];
         find_replace(paths[i], find, replace, replaced);
         replace_paths[i] = copy_string(replaced);
     }
     return replace_paths;
 }
free_data()
void free_data (data d)
Definition at line 503 of file data.c.
References free_matrix(), data::shallow, matrix::vals, data::X, and data::y.
Referenced by concat_datas(), eval_cifar_csv(), load_threads(), test_cifar(), test_cifar_csv(), test_cifar_csvtrain(), test_classifier(), train_captcha(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_go(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), validate_classifier_crop(), validate_compare(), and validate_dice().
 {
     if(!d.shallow){
         free_matrix(d.X);
         free_matrix(d.y);
     }else{
         free(d.X.vals);
         free(d.y.vals);
     }
 }
get_data_part()
data get_data_part (data d, int part, int total)
Definition at line 1173 of file data.c.
References matrix::cols, matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     data p = {0};
     p.shallow = 1;
     p.X.rows = d.X.rows * (part + 1) / total - d.X.rows * part / total;
     p.y.rows = d.y.rows * (part + 1) / total - d.y.rows * part / total;
     p.X.cols = d.X.cols;
     p.y.cols = d.y.cols;
     p.X.vals = d.X.vals + d.X.rows * part / total;
     p.y.vals = d.y.vals + d.y.rows * part / total;
     return p;
 }
get_labels()
char** get_labels (char * filename)
Definition at line 495 of file data.c.
References free_list(), get_paths(), and list_to_array().
Referenced by demo_classifier(), gun_classifier(), label_classifier(), predict_classifier(), run_detector(), test_captcha(), test_detector(), test_tag(), threat_classifier(), train_captcha(), train_cifar(), train_cifar_distill(), train_classifier(), try_classifier(), valid_captcha(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_detector(), and validate_detector_flip().
 {
     list *plist = get_paths(filename);
     char **labels = (char **)list_to_array(plist);
     free_list(plist);
     return labels;
 }
get_next_batch()
void get_next_batch (data d, int n, int offset, float * X, float * y)
Definition at line 1019 of file data.c.
References matrix::cols, matrix::vals, data::X, and data::y.
Referenced by train_colorizer(), train_dcgan(), and train_network().
 {
     int j;
     for(j = 0; j < n; ++j){
         int index = offset + j;
         memcpy(X+j*d.X.cols, d.X.vals[index], d.X.cols*sizeof(float));
         if(y) memcpy(y+j*d.y.cols, d.y.vals[index], d.y.cols*sizeof(float));
     }
 }
get_paths()
list* get_paths (char * filename)
Definition at line 12 of file data.c.
References fgetl(), file_error(), list_insert(), and make_list().
Referenced by BattleRoyaleWithCheese(), change_leaves(), get_labels(), label_classifier(), SortMaster3000(), test_classifier(), train_captcha(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), valid_captcha(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_compare(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_dice(), validate_yolo(), and validate_yolo_recall().
 {
     char *path;
     FILE *file = fopen(filename, "r");
     if(!file) file_error(filename);
     list *lines = make_list();
     while((path=fgetl(file))){
         list_insert(lines, path);
     }
     fclose(file);
     return lines;
 }
get_random_batch()
void get_random_batch (data d, int n, float * X, float * y)
Definition at line 1009 of file data.c.
References matrix::cols, matrix::rows, matrix::vals, data::X, and data::y.
Referenced by train_network_sgd().
 {
     int j;
     for(j = 0; j < n; ++j){
         int index = rand()%d.X.rows;
         memcpy(X+j*d.X.cols, d.X.vals[index], d.X.cols*sizeof(float));
         memcpy(y+j*d.y.cols, d.y.vals[index], d.y.cols*sizeof(float));
     }
 }
get_random_data()
data get_random_data (data d, int num)
Definition at line 1186 of file data.c.
References matrix::cols, matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     data r = {0};
     r.shallow = 1;
     r.X.rows = num;
     r.y.rows = num;
     r.X.cols = d.X.cols;
     r.y.cols = d.y.cols;
     r.X.vals = calloc(num, sizeof(float *));
     r.y.vals = calloc(num, sizeof(float *));
     int i;
     for(i = 0; i < num; ++i){
         int index = rand()%d.X.rows;
         r.X.vals[i] = d.X.vals[index];
         r.y.vals[i] = d.y.vals[index];
     }
     return r;
 }
get_random_paths()
char** get_random_paths (char ** paths, int n, int m)
Definition at line 42 of file data.c.
References mutex.
Referenced by load_data_augment(), load_data_captcha(), load_data_captcha_encode(), load_data_compare(), load_data_detection(), load_data_old(), load_data_region(), load_data_regression(), load_data_super(), load_data_tag(), and load_data_writing().
 {
     char **random_paths = calloc(n, sizeof(char*));
     int i;
     pthread_mutex_lock(&mutex);
     for(i = 0; i < n; ++i){
         int index = rand()%m;
         random_paths[i] = paths[index];
         //if(i == 0) printf("%s\n", paths[index]);
     }
     pthread_mutex_unlock(&mutex);
     return random_paths;
 }
load_all_cifar10()
data load_all_cifar10 ()
Definition at line 1041 of file data.c.
References matrix::cols, file_error(), make_matrix(), scale_data_rows(), data::shallow, smooth_data(), matrix::vals, data::X, and data::y.
Referenced by extract_cifar(), test_cifar_csvtrain(), train_cifar(), and train_cifar_distill().
 {
     data d = {0};
     d.shallow = 0;
     int i,j,b;
     matrix X = make_matrix(50000, 3072);
     matrix y = make_matrix(50000, 10);
     d.X = X;
     d.y = y;
     for(b = 0; b < 5; ++b){
         char buff[256];
         sprintf(buff, "data/cifar/cifar-10-batches-bin/data_batch_%d.bin", b+1);
         FILE *fp = fopen(buff, "rb");
         if(!fp) file_error(buff);
         for(i = 0; i < 10000; ++i){
             unsigned char bytes[3073];
             fread(bytes, 1, 3073, fp);
             int class = bytes[0];
             y.vals[i+b*10000][class] = 1;
             for(j = 0; j < X.cols; ++j){
                 X.vals[i+b*10000][j] = (double)bytes[j+1];
             }
         }
         fclose(fp);
     }
     //normalize_data_rows(d);
     scale_data_rows(d, 1./255);
     smooth_data(d);
     return d;
 }
load_categorical_data_csv()
data load_categorical_data_csv (char * filename, int target, int k)
Definition at line 965 of file data.c.
References matrix::cols, csv_to_matrix(), load_args::d, one_hot_encode(), pop_column(), matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     data d = {0};
     d.shallow = 0;
     matrix X = csv_to_matrix(filename);
     float *truth_1d = pop_column(&X, target);
     float **truth = one_hot_encode(truth_1d, X.rows, k);
     matrix y;
     y.rows = X.rows;
     y.cols = k;
     y.vals = truth;
     d.X = X;
     d.y = y;
     free(truth_1d);
     return d;
 }
load_cifar10_data()
data load_cifar10_data (char * filename)
Definition at line 982 of file data.c.
References matrix::cols, load_args::d, file_error(), make_matrix(), scale_data_rows(), data::shallow, matrix::vals, data::X, and data::y.
Referenced by eval_cifar_csv(), extract_cifar(), test_cifar(), test_cifar_csv(), and test_cifar_multi().
 {
     data d = {0};
     d.shallow = 0;
     long i,j;
     matrix X = make_matrix(10000, 3072);
     matrix y = make_matrix(10000, 10);
     d.X = X;
     d.y = y;
     FILE *fp = fopen(filename, "rb");
     if(!fp) file_error(filename);
     for(i = 0; i < 10000; ++i){
         unsigned char bytes[3073];
         fread(bytes, 1, 3073, fp);
         int class = bytes[0];
         y.vals[i][class] = 1;
         for(j = 0; j < X.cols; ++j){
             X.vals[i][j] = (double)bytes[j+1];
         }
     }
     scale_data_rows(d, 1./255);
     //normalize_data_rows(d);
     fclose(fp);
     return d;
 }
load_data()
pthread_t load_data (load_args args)
Definition at line 814 of file data.c.
References error(), and load_threads().
Referenced by train_classifier(), train_detector(), and train_regressor().
 {
     pthread_t thread;
     struct load_args *ptr = calloc(1, sizeof(struct load_args));
     *ptr = args;
     if(pthread_create(&thread, 0, load_threads, ptr)) error("Thread creation failed");
     return thread;
 }
load_data_augment()
data load_data_augment (char ** paths, int n, int m, char ** labels, int k, tree * hierarchy, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure, int center)
Definition at line 904 of file data.c.
References load_args::d, get_random_paths(), load_image_augment_paths(), load_labels_paths(), data::shallow, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_augment_paths(paths, n, min, max, size, angle, aspect, hue, saturation, exposure, center);
     d.y = load_labels_paths(paths, n, labels, k, hierarchy);
     if(m) free(paths);
     return d;
 }
load_data_captcha()
data load_data_captcha (char ** paths, int n, int m, int k, int w, int h)
Definition at line 363 of file data.c.
References fill_truth_captcha(), get_random_paths(), load_image_paths(), make_matrix(), NUMCHARS, data::shallow, matrix::vals, data::X, and data::y.
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_paths(paths, n, w, h);
     d.y = make_matrix(n, k*NUMCHARS);
     int i;
     for(i = 0; i < n; ++i){
         fill_truth_captcha(paths[i], k, d.y.vals[i]);
     }
     if(m) free(paths);
     return d;
 }
load_data_captcha_encode()
data load_data_captcha_encode (char ** paths, int n, int m, int w, int h)
Definition at line 378 of file data.c.
References matrix::cols, get_random_paths(), load_image_paths(), data::shallow, data::X, and data::y.
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_paths(paths, n, w, h);
     d.X.cols = 17100;
     d.y = d.X;
     if(m) free(paths);
     return d;
 }
load_data_compare()
data load_data_compare (int n, char ** paths, int m, int classes, int w, int h)
Definition at line 568 of file data.c.
References matrix::cols, image::data, find_replace(), free_image(), get_random_paths(), load_image_color(), make_matrix(), matrix::rows, SECRET_NUM, data::shallow, matrix::vals, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, 2*n, m);
     int i,j;
     data d = {0};
     d.shallow = 0;
     d.X.rows = n;
     d.X.vals = calloc(d.X.rows, sizeof(float*));
     d.X.cols = h*w*6;
     int k = 2*(classes);
     d.y = make_matrix(n, k);
     for(i = 0; i < n; ++i){
         image im1 = load_image_color(paths[i*2],   w, h);
         image im2 = load_image_color(paths[i*2+1], w, h);
         d.X.vals[i] = calloc(d.X.cols, sizeof(float));
         memcpy(d.X.vals[i],         im1.data, h*w*3*sizeof(float));
         memcpy(d.X.vals[i] + h*w*3, im2.data, h*w*3*sizeof(float));
         int id;
         float iou;
         char imlabel1[4096];
         char imlabel2[4096];
         find_replace(paths[i*2],   "imgs", "labels", imlabel1);
         find_replace(imlabel1, "jpg", "txt", imlabel1);
         FILE *fp1 = fopen(imlabel1, "r");
         while(fscanf(fp1, "%d %f", &id, &iou) == 2){
             if (d.y.vals[i][2*id] < iou) d.y.vals[i][2*id] = iou;
         }
         find_replace(paths[i*2+1], "imgs", "labels", imlabel2);
         find_replace(imlabel2, "jpg", "txt", imlabel2);
         FILE *fp2 = fopen(imlabel2, "r");
         while(fscanf(fp2, "%d %f", &id, &iou) == 2){
             if (d.y.vals[i][2*id + 1] < iou) d.y.vals[i][2*id + 1] = iou;
         }
         for (j = 0; j < classes; ++j){
             if (d.y.vals[i][2*j] > .5 &&  d.y.vals[i][2*j+1] < .5){
                 d.y.vals[i][2*j] = 1;
                 d.y.vals[i][2*j+1] = 0;
             } else if (d.y.vals[i][2*j] < .5 &&  d.y.vals[i][2*j+1] > .5){
                 d.y.vals[i][2*j] = 0;
                 d.y.vals[i][2*j+1] = 1;
             } else {
                 d.y.vals[i][2*j]   = SECRET_NUM;
                 d.y.vals[i][2*j+1] = SECRET_NUM;
             }
         }
         fclose(fp1);
         fclose(fp2);
         free_image(im1);
         free_image(im2);
     }
     if(m) free(paths);
     return d;
 }
load_data_detection()
data load_data_detection (int n, char ** paths, int m, int w, int h, int boxes, int classes, float jitter, float hue, float saturation, float exposure)
Definition at line 685 of file data.c.
References image::c, matrix::cols, image::data, fill_image(), fill_truth_detection(), flip_image(), free_image(), get_random_paths(), image::h, load_image_color(), make_image(), make_matrix(), place_image(), rand_uniform(), random_distort_image(), matrix::rows, data::shallow, matrix::vals, image::w, data::X, and data::y.
Referenced by load_thread().
 {
     char **random_paths = get_random_paths(paths, n, m);
     int i;
     data d = {0};
     d.shallow = 0;
     d.X.rows = n;
     d.X.vals = calloc(d.X.rows, sizeof(float*));
     d.X.cols = h*w*3;
     d.y = make_matrix(n, 5*boxes);
     for(i = 0; i < n; ++i){
         image orig = load_image_color(random_paths[i], 0, 0);
         image sized = make_image(w, h, orig.c);
         fill_image(sized, .5);
         float dw = jitter * orig.w;
         float dh = jitter * orig.h;
         float new_ar = (orig.w + rand_uniform(-dw, dw)) / (orig.h + rand_uniform(-dh, dh));
         float scale = rand_uniform(.25, 2);
         float nw, nh;
         if(new_ar < 1){
             nh = scale * h;
             nw = nh * new_ar;
         } else {
             nw = scale * w;
             nh = nw / new_ar;
         }
         float dx = rand_uniform(0, w - nw);
         float dy = rand_uniform(0, h - nh);
         place_image(orig, nw, nh, dx, dy, sized);
         random_distort_image(sized, hue, saturation, exposure);
         int flip = rand()%2;
         if(flip) flip_image(sized);
         d.X.vals[i] = sized.data;
         fill_truth_detection(random_paths[i], boxes, d.y.vals[i], classes, flip, -dx/w, -dy/h, nw/w, nh/h);
         free_image(orig);
     }
     free(random_paths);
     return d;
 }
load_data_in_thread()
pthread_t load_data_in_thread (load_args args)
Definition at line 776 of file data.c.
References error(), and load_thread().
Referenced by load_threads(), test_classifier(), train_captcha(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), validate_classifier_crop(), validate_coco(), validate_compare(), validate_detector(), validate_detector_flip(), and validate_yolo().
 {
     pthread_t thread;
     struct load_args *ptr = calloc(1, sizeof(struct load_args));
     *ptr = args;
     if(pthread_create(&thread, 0, load_thread, ptr)) error("Thread creation failed");
     return thread;
 }
load_data_old()
data load_data_old (char ** paths, int n, int m, char ** labels, int k, int w, int h)
Definition at line 838 of file data.c.
References load_args::d, get_random_paths(), load_image_paths(), load_labels_paths(), data::shallow, data::X, and data::y.
Referenced by load_thread(), train_dice(), and validate_dice().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_paths(paths, n, w, h);
     d.y = load_labels_paths(paths, n, labels, k, 0);
     if(m) free(paths);
     return d;
 }
load_data_region()
data load_data_region (int n, char ** paths, int m, int w, int h, int size, int classes, float jitter, float hue, float saturation, float exposure)
Definition at line 514 of file data.c.
References matrix::cols, crop_image(), image::data, fill_truth_region(), flip_image(), free_image(), get_random_paths(), image::h, load_image_color(), make_matrix(), rand_uniform(), random_distort_image(), resize_image(), matrix::rows, data::shallow, matrix::vals, image::w, data::X, and data::y.
Referenced by load_thread().
 {
     char **random_paths = get_random_paths(paths, n, m);
     int i;
     data d = {0};
     d.shallow = 0;
     d.X.rows = n;
     d.X.vals = calloc(d.X.rows, sizeof(float*));
     d.X.cols = h*w*3;
     int k = size*size*(5+classes);
     d.y = make_matrix(n, k);
     for(i = 0; i < n; ++i){
         image orig = load_image_color(random_paths[i], 0, 0);
         int oh = orig.h;
         int ow = orig.w;
         int dw = (ow*jitter);
         int dh = (oh*jitter);
         int pleft  = rand_uniform(-dw, dw);
         int pright = rand_uniform(-dw, dw);
         int ptop   = rand_uniform(-dh, dh);
         int pbot   = rand_uniform(-dh, dh);
         int swidth =  ow - pleft - pright;
         int sheight = oh - ptop - pbot;
         float sx = (float)swidth  / ow;
         float sy = (float)sheight / oh;
         int flip = rand()%2;
         image cropped = crop_image(orig, pleft, ptop, swidth, sheight);
         float dx = ((float)pleft/ow)/sx;
         float dy = ((float)ptop /oh)/sy;
         image sized = resize_image(cropped, w, h);
         if(flip) flip_image(sized);
         random_distort_image(sized, hue, saturation, exposure);
         d.X.vals[i] = sized.data;
         fill_truth_region(random_paths[i], d.y.vals[i], classes, size, flip, dx, dy, 1./sx, 1./sy);
         free_image(orig);
         free_image(cropped);
     }
     free(random_paths);
     return d;
 }
load_data_regression()
data load_data_regression (char ** paths, int n, int m, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure)
Definition at line 893 of file data.c.
References load_args::d, get_random_paths(), load_image_augment_paths(), load_regression_labels_paths(), data::shallow, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     d.X = load_image_augment_paths(paths, n, min, max, size, angle, aspect, hue, saturation, exposure, 0);
     d.y = load_regression_labels_paths(paths, n);
     if(m) free(paths);
     return d;
 }
load_data_super()
data load_data_super (char ** paths, int n, int m, int w, int h, int scale)
Definition at line 863 of file data.c.
References matrix::cols, load_args::d, image::data, flip_image(), free_image(), get_random_paths(), load_args::im, load_image_color(), load_args::n, random_crop_image(), resize_image(), matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.shallow = 0;
     int i;
     d.X.rows = n;
     d.X.vals = calloc(n, sizeof(float*));
     d.X.cols = w*h*3;
     d.y.rows = n;
     d.y.vals = calloc(n, sizeof(float*));
     d.y.cols = w*scale * h*scale * 3;
     for(i = 0; i < n; ++i){
         image im = load_image_color(paths[i], 0, 0);
         image crop = random_crop_image(im, w*scale, h*scale);
         int flip = rand()%2;
         if (flip) flip_image(crop);
         image resize = resize_image(crop, w, h);
         d.X.vals[i] = resize.data;
         d.y.vals[i] = crop.data;
         free_image(im);
     }
     if(m) free(paths);
     return d;
 }
load_data_swag()
data load_data_swag (char ** paths, int n, int classes, float jitter)
Definition at line 632 of file data.c.
References matrix::cols, crop_image(), image::data, fill_truth_swag(), flip_image(), free_image(), data::h, image::h, load_image_color(), make_matrix(), rand_uniform(), resize_image(), matrix::rows, data::shallow, matrix::vals, data::w, image::w, data::X, and data::y.
Referenced by load_thread().
 {
     int index = rand()%n;
     char *random_path = paths[index];
     image orig = load_image_color(random_path, 0, 0);
     int h = orig.h;
     int w = orig.w;
     data d = {0};
     d.shallow = 0;
     d.w = w;
     d.h = h;
     d.X.rows = 1;
     d.X.vals = calloc(d.X.rows, sizeof(float*));
     d.X.cols = h*w*3;
     int k = (4+classes)*30;
     d.y = make_matrix(1, k);
     int dw = w*jitter;
     int dh = h*jitter;
     int pleft  = rand_uniform(-dw, dw);
     int pright = rand_uniform(-dw, dw);
     int ptop   = rand_uniform(-dh, dh);
     int pbot   = rand_uniform(-dh, dh);
     int swidth =  w - pleft - pright;
     int sheight = h - ptop - pbot;
     float sx = (float)swidth  / w;
     float sy = (float)sheight / h;
     int flip = rand()%2;
     image cropped = crop_image(orig, pleft, ptop, swidth, sheight);
     float dx = ((float)pleft/w)/sx;
     float dy = ((float)ptop /h)/sy;
     image sized = resize_image(cropped, w, h);
     if(flip) flip_image(sized);
     d.X.vals[0] = sized.data;
     fill_truth_swag(random_path, d.y.vals[0], classes, flip, dx, dy, 1./sx, 1./sy);
     free_image(orig);
     free_image(cropped);
     return d;
 }
load_data_tag()
data load_data_tag (char ** paths, int n, int m, int k, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure)
Definition at line 915 of file data.c.
References load_args::d, get_random_paths(), data::h, load_image_augment_paths(), load_tags_paths(), data::shallow, load_args::size, data::w, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     data d = {0};
     d.w = size;
     d.h = size;
     d.shallow = 0;
     d.X = load_image_augment_paths(paths, n, min, max, size, angle, aspect, hue, saturation, exposure, 0);
     d.y = load_tags_paths(paths, n, k);
     if(m) free(paths);
     return d;
 }
load_data_writing()
data load_data_writing (char ** paths, int n, int m, int w, int h, int out_w, int out_h)
Definition at line 823 of file data.c.
References load_args::d, find_replace_paths(), get_random_paths(), load_image_paths(), load_image_paths_gray(), load_args::n, data::shallow, data::X, and data::y.
Referenced by load_thread().
 {
     if(m) paths = get_random_paths(paths, n, m);
     char **replace_paths = find_replace_paths(paths, n, ".png", "-label.png");
     data d = {0};
     d.shallow = 0;
     d.X = load_image_paths(paths, n, w, h);
     d.y = load_image_paths_gray(replace_paths, n, out_w, out_h);
     if(m) free(paths);
     int i;
     for(i = 0; i < n; ++i) free(replace_paths[i]);
     free(replace_paths);
     return d;
 }
load_go()
data load_go (char * filename)
Definition at line 1074 of file data.c.
References fgetl(), file_error(), make_matrix(), resize_matrix(), matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     FILE *fp = fopen(filename, "rb");
     matrix X = make_matrix(3363059, 361);
     matrix y = make_matrix(3363059, 361);
     int row, col;
     if(!fp) file_error(filename);
     char *label;
     int count = 0;
     while((label = fgetl(fp))){
         int i;
         if(count == X.rows){
             X = resize_matrix(X, count*2);
             y = resize_matrix(y, count*2);
         }
         sscanf(label, "%d %d", &row, &col);
         char *board = fgetl(fp);
         int index = row*19 + col;
         y.vals[count][index] = 1;
         for(i = 0; i < 19*19; ++i){
             float val = 0;
             if(board[i] == '1') val = 1;
             else if(board[i] == '2') val = -1;
             X.vals[count][i] = val;
         }
         ++count;
         free(label);
         free(board);
     }
     X = resize_matrix(X, count);
     y = resize_matrix(y, count);
     data d = {0};
     d.shallow = 0;
     d.X = X;
     d.y = y;
     fclose(fp);
     return d;
 }
load_image_augment_paths()
matrix load_image_augment_paths (char ** paths, int n, int min, int max, int size, float angle, float aspect, float hue, float saturation, float exposure, int center)
Definition at line 105 of file data.c.
References image::c, center_crop_image(), matrix::cols, image::data, flip_image(), free_image(), image::h, load_image_color(), random_augment_image(), random_distort_image(), matrix::rows, matrix::vals, and image::w.
Referenced by load_data_augment(), load_data_regression(), and load_data_tag().
 {
     int i;
     matrix X;
     X.rows = n;
     X.vals = calloc(X.rows, sizeof(float*));
     X.cols = 0;
     for(i = 0; i < n; ++i){
         image im = load_image_color(paths[i], 0, 0);
         image crop;
         if(center){
             crop = center_crop_image(im, size, size);
         } else {
             crop = random_augment_image(im, angle, aspect, min, max, size);
         }
         int flip = rand()%2;
         if (flip) flip_image(crop);
         random_distort_image(crop, hue, saturation, exposure);
         /*
         show_image(im, "orig");
         show_image(crop, "crop");
         cvWaitKey(0);
         */
         free_image(im);
         X.vals[i] = crop.data;
         X.cols = crop.h*crop.w*crop.c;
     }
     return X;
 }
load_image_paths()
matrix load_image_paths (char ** paths, int n, int w, int h)
Definition at line 89 of file data.c.
References image::c, matrix::cols, image::data, image::h, load_image_color(), matrix::rows, matrix::vals, and image::w.
Referenced by load_data_captcha(), load_data_captcha_encode(), load_data_old(), and load_data_writing().
 {
     int i;
     matrix X;
     X.rows = n;
     X.vals = calloc(X.rows, sizeof(float*));
     X.cols = 0;
     for(i = 0; i < n; ++i){
         image im = load_image_color(paths[i], w, h);
         X.vals[i] = im.data;
         X.cols = im.h*im.w*im.c;
     }
     return X;
 }
load_image_paths_gray()
matrix load_image_paths_gray (char ** paths, int n, int w, int h)
Definition at line 68 of file data.c.
References image::c, matrix::cols, image::data, free_image(), grayscale_image(), image::h, load_image(), matrix::rows, matrix::vals, and image::w.
Referenced by load_data_writing().
 {
     int i;
     matrix X;
     X.rows = n;
     X.vals = calloc(X.rows, sizeof(float*));
     X.cols = 0;
     for(i = 0; i < n; ++i){
         image im = load_image(paths[i], w, h, 3);
         image gray = grayscale_image(im);
         free_image(im);
         im = gray;
         X.vals[i] = im.data;
         X.cols = im.h*im.w*im.c;
     }
     return X;
 }
load_labels_paths()
matrix load_labels_paths (char ** paths, int n, char ** labels, int k, tree * hierarchy)
Definition at line 454 of file data.c.
References fill_hierarchy(), fill_truth(), make_matrix(), and matrix::vals.
Referenced by load_data_augment(), and load_data_old().
 {
     matrix y = make_matrix(n, k);
     int i;
     for(i = 0; i < n && labels; ++i){
         fill_truth(paths[i], labels, k, y.vals[i]);
         if(hierarchy){
             fill_hierarchy(y.vals[i], k, hierarchy);
         }
     }
     return y;
 }
load_regression_labels_paths()
matrix load_regression_labels_paths (char ** paths, int n)
Definition at line 436 of file data.c.
References find_replace(), make_matrix(), and matrix::vals.
Referenced by load_data_regression().
 {
     matrix y = make_matrix(n, 1);
     int i;
     for(i = 0; i < n; ++i){
         char labelpath[4096];
         find_replace(paths[i], "images", "targets", labelpath);
         find_replace(labelpath, "JPEGImages", "targets", labelpath);
         find_replace(labelpath, ".jpg", ".txt", labelpath);
         find_replace(labelpath, ".png", ".txt", labelpath);
         FILE *file = fopen(labelpath, "r");
         fscanf(file, "%f", &(y.vals[i][0]));
         fclose(file);
     }
     return y;
 }
load_tags_paths()
matrix load_tags_paths (char ** paths, int n, int k)
Definition at line 467 of file data.c.
References find_replace(), make_matrix(), and matrix::vals.
Referenced by load_data_tag().
 {
     matrix y = make_matrix(n, k);
     int i;
     int count = 0;
     for(i = 0; i < n; ++i){
         char label[4096];
         find_replace(paths[i], "imgs", "labels", label);
         find_replace(label, "_iconl.jpeg", ".txt", label);
         FILE *file = fopen(label, "r");
         if(!file){
             find_replace(label, "labels", "labels2", label);
             file = fopen(label, "r");
             if(!file) continue;
         }
         ++count;
         int tag;
         while(fscanf(file, "%d", &tag) == 1){
             if(tag < k){
                 y.vals[i][tag] = 1;
             }
         }
         fclose(file);
     }
     printf("%d/%d\n", count, n);
     return y;
 }
load_thread()
void* load_thread (void * ptr)
Definition at line 737 of file data.c.
References load_args::angle, load_args::aspect, load_args::center, load_args::classes, CLASSIFICATION_DATA, COMPARE_DATA, load_args::d, DETECTION_DATA, load_args::exposure, load_args::h, load_args::hierarchy, load_args::hue, load_args::im, IMAGE_DATA, load_args::jitter, load_args::labels, LETTERBOX_DATA, letterbox_image(), load_data_augment(), load_data_compare(), load_data_detection(), load_data_old(), load_data_region(), load_data_regression(), load_data_super(), load_data_swag(), load_data_tag(), load_data_writing(), load_image_color(), load_args::m, load_args::max, load_args::min, load_args::n, load_args::num_boxes, OLD_CLASSIFICATION_DATA, load_args::out_h, load_args::out_w, load_args::path, load_args::paths, REGION_DATA, REGRESSION_DATA, resize_image(), load_args::resized, load_args::saturation, load_args::scale, load_args::size, SUPER_DATA, SWAG_DATA, TAG_DATA, load_args::type, load_args::w, and WRITING_DATA.
Referenced by load_data_in_thread(), test_classifier(), train_captcha(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), validate_classifier_crop(), and validate_compare().
 {
     //printf("Loading data: %d\n", rand());
     load_args a = *(struct load_args*)ptr;
     if(a.exposure == 0) a.exposure = 1;
     if(a.saturation == 0) a.saturation = 1;
     if(a.aspect == 0) a.aspect = 1;
     if (a.type == OLD_CLASSIFICATION_DATA){
         *a.d = load_data_old(a.paths, a.n, a.m, a.labels, a.classes, a.w, a.h);
     } else if (a.type == REGRESSION_DATA){
         *a.d = load_data_regression(a.paths, a.n, a.m, a.min, a.max, a.size, a.angle, a.aspect, a.hue, a.saturation, a.exposure);
     } else if (a.type == CLASSIFICATION_DATA){
         *a.d = load_data_augment(a.paths, a.n, a.m, a.labels, a.classes, a.hierarchy, a.min, a.max, a.size, a.angle, a.aspect, a.hue, a.saturation, a.exposure, a.center);
     } else if (a.type == SUPER_DATA){
         *a.d = load_data_super(a.paths, a.n, a.m, a.w, a.h, a.scale);
     } else if (a.type == WRITING_DATA){
         *a.d = load_data_writing(a.paths, a.n, a.m, a.w, a.h, a.out_w, a.out_h);
     } else if (a.type == REGION_DATA){
         *a.d = load_data_region(a.n, a.paths, a.m, a.w, a.h, a.num_boxes, a.classes, a.jitter, a.hue, a.saturation, a.exposure);
     } else if (a.type == DETECTION_DATA){
         *a.d = load_data_detection(a.n, a.paths, a.m, a.w, a.h, a.num_boxes, a.classes, a.jitter, a.hue, a.saturation, a.exposure);
     } else if (a.type == SWAG_DATA){
         *a.d = load_data_swag(a.paths, a.n, a.classes, a.jitter);
     } else if (a.type == COMPARE_DATA){
         *a.d = load_data_compare(a.n, a.paths, a.m, a.classes, a.w, a.h);
     } else if (a.type == IMAGE_DATA){
         *(a.im) = load_image_color(a.path, 0, 0);
         *(a.resized) = resize_image(*(a.im), a.w, a.h);
     } else if (a.type == LETTERBOX_DATA){
         *(a.im) = load_image_color(a.path, 0, 0);
         *(a.resized) = letterbox_image(*(a.im), a.w, a.h);
     } else if (a.type == TAG_DATA){
         *a.d = load_data_tag(a.paths, a.n, a.m, a.classes, a.min, a.max, a.size, a.angle, a.aspect, a.hue, a.saturation, a.exposure);
     }
     free(ptr);
     return 0;
 }
load_threads()
void* load_threads (void * ptr)
Definition at line 785 of file data.c.
References concat_datas(), load_args::d, free_data(), load_data_in_thread(), load_args::n, data::shallow, and load_args::threads.
Referenced by load_data().
 {
     int i;
     load_args args = *(load_args *)ptr;
     if (args.threads == 0) args.threads = 1;
     data *out = args.d;
     int total = args.n;
     free(ptr);
     data *buffers = calloc(args.threads, sizeof(data));
     pthread_t *threads = calloc(args.threads, sizeof(pthread_t));
     for(i = 0; i < args.threads; ++i){
         args.d = buffers + i;
         args.n = (i+1) * total/args.threads - i * total/args.threads;
         threads[i] = load_data_in_thread(args);
     }
     for(i = 0; i < args.threads; ++i){
         pthread_join(threads[i], 0);
     }
     *out = concat_datas(buffers, args.threads);
     out->shallow = 0;
     for(i = 0; i < args.threads; ++i){
         buffers[i].shallow = 1;
         free_data(buffers[i]);
     }
     free(buffers);
     free(threads);
     return 0;
 }
normalize_data_rows()
void normalize_data_rows (data d)
Definition at line 1165 of file data.c.
References matrix::cols, normalize_array(), matrix::rows, matrix::vals, and data::X.
 {
     int i;
     for(i = 0; i < d.X.rows; ++i){
         normalize_array(d.X.vals[i], d.X.cols);
     }
 }
print_letters()
void print_letters (float * pred, int n)
Definition at line 338 of file data.c.
References int_to_alphanum(), max_index(), and NUMCHARS.
 {
     int i;
     for(i = 0; i < n; ++i){
         int index = max_index(pred+i*NUMCHARS, NUMCHARS);
         printf("%c", int_to_alphanum(index));
     }
     printf("\n");
 }
randomize_boxes()
void randomize_boxes (box_label * b, int n)
Definition at line 164 of file data.c.
Referenced by fill_truth_detection(), fill_truth_region(), and fill_truth_swag().
 {
     int i;
     for(i = 0; i < n; ++i){
         box_label swap = b[i];
         int index = rand()%n;
         b[i] = b[index];
         b[index] = swap;
     }
 }
randomize_data()
void randomize_data (data d)
Definition at line 1121 of file data.c.
References matrix::rows, matrix::vals, data::X, and data::y.
 {
     int i;
     for(i = d.X.rows-1; i > 0; --i){
         int index = rand()%i;
         float *swap = d.X.vals[index];
         d.X.vals[index] = d.X.vals[i];
         d.X.vals[i] = swap;
         swap = d.y.vals[index];
         d.y.vals[index] = d.y.vals[i];
         d.y.vals[i] = swap;
     }
 }
read_boxes()
box_label* read_boxes (char * filename, int * n)
Definition at line 138 of file data.c.
References box_label::bottom, file_error(), box_label::h, box_label::id, box_label::left, box_label::right, box_label::top, box_label::w, box_label::x, and box_label::y.
Referenced by fill_truth_detection(), fill_truth_region(), fill_truth_swag(), validate_coco_recall(), validate_detector_recall(), and validate_yolo_recall().
 {
     box_label *boxes = calloc(1, sizeof(box_label));
     FILE *file = fopen(filename, "r");
     if(!file) file_error(filename);
     float x, y, h, w;
     int id;
     int count = 0;
     while(fscanf(file, "%d %f %f %f %f", &id, &x, &y, &w, &h) == 5){
         boxes = realloc(boxes, (count+1)*sizeof(box_label));
         boxes[count].id = id;
         boxes[count].x = x;
         boxes[count].y = y;
         boxes[count].h = h;
         boxes[count].w = w;
         boxes[count].left   = x - w/2;
         boxes[count].right  = x + w/2;
         boxes[count].top    = y - h/2;
         boxes[count].bottom = y + h/2;
         ++count;
     }
     fclose(file);
     *n = count;
     return boxes;
 }
scale_data_rows()
void scale_data_rows (data d, float s)
Definition at line 1136 of file data.c.
References matrix::cols, matrix::rows, scale_array(), matrix::vals, and data::X.
Referenced by load_all_cifar10(), and load_cifar10_data().
 {
     int i;
     for(i = 0; i < d.X.rows; ++i){
         scale_array(d.X.vals[i], d.X.cols, s);
     }
 }
smooth_data()
void smooth_data (data d)
Definition at line 1029 of file data.c.
References matrix::cols, matrix::rows, matrix::vals, and data::y.
Referenced by load_all_cifar10().
 {
     int i, j;
     float scale = 1. / d.y.cols;
     float eps = .1;
     for(i = 0; i < d.y.rows; ++i){
         for(j = 0; j < d.y.cols; ++j){
             d.y.vals[i][j] = eps * scale + (1-eps) * d.y.vals[i][j];
         }
     }
 }
split_data()
data* split_data (data d, int part, int total)
Definition at line 1209 of file data.c.
References matrix::cols, matrix::rows, data::shallow, matrix::vals, data::X, and data::y.
 {
     data *split = calloc(2, sizeof(data));
     int i;
     int start = part*d.X.rows/total;
     int end = (part+1)*d.X.rows/total;
     data train;
     data test;
     train.shallow = test.shallow = 1;
     test.X.rows = test.y.rows = end-start;
     train.X.rows = train.y.rows = d.X.rows - (end-start);
     train.X.cols = test.X.cols = d.X.cols;
     train.y.cols = test.y.cols = d.y.cols;
     train.X.vals = calloc(train.X.rows, sizeof(float*));
     test.X.vals = calloc(test.X.rows, sizeof(float*));
     train.y.vals = calloc(train.y.rows, sizeof(float*));
     test.y.vals = calloc(test.y.rows, sizeof(float*));
     for(i = 0; i < start; ++i){
         train.X.vals[i] = d.X.vals[i];
         train.y.vals[i] = d.y.vals[i];
     }
     for(i = start; i < end; ++i){
         test.X.vals[i-start] = d.X.vals[i];
         test.y.vals[i-start] = d.y.vals[i];
     }
     for(i = end; i < d.X.rows; ++i){
         train.X.vals[i-(end-start)] = d.X.vals[i];
         train.y.vals[i-(end-start)] = d.y.vals[i];
     }
     split[0] = train;
     split[1] = test;
     return split;
 }
translate_data_rows()
void translate_data_rows (data d, float s)
Definition at line 1144 of file data.c.
References matrix::cols, matrix::rows, translate_array(), matrix::vals, and data::X.
 {
     int i;
     for(i = 0; i < d.X.rows; ++i){
         translate_array(d.X.vals[i], d.X.cols, s);
     }
 }
Variable Documentation
mutex
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 10 of file data.c.
Referenced by get_random_paths().