Darknet: cost_layer.c File Reference
cost_layer.c File Reference
#include "cost_layer.h"
#include "utils.h"
#include "cuda.h"
#include "blas.h"
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
Functions
COST_TYPE get_cost_type (char *s)
char * get_cost_string (COST_TYPE a)
cost_layer make_cost_layer (int batch, int inputs, COST_TYPE cost_type, float scale)
void resize_cost_layer (cost_layer *l, int inputs)
void forward_cost_layer (cost_layer l, network net)
void backward_cost_layer (const cost_layer l, network net)
Function Documentation
backward_cost_layer()
void backward_cost_layer (const cost_layer l, network net)
Definition at line 95 of file cost_layer.c.
References axpy_cpu(), layer::batch, layer::cost, layer::cost_type, network::delta, layer::delta, layer::inputs, L1, MASKED, layer::output, layer::ratio, layer::scale, SECRET_NUM, SMOOTH, layer::smooth, sum_array(), layer::thresh, and network::truth.
Referenced by make_cost_layer().
 {
     axpy_cpu(l.batch*l.inputs, l.scale, l.delta, 1, net.delta, 1);
 }
forward_cost_layer()
void forward_cost_layer (cost_layer l, network net)
Definition at line 76 of file cost_layer.c.
References layer::batch, layer::cost, layer::cost_type, layer::delta, network::input, layer::inputs, L1, l1_cpu(), l2_cpu(), MASKED, layer::output, SECRET_NUM, SMOOTH, smooth_l1_cpu(), sum_array(), and network::truth.
Referenced by make_cost_layer().
 {
     if (!net.truth) return;
     if(l.cost_type == MASKED){
         int i;
         for(i = 0; i < l.batch*l.inputs; ++i){
             if(net.truth[i] == SECRET_NUM) net.input[i] = SECRET_NUM;
         }
     }
     if(l.cost_type == SMOOTH){
         smooth_l1_cpu(l.batch*l.inputs, net.input, net.truth, l.delta, l.output);
     }else if(l.cost_type == L1){
         l1_cpu(l.batch*l.inputs, net.input, net.truth, l.delta, l.output);
     } else {
         l2_cpu(l.batch*l.inputs, net.input, net.truth, l.delta, l.output);
     }
     l.cost[0] = sum_array(l.output, l.batch*l.inputs);
 }
get_cost_string()
char* get_cost_string (COST_TYPE a)
Definition at line 20 of file cost_layer.c.
References L1, MASKED, SMOOTH, and SSE.
 {
     switch(a){
         case SSE:
             return "sse";
         case MASKED:
             return "masked";
         case SMOOTH:
             return "smooth";
         case L1:
             return "L1";
     }
     return "sse";
 }
get_cost_type()
COST_TYPE get_cost_type (char * s)
Definition at line 10 of file cost_layer.c.
References L1, MASKED, SMOOTH, and SSE.
Referenced by parse_cost().
 {
     if (strcmp(s, "sse")==0) return SSE;
     if (strcmp(s, "masked")==0) return MASKED;
     if (strcmp(s, "smooth")==0) return SMOOTH;
     if (strcmp(s, "L1")==0) return L1;
     fprintf(stderr, "Couldn't find cost type %s, going with SSE\n", s);
     return SSE;
 }
make_cost_layer()
cost_layer make_cost_layer (int batch, int inputs, COST_TYPE cost_type, float scale)
Definition at line 35 of file cost_layer.c.
References layer::backward, backward_cost_layer(), layer::backward_gpu, layer::batch, COST, layer::cost, layer::cost_type, layer::delta, layer::forward, forward_cost_layer(), layer::forward_gpu, layer::inputs, layer::output, layer::outputs, layer::scale, and layer::type.
Referenced by parse_cost().
 {
     fprintf(stderr, "cost                                           %4d\n",  inputs);
     cost_layer l = {0};
     l.type = COST;
     l.scale = scale;
     l.batch = batch;
     l.inputs = inputs;
     l.outputs = inputs;
     l.cost_type = cost_type;
     l.delta = calloc(inputs*batch, sizeof(float));
     l.output = calloc(inputs*batch, sizeof(float));
     l.cost = calloc(1, sizeof(float));
     l.forward = forward_cost_layer;
     l.backward = backward_cost_layer;
     #ifdef GPU
     l.forward_gpu = forward_cost_layer_gpu;
     l.backward_gpu = backward_cost_layer_gpu;
     l.delta_gpu = cuda_make_array(l.output, inputs*batch);
     l.output_gpu = cuda_make_array(l.delta, inputs*batch);
     #endif
     return l;
 }
resize_cost_layer()
void resize_cost_layer (cost_layer * l, int inputs)
Definition at line 62 of file cost_layer.c.
References layer::batch, layer::delta, layer::inputs, layer::output, and layer::outputs.
Referenced by resize_network().
 {
     l->inputs = inputs;
     l->outputs = inputs;
     l->delta = realloc(l->delta, inputs*l->batch*sizeof(float));
     l->output = realloc(l->output, inputs*l->batch*sizeof(float));
 #ifdef GPU
     cuda_free(l->delta_gpu);
     cuda_free(l->output_gpu);
     l->delta_gpu = cuda_make_array(l->delta, inputs*l->batch);
     l->output_gpu = cuda_make_array(l->output, inputs*l->batch);
 #endif
 }