Darknet: dropout_layer.c File Reference
dropout_layer.c File Reference
#include "dropout_layer.h"
#include "utils.h"
#include "cuda.h"
#include <stdlib.h>
#include <stdio.h>
Functions
dropout_layer make_dropout_layer (int batch, int inputs, float probability)
void resize_dropout_layer (dropout_layer *l, int inputs)
void forward_dropout_layer (dropout_layer l, network net)
void backward_dropout_layer (dropout_layer l, network net)
Function Documentation
backward_dropout_layer()
void backward_dropout_layer (dropout_layer l, network net)
Definition at line 50 of file dropout_layer.c.
References layer::batch, network::delta, layer::inputs, layer::probability, layer::rand, and layer::scale.
Referenced by make_dropout_layer().
 {
     int i;
     if(!net.delta) return;
     for(i = 0; i < l.batch * l.inputs; ++i){
         float r = l.rand[i];
         if(r < l.probability) net.delta[i] = 0;
         else net.delta[i] *= l.scale;
     }
 }
forward_dropout_layer()
void forward_dropout_layer (dropout_layer l, network net)
Definition at line 38 of file dropout_layer.c.
References layer::batch, network::input, layer::inputs, layer::probability, layer::rand, rand_uniform(), layer::scale, and network::train.
Referenced by make_dropout_layer().
 {
     int i;
     if (!net.train) return;
     for(i = 0; i < l.batch * l.inputs; ++i){
         float r = rand_uniform(0, 1);
         l.rand[i] = r;
         if(r < l.probability) net.input[i] = 0;
         else net.input[i] *= l.scale;
     }
 }
make_dropout_layer()
dropout_layer make_dropout_layer (int batch, int inputs, float probability)
Definition at line 7 of file dropout_layer.c.
References layer::backward, backward_dropout_layer(), layer::backward_gpu, layer::batch, DROPOUT, layer::forward, forward_dropout_layer(), layer::forward_gpu, layer::inputs, layer::outputs, layer::probability, layer::rand, layer::scale, and layer::type.
Referenced by parse_dropout().
 {
     dropout_layer l = {0};
     l.type = DROPOUT;
     l.probability = probability;
     l.inputs = inputs;
     l.outputs = inputs;
     l.batch = batch;
     l.rand = calloc(inputs*batch, sizeof(float));
     l.scale = 1./(1.-probability);
     l.forward = forward_dropout_layer;
     l.backward = backward_dropout_layer;
     #ifdef GPU
     l.forward_gpu = forward_dropout_layer_gpu;
     l.backward_gpu = backward_dropout_layer_gpu;
     l.rand_gpu = cuda_make_array(l.rand, inputs*batch);
     #endif
     fprintf(stderr, "dropout       p = %.2f               %4d  ->  %4d\n", probability, inputs, inputs);
     return l;
 }
resize_dropout_layer()
void resize_dropout_layer (dropout_layer * l, int inputs)
Definition at line 28 of file dropout_layer.c.
References layer::batch, layer::inputs, and layer::rand.
 {
     l->rand = realloc(l->rand, l->inputs*l->batch*sizeof(float));
     #ifdef GPU
     cuda_free(l->rand_gpu);
     l->rand_gpu = cuda_make_array(l->rand, inputs*l->batch);
     #endif
 }