Darknet: utils.h File Reference
utils.h File Reference
#include <stdio.h>
#include <time.h>
#include "list.h"
Macros
#define SECRET_NUM -1234
#define TWO_PI 6.2831853071795864769252866
Functions
int * read_intlist (char *s, int *n, int d)
int * read_map (char *filename)
void shuffle (void *arr, size_t n, size_t size)
void sorta_shuffle (void *arr, size_t n, size_t size, size_t sections)
void free_ptrs (void **ptrs, int n)
char * basecfg (char *cfgfile)
int alphanum_to_int (char c)
char int_to_alphanum (int i)
int read_int (int fd)
void write_int (int fd, int n)
void read_all (int fd, char *buffer, size_t bytes)
void write_all (int fd, char *buffer, size_t bytes)
int read_all_fail (int fd, char *buffer, size_t bytes)
int write_all_fail (int fd, char *buffer, size_t bytes)
void find_replace (char *str, char *orig, char *rep, char *output)
void error (const char *s)
void malloc_error ()
void file_error (char *s)
void strip (char *s)
void strip_char (char *s, char bad)
void top_k (float *a, int n, int k, int *index)
list * split_str (char *s, char delim)
char * fgetl (FILE *fp)
list * parse_csv_line (char *line)
char * copy_string (char *s)
int count_fields (char *line)
float * parse_fields (char *line, int n)
void normalize_array (float *a, int n)
void scale_array (float *a, int n, float s)
void translate_array (float *a, int n, float s)
int max_index (float *a, int n)
float constrain (float min, float max, float a)
int constrain_int (int a, int min, int max)
float mse_array (float *a, int n)
float rand_normal ()
size_t rand_size_t ()
float rand_uniform (float min, float max)
float rand_scale (float s)
int rand_int (int min, int max)
float sum_array (float *a, int n)
float mean_array (float *a, int n)
void mean_arrays (float **a, int n, int els, float *avg)
float variance_array (float *a, int n)
float mag_array (float *a, int n)
float dist_array (float *a, float *b, int n, int sub)
float ** one_hot_encode (float *a, int n, int k)
float sec (clock_t clocks)
int find_int_arg (int argc, char **argv, char *arg, int def)
float find_float_arg (int argc, char **argv, char *arg, float def)
int find_arg (int argc, char *argv[], char *arg)
char * find_char_arg (int argc, char **argv, char *arg, char *def)
int sample_array (float *a, int n)
void print_statistics (float *a, int n)
Macro Definition Documentation
SECRET_NUM
#define SECRET_NUM -1234
Definition at line 7 of file utils.h.
Referenced by backward_cost_layer(), fill_hierarchy(), fix_data_captcha(), forward_cost_layer(), and load_data_compare().
TWO_PI
#define TWO_PI 6.2831853071795864769252866
Definition at line 8 of file utils.h.
Referenced by rand_normal(), and random_augment_image().
Function Documentation
alphanum_to_int()
int alphanum_to_int (char c)
Definition at line 153 of file utils.c.
Referenced by fill_truth_captcha().
 {
     return (c < 58) ? c - 48 : c-87;
 }
basecfg()
char* basecfg (char * cfgfile)
Definition at line 139 of file utils.c.
References copy_string().
Referenced by run_nightmare(), test_char_rnn(), test_tactic_rnn(), train_captcha(), train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_go(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), valid_char_rnn(), valid_go(), valid_tactic_rnn(), validate_coco_recall(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_yolo(), validate_yolo_recall(), and vec_char_rnn().
 {
     char *c = cfgfile;
     char *next;
     while((next = strchr(c, '/')))
     {
         c = next+1;
     }
     c = copy_string(c);
     next = strchr(c, '.');
     if (next) *next = 0;
     return c;
 }
constrain()
float constrain (float min, float max, float a)
Definition at line 476 of file utils.c.
Referenced by correct_boxes().
 {
     if (a < min) return min;
     if (a > max) return max;
     return a;
 }
constrain_int()
int constrain_int (int a, int min, int max)
Definition at line 469 of file utils.c.
Referenced by crop_image().
 {
     if (a < min) return min;
     if (a > max) return max;
     return a;
 }
copy_string()
char* copy_string (char * s)
Definition at line 368 of file utils.c.
Referenced by basecfg(), find_replace_paths(), and parse_csv_line().
 {
     char *copy = malloc(strlen(s)+1);
     strncpy(copy, s, strlen(s)+1);
     return copy;
 }
count_fields()
int count_fields (char * line)
Definition at line 392 of file utils.c.
Referenced by csv_to_matrix().
 {
     int count = 0;
     int done = 0;
     char *c;
     for(c = line; !done; ++c){
         done = (*c == '\0');
         if(*c == ',' || done) ++count;
     }
     return count;
 }
dist_array()
float dist_array (float * a, float * b, int n, int sub)
Definition at line 483 of file utils.c.
Referenced by best_3d_shift(), best_3d_shift_r(), and composite_3d().
 {
     int i;
     float sum = 0;
     for(i = 0; i < n; i += sub) sum += pow(a[i]-b[i], 2);
     return sqrt(sum);
 }
error()
void error (const char * s)
Definition at line 213 of file utils.c.
Referenced by demo_art(), demo_classifier(), demo_regressor(), get_rnn_data(), get_rnn_token_data(), gun_classifier(), load_data(), load_data_in_thread(), parse_avgpool(), parse_convolutional(), parse_crop(), parse_deconvolutional(), parse_local(), parse_maxpool(), parse_net_options(), parse_network_cfg(), parse_reorg(), parse_route(), read_all(), resize_network(), threat_classifier(), train_network_datum(), valid_char_rnn(), valid_tactic_rnn(), write_all(), and write_int().
 {
     perror(s);
     assert(0);
     exit(-1);
 }
fgetl()
char* fgetl (FILE * fp)
Definition at line 280 of file utils.c.
References malloc_error().
Referenced by csv_to_matrix(), engine_go(), get_paths(), load_go(), read_cfg(), read_data_cfg(), read_map(), read_tokens(), read_tree(), score_game(), test_go(), and vec_char_rnn().
 {
     if(feof(fp)) return 0;
     size_t size = 512;
     char *line = malloc(size*sizeof(char));
     if(!fgets(line, size, fp)){
         free(line);
         return 0;
     }
     size_t curr = strlen(line);
     while((line[curr-1] != '\n') && !feof(fp)){
         if(curr == size-1){
             size *= 2;
             line = realloc(line, size*sizeof(char));
             if(!line) {
                 printf("%ld\n", size);
                 malloc_error();
             }
         }
         size_t readsize = size-curr;
         if(readsize > INT_MAX) readsize = INT_MAX-1;
         fgets(&line[curr], readsize, fp);
         curr = strlen(line);
     }
     if(line[curr-1] == '\n') line[curr-1] = '\0';
     return line;
 }
file_error()
void file_error (char * s)
Definition at line 226 of file utils.c.
Referenced by csv_to_matrix(), get_paths(), load_all_cifar10(), load_cifar10_data(), load_go(), load_weights_upto(), read_boxes(), read_cfg(), read_data_cfg(), read_map(), and save_weights_upto().
 {
     fprintf(stderr, "Couldn't open file: %s\n", s);
     exit(0);
 }
find_arg()
int find_arg (int argc, char * argv[], char * arg)
Definition at line 80 of file utils.c.
References del_arg().
Referenced by main(), run_char_rnn(), run_classifier(), run_detector(), run_go(), run_lsd(), run_nightmare(), run_regressor(), run_super(), and run_tag().
 {
     int i;
     for(i = 0; i < argc; ++i) {
         if(!argv[i]) continue;
         if(0==strcmp(argv[i], arg)) {
             del_arg(argc, argv, i);
             return 1;
         }
     }
     return 0;
 }
find_char_arg()
char* find_char_arg (int argc, char ** argv, char * arg, char * def)
Definition at line 123 of file utils.c.
References del_arg().
Referenced by main(), run_char_rnn(), run_classifier(), run_coco(), run_detector(), run_go(), run_lsd(), run_nightmare(), run_regressor(), and run_yolo().
 {
     int i;
     for(i = 0; i < argc-1; ++i){
         if(!argv[i]) continue;
         if(0==strcmp(argv[i], arg)){
             def = argv[i+1];
             del_arg(argc, argv, i);
             del_arg(argc, argv, i);
             break;
         }
     }
     return def;
 }
find_float_arg()
float find_float_arg (int argc, char ** argv, char * arg, float def)
Definition at line 108 of file utils.c.
References del_arg().
Referenced by main(), run_char_rnn(), run_coco(), run_detector(), run_nightmare(), and run_yolo().
 {
     int i;
     for(i = 0; i < argc-1; ++i){
         if(!argv[i]) continue;
         if(0==strcmp(argv[i], arg)){
             def = atof(argv[i+1]);
             del_arg(argc, argv, i);
             del_arg(argc, argv, i);
             break;
         }
     }
     return def;
 }
find_int_arg()
int find_int_arg (int argc, char ** argv, char * arg, int def)
Definition at line 93 of file utils.c.
References del_arg().
Referenced by main(), run_art(), run_char_rnn(), run_classifier(), run_coco(), run_detector(), run_nightmare(), run_regressor(), and run_yolo().
 {
     int i;
     for(i = 0; i < argc-1; ++i){
         if(!argv[i]) continue;
         if(0==strcmp(argv[i], arg)){
             def = atoi(argv[i+1]);
             del_arg(argc, argv, i);
             del_arg(argc, argv, i);
             break;
         }
     }
     return def;
 }
find_replace()
void find_replace (char * str, char * orig, char * rep, char * output)
Definition at line 176 of file utils.c.
Referenced by fill_truth_detection(), fill_truth_region(), fill_truth_swag(), find_replace_paths(), load_data_compare(), load_regression_labels_paths(), load_tags_paths(), validate_coco_recall(), validate_detector_recall(), and validate_yolo_recall().
 {
     char buffer[4096] = {0};
     char *p;
     sprintf(buffer, "%s", str);
     if(!(p = strstr(buffer, orig))){  // Is 'orig' even in 'str'?
         sprintf(output, "%s", str);
         return;
     }
     *p = '\0';
     sprintf(output, "%s%s%s", buffer, rep, p+strlen(orig));
 }
free_ptrs()
void free_ptrs (void ** ptrs, int n)
Definition at line 273 of file utils.c.
Referenced by test_detector(), train_cifar(), train_cifar_distill(), train_classifier(), train_compare(), train_regressor(), and train_tag().
 {
     int i;
     for(i = 0; i < n; ++i) free(ptrs[i]);
     free(ptrs);
 }
int_to_alphanum()
char int_to_alphanum (int i)
Definition at line 157 of file utils.c.
Referenced by print_letters().
 {
     if (i == 36) return '.';
     return (i < 10) ? i + 48 : i + 87;
 }
mag_array()
float mag_array (float * a, int n)
Definition at line 519 of file utils.c.
Referenced by forward_detection_layer(), forward_region_layer(), reconstruct_picture(), and test_resize().
 {
     int i;
     float sum = 0;
     for(i = 0; i < n; ++i){
         sum += a[i]*a[i];
     }
     return sqrt(sum);
 }
malloc_error()
void malloc_error ()
Definition at line 220 of file utils.c.
Referenced by fgetl().
 {
     fprintf(stderr, "Malloc error\n");
     exit(-1);
 }
max_index()
int max_index (float * a, int n)
Definition at line 550 of file utils.c.
Referenced by compare_networks(), draw_detections(), extract_cifar(), generate_move(), get_predicted_class_network(), label_classifier(), print_letters(), test_cifar_multi(), and valid_go().
 {
     if(n <= 0) return -1;
     int i, max_i = 0;
     float max = a[0];
     for(i = 1; i < n; ++i){
         if(a[i] > max){
             max = a[i];
             max_i = i;
         }
     }
     return max_i;
 }
mean_array()
float mean_array (float * a, int n)
Definition at line 432 of file utils.c.
References sum_array().
Referenced by calculate_loss(), normalize_array(), print_network(), print_statistics(), and variance_array().
 {
     return sum_array(a,n)/n;
 }
mean_arrays()
void mean_arrays (float ** a, int n, int els, float * avg)
Definition at line 437 of file utils.c.
 {
     int i;
     int j;
     memset(avg, 0, els*sizeof(float));
     for(j = 0; j < n; ++j){
         for(i = 0; i < els; ++i){
             avg[i] += a[j][i];
         }
     }
     for(i = 0; i < els; ++i){
         avg[i] /= n;
     }
 }
mse_array()
float mse_array (float * a, int n)
Definition at line 491 of file utils.c.
Referenced by print_statistics().
 {
     int i;
     float sum = 0;
     for(i = 0; i < n; ++i) sum += a[i]*a[i];
     return sqrt(sum/n);
 }
normalize_array()
void normalize_array (float * a, int n)
Definition at line 499 of file utils.c.
References mean_array(), and variance_array().
Referenced by normalize_data_rows(), and optimize_picture().
 {
     int i;
     float mu = mean_array(a,n);
     float sigma = sqrt(variance_array(a,n));
     for(i = 0; i < n; ++i){
         a[i] = (a[i] - mu)/sigma;
     }
     mu = mean_array(a,n);
     sigma = sqrt(variance_array(a,n));
 }
one_hot_encode()
float** one_hot_encode (float * a, int n, int k)
Definition at line 637 of file utils.c.
Referenced by load_categorical_data_csv().
 {
     int i;
     float **t = calloc(n, sizeof(float*));
     for(i = 0; i < n; ++i){
         t[i] = calloc(k, sizeof(float));
         int index = (int)a[i];
         t[i][index] = 1;
     }
     return t;
 }
parse_csv_line()
list* parse_csv_line (char * line)
Definition at line 375 of file utils.c.
References copy_string(), list_insert(), and make_list().
 {
     list *l = make_list();
     char *c, *p;
     int in = 0;
     for(c = line, p = line; *c != '\0'; ++c){
         if(*c == '"') in = !in;
         else if(*c == ',' && !in){
             *c = '\0';
             list_insert(l, copy_string(p));
             p = c+1;
         }
     }
     list_insert(l, copy_string(p));
     return l;
 }
parse_fields()
float* parse_fields (char * line, int n)
Definition at line 404 of file utils.c.
Referenced by csv_to_matrix().
 {
     float *field = calloc(n, sizeof(float));
     char *c, *p, *end;
     int count = 0;
     int done = 0;
     for(c = line, p = line; !done; ++c){
         done = (*c == '\0');
         if(*c == ',' || done){
             *c = '\0';
             field[count] = strtod(p, &end);
             if(p == c) field[count] = nan("");
             if(end != c && (end != c-1 || *end != '\r')) field[count] = nan(""); //DOS file formats!
             p = c+1;
             ++count;
         }
     }
     return field;
 }
print_statistics()
void print_statistics (float * a, int n)
Definition at line 452 of file utils.c.
References mean_array(), mse_array(), and variance_array().
Referenced by statistics_connected_layer().
 {
     float m = mean_array(a, n);
     float v = variance_array(a, n);
     printf("MSE: %.6f, Mean: %.6f, Variance: %.6f\n", mse_array(a, n), m, v);
 }
rand_int()
int rand_int (int min, int max)
Definition at line 564 of file utils.c.
Referenced by random_augment_image(), and random_crop_image().
 {
     if (max < min){
         int s = min;
         min = max;
         max = s;
     }
     int r = (rand()%(max - min + 1)) + min;
     return r;
 }
rand_normal()
float rand_normal ()
Definition at line 576 of file utils.c.
References TWO_PI.
Referenced by make_convolutional_layer(), make_deconvolutional_layer(), make_random_image(), test_dcgan(), and train_dcgan().
 {
     static int haveSpare = 0;
     static double rand1, rand2;
     if(haveSpare)
     {
         haveSpare = 0;
         return sqrt(rand1) * sin(rand2);
     }
     haveSpare = 1;
     rand1 = rand() / ((double) RAND_MAX);
     if(rand1 < 1e-100) rand1 = 1e-100;
     rand1 = -2 * log(rand1);
     rand2 = (rand() / ((double) RAND_MAX)) * TWO_PI;
     return sqrt(rand1) * cos(rand2);
 }
rand_scale()
float rand_scale (float s)
Definition at line 630 of file utils.c.
References rand_uniform().
Referenced by random_augment_image(), random_distort_image(), and test_resize().
 {
     float scale = rand_uniform(1, s);
     if(rand()%2) return scale;
     return 1./scale;
 }
rand_size_t()
size_t rand_size_t ()
Definition at line 608 of file utils.c.
Referenced by train_char_rnn().
 {
     return  ((size_t)(rand()&0xff) << 56) |
             ((size_t)(rand()&0xff) << 48) |
             ((size_t)(rand()&0xff) << 40) |
             ((size_t)(rand()&0xff) << 32) |
             ((size_t)(rand()&0xff) << 24) |
             ((size_t)(rand()&0xff) << 16) |
             ((size_t)(rand()&0xff) << 8) |
             ((size_t)(rand()&0xff) << 0);
 }
rand_uniform()
float rand_uniform (float min, float max)
Definition at line 620 of file utils.c.
Referenced by forward_dropout_layer(), get_current_rate(), load_data_detection(), load_data_region(), load_data_swag(), make_connected_layer(), make_local_layer(), rand_scale(), random_augment_image(), random_distort_image(), sample_array(), and test_resize().
 {
     if(max < min){
         float swap = min;
         min = max;
         max = swap;
     }
     return ((float)rand()/RAND_MAX * (max - min)) + min;
 }
read_all()
void read_all (int fd, char * buffer, size_t bytes)
Definition at line 347 of file utils.c.
References error().
 {
     size_t n = 0;
     while(n < bytes){
         int next = read(fd, buffer + n, bytes-n);
         if(next <= 0) error("read failed");
         n += next;
     }
 }
read_all_fail()
int read_all_fail (int fd, char * buffer, size_t bytes)
Definition at line 325 of file utils.c.
 {
     size_t n = 0;
     while(n < bytes){
         int next = read(fd, buffer + n, bytes-n);
         if(next <= 0) return 1;
         n += next;
     }
     return 0;
 }
read_int()
int read_int (int fd)
Definition at line 311 of file utils.c.
 {
     int n = 0;
     int next = read(fd, &n, sizeof(int));
     if(next <= 0) return -1;
     return n;
 }
read_intlist()
int* read_intlist (char * s, int * n, int d)
Definition at line 12 of file utils.c.
Referenced by run_classifier().
 {
     int *gpus = 0;
     if(gpu_list){
         int len = strlen(gpu_list);
         *ngpus = 1;
         int i;
         for(i = 0; i < len; ++i){
             if (gpu_list[i] == ',') ++*ngpus;
         }
         gpus = calloc(*ngpus, sizeof(int));
         for(i = 0; i < *ngpus; ++i){
             gpus[i] = atoi(gpu_list);
             gpu_list = strchr(gpu_list, ',')+1;
         }
     } else {
         gpus = calloc(1, sizeof(float));
         *gpus = d;
         *ngpus = 1;
     }
     return gpus;
 }
read_map()
int* read_map (char * filename)
Definition at line 35 of file utils.c.
References fgetl(), and file_error().
Referenced by parse_region(), validate_detector(), and validate_detector_flip().
 {
     int n = 0;
     int *map = 0;
     char *str;
     FILE *file = fopen(filename, "r");
     if(!file) file_error(filename);
     while((str=fgetl(file))){
         ++n;
         map = realloc(map, n*sizeof(int));
         map[n-1] = atoi(str);
     }
     return map;
 }
sample_array()
int sample_array (float * a, int n)
Definition at line 537 of file utils.c.
References rand_uniform(), scale_array(), and sum_array().
Referenced by generate_move(), test_char_rnn(), and test_tactic_rnn().
 {
     float sum = sum_array(a, n);
     scale_array(a, n, 1./sum);
     float r = rand_uniform(0, 1);
     int i;
     for(i = 0; i < n; ++i){
         r = r - a[i];
         if (r <= 0) return i;
     }
     return n-1;
 }
scale_array()
void scale_array (float * a, int n, float s)
Definition at line 529 of file utils.c.
Referenced by sample_array(), and scale_data_rows().
 {
     int i;
     for(i = 0; i < n; ++i){
         a[i] *= s;
     }
 }
sec()
float sec (clock_t clocks)
Definition at line 192 of file utils.c.
Referenced by BattleRoyaleWithCheese(), gemm_cpu(), predict_classifier(), predict_regressor(), SortMaster3000(), test_cifar(), test_classifier(), test_coco(), test_dcgan(), test_detector(), test_lsd(), test_super(), test_tag(), test_voxel(), test_writing(), test_yolo(), train_captcha(), train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_go(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), try_classifier(), validate_classifier_crop(), and validate_compare().
 {
     return (float)clocks/CLOCKS_PER_SEC;
 }
shuffle()
void shuffle (void * arr, size_t n, size_t size)
Definition at line 61 of file utils.c.
Referenced by BattleRoyaleWithCheese(), and sorta_shuffle().
 {
     size_t i;
     void *swp = calloc(1, size);
     for(i = 0; i < n-1; ++i){
         size_t j = i + rand()/(RAND_MAX / (n-i)+1);
         memcpy(swp,          arr+(j*size), size);
         memcpy(arr+(j*size), arr+(i*size), size);
         memcpy(arr+(i*size), swp,          size);
     }
 }
sorta_shuffle()
void sorta_shuffle (void * arr, size_t n, size_t size, size_t sections)
Definition at line 50 of file utils.c.
References shuffle().
Referenced by BattleRoyaleWithCheese().
 {
     size_t i;
     for(i = 0; i < sections; ++i){
         size_t start = n*i/sections;
         size_t end = n*(i+1)/sections;
         size_t num = end-start;
         shuffle(arr+(start*size), num, size);
     }
 }
split_str()
list* split_str (char * s, char delim)
Definition at line 232 of file utils.c.
References list_insert(), and make_list().
 {
     size_t i;
     size_t len = strlen(s);
     list *l = make_list();
     list_insert(l, s);
     for(i = 0; i < len; ++i){
         if(s[i] == delim){
             s[i] = '\0';
             list_insert(l, &(s[i+1]));
         }
     }
     return l;
 }
strip()
void strip (char * s)
Definition at line 247 of file utils.c.
Referenced by read_cfg(), read_data_cfg(), and vec_char_rnn().
 {
     size_t i;
     size_t len = strlen(s);
     size_t offset = 0;
     for(i = 0; i < len; ++i){
         char c = s[i];
         if(c==' '||c=='\t'||c=='\n') ++offset;
         else s[i-offset] = c;
     }
     s[len-offset] = '\0';
 }
strip_char()
void strip_char (char * s, char bad)
Definition at line 260 of file utils.c.
 {
     size_t i;
     size_t len = strlen(s);
     size_t offset = 0;
     for(i = 0; i < len; ++i){
         char c = s[i];
         if(c==bad) ++offset;
         else s[i-offset] = c;
     }
     s[len-offset] = '\0';
 }
sum_array()
float sum_array (float * a, int n)
Definition at line 424 of file utils.c.
Referenced by backward_bias(), backward_cost_layer(), forward_cost_layer(), mean_array(), rescale_weights(), and sample_array().
 {
     int i;
     float sum = 0;
     for(i = 0; i < n; ++i) sum += a[i];
     return sum;
 }
top_k()
void top_k (float * a, int n, int k, int * index)
Definition at line 197 of file utils.c.
Referenced by forward_detection_layer(), generate_move(), matrix_topk_accuracy(), predict_classifier(), test_go(), top_predictions(), validate_classifier_10(), validate_classifier_full(), validate_classifier_multi(), and validate_classifier_single().
 {
     int i,j;
     for(j = 0; j < k; ++j) index[j] = -1;
     for(i = 0; i < n; ++i){
         int curr = i;
         for(j = 0; j < k; ++j){
             if((index[j] < 0) || a[curr] > a[index[j]]){
                 int swap = curr;
                 curr = index[j];
                 index[j] = swap;
             }
         }
     }
 }
translate_array()
void translate_array (float * a, int n, float s)
Definition at line 511 of file utils.c.
Referenced by translate_data_rows().
 {
     int i;
     for(i = 0; i < n; ++i){
         a[i] += s;
     }
 }
variance_array()
float variance_array (float * a, int n)
Definition at line 459 of file utils.c.
References mean_array().
Referenced by calculate_loss(), normalize_array(), print_network(), and print_statistics().
 {
     int i;
     float sum = 0;
     float mean = mean_array(a, n);
     for(i = 0; i < n; ++i) sum += (a[i] - mean)*(a[i]-mean);
     float variance = sum/n;
     return variance;
 }
write_all()
void write_all (int fd, char * buffer, size_t bytes)
Definition at line 357 of file utils.c.
References error().
 {
     size_t n = 0;
     while(n < bytes){
         size_t next = write(fd, buffer + n, bytes-n);
         if(next <= 0) error("write failed");
         n += next;
     }
 }
write_all_fail()
int write_all_fail (int fd, char * buffer, size_t bytes)
Definition at line 336 of file utils.c.
 {
     size_t n = 0;
     while(n < bytes){
         size_t next = write(fd, buffer + n, bytes-n);
         if(next <= 0) return 1;
         n += next;
     }
     return 0;
 }
write_int()
void write_int (int fd, int n)
Definition at line 319 of file utils.c.
References error().
 {
     int next = write(fd, &n, sizeof(int));
     if(next <= 0) error("read failed");
 }