Darknet: lsd.c File Reference
lsd.c File Reference
#include "network.h"
#include "cost_layer.h"
#include "utils.h"
#include "parser.h"
#include "blas.h"
Functions
void test_dcgan (char *cfgfile, char *weightfile)
void dcgan_batch (network gnet, network anet)
void train_dcgan (char *cfg, char *weight, char *acfg, char *aweight, int clear, int display, char *train_images)
void train_colorizer (char *cfg, char *weight, char *acfg, char *aweight, int clear, int display)
void test_lsd (char *cfgfile, char *weightfile, char *filename, int gray)
void run_lsd (int argc, char **argv)
Function Documentation
dcgan_batch()
void dcgan_batch (network gnet, network anet)
Definition at line 436 of file lsd.c.
 {
     //float *input = calloc(x_size, sizeof(float));
 }
run_lsd()
void run_lsd (int argc, char ** argv)
Definition at line 1111 of file lsd.c.
References find_arg(), find_char_arg(), test_dcgan(), test_lsd(), train_colorizer(), and train_dcgan().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     int clear = find_arg(argc, argv, "-clear");
     int display = find_arg(argc, argv, "-display");
     char *file = find_char_arg(argc, argv, "-file", "/home/pjreddie/data/imagenet/imagenet1k.train.list");
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5] : 0;
     char *acfg = argv[5];
     char *aweights = (argc > 6) ? argv[6] : 0;
     //if(0==strcmp(argv[2], "train")) train_lsd(cfg, weights, clear);
     //else if(0==strcmp(argv[2], "train2")) train_lsd2(cfg, weights, acfg, aweights, clear);
     //else if(0==strcmp(argv[2], "traincolor")) train_colorizer(cfg, weights, acfg, aweights, clear);
     //else if(0==strcmp(argv[2], "train3")) train_lsd3(argv[3], argv[4], argv[5], argv[6], argv[7], argv[8], clear);
     if(0==strcmp(argv[2], "traingan")) train_dcgan(cfg, weights, acfg, aweights, clear, display, file);
     else if(0==strcmp(argv[2], "traincolor")) train_colorizer(cfg, weights, acfg, aweights, clear, display);
     else if(0==strcmp(argv[2], "gan")) test_dcgan(cfg, weights);
     else if(0==strcmp(argv[2], "test")) test_lsd(cfg, weights, filename, 0);
     else if(0==strcmp(argv[2], "color")) test_lsd(cfg, weights, filename, 1);
     /*
        else if(0==strcmp(argv[2], "valid")) validate_lsd(cfg, weights);
      */
 }
test_dcgan()
void test_dcgan (char * cfgfile, char * weightfile)
Definition at line 390 of file lsd.c.
References image::c, network::c, image::data, free_image(), get_network_image_layer(), image::h, network::h, network::layers, load_weights(), make_image(), network::n, network_predict(), normalize_image(), layer::out_c, parse_network_cfg(), rand_normal(), save_image(), sec(), set_batch_network(), show_image(), image::w, and network::w.
Referenced by run_lsd().
 {
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     clock_t time;
     char buff[256];
     char *input = buff;
     int i, imlayer = 0;
     for (i = 0; i < net.n; ++i) {
         if (net.layers[i].out_c == 3) {
             imlayer = i;
             printf("%d\n", i);
             break;
         }
     }
     while(1){
         image im = make_image(net.w, net.h, net.c);
         int i;
         for(i = 0; i < im.w*im.h*im.c; ++i){
             im.data[i] = rand_normal();
         }
         float *X = im.data;
         time=clock();
         network_predict(net, X);
         image out = get_network_image_layer(net, imlayer);
         //yuv_to_rgb(out);
         normalize_image(out);
         printf("%s: Predicted in %f seconds.\n", input, sec(clock()-time));
         show_image(out, "out");
         save_image(out, "out");
 #ifdef OPENCV
         cvWaitKey(0);
 #endif
         free_image(im);
     }
 }
test_lsd()
void test_lsd (char * cfgfile, char * weightfile, char * filename, int gray)
Definition at line 1052 of file lsd.c.
References constrain_image(), crop_image(), image::data, free_image(), get_network_image_layer(), grayscale_image_3c(), image::h, network::h, network::layers, load_image_color(), load_weights(), network::n, network_predict(), layer::out_c, parse_network_cfg(), resize_min(), save_image(), sec(), set_batch_network(), show_image(), image::w, and network::w.
Referenced by run_lsd().
 {
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     clock_t time;
     char buff[256];
     char *input = buff;
     int i, imlayer = 0;
     for (i = 0; i < net.n; ++i) {
         if (net.layers[i].out_c == 3) {
             imlayer = i;
             printf("%d\n", i);
             break;
         }
     }
     while(1){
         if(filename){
             strncpy(input, filename, 256);
         }else{
             printf("Enter Image Path: ");
             fflush(stdout);
             input = fgets(input, 256, stdin);
             if(!input) return;
             strtok(input, "\n");
         }
         image im = load_image_color(input, 0, 0);
         image resized = resize_min(im, net.w);
         image crop = crop_image(resized, (resized.w - net.w)/2, (resized.h - net.h)/2, net.w, net.h);
         if(gray) grayscale_image_3c(crop);
         float *X = crop.data;
         time=clock();
         network_predict(net, X);
         image out = get_network_image_layer(net, imlayer);
         //yuv_to_rgb(out);
         constrain_image(out);
         printf("%s: Predicted in %f seconds.\n", input, sec(clock()-time));
         show_image(out, "out");
         show_image(crop, "crop");
         save_image(out, "out");
 #ifdef OPENCV
         cvWaitKey(0);
 #endif
         free_image(im);
         free_image(resized);
         free_image(crop);
         if (filename) break;
     }
 }
train_colorizer()
void train_colorizer (char * cfg, char * weight, char * acfg, char * aweight, int clear, int display)
Definition at line 623 of file lsd.c.
References basecfg(), network::batch, layer::batch, network::c, load_args::classes, CLASSIFICATION_DATA, concat_data(), copy_cpu(), copy_data(), network::cost, load_args::d, network::decay, network::delta, float_to_image(), free_data(), get_base_args(), get_current_batch(), get_current_rate(), get_next_batch(), get_paths(), grayscale_image_3c(), network::h, network::inputs, load_args::labels, network::layers, network::learning_rate, list_to_array(), load_data_in_thread(), load_network(), load_thread(), load_args::m, network::max_batches, network::momentum, network::n, load_args::n, layer::out_c, layer::output, network::outputs, layer::outputs, load_args::paths, save_weights(), sec(), network::seen, show_image(), list::size, network::subdivisions, network::train, train_network(), network::truths, load_args::type, matrix::vals, network::w, data::X, and data::y.
Referenced by run_lsd().
 {
 #ifdef GPU
     //char *train_images = "/home/pjreddie/data/coco/train1.txt";
     //char *train_images = "/home/pjreddie/data/coco/trainvalno5k.txt";
     char *train_images = "/home/pjreddie/data/imagenet/imagenet1k.train.list";
     char *backup_directory = "/home/pjreddie/backup/";
     srand(time(0));
     char *base = basecfg(cfg);
     char *abase = basecfg(acfg);
     printf("%s\n", base);
     network net = load_network(cfg, weight, clear);
     network anet = load_network(acfg, aweight, clear);
     int i, j, k;
     layer imlayer = {0};
     for (i = 0; i < net.n; ++i) {
         if (net.layers[i].out_c == 3) {
             imlayer = net.layers[i];
             break;
         }
     }
     printf("Learning Rate: %g, Momentum: %g, Decay: %g\n", net.learning_rate, net.momentum, net.decay);
     int imgs = net.batch*net.subdivisions;
     i = *net.seen/imgs;
     data train, buffer;
     list *plist = get_paths(train_images);
     //int N = plist->size;
     char **paths = (char **)list_to_array(plist);
     load_args args= get_base_args(net);
     args.paths = paths;
     args.n = imgs;
     args.m = plist->size;
     args.d = &buffer;
     args.type = CLASSIFICATION_DATA;
     args.classes = 1;
     char *ls[2] = {"imagenet"};
     args.labels = ls;
     pthread_t load_thread = load_data_in_thread(args);
     clock_t time;
     int x_size = net.inputs*net.batch;
     int y_size = x_size;
     net.delta = 0;
     net.train = 1;
     float *pixs = calloc(x_size, sizeof(float));
     float *graypixs = calloc(x_size, sizeof(float));
     float *y = calloc(y_size, sizeof(float));
     int ay_size = anet.outputs*anet.batch;
     anet.delta = 0;
     anet.train = 1;
     float *imerror = cuda_make_array(0, imlayer.outputs*imlayer.batch);
     float aloss_avg = -1;
     float gloss_avg = -1;
     //data generated = copy_data(train);
     while (get_current_batch(net) < net.max_batches) {
         i += 1;
         time=clock();
         pthread_join(load_thread, 0);
         train = buffer;
         load_thread = load_data_in_thread(args);
         printf("Loaded: %lf seconds\n", sec(clock()-time));
         data gray = copy_data(train);
         for(j = 0; j < imgs; ++j){
             image gim = float_to_image(net.w, net.h, net.c, gray.X.vals[j]);
             grayscale_image_3c(gim);
             train.y.vals[j][0] = .95;
             gray.y.vals[j][0] = .05;
         }
         time=clock();
         float gloss = 0;
         for(j = 0; j < net.subdivisions; ++j){
             get_next_batch(train, net.batch, j*net.batch, pixs, 0);
             get_next_batch(gray, net.batch, j*net.batch, graypixs, 0);
             cuda_push_array(net.input_gpu, graypixs, net.inputs*net.batch);
             cuda_push_array(net.truth_gpu, pixs, net.truths*net.batch);
             /*
                image origi = float_to_image(net.w, net.h, 3, pixs);
                image grayi = float_to_image(net.w, net.h, 3, graypixs);
                show_image(grayi, "gray");
                show_image(origi, "orig");
                cvWaitKey(0);
              */
             *net.seen += net.batch;
             forward_network_gpu(net);
             fill_ongpu(imlayer.outputs*imlayer.batch, 0, imerror, 1);
             copy_ongpu(anet.inputs*anet.batch, imlayer.output_gpu, 1, anet.input_gpu, 1);
             fill_ongpu(anet.inputs*anet.batch, .95, anet.truth_gpu, 1);
             anet.delta_gpu = imerror;
             forward_network_gpu(anet);
             backward_network_gpu(anet);
             scal_ongpu(imlayer.outputs*imlayer.batch, 1./100., net.layers[net.n-1].delta_gpu, 1);
             scal_ongpu(imlayer.outputs*imlayer.batch, 1, imerror, 1);
             printf("realness %f\n", cuda_mag_array(imerror, imlayer.outputs*imlayer.batch));
             printf("features %f\n", cuda_mag_array(net.layers[net.n-1].delta_gpu, imlayer.outputs*imlayer.batch));
             axpy_ongpu(imlayer.outputs*imlayer.batch, 1, imerror, 1, net.layers[net.n-1].delta_gpu, 1);
             backward_network_gpu(net);
             gloss += *net.cost /(net.subdivisions*net.batch);
             for(k = 0; k < net.batch; ++k){
                 int index = j*net.batch + k;
                 copy_cpu(imlayer.outputs, imlayer.output + k*imlayer.outputs, 1, gray.X.vals[index], 1);
             }
         }
         harmless_update_network_gpu(anet);
         data merge = concat_data(train, gray);
         //randomize_data(merge);
         float aloss = train_network(anet, merge);
         update_network_gpu(net);
             #ifdef OPENCV
         if(display){
             image im = float_to_image(anet.w, anet.h, anet.c, gray.X.vals[0]);
             image im2 = float_to_image(anet.w, anet.h, anet.c, train.X.vals[0]);
             show_image(im, "gen");
             show_image(im2, "train");
             cvWaitKey(50);
         }
         #endif
         free_data(merge);
         free_data(train);
         free_data(gray);
         if (aloss_avg < 0) aloss_avg = aloss;
         aloss_avg = aloss_avg*.9 + aloss*.1;
         gloss_avg = gloss_avg*.9 + gloss*.1;
         printf("%d: gen: %f, adv: %f | gen_avg: %f, adv_avg: %f, %f rate, %lf seconds, %d images\n", i, gloss, aloss, gloss_avg, aloss_avg, get_current_rate(net), sec(clock()-time), i*imgs);
         if(i%1000==0){
             char buff[256];
             sprintf(buff, "%s/%s_%d.weights", backup_directory, base, i);
             save_weights(net, buff);
             sprintf(buff, "%s/%s_%d.weights", backup_directory, abase, i);
             save_weights(anet, buff);
         }
         if(i%100==0){
             char buff[256];
             sprintf(buff, "%s/%s.backup", backup_directory, base);
             save_weights(net, buff);
             sprintf(buff, "%s/%s.backup", backup_directory, abase);
             save_weights(anet, buff);
         }
     }
     char buff[256];
     sprintf(buff, "%s/%s_final.weights", backup_directory, base);
     save_weights(net, buff);
 #endif
 }
train_dcgan()
void train_dcgan (char * cfg, char * weight, char * acfg, char * aweight, int clear, int display, char * train_images)
Definition at line 442 of file lsd.c.
References basecfg(), network::batch, layer::batch, network::c, load_args::classes, CLASSIFICATION_DATA, concat_data(), copy_cpu(), copy_data(), network::cost, load_args::d, network::decay, float_to_image(), free_data(), get_base_args(), get_current_batch(), get_current_rate(), get_next_batch(), get_paths(), network::h, network::input, network::inputs, load_args::labels, network::layers, network::learning_rate, list_to_array(), load_data_in_thread(), load_network(), load_thread(), load_args::m, network::max_batches, network::momentum, network::n, load_args::n, layer::out_c, network::output, network::outputs, layer::outputs, load_args::paths, rand_normal(), save_weights(), sec(), network::seen, show_image(), list::size, network::subdivisions, load_args::threads, network::train, train_network(), network::truth, network::truths, load_args::type, matrix::vals, network::w, data::X, and data::y.
Referenced by run_lsd().
 {
 #ifdef GPU
     //char *train_images = "/home/pjreddie/data/coco/train1.txt";
     //char *train_images = "/home/pjreddie/data/coco/trainvalno5k.txt";
     //char *train_images = "/home/pjreddie/data/imagenet/imagenet1k.train.list";
     //char *train_images = "data/64.txt";
     //char *train_images = "data/alp.txt";
     //char *train_images = "data/cifar.txt";
     char *backup_directory = "/home/pjreddie/backup/";
     srand(time(0));
     char *base = basecfg(cfg);
     char *abase = basecfg(acfg);
     printf("%s\n", base);
     network gnet = load_network(cfg, weight, clear);
     network anet = load_network(acfg, aweight, clear);
     float orig_rate = anet.learning_rate;
     int start = 0;
     int i, j, k;
     layer imlayer = {0};
     for (i = 0; i < gnet.n; ++i) {
         if (gnet.layers[i].out_c == 3) {
             imlayer = gnet.layers[i];
             break;
         }
     }
     printf("Learning Rate: %g, Momentum: %g, Decay: %g\n", gnet.learning_rate, gnet.momentum, gnet.decay);
     int imgs = gnet.batch*gnet.subdivisions;
     i = *gnet.seen/imgs;
     data train, buffer;
     list *plist = get_paths(train_images);
     //int N = plist->size;
     char **paths = (char **)list_to_array(plist);
     load_args args= get_base_args(anet);
     args.paths = paths;
     args.n = imgs;
     args.m = plist->size;
     args.d = &buffer;
     args.type = CLASSIFICATION_DATA;
     args.threads=16;
     args.classes = 1;
     char *ls[2] = {"imagenet", "zzzzzzzz"};
     args.labels = ls;
     pthread_t load_thread = load_data_in_thread(args);
     clock_t time;
     gnet.train = 1;
     anet.train = 1;
     int x_size = gnet.inputs*gnet.batch;
     int y_size = gnet.truths*gnet.batch;
     float *imerror = cuda_make_array(0, y_size);
     int ay_size = anet.truths*anet.batch;
     float aloss_avg = -1;
     //data generated = copy_data(train);
     while (get_current_batch(gnet) < gnet.max_batches) {
     start += 1;
         i += 1;
         time=clock();
         pthread_join(load_thread, 0);
         train = buffer;
         //translate_data_rows(train, -.5);
         //scale_data_rows(train, 2);
         load_thread = load_data_in_thread(args);
         printf("Loaded: %lf seconds\n", sec(clock()-time));
         data gen = copy_data(train);
         for (j = 0; j < imgs; ++j) {
             train.y.vals[j][0] = .95;
             gen.y.vals[j][0] = .05;
         }
         time=clock();
         for(j = 0; j < gnet.subdivisions; ++j){
             get_next_batch(train, gnet.batch, j*gnet.batch, gnet.truth, 0);
             int z;
             for(z = 0; z < x_size; ++z){
                 gnet.input[z] = rand_normal();
             }
             cuda_push_array(gnet.input_gpu, gnet.input, x_size);
             cuda_push_array(gnet.truth_gpu, gnet.truth, y_size);
             *gnet.seen += gnet.batch;
             forward_network_gpu(gnet);
             fill_ongpu(imlayer.outputs*imlayer.batch, 0, imerror, 1);
             fill_ongpu(anet.truths*anet.batch, .95, anet.truth_gpu, 1);
             copy_ongpu(anet.inputs*anet.batch, imlayer.output_gpu, 1, anet.input_gpu, 1);
             anet.delta_gpu = imerror;
             forward_network_gpu(anet);
             backward_network_gpu(anet);
             float genaloss = *anet.cost / anet.batch;
             printf("%f\n", genaloss);
             scal_ongpu(imlayer.outputs*imlayer.batch, 1, imerror, 1);
             scal_ongpu(imlayer.outputs*imlayer.batch, .00, gnet.layers[gnet.n-1].delta_gpu, 1);
             printf("realness %f\n", cuda_mag_array(imerror, imlayer.outputs*imlayer.batch));
             printf("features %f\n", cuda_mag_array(gnet.layers[gnet.n-1].delta_gpu, imlayer.outputs*imlayer.batch));
             axpy_ongpu(imlayer.outputs*imlayer.batch, 1, imerror, 1, gnet.layers[gnet.n-1].delta_gpu, 1);
             backward_network_gpu(gnet);
             for(k = 0; k < gnet.batch; ++k){
                 int index = j*gnet.batch + k;
                 copy_cpu(gnet.outputs, gnet.output + k*gnet.outputs, 1, gen.X.vals[index], 1);
             }
         }
         harmless_update_network_gpu(anet);
         data merge = concat_data(train, gen);
         //randomize_data(merge);
         float aloss = train_network(anet, merge);
         //translate_image(im, 1);
         //scale_image(im, .5);
         //translate_image(im2, 1);
         //scale_image(im2, .5);
             #ifdef OPENCV
         if(display){
             image im = float_to_image(anet.w, anet.h, anet.c, gen.X.vals[0]);
             image im2 = float_to_image(anet.w, anet.h, anet.c, train.X.vals[0]);
             show_image(im, "gen");
             show_image(im2, "train");
             cvWaitKey(50);
         }
         #endif
 /*
         if(aloss < .1){
             anet.learning_rate = 0;
         } else if (aloss > .3){
             anet.learning_rate = orig_rate;
         }
         */
         update_network_gpu(gnet);
         free_data(merge);
         free_data(train);
         free_data(gen);
         if (aloss_avg < 0) aloss_avg = aloss;
         aloss_avg = aloss_avg*.9 + aloss*.1;
         printf("%d: adv: %f | adv_avg: %f, %f rate, %lf seconds, %d images\n", i, aloss, aloss_avg, get_current_rate(gnet), sec(clock()-time), i*imgs);
         if(i%10000==0){
             char buff[256];
             sprintf(buff, "%s/%s_%d.weights", backup_directory, base, i);
             save_weights(gnet, buff);
             sprintf(buff, "%s/%s_%d.weights", backup_directory, abase, i);
             save_weights(anet, buff);
         }
         if(i%1000==0){
             char buff[256];
             sprintf(buff, "%s/%s.backup", backup_directory, base);
             save_weights(gnet, buff);
             sprintf(buff, "%s/%s.backup", backup_directory, abase);
             save_weights(anet, buff);
         }
     }
     char buff[256];
     sprintf(buff, "%s/%s_final.weights", backup_directory, base);
     save_weights(gnet, buff);
 #endif
 }