Darknet: col2im.c File Reference
col2im.c File Reference
#include <stdio.h>
#include <math.h>
Functions
void col2im_add_pixel (float *im, int height, int width, int channels, int row, int col, int channel, int pad, float val)
void col2im_cpu (float *data_col, int channels, int height, int width, int ksize, int stride, int pad, float *data_im)
Function Documentation
col2im_add_pixel()
void col2im_add_pixel (float * im, int height, int width, int channels, int row, int col, int channel, int pad, float val)
Definition at line 3 of file col2im.c.
Referenced by col2im_cpu().
 {
     row -= pad;
     col -= pad;
     if (row < 0 || col < 0 ||
         row >= height || col >= width) return;
     im[col + width*(row + height*channel)] += val;
 }
col2im_cpu()
void col2im_cpu (float * data_col, int channels, int height, int width, int ksize, int stride, int pad, float * data_im)
Definition at line 14 of file col2im.c.
References col2im_add_pixel().
Referenced by backward_convolutional_layer(), backward_local_layer(), and forward_deconvolutional_layer().
 {
     int c,h,w;
     int height_col = (height + 2*pad - ksize) / stride + 1;
     int width_col = (width + 2*pad - ksize) / stride + 1;
     int channels_col = channels * ksize * ksize;
     for (c = 0; c < channels_col; ++c) {
         int w_offset = c % ksize;
         int h_offset = (c / ksize) % ksize;
         int c_im = c / ksize / ksize;
         for (h = 0; h < height_col; ++h) {
             for (w = 0; w < width_col; ++w) {
                 int im_row = h_offset + h * stride;
                 int im_col = w_offset + w * stride;
                 int col_index = (c * height_col + h) * width_col + w;
                 double val = data_col[col_index];
                 col2im_add_pixel(data_im, height, width, channels,
                         im_row, im_col, c_im, pad, val);
             }
         }
     }
 }