Darknet: classifier.h File Reference
classifier.h File Reference
Functions
list * read_data_cfg (char *filename)
Function Documentation
read_data_cfg()
list* read_data_cfg (char * filename)
Definition at line 7 of file option_list.c.
Referenced by demo_classifier(), gun_classifier(), label_classifier(), predict_classifier(), run_detector(), test_classifier(), test_detector(), threat_classifier(), train_classifier(), train_detector(), train_regressor(), try_classifier(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_detector(), and validate_detector_flip().
 {
     FILE *file = fopen(filename, "r");
     if(file == 0) file_error(filename);
     char *line;
     int nu = 0;
     list *options = make_list();
     while((line=fgetl(file)) != 0){
         ++ nu;
         strip(line);
         switch(line[0]){
             case '\0':
             case '#':
             case ';':
                 free(line);
                 break;
             default:
                 if(!read_option(line, options)){
                     fprintf(stderr, "Config file error line %d, could parse: %s\n", nu, line);
                     free(line);
                 }
                 break;
         }
     }
     fclose(file);
     return options;
 }