Darknet: im2col.h File Reference
im2col.h File Reference
Functions
void im2col_cpu (float *data_im, int channels, int height, int width, int ksize, int stride, int pad, float *data_col)
Function Documentation
im2col_cpu()
void im2col_cpu (float * data_im, int channels, int height, int width, int ksize, int stride, int pad, float * data_col)
Definition at line 16 of file im2col.c.
References im2col_get_pixel().
Referenced by backward_convolutional_layer(), backward_deconvolutional_layer(), backward_local_layer(), forward_convolutional_layer(), and forward_local_layer().
 {
     int c,h,w;
     int height_col = (height + 2*pad - ksize) / stride + 1;
     int width_col = (width + 2*pad - ksize) / stride + 1;
     int channels_col = channels * ksize * ksize;
     for (c = 0; c < channels_col; ++c) {
         int w_offset = c % ksize;
         int h_offset = (c / ksize) % ksize;
         int c_im = c / ksize / ksize;
         for (h = 0; h < height_col; ++h) {
             for (w = 0; w < width_col; ++w) {
                 int im_row = h_offset + h * stride;
                 int im_col = w_offset + w * stride;
                 int col_index = (c * height_col + h) * width_col + w;
                 data_col[col_index] = im2col_get_pixel(data_im, height, width, channels,
                         im_row, im_col, c_im, pad);
             }
         }
     }
 }