Darknet: parser.c File Reference
parser.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "activation_layer.h"
#include "activations.h"
#include "assert.h"
#include "avgpool_layer.h"
#include "batchnorm_layer.h"
#include "blas.h"
#include "connected_layer.h"
#include "deconvolutional_layer.h"
#include "convolutional_layer.h"
#include "cost_layer.h"
#include "crnn_layer.h"
#include "crop_layer.h"
#include "detection_layer.h"
#include "dropout_layer.h"
#include "gru_layer.h"
#include "list.h"
#include "local_layer.h"
#include "maxpool_layer.h"
#include "normalization_layer.h"
#include "option_list.h"
#include "parser.h"
#include "region_layer.h"
#include "reorg_layer.h"
#include "rnn_layer.h"
#include "route_layer.h"
#include "shortcut_layer.h"
#include "softmax_layer.h"
#include "utils.h"
Data Structures
struct section
struct size_params
Typedefs
typedef struct size_params size_params
Functions
list * read_cfg (char *filename)
LAYER_TYPE string_to_layer_type (char *type)
void free_section (section *s)
void parse_data (char *data, float *a, int n)
local_layer parse_local (list *options, size_params params)
layer parse_deconvolutional (list *options, size_params params)
convolutional_layer parse_convolutional (list *options, size_params params)
layer parse_crnn (list *options, size_params params)
layer parse_rnn (list *options, size_params params)
layer parse_gru (list *options, size_params params)
connected_layer parse_connected (list *options, size_params params)
softmax_layer parse_softmax (list *options, size_params params)
layer parse_region (list *options, size_params params)
detection_layer parse_detection (list *options, size_params params)
cost_layer parse_cost (list *options, size_params params)
crop_layer parse_crop (list *options, size_params params)
layer parse_reorg (list *options, size_params params)
maxpool_layer parse_maxpool (list *options, size_params params)
avgpool_layer parse_avgpool (list *options, size_params params)
dropout_layer parse_dropout (list *options, size_params params)
layer parse_normalization (list *options, size_params params)
layer parse_batchnorm (list *options, size_params params)
layer parse_shortcut (list *options, size_params params, network net)
layer parse_activation (list *options, size_params params)
route_layer parse_route (list *options, size_params params, network net)
learning_rate_policy get_policy (char *s)
void parse_net_options (list *options, network *net)
int is_network (section *s)
network parse_network_cfg (char *filename)
void save_convolutional_weights_binary (layer l, FILE *fp)
void save_convolutional_weights (layer l, FILE *fp)
void save_batchnorm_weights (layer l, FILE *fp)
void save_connected_weights (layer l, FILE *fp)
void save_weights_upto (network net, char *filename, int cutoff)
void save_weights (network net, char *filename)
void transpose_matrix (float *a, int rows, int cols)
void load_connected_weights (layer l, FILE *fp, int transpose)
void load_batchnorm_weights (layer l, FILE *fp)
void load_convolutional_weights_binary (layer l, FILE *fp)
void load_convolutional_weights (layer l, FILE *fp)
void load_weights_upto (network *net, char *filename, int start, int cutoff)
void load_weights (network *net, char *filename)
Typedef Documentation
size_params
typedef struct size_params size_params
Function Documentation
free_section()
void free_section (section * s)
Definition at line 77 of file parser.c.
References list::front, kvp::key, node::next, section::options, section::type, and node::val.
Referenced by parse_network_cfg().
 {
     free(s->type);
     node *n = s->options->front;
     while(n){
         kvp *pair = (kvp *)n->val;
         free(pair->key);
         free(pair);
         node *next = n->next;
         free(n);
         n = next;
     }
     free(s->options);
     free(s);
 }
get_policy()
learning_rate_policy get_policy (char * s)
Definition at line 522 of file parser.c.
References CONSTANT, EXP, POLY, RANDOM, SIG, STEP, and STEPS.
Referenced by parse_net_options().
 {
     if (strcmp(s, "random")==0) return RANDOM;
     if (strcmp(s, "poly")==0) return POLY;
     if (strcmp(s, "constant")==0) return CONSTANT;
     if (strcmp(s, "step")==0) return STEP;
     if (strcmp(s, "exp")==0) return EXP;
     if (strcmp(s, "sigmoid")==0) return SIG;
     if (strcmp(s, "steps")==0) return STEPS;
     fprintf(stderr, "Couldn't find policy %s, going with constant\n", s);
     return CONSTANT;
 }
is_network()
int is_network (section * s)
Definition at line 612 of file parser.c.
References section::type.
Referenced by parse_network_cfg().
 {
     return (strcmp(s->type, "[net]")==0
             || strcmp(s->type, "[network]")==0);
 }
load_batchnorm_weights()
void load_batchnorm_weights (layer l, FILE * fp)
Definition at line 971 of file parser.c.
References layer::c, gpu_index, layer::rolling_mean, layer::rolling_variance, and layer::scales.
Referenced by load_weights_upto().
 {
     fread(l.scales, sizeof(float), l.c, fp);
     fread(l.rolling_mean, sizeof(float), l.c, fp);
     fread(l.rolling_variance, sizeof(float), l.c, fp);
 #ifdef GPU
     if(gpu_index >= 0){
         push_batchnorm_layer(l);
     }
 #endif
 }
load_connected_weights()
void load_connected_weights (layer l, FILE * fp, int transpose)
Definition at line 947 of file parser.c.
References layer::batch_normalize, layer::biases, layer::dontloadscales, gpu_index, layer::inputs, layer::outputs, layer::rolling_mean, layer::rolling_variance, layer::scales, transpose_matrix(), and layer::weights.
Referenced by load_weights_upto().
 {
     fread(l.biases, sizeof(float), l.outputs, fp);
     fread(l.weights, sizeof(float), l.outputs*l.inputs, fp);
     if(transpose){
         transpose_matrix(l.weights, l.inputs, l.outputs);
     }
     //printf("Biases: %f mean %f variance\n", mean_array(l.biases, l.outputs), variance_array(l.biases, l.outputs));
     //printf("Weights: %f mean %f variance\n", mean_array(l.weights, l.outputs*l.inputs), variance_array(l.weights, l.outputs*l.inputs));
     if (l.batch_normalize && (!l.dontloadscales)){
         fread(l.scales, sizeof(float), l.outputs, fp);
         fread(l.rolling_mean, sizeof(float), l.outputs, fp);
         fread(l.rolling_variance, sizeof(float), l.outputs, fp);
         //printf("Scales: %f mean %f variance\n", mean_array(l.scales, l.outputs), variance_array(l.scales, l.outputs));
         //printf("rolling_mean: %f mean %f variance\n", mean_array(l.rolling_mean, l.outputs), variance_array(l.rolling_mean, l.outputs));
         //printf("rolling_variance: %f mean %f variance\n", mean_array(l.rolling_variance, l.outputs), variance_array(l.rolling_variance, l.outputs));
     }
 #ifdef GPU
     if(gpu_index >= 0){
         push_connected_layer(l);
     }
 #endif
 }
load_convolutional_weights()
void load_convolutional_weights (layer l, FILE * fp)
Definition at line 1013 of file parser.c.
References layer::adam, layer::batch_normalize, layer::biases, layer::binary, layer::c, layer::dontloadscales, fill_cpu(), layer::flipped, gpu_index, layer::n, layer::rolling_mean, layer::rolling_variance, layer::scales, layer::size, transpose_matrix(), and layer::weights.
Referenced by load_weights_upto().
 {
     if(l.binary){
         //load_convolutional_weights_binary(l, fp);
         //return;
     }
     int num = l.n*l.c*l.size*l.size;
     fread(l.biases, sizeof(float), l.n, fp);
     if (l.batch_normalize && (!l.dontloadscales)){
         fread(l.scales, sizeof(float), l.n, fp);
         fread(l.rolling_mean, sizeof(float), l.n, fp);
         fread(l.rolling_variance, sizeof(float), l.n, fp);
         if(0){
             int i;
             for(i = 0; i < l.n; ++i){
                 printf("%g, ", l.rolling_mean[i]);
             }
             printf("\n");
             for(i = 0; i < l.n; ++i){
                 printf("%g, ", l.rolling_variance[i]);
             }
             printf("\n");
         }
         if(0){
             fill_cpu(l.n, 0, l.rolling_mean, 1);
             fill_cpu(l.n, 0, l.rolling_variance, 1);
         }
     }
     fread(l.weights, sizeof(float), num, fp);
     if(l.adam){
         //fread(l.m, sizeof(float), num, fp);
         //fread(l.v, sizeof(float), num, fp);
     }
     //if(l.c == 3) scal_cpu(num, 1./256, l.weights, 1);
     if (l.flipped) {
         transpose_matrix(l.weights, l.c*l.size*l.size, l.n);
     }
     //if (l.binary) binarize_weights(l.weights, l.n, l.c*l.size*l.size, l.weights);
 #ifdef GPU
     if(gpu_index >= 0){
         push_convolutional_layer(l);
     }
 #endif
 }
load_convolutional_weights_binary()
void load_convolutional_weights_binary (layer l, FILE * fp)
Definition at line 983 of file parser.c.
References layer::batch_normalize, layer::biases, layer::c, size_params::c, layer::dontloadscales, gpu_index, size_params::index, layer::n, layer::rolling_mean, layer::rolling_variance, layer::scales, layer::size, and layer::weights.
 {
     fread(l.biases, sizeof(float), l.n, fp);
     if (l.batch_normalize && (!l.dontloadscales)){
         fread(l.scales, sizeof(float), l.n, fp);
         fread(l.rolling_mean, sizeof(float), l.n, fp);
         fread(l.rolling_variance, sizeof(float), l.n, fp);
     }
     int size = l.c*l.size*l.size;
     int i, j, k;
     for(i = 0; i < l.n; ++i){
         float mean = 0;
         fread(&mean, sizeof(float), 1, fp);
         for(j = 0; j < size/8; ++j){
             int index = i*size + j*8;
             unsigned char c = 0;
             fread(&c, sizeof(char), 1, fp);
             for(k = 0; k < 8; ++k){
                 if (j*8 + k >= size) break;
                 l.weights[index + k] = (c & 1<<k) ? mean : -mean;
             }
         }
     }
 #ifdef GPU
     if(gpu_index >= 0){
         push_convolutional_layer(l);
     }
 #endif
 }
load_weights()
void load_weights (network * net, char * filename)
Definition at line 1127 of file parser.c.
References load_weights_upto(), and network::n.
Referenced by average(), BattleRoyaleWithCheese(), demo_art(), demo_classifier(), demo_regressor(), denormalize_net(), engine_go(), gun_classifier(), label_classifier(), load_network(), normalize_net(), oneoff(), predict_classifier(), predict_regressor(), rescale_net(), reset_normalize_net(), rgbgr_net(), run_nightmare(), self_go(), SortMaster3000(), statistics_net(), test_captcha(), test_char_rnn(), test_cifar(), test_cifar_csv(), test_cifar_csvtrain(), test_cifar_multi(), test_classifier(), test_coco(), test_dcgan(), test_detector(), test_dice(), test_go(), test_lsd(), test_super(), test_tactic_rnn(), test_tag(), test_voxel(), test_writing(), test_yolo(), threat_classifier(), train_captcha(), train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_compare(), train_detector(), train_dice(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), try_classifier(), valid_captcha(), valid_char_rnn(), valid_go(), valid_tactic_rnn(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_compare(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_dice(), validate_yolo(), validate_yolo_recall(), vec_char_rnn(), and visualize().
 {
     load_weights_upto(net, filename, 0, net->n);
 }
load_weights_upto()
void load_weights_upto (network * net, char * filename, int start, int cutoff)
Definition at line 1059 of file parser.c.
References BATCHNORM, layer::biases, layer::c, CONNECTED, CONVOLUTIONAL, CRNN, DECONVOLUTIONAL, layer::dontload, file_error(), gpu_index, network::gpu_index, GRU, layer::input_h_layer, layer::input_layer, layer::input_r_layer, layer::input_z_layer, network::layers, load_batchnorm_weights(), load_connected_weights(), load_convolutional_weights(), LOCAL, network::n, layer::n, layer::out_h, layer::out_w, layer::output_layer, layer::outputs, RNN, network::seen, layer::self_layer, layer::size, layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, layer::type, and layer::weights.
Referenced by load_weights(), oneoff2(), and partial().
 {
 #ifdef GPU
     if(net->gpu_index >= 0){
         cuda_set_device(net->gpu_index);
     }
 #endif
     fprintf(stderr, "Loading weights from %s...", filename);
     fflush(stdout);
     FILE *fp = fopen(filename, "rb");
     if(!fp) file_error(filename);
     int major;
     int minor;
     int revision;
     fread(&major, sizeof(int), 1, fp);
     fread(&minor, sizeof(int), 1, fp);
     fread(&revision, sizeof(int), 1, fp);
     fread(net->seen, sizeof(int), 1, fp);
     int transpose = (major > 1000) || (minor > 1000);
     int i;
     for(i = start; i < net->n && i < cutoff; ++i){
         layer l = net->layers[i];
         if (l.dontload) continue;
         if(l.type == CONVOLUTIONAL || l.type == DECONVOLUTIONAL){
             load_convolutional_weights(l, fp);
         }
         if(l.type == CONNECTED){
             load_connected_weights(l, fp, transpose);
         }
         if(l.type == BATCHNORM){
             load_batchnorm_weights(l, fp);
         }
         if(l.type == CRNN){
             load_convolutional_weights(*(l.input_layer), fp);
             load_convolutional_weights(*(l.self_layer), fp);
             load_convolutional_weights(*(l.output_layer), fp);
         }
         if(l.type == RNN){
             load_connected_weights(*(l.input_layer), fp, transpose);
             load_connected_weights(*(l.self_layer), fp, transpose);
             load_connected_weights(*(l.output_layer), fp, transpose);
         }
         if(l.type == GRU){
             load_connected_weights(*(l.input_z_layer), fp, transpose);
             load_connected_weights(*(l.input_r_layer), fp, transpose);
             load_connected_weights(*(l.input_h_layer), fp, transpose);
             load_connected_weights(*(l.state_z_layer), fp, transpose);
             load_connected_weights(*(l.state_r_layer), fp, transpose);
             load_connected_weights(*(l.state_h_layer), fp, transpose);
         }
         if(l.type == LOCAL){
             int locations = l.out_w*l.out_h;
             int size = l.size*l.size*l.c*l.n*locations;
             fread(l.biases, sizeof(float), l.outputs, fp);
             fread(l.weights, sizeof(float), size, fp);
 #ifdef GPU
             if(gpu_index >= 0){
                 push_local_layer(l);
             }
 #endif
         }
     }
     fprintf(stderr, "Done!\n");
     fclose(fp);
 }
parse_activation()
layer parse_activation (list * options, size_params params)
Definition at line 464 of file parser.c.
References size_params::batch, layer::c, size_params::c, get_activation(), layer::h, size_params::h, size_params::inputs, make_activation_layer(), option_find_str(), layer::out_c, layer::out_h, layer::out_w, layer::w, and size_params::w.
Referenced by parse_network_cfg().
 {
     char *activation_s = option_find_str(options, "activation", "linear");
     ACTIVATION activation = get_activation(activation_s);
     layer l = make_activation_layer(params.batch, params.inputs, activation);
     l.out_h = params.h;
     l.out_w = params.w;
     l.out_c = params.c;
     l.h = params.h;
     l.w = params.w;
     l.c = params.c;
     return l;
 }
parse_avgpool()
avgpool_layer parse_avgpool (list * options, size_params params)
Definition at line 407 of file parser.c.
References size_params::batch, size_params::c, error(), size_params::h, make_avgpool_layer(), and size_params::w.
Referenced by parse_network_cfg().
 {
     int batch,w,h,c;
     w = params.w;
     h = params.h;
     c = params.c;
     batch=params.batch;
     if(!(h && w && c)) error("Layer before avgpool layer must output image.");
     avgpool_layer layer = make_avgpool_layer(batch,w,h,c);
     return layer;
 }
parse_batchnorm()
layer parse_batchnorm (list * options, size_params params)
Definition at line 440 of file parser.c.
References size_params::batch, size_params::c, size_params::h, make_batchnorm_layer(), and size_params::w.
Referenced by parse_network_cfg().
 {
     layer l = make_batchnorm_layer(params.batch, params.w, params.h, params.c);
     return l;
 }
parse_connected()
connected_layer parse_connected (list * options, size_params params)
Definition at line 242 of file parser.c.
References size_params::batch, get_activation(), size_params::inputs, make_connected_layer(), option_find_int(), option_find_int_quiet(), and option_find_str().
Referenced by parse_network_cfg().
 {
     int output = option_find_int(options, "output",1);
     char *activation_s = option_find_str(options, "activation", "logistic");
     ACTIVATION activation = get_activation(activation_s);
     int batch_normalize = option_find_int_quiet(options, "batch_normalize", 0);
     connected_layer layer = make_connected_layer(params.batch, params.inputs, output, activation, batch_normalize);
     return layer;
 }
parse_convolutional()
convolutional_layer parse_convolutional (list * options, size_params params)
Definition at line 167 of file parser.c.
References network::adam, network::B1, layer::B1, network::B2, layer::B2, size_params::batch, size_params::c, layer::dot, network::eps, layer::eps, error(), layer::flipped, get_activation(), size_params::h, make_convolutional_layer(), size_params::net, option_find_float_quiet(), option_find_int(), option_find_int_quiet(), option_find_str(), and size_params::w.
Referenced by parse_network_cfg().
 {
     int n = option_find_int(options, "filters",1);
     int size = option_find_int(options, "size",1);
     int stride = option_find_int(options, "stride",1);
     int pad = option_find_int_quiet(options, "pad",0);
     int padding = option_find_int_quiet(options, "padding",0);
     if(pad) padding = size/2;
     char *activation_s = option_find_str(options, "activation", "logistic");
     ACTIVATION activation = get_activation(activation_s);
     int batch,h,w,c;
     h = params.h;
     w = params.w;
     c = params.c;
     batch=params.batch;
     if(!(h && w && c)) error("Layer before convolutional layer must output image.");
     int batch_normalize = option_find_int_quiet(options, "batch_normalize", 0);
     int binary = option_find_int_quiet(options, "binary", 0);
     int xnor = option_find_int_quiet(options, "xnor", 0);
     convolutional_layer layer = make_convolutional_layer(batch,h,w,c,n,size,stride,padding,activation, batch_normalize, binary, xnor, params.net.adam);
     layer.flipped = option_find_int_quiet(options, "flipped", 0);
     layer.dot = option_find_float_quiet(options, "dot", 0);
     if(params.net.adam){
         layer.B1 = params.net.B1;
         layer.B2 = params.net.B2;
         layer.eps = params.net.eps;
     }
     return layer;
 }
parse_cost()
cost_layer parse_cost (list * options, size_params params)
Definition at line 337 of file parser.c.
References size_params::batch, get_cost_type(), size_params::inputs, make_cost_layer(), option_find_float_quiet(), option_find_str(), layer::ratio, and layer::thresh.
Referenced by parse_network_cfg().
 {
     char *type_s = option_find_str(options, "type", "sse");
     COST_TYPE type = get_cost_type(type_s);
     float scale = option_find_float_quiet(options, "scale",1);
     cost_layer layer = make_cost_layer(params.batch, params.inputs, type, scale);
     layer.ratio =  option_find_float_quiet(options, "ratio",0);
     layer.thresh =  option_find_float_quiet(options, "thresh",0);
     return layer;
 }
parse_crnn()
layer parse_crnn (list * options, size_params params)
Definition at line 201 of file parser.c.
References size_params::batch, size_params::c, get_activation(), size_params::h, make_crnn_layer(), option_find_int(), option_find_int_quiet(), option_find_str(), layer::shortcut, size_params::time_steps, and size_params::w.
Referenced by parse_network_cfg().
 {
     int output_filters = option_find_int(options, "output_filters",1);
     int hidden_filters = option_find_int(options, "hidden_filters",1);
     char *activation_s = option_find_str(options, "activation", "logistic");
     ACTIVATION activation = get_activation(activation_s);
     int batch_normalize = option_find_int_quiet(options, "batch_normalize", 0);
     layer l = make_crnn_layer(params.batch, params.w, params.h, params.c, hidden_filters, output_filters, params.time_steps, activation, batch_normalize);
     l.shortcut = option_find_int_quiet(options, "shortcut", 0);
     return l;
 }
parse_crop()
crop_layer parse_crop (list * options, size_params params)
Definition at line 348 of file parser.c.
References size_params::batch, size_params::c, error(), size_params::h, make_crop_layer(), layer::noadjust, option_find_float(), option_find_int(), option_find_int_quiet(), layer::shift, and size_params::w.
Referenced by parse_network_cfg().
 {
     int crop_height = option_find_int(options, "crop_height",1);
     int crop_width = option_find_int(options, "crop_width",1);
     int flip = option_find_int(options, "flip",0);
     float angle = option_find_float(options, "angle",0);
     float saturation = option_find_float(options, "saturation",1);
     float exposure = option_find_float(options, "exposure",1);
     int batch,h,w,c;
     h = params.h;
     w = params.w;
     c = params.c;
     batch=params.batch;
     if(!(h && w && c)) error("Layer before crop layer must output image.");
     int noadjust = option_find_int_quiet(options, "noadjust",0);
     crop_layer l = make_crop_layer(batch,h,w,c,crop_height,crop_width,flip, angle, saturation, exposure);
     l.shift = option_find_float(options, "shift", 0);
     l.noadjust = noadjust;
     return l;
 }
parse_data()
void parse_data (char * data, float * a, int n)
Definition at line 93 of file parser.c.
 {
     int i;
     if(!data) return;
     char *curr = data;
     char *next = data;
     int done = 0;
     for(i = 0; i < n && !done; ++i){
         while(*++next !='\0' && *next != ',');
         if(*next == '\0') done = 1;
         *next = '\0';
         sscanf(curr, "%g", &a[i]);
         curr = next+1;
     }
 }
parse_deconvolutional()
layer parse_deconvolutional (list * options, size_params params)
Definition at line 141 of file parser.c.
References network::adam, size_params::batch, size_params::c, error(), get_activation(), size_params::h, make_deconvolutional_layer(), size_params::net, option_find_int(), option_find_int_quiet(), option_find_str(), and size_params::w.
Referenced by parse_network_cfg().
 {
     int n = option_find_int(options, "filters",1);
     int size = option_find_int(options, "size",1);
     int stride = option_find_int(options, "stride",1);
     char *activation_s = option_find_str(options, "activation", "logistic");
     ACTIVATION activation = get_activation(activation_s);
     int batch,h,w,c;
     h = params.h;
     w = params.w;
     c = params.c;
     batch=params.batch;
     if(!(h && w && c)) error("Layer before deconvolutional layer must output image.");
     int batch_normalize = option_find_int_quiet(options, "batch_normalize", 0);
     int pad = option_find_int_quiet(options, "pad",0);
     int padding = option_find_int_quiet(options, "padding",0);
     if(pad) padding = size/2;
     layer l = make_deconvolutional_layer(batch,h,w,c,n,size,stride,padding, activation, batch_normalize, params.net.adam);
     return l;
 }
parse_detection()
detection_layer parse_detection (list * options, size_params params)
Definition at line 313 of file parser.c.
References size_params::batch, layer::class_scale, layer::coord_scale, layer::forced, size_params::inputs, layer::jitter, make_detection_layer(), layer::max_boxes, layer::noobject_scale, layer::object_scale, option_find_float(), option_find_int(), option_find_int_quiet(), layer::random, layer::reorg, layer::softmax, and layer::sqrt.
Referenced by parse_network_cfg().
 {
     int coords = option_find_int(options, "coords", 1);
     int classes = option_find_int(options, "classes", 1);
     int rescore = option_find_int(options, "rescore", 0);
     int num = option_find_int(options, "num", 1);
     int side = option_find_int(options, "side", 7);
     detection_layer layer = make_detection_layer(params.batch, params.inputs, num, side, classes, coords, rescore);
     layer.softmax = option_find_int(options, "softmax", 0);
     layer.sqrt = option_find_int(options, "sqrt", 0);
     layer.max_boxes = option_find_int_quiet(options, "max",30);
     layer.coord_scale = option_find_float(options, "coord_scale", 1);
     layer.forced = option_find_int(options, "forced", 0);
     layer.object_scale = option_find_float(options, "object_scale", 1);
     layer.noobject_scale = option_find_float(options, "noobject_scale", 1);
     layer.class_scale = option_find_float(options, "class_scale", 1);
     layer.jitter = option_find_float(options, "jitter", .2);
     layer.random = option_find_int_quiet(options, "random", 0);
     layer.reorg = option_find_int_quiet(options, "reorg", 0);
     return layer;
 }
parse_dropout()
dropout_layer parse_dropout (list * options, size_params params)
Definition at line 420 of file parser.c.
References size_params::batch, size_params::c, size_params::h, size_params::inputs, make_dropout_layer(), option_find_float(), layer::out_c, layer::out_h, layer::out_w, and size_params::w.
Referenced by parse_network_cfg().
 {
     float probability = option_find_float(options, "probability", .5);
     dropout_layer layer = make_dropout_layer(params.batch, params.inputs, probability);
     layer.out_w = params.w;
     layer.out_h = params.h;
     layer.out_c = params.c;
     return layer;
 }
parse_gru()
layer parse_gru (list * options, size_params params)
Definition at line 232 of file parser.c.
References size_params::batch, size_params::inputs, make_gru_layer(), option_find_int(), option_find_int_quiet(), and size_params::time_steps.
Referenced by parse_network_cfg().
 {
     int output = option_find_int(options, "output",1);
     int batch_normalize = option_find_int_quiet(options, "batch_normalize", 0);
     layer l = make_gru_layer(params.batch, params.inputs, output, params.time_steps, batch_normalize);
     return l;
 }
parse_local()
local_layer parse_local (list * options, size_params params)
Definition at line 120 of file parser.c.
References size_params::batch, size_params::c, error(), get_activation(), size_params::h, make_local_layer(), option_find_int(), option_find_str(), and size_params::w.
Referenced by parse_network_cfg().
 {
     int n = option_find_int(options, "filters",1);
     int size = option_find_int(options, "size",1);
     int stride = option_find_int(options, "stride",1);
     int pad = option_find_int(options, "pad",0);
     char *activation_s = option_find_str(options, "activation", "logistic");
     ACTIVATION activation = get_activation(activation_s);
     int batch,h,w,c;
     h = params.h;
     w = params.w;
     c = params.c;
     batch=params.batch;
     if(!(h && w && c)) error("Layer before local layer must output image.");
     local_layer layer = make_local_layer(batch,h,w,c,n,size,stride,pad,activation);
     return layer;
 }
parse_maxpool()
maxpool_layer parse_maxpool (list * options, size_params params)
Definition at line 390 of file parser.c.
References size_params::batch, size_params::c, error(), size_params::h, make_maxpool_layer(), option_find_int(), option_find_int_quiet(), and size_params::w.
Referenced by parse_network_cfg().
 {
     int stride = option_find_int(options, "stride",1);
     int size = option_find_int(options, "size",stride);
     int padding = option_find_int_quiet(options, "padding", (size-1)/2);
     int batch,h,w,c;
     h = params.h;
     w = params.w;
     c = params.c;
     batch=params.batch;
     if(!(h && w && c)) error("Layer before maxpool layer must output image.");
     maxpool_layer layer = make_maxpool_layer(batch,h,w,c,size,stride,padding);
     return layer;
 }
parse_net_options()
void parse_net_options (list * options, network * net)
Definition at line 535 of file parser.c.
References network::adam, network::angle, network::aspect, network::B1, network::B2, network::batch, network::burn_in, network::c, network::center, network::decay, network::eps, error(), EXP, network::exposure, network::gamma, get_policy(), network::h, network::hue, network::inputs, network::learning_rate, network::max_batches, network::max_crop, network::min_crop, network::momentum, network::notruth, network::num_steps, option_find(), option_find_float(), option_find_float_quiet(), option_find_int(), option_find_int_quiet(), option_find_str(), network::policy, POLY, network::power, RANDOM, network::saturation, network::scale, network::scales, SIG, STEP, network::step, STEPS, network::steps, network::subdivisions, network::time_steps, and network::w.
Referenced by parse_network_cfg().
 {
     net->batch = option_find_int(options, "batch",1);
     net->learning_rate = option_find_float(options, "learning_rate", .001);
     net->momentum = option_find_float(options, "momentum", .9);
     net->decay = option_find_float(options, "decay", .0001);
     int subdivs = option_find_int(options, "subdivisions",1);
     net->time_steps = option_find_int_quiet(options, "time_steps",1);
     net->notruth = option_find_int_quiet(options, "notruth",0);
     net->batch /= subdivs;
     net->batch *= net->time_steps;
     net->subdivisions = subdivs;
     net->adam = option_find_int_quiet(options, "adam", 0);
     if(net->adam){
         net->B1 = option_find_float(options, "B1", .9);
         net->B2 = option_find_float(options, "B2", .999);
         net->eps = option_find_float(options, "eps", .00000001);
     }
     net->h = option_find_int_quiet(options, "height",0);
     net->w = option_find_int_quiet(options, "width",0);
     net->c = option_find_int_quiet(options, "channels",0);
     net->inputs = option_find_int_quiet(options, "inputs", net->h * net->w * net->c);
     net->max_crop = option_find_int_quiet(options, "max_crop",net->w*2);
     net->min_crop = option_find_int_quiet(options, "min_crop",net->w);
     net->center = option_find_int_quiet(options, "center",0);
     net->angle = option_find_float_quiet(options, "angle", 0);
     net->aspect = option_find_float_quiet(options, "aspect", 1);
     net->saturation = option_find_float_quiet(options, "saturation", 1);
     net->exposure = option_find_float_quiet(options, "exposure", 1);
     net->hue = option_find_float_quiet(options, "hue", 0);
     if(!net->inputs && !(net->h && net->w && net->c)) error("No input parameters supplied");
     char *policy_s = option_find_str(options, "policy", "constant");
     net->policy = get_policy(policy_s);
     net->burn_in = option_find_int_quiet(options, "burn_in", 0);
     net->power = option_find_float_quiet(options, "power", 4);
     if(net->policy == STEP){
         net->step = option_find_int(options, "step", 1);
         net->scale = option_find_float(options, "scale", 1);
     } else if (net->policy == STEPS){
         char *l = option_find(options, "steps");
         char *p = option_find(options, "scales");
         if(!l || !p) error("STEPS policy must have steps and scales in cfg file");
         int len = strlen(l);
         int n = 1;
         int i;
         for(i = 0; i < len; ++i){
             if (l[i] == ',') ++n;
         }
         int *steps = calloc(n, sizeof(int));
         float *scales = calloc(n, sizeof(float));
         for(i = 0; i < n; ++i){
             int step    = atoi(l);
             float scale = atof(p);
             l = strchr(l, ',')+1;
             p = strchr(p, ',')+1;
             steps[i] = step;
             scales[i] = scale;
         }
         net->scales = scales;
         net->steps = steps;
         net->num_steps = n;
     } else if (net->policy == EXP){
         net->gamma = option_find_float(options, "gamma", 1);
     } else if (net->policy == SIG){
         net->gamma = option_find_float(options, "gamma", 1);
         net->step = option_find_int(options, "step", 1);
     } else if (net->policy == POLY || net->policy == RANDOM){
     }
     net->max_batches = option_find_int(options, "max_batches", 0);
 }
parse_network_cfg()
network parse_network_cfg (char * filename)
Definition at line 618 of file parser.c.
References ACTIVE, AVGPOOL, network::batch, size_params::batch, BATCHNORM, network::c, size_params::c, CONNECTED, CONVOLUTIONAL, COST, CRNN, CROP, DECONVOLUTIONAL, layer::delta, DETECTION, DROPOUT, error(), free_list(), free_section(), list::front, get_network_output_layer(), gpu_index, network::gpu_index, GRU, network::h, size_params::h, network::hierarchy, size_params::index, network::input, network::inputs, size_params::inputs, is_network(), network::layers, LOCAL, make_network(), MAXPOOL, network::n, size_params::net, node::next, NORMALIZATION, option_find_float_quiet(), option_find_int_quiet(), option_unused(), section::options, network::output, layer::output, network::outputs, layer::outputs, parse_activation(), parse_avgpool(), parse_batchnorm(), parse_connected(), parse_convolutional(), parse_cost(), parse_crnn(), parse_crop(), parse_deconvolutional(), parse_detection(), parse_dropout(), parse_gru(), parse_local(), parse_maxpool(), parse_net_options(), parse_normalization(), parse_region(), parse_reorg(), parse_rnn(), parse_route(), parse_shortcut(), parse_softmax(), read_cfg(), REGION, REORG, RNN, ROUTE, SHORTCUT, list::size, SOFTMAX, string_to_layer_type(), network::time_steps, size_params::time_steps, network::truth, network::truths, layer::truths, section::type, node::val, network::w, size_params::w, network::workspace, and layer::workspace_size.
Referenced by average(), BattleRoyaleWithCheese(), demo_art(), demo_classifier(), demo_regressor(), denormalize_net(), engine_go(), gun_classifier(), label_classifier(), load_network(), normalize_net(), oneoff(), oneoff2(), operations(), partial(), predict_classifier(), predict_regressor(), rescale_net(), reset_normalize_net(), rgbgr_net(), run_nightmare(), self_go(), SortMaster3000(), speed(), statistics_net(), test_captcha(), test_char_rnn(), test_cifar(), test_cifar_csv(), test_cifar_csvtrain(), test_cifar_multi(), test_classifier(), test_coco(), test_dcgan(), test_detector(), test_dice(), test_go(), test_lsd(), test_super(), test_tactic_rnn(), test_tag(), test_voxel(), test_writing(), test_yolo(), threat_classifier(), train_captcha(), train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_compare(), train_detector(), train_dice(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), train_yolo(), try_classifier(), valid_captcha(), valid_char_rnn(), valid_go(), valid_tactic_rnn(), validate_classifier_10(), validate_classifier_crop(), validate_classifier_full(), validate_classifier_multi(), validate_classifier_single(), validate_coco(), validate_coco_recall(), validate_compare(), validate_detector(), validate_detector_flip(), validate_detector_recall(), validate_dice(), validate_yolo(), validate_yolo_recall(), vec_char_rnn(), and visualize().
 {
     list *sections = read_cfg(filename);
     node *n = sections->front;
     if(!n) error("Config file has no sections");
     network net = make_network(sections->size - 1);
     net.gpu_index = gpu_index;
     size_params params;
     section *s = (section *)n->val;
     list *options = s->options;
     if(!is_network(s)) error("First section must be [net] or [network]");
     parse_net_options(options, &net);
     params.h = net.h;
     params.w = net.w;
     params.c = net.c;
     params.inputs = net.inputs;
     params.batch = net.batch;
     params.time_steps = net.time_steps;
     params.net = net;
     size_t workspace_size = 0;
     n = n->next;
     int count = 0;
     free_section(s);
     fprintf(stderr, "layer     filters    size              input                output\n");
     while(n){
         params.index = count;
         fprintf(stderr, "%5d ", count);
         s = (section *)n->val;
         options = s->options;
         layer l = {0};
         LAYER_TYPE lt = string_to_layer_type(s->type);
         if(lt == CONVOLUTIONAL){
             l = parse_convolutional(options, params);
         }else if(lt == DECONVOLUTIONAL){
             l = parse_deconvolutional(options, params);
         }else if(lt == LOCAL){
             l = parse_local(options, params);
         }else if(lt == ACTIVE){
             l = parse_activation(options, params);
         }else if(lt == RNN){
             l = parse_rnn(options, params);
         }else if(lt == GRU){
             l = parse_gru(options, params);
         }else if(lt == CRNN){
             l = parse_crnn(options, params);
         }else if(lt == CONNECTED){
             l = parse_connected(options, params);
         }else if(lt == CROP){
             l = parse_crop(options, params);
         }else if(lt == COST){
             l = parse_cost(options, params);
         }else if(lt == REGION){
             l = parse_region(options, params);
         }else if(lt == DETECTION){
             l = parse_detection(options, params);
         }else if(lt == SOFTMAX){
             l = parse_softmax(options, params);
             net.hierarchy = l.softmax_tree;
         }else if(lt == NORMALIZATION){
             l = parse_normalization(options, params);
         }else if(lt == BATCHNORM){
             l = parse_batchnorm(options, params);
         }else if(lt == MAXPOOL){
             l = parse_maxpool(options, params);
         }else if(lt == REORG){
             l = parse_reorg(options, params);
         }else if(lt == AVGPOOL){
             l = parse_avgpool(options, params);
         }else if(lt == ROUTE){
             l = parse_route(options, params, net);
         }else if(lt == SHORTCUT){
             l = parse_shortcut(options, params, net);
         }else if(lt == DROPOUT){
             l = parse_dropout(options, params);
             l.output = net.layers[count-1].output;
             l.delta = net.layers[count-1].delta;
 #ifdef GPU
             l.output_gpu = net.layers[count-1].output_gpu;
             l.delta_gpu = net.layers[count-1].delta_gpu;
 #endif
         }else{
             fprintf(stderr, "Type not recognized: %s\n", s->type);
         }
         l.truth = option_find_int_quiet(options, "truth", 0);
         l.onlyforward = option_find_int_quiet(options, "onlyforward", 0);
         l.stopbackward = option_find_int_quiet(options, "stopbackward", 0);
         l.dontload = option_find_int_quiet(options, "dontload", 0);
         l.dontloadscales = option_find_int_quiet(options, "dontloadscales", 0);
         l.learning_rate_scale = option_find_float_quiet(options, "learning_rate", 1);
         l.smooth = option_find_float_quiet(options, "smooth", 0);
         option_unused(options);
         net.layers[count] = l;
         if (l.workspace_size > workspace_size) workspace_size = l.workspace_size;
         free_section(s);
         n = n->next;
         ++count;
         if(n){
             params.h = l.out_h;
             params.w = l.out_w;
             params.c = l.out_c;
             params.inputs = l.outputs;
         }
     }
     free_list(sections);
     layer out = get_network_output_layer(net);
     net.outputs = out.outputs;
     net.truths = out.outputs;
     if(net.layers[net.n-1].truths) net.truths = net.layers[net.n-1].truths;
     net.output = out.output;
     net.input = calloc(net.inputs*net.batch, sizeof(float));
     net.truth = calloc(net.truths*net.batch, sizeof(float));
 #ifdef GPU
     net.output_gpu = out.output_gpu;
     net.input_gpu = cuda_make_array(net.input, net.inputs*net.batch);
     net.truth_gpu = cuda_make_array(net.truth, net.truths*net.batch);
 #endif
     if(workspace_size){
         //printf("%ld\n", workspace_size);
 #ifdef GPU
         if(gpu_index >= 0){
             net.workspace = cuda_make_array(0, (workspace_size-1)/sizeof(float)+1);
         }else {
             net.workspace = calloc(1, workspace_size);
         }
 #else
         net.workspace = calloc(1, workspace_size);
 #endif
     }
     return net;
 }
parse_normalization()
layer parse_normalization (list * options, size_params params)
Definition at line 430 of file parser.c.
References size_params::batch, size_params::c, size_params::h, make_normalization_layer(), option_find_float(), option_find_int(), and size_params::w.
Referenced by parse_network_cfg().
 {
     float alpha = option_find_float(options, "alpha", .0001);
     float beta =  option_find_float(options, "beta" , .75);
     float kappa = option_find_float(options, "kappa", 1);
     int size = option_find_int(options, "size", 5);
     layer l = make_normalization_layer(params.batch, params.w, params.h, params.c, size, alpha, beta, kappa);
     return l;
 }
parse_region()
layer parse_region (list * options, size_params params)
Definition at line 264 of file parser.c.
References layer::absolute, size_params::batch, layer::bias_match, layer::biases, layer::class_scale, layer::classfix, layer::coord_scale, size_params::h, size_params::inputs, layer::jitter, layer::log, make_region_layer(), layer::map, layer::max_boxes, layer::noobject_scale, layer::object_scale, option_find_float(), option_find_int(), option_find_int_quiet(), option_find_str(), layer::outputs, layer::random, read_map(), read_tree(), layer::rescore, layer::softmax, layer::softmax_tree, layer::sqrt, layer::thresh, and size_params::w.
Referenced by parse_network_cfg().
 {
     int coords = option_find_int(options, "coords", 4);
     int classes = option_find_int(options, "classes", 20);
     int num = option_find_int(options, "num", 1);
     layer l = make_region_layer(params.batch, params.w, params.h, num, classes, coords);
     assert(l.outputs == params.inputs);
     l.log = option_find_int_quiet(options, "log", 0);
     l.sqrt = option_find_int_quiet(options, "sqrt", 0);
     l.softmax = option_find_int(options, "softmax", 0);
     l.max_boxes = option_find_int_quiet(options, "max",30);
     l.jitter = option_find_float(options, "jitter", .2);
     l.rescore = option_find_int_quiet(options, "rescore",0);
     l.thresh = option_find_float(options, "thresh", .5);
     l.classfix = option_find_int_quiet(options, "classfix", 0);
     l.absolute = option_find_int_quiet(options, "absolute", 0);
     l.random = option_find_int_quiet(options, "random", 0);
     l.coord_scale = option_find_float(options, "coord_scale", 1);
     l.object_scale = option_find_float(options, "object_scale", 1);
     l.noobject_scale = option_find_float(options, "noobject_scale", 1);
     l.class_scale = option_find_float(options, "class_scale", 1);
     l.bias_match = option_find_int_quiet(options, "bias_match",0);
     char *tree_file = option_find_str(options, "tree", 0);
     if (tree_file) l.softmax_tree = read_tree(tree_file);
     char *map_file = option_find_str(options, "map", 0);
     if (map_file) l.map = read_map(map_file);
     char *a = option_find_str(options, "anchors", 0);
     if(a){
         int len = strlen(a);
         int n = 1;
         int i;
         for(i = 0; i < len; ++i){
             if (a[i] == ',') ++n;
         }
         for(i = 0; i < n; ++i){
             float bias = atof(a);
             l.biases[i] = bias;
             a = strchr(a, ',')+1;
         }
     }
     return l;
 }
parse_reorg()
layer parse_reorg (list * options, size_params params)
Definition at line 372 of file parser.c.
References size_params::batch, size_params::c, error(), flatten(), size_params::h, make_reorg_layer(), option_find_int(), option_find_int_quiet(), and size_params::w.
Referenced by parse_network_cfg().
 {
     int stride = option_find_int(options, "stride",1);
     int reverse = option_find_int_quiet(options, "reverse",0);
     int flatten = option_find_int_quiet(options, "flatten",0);
     int extra = option_find_int_quiet(options, "extra",0);
     int batch,h,w,c;
     h = params.h;
     w = params.w;
     c = params.c;
     batch=params.batch;
     if(!(h && w && c)) error("Layer before reorg layer must output image.");
     layer layer = make_reorg_layer(batch,w,h,c,stride,reverse, flatten, extra);
     return layer;
 }
parse_rnn()
layer parse_rnn (list * options, size_params params)
Definition at line 216 of file parser.c.
References size_params::batch, get_activation(), size_params::inputs, make_rnn_layer(), option_find_int(), option_find_int_quiet(), option_find_str(), layer::shortcut, and size_params::time_steps.
Referenced by parse_network_cfg().
 {
     int output = option_find_int(options, "output",1);
     int hidden = option_find_int(options, "hidden",1);
     char *activation_s = option_find_str(options, "activation", "logistic");
     ACTIVATION activation = get_activation(activation_s);
     int batch_normalize = option_find_int_quiet(options, "batch_normalize", 0);
     int logistic = option_find_int_quiet(options, "logistic", 0);
     layer l = make_rnn_layer(params.batch, params.inputs, hidden, output, params.time_steps, activation, batch_normalize, logistic);
     l.shortcut = option_find_int_quiet(options, "shortcut", 0);
     return l;
 }
parse_route()
route_layer parse_route (list * options, size_params params, network net)
Definition at line 481 of file parser.c.
References size_params::batch, error(), size_params::index, network::layers, make_route_layer(), option_find(), layer::out_c, layer::out_h, layer::out_w, and layer::outputs.
Referenced by parse_network_cfg().
 {
     char *l = option_find(options, "layers");
     int len = strlen(l);
     if(!l) error("Route Layer must specify input layers");
     int n = 1;
     int i;
     for(i = 0; i < len; ++i){
         if (l[i] == ',') ++n;
     }
     int *layers = calloc(n, sizeof(int));
     int *sizes = calloc(n, sizeof(int));
     for(i = 0; i < n; ++i){
         int index = atoi(l);
         l = strchr(l, ',')+1;
         if(index < 0) index = params.index + index;
         layers[i] = index;
         sizes[i] = net.layers[index].outputs;
     }
     int batch = params.batch;
     route_layer layer = make_route_layer(batch, n, layers, sizes);
     convolutional_layer first = net.layers[layers[0]];
     layer.out_w = first.out_w;
     layer.out_h = first.out_h;
     layer.out_c = first.out_c;
     for(i = 1; i < n; ++i){
         int index = layers[i];
         convolutional_layer next = net.layers[index];
         if(next.out_w == first.out_w && next.out_h == first.out_h){
             layer.out_c += next.out_c;
         }else{
             layer.out_h = layer.out_w = layer.out_c = 0;
         }
     }
     return layer;
 }
parse_shortcut()
layer parse_shortcut (list * options, size_params params, network net)
Definition at line 446 of file parser.c.
References layer::activation, size_params::batch, size_params::c, get_activation(), size_params::h, size_params::index, network::layers, make_shortcut_layer(), option_find(), option_find_str(), layer::out_c, layer::out_h, layer::out_w, and size_params::w.
Referenced by parse_network_cfg().
 {
     char *l = option_find(options, "from");
     int index = atoi(l);
     if(index < 0) index = params.index + index;
     int batch = params.batch;
     layer from = net.layers[index];
     layer s = make_shortcut_layer(batch, index, params.w, params.h, params.c, from.out_w, from.out_h, from.out_c);
     char *activation_s = option_find_str(options, "activation", "linear");
     ACTIVATION activation = get_activation(activation_s);
     s.activation = activation;
     return s;
 }
parse_softmax()
softmax_layer parse_softmax (list * options, size_params params)
Definition at line 254 of file parser.c.
References size_params::batch, size_params::inputs, make_softmax_layer(), option_find_float_quiet(), option_find_int_quiet(), option_find_str(), read_tree(), layer::softmax_tree, and layer::temperature.
Referenced by parse_network_cfg().
 {
     int groups = option_find_int_quiet(options, "groups",1);
     softmax_layer layer = make_softmax_layer(params.batch, params.inputs, groups);
     layer.temperature = option_find_float_quiet(options, "temperature", 1);
     char *tree_file = option_find_str(options, "tree", 0);
     if (tree_file) layer.softmax_tree = read_tree(tree_file);
     return layer;
 }
read_cfg()
list * read_cfg (char * filename)
Definition at line 752 of file parser.c.
References fgetl(), file_error(), list_insert(), make_list(), section::options, read_option(), strip(), and section::type.
Referenced by parse_network_cfg().
 {
     FILE *file = fopen(filename, "r");
     if(file == 0) file_error(filename);
     char *line;
     int nu = 0;
     list *sections = make_list();
     section *current = 0;
     while((line=fgetl(file)) != 0){
         ++ nu;
         strip(line);
         switch(line[0]){
             case '[':
                 current = malloc(sizeof(section));
                 list_insert(sections, current);
                 current->options = make_list();
                 current->type = line;
                 break;
             case '\0':
             case '#':
             case ';':
                 free(line);
                 break;
             default:
                 if(!read_option(line, current->options)){
                     fprintf(stderr, "Config file error line %d, could parse: %s\n", nu, line);
                     free(line);
                 }
                 break;
         }
     }
     fclose(file);
     return sections;
 }
save_batchnorm_weights()
void save_batchnorm_weights (layer l, FILE * fp)
Definition at line 844 of file parser.c.
References layer::c, gpu_index, layer::rolling_mean, layer::rolling_variance, and layer::scales.
Referenced by save_weights_upto().
 {
 #ifdef GPU
     if(gpu_index >= 0){
         pull_batchnorm_layer(l);
     }
 #endif
     fwrite(l.scales, sizeof(float), l.c, fp);
     fwrite(l.rolling_mean, sizeof(float), l.c, fp);
     fwrite(l.rolling_variance, sizeof(float), l.c, fp);
 }
save_connected_weights()
void save_connected_weights (layer l, FILE * fp)
Definition at line 856 of file parser.c.
References layer::batch_normalize, layer::biases, gpu_index, layer::inputs, layer::outputs, layer::rolling_mean, layer::rolling_variance, layer::scales, and layer::weights.
Referenced by save_weights_upto().
 {
 #ifdef GPU
     if(gpu_index >= 0){
         pull_connected_layer(l);
     }
 #endif
     fwrite(l.biases, sizeof(float), l.outputs, fp);
     fwrite(l.weights, sizeof(float), l.outputs*l.inputs, fp);
     if (l.batch_normalize){
         fwrite(l.scales, sizeof(float), l.outputs, fp);
         fwrite(l.rolling_mean, sizeof(float), l.outputs, fp);
         fwrite(l.rolling_variance, sizeof(float), l.outputs, fp);
     }
 }
save_convolutional_weights()
void save_convolutional_weights (layer l, FILE * fp)
Definition at line 819 of file parser.c.
References layer::adam, layer::batch_normalize, layer::biases, layer::binary, layer::c, gpu_index, layer::n, layer::rolling_mean, layer::rolling_variance, layer::scales, layer::size, and layer::weights.
Referenced by save_weights_upto().
 {
     if(l.binary){
         //save_convolutional_weights_binary(l, fp);
         //return;
     }
 #ifdef GPU
     if(gpu_index >= 0){
         pull_convolutional_layer(l);
     }
 #endif
     int num = l.n*l.c*l.size*l.size;
     fwrite(l.biases, sizeof(float), l.n, fp);
     if (l.batch_normalize){
         fwrite(l.scales, sizeof(float), l.n, fp);
         fwrite(l.rolling_mean, sizeof(float), l.n, fp);
         fwrite(l.rolling_variance, sizeof(float), l.n, fp);
     }
     fwrite(l.weights, sizeof(float), num, fp);
     if(l.adam){
         //fwrite(l.m, sizeof(float), num, fp);
         //fwrite(l.v, sizeof(float), num, fp);
     }
 }
save_convolutional_weights_binary()
void save_convolutional_weights_binary (layer l, FILE * fp)
Definition at line 787 of file parser.c.
References layer::batch_normalize, layer::biases, binarize_weights(), layer::binary_weights, layer::c, size_params::c, gpu_index, size_params::index, layer::n, layer::rolling_mean, layer::rolling_variance, layer::scales, layer::size, and layer::weights.
 {
 #ifdef GPU
     if(gpu_index >= 0){
         pull_convolutional_layer(l);
     }
 #endif
     binarize_weights(l.weights, l.n, l.c*l.size*l.size, l.binary_weights);
     int size = l.c*l.size*l.size;
     int i, j, k;
     fwrite(l.biases, sizeof(float), l.n, fp);
     if (l.batch_normalize){
         fwrite(l.scales, sizeof(float), l.n, fp);
         fwrite(l.rolling_mean, sizeof(float), l.n, fp);
         fwrite(l.rolling_variance, sizeof(float), l.n, fp);
     }
     for(i = 0; i < l.n; ++i){
         float mean = l.binary_weights[i*size];
         if(mean < 0) mean = -mean;
         fwrite(&mean, sizeof(float), 1, fp);
         for(j = 0; j < size/8; ++j){
             int index = i*size + j*8;
             unsigned char c = 0;
             for(k = 0; k < 8; ++k){
                 if (j*8 + k >= size) break;
                 if (l.binary_weights[index + k] > 0) c = (c | 1<<k);
             }
             fwrite(&c, sizeof(char), 1, fp);
         }
     }
 }
save_weights()
void save_weights (network net, char * filename)
Definition at line 929 of file parser.c.
References network::n, and save_weights_upto().
Referenced by average(), denormalize_net(), normalize_net(), oneoff(), rescale_net(), reset_normalize_net(), rgbgr_net(), train_captcha(), train_char_rnn(), train_cifar(), train_cifar_distill(), train_classifier(), train_coco(), train_colorizer(), train_compare(), train_dcgan(), train_detector(), train_dice(), train_go(), train_regressor(), train_super(), train_swag(), train_tag(), train_voxel(), train_writing(), and train_yolo().
 {
     save_weights_upto(net, filename, net.n);
 }
save_weights_upto()
void save_weights_upto (network net, char * filename, int cutoff)
Definition at line 872 of file parser.c.
References BATCHNORM, layer::biases, layer::c, CONNECTED, CONVOLUTIONAL, CRNN, DECONVOLUTIONAL, file_error(), gpu_index, network::gpu_index, GRU, layer::input_h_layer, layer::input_layer, layer::input_r_layer, layer::input_z_layer, network::layers, LOCAL, network::n, layer::n, layer::out_h, layer::out_w, layer::output_layer, layer::outputs, RNN, save_batchnorm_weights(), save_connected_weights(), save_convolutional_weights(), network::seen, layer::self_layer, layer::size, layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, layer::type, and layer::weights.
Referenced by oneoff2(), partial(), and save_weights().
 {
 #ifdef GPU
     if(net.gpu_index >= 0){
         cuda_set_device(net.gpu_index);
     }
 #endif
     fprintf(stderr, "Saving weights to %s\n", filename);
     FILE *fp = fopen(filename, "wb");
     if(!fp) file_error(filename);
     int major = 0;
     int minor = 1;
     int revision = 0;
     fwrite(&major, sizeof(int), 1, fp);
     fwrite(&minor, sizeof(int), 1, fp);
     fwrite(&revision, sizeof(int), 1, fp);
     fwrite(net.seen, sizeof(int), 1, fp);
     int i;
     for(i = 0; i < net.n && i < cutoff; ++i){
         layer l = net.layers[i];
         if(l.type == CONVOLUTIONAL || l.type == DECONVOLUTIONAL){
             save_convolutional_weights(l, fp);
         } if(l.type == CONNECTED){
             save_connected_weights(l, fp);
         } if(l.type == BATCHNORM){
             save_batchnorm_weights(l, fp);
         } if(l.type == RNN){
             save_connected_weights(*(l.input_layer), fp);
             save_connected_weights(*(l.self_layer), fp);
             save_connected_weights(*(l.output_layer), fp);
         } if(l.type == GRU){
             save_connected_weights(*(l.input_z_layer), fp);
             save_connected_weights(*(l.input_r_layer), fp);
             save_connected_weights(*(l.input_h_layer), fp);
             save_connected_weights(*(l.state_z_layer), fp);
             save_connected_weights(*(l.state_r_layer), fp);
             save_connected_weights(*(l.state_h_layer), fp);
         } if(l.type == CRNN){
             save_convolutional_weights(*(l.input_layer), fp);
             save_convolutional_weights(*(l.self_layer), fp);
             save_convolutional_weights(*(l.output_layer), fp);
         } if(l.type == LOCAL){
 #ifdef GPU
             if(gpu_index >= 0){
                 pull_local_layer(l);
             }
 #endif
             int locations = l.out_w*l.out_h;
             int size = l.size*l.size*l.c*l.n*locations;
             fwrite(l.biases, sizeof(float), l.outputs, fp);
             fwrite(l.weights, sizeof(float), size, fp);
         }
     }
     fclose(fp);
 }
string_to_layer_type()
LAYER_TYPE string_to_layer_type (char * type)
Definition at line 41 of file parser.c.
References ACTIVE, AVGPOOL, BATCHNORM, BLANK, CONNECTED, CONVOLUTIONAL, COST, CRNN, CROP, DECONVOLUTIONAL, DETECTION, DROPOUT, GRU, LOCAL, MAXPOOL, NETWORK, NORMALIZATION, REGION, REORG, RNN, ROUTE, SHORTCUT, and SOFTMAX.
Referenced by parse_network_cfg().
 {
     if (strcmp(type, "[shortcut]")==0) return SHORTCUT;
     if (strcmp(type, "[crop]")==0) return CROP;
     if (strcmp(type, "[cost]")==0) return COST;
     if (strcmp(type, "[detection]")==0) return DETECTION;
     if (strcmp(type, "[region]")==0) return REGION;
     if (strcmp(type, "[local]")==0) return LOCAL;
     if (strcmp(type, "[conv]")==0
             || strcmp(type, "[convolutional]")==0) return CONVOLUTIONAL;
     if (strcmp(type, "[deconv]")==0
             || strcmp(type, "[deconvolutional]")==0) return DECONVOLUTIONAL;
     if (strcmp(type, "[activation]")==0) return ACTIVE;
     if (strcmp(type, "[net]")==0
             || strcmp(type, "[network]")==0) return NETWORK;
     if (strcmp(type, "[crnn]")==0) return CRNN;
     if (strcmp(type, "[gru]")==0) return GRU;
     if (strcmp(type, "[rnn]")==0) return RNN;
     if (strcmp(type, "[conn]")==0
             || strcmp(type, "[connected]")==0) return CONNECTED;
     if (strcmp(type, "[max]")==0
             || strcmp(type, "[maxpool]")==0) return MAXPOOL;
     if (strcmp(type, "[reorg]")==0) return REORG;
     if (strcmp(type, "[avg]")==0
             || strcmp(type, "[avgpool]")==0) return AVGPOOL;
     if (strcmp(type, "[dropout]")==0) return DROPOUT;
     if (strcmp(type, "[lrn]")==0
             || strcmp(type, "[normalization]")==0) return NORMALIZATION;
     if (strcmp(type, "[batchnorm]")==0) return BATCHNORM;
     if (strcmp(type, "[soft]")==0
             || strcmp(type, "[softmax]")==0) return SOFTMAX;
     if (strcmp(type, "[route]")==0) return ROUTE;
     return BLANK;
 }
transpose_matrix()
void transpose_matrix (float * a, int rows, int cols)
Definition at line 934 of file parser.c.
Referenced by load_connected_weights(), and load_convolutional_weights().
 {
     float *transpose = calloc(rows*cols, sizeof(float));
     int x, y;
     for(x = 0; x < rows; ++x){
         for(y = 0; y < cols; ++y){
             transpose[y*rows + x] = a[x*cols + y];
         }
     }
     memcpy(a, transpose, rows*cols*sizeof(float));
     free(transpose);
 }