Darknet: detection_layer.c File Reference
detection_layer.c File Reference
#include "detection_layer.h"
#include "activations.h"
#include "softmax_layer.h"
#include "blas.h"
#include "box.h"
#include "cuda.h"
#include "utils.h"
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include <stdlib.h>
Functions
detection_layer make_detection_layer (int batch, int inputs, int n, int side, int classes, int coords, int rescore)
void forward_detection_layer (const detection_layer l, network net)
void backward_detection_layer (const detection_layer l, network net)
void get_detection_boxes (layer l, int w, int h, float thresh, float **probs, box *boxes, int only_objectness)
Function Documentation
backward_detection_layer()
void backward_detection_layer (const detection_layer l, network net)
Definition at line 219 of file detection_layer.c.
References axpy_cpu(), layer::batch, network::delta, layer::delta, and layer::inputs.
Referenced by make_detection_layer().
 {
     axpy_cpu(l.batch*l.inputs, 1, l.delta, 1, net.delta, 1);
 }
forward_detection_layer()
void forward_detection_layer (const detection_layer l, network net)
Definition at line 49 of file detection_layer.c.
References layer::batch, box_iou(), box_rmse(), layer::class_scale, layer::classes, layer::coord_scale, layer::coords, layer::cost, layer::delta, float_to_box(), layer::forced, box::h, network::input, layer::inputs, mag_array(), layer::n, layer::noobject_scale, layer::object_scale, layer::output, layer::outputs, layer::random, layer::rescore, network::seen, layer::side, layer::softmax, softmax(), layer::sqrt, top_k(), network::train, network::truth, box::w, box::x, and box::y.
Referenced by get_detection_boxes(), and make_detection_layer().
 {
     int locations = l.side*l.side;
     int i,j;
     memcpy(l.output, net.input, l.outputs*l.batch*sizeof(float));
     //if(l.reorg) reorg(l.output, l.w*l.h, size*l.n, l.batch, 1);
     int b;
     if (l.softmax){
         for(b = 0; b < l.batch; ++b){
             int index = b*l.inputs;
             for (i = 0; i < locations; ++i) {
                 int offset = i*l.classes;
                 softmax(l.output + index + offset, l.classes, 1, 1,
                         l.output + index + offset);
             }
         }
     }
     if(net.train){
         float avg_iou = 0;
         float avg_cat = 0;
         float avg_allcat = 0;
         float avg_obj = 0;
         float avg_anyobj = 0;
         int count = 0;
         *(l.cost) = 0;
         int size = l.inputs * l.batch;
         memset(l.delta, 0, size * sizeof(float));
         for (b = 0; b < l.batch; ++b){
             int index = b*l.inputs;
             for (i = 0; i < locations; ++i) {
                 int truth_index = (b*locations + i)*(1+l.coords+l.classes);
                 int is_obj = net.truth[truth_index];
                 for (j = 0; j < l.n; ++j) {
                     int p_index = index + locations*l.classes + i*l.n + j;
                     l.delta[p_index] = l.noobject_scale*(0 - l.output[p_index]);
                     *(l.cost) += l.noobject_scale*pow(l.output[p_index], 2);
                     avg_anyobj += l.output[p_index];
                 }
                 int best_index = -1;
                 float best_iou = 0;
                 float best_rmse = 20;
                 if (!is_obj){
                     continue;
                 }
                 int class_index = index + i*l.classes;
                 for(j = 0; j < l.classes; ++j) {
                     l.delta[class_index+j] = l.class_scale * (net.truth[truth_index+1+j] - l.output[class_index+j]);
                     *(l.cost) += l.class_scale * pow(net.truth[truth_index+1+j] - l.output[class_index+j], 2);
                     if(net.truth[truth_index + 1 + j]) avg_cat += l.output[class_index+j];
                     avg_allcat += l.output[class_index+j];
                 }
                 box truth = float_to_box(net.truth + truth_index + 1 + l.classes, 1);
                 truth.x /= l.side;
                 truth.y /= l.side;
                 for(j = 0; j < l.n; ++j){
                     int box_index = index + locations*(l.classes + l.n) + (i*l.n + j) * l.coords;
                     box out = float_to_box(l.output + box_index, 1);
                     out.x /= l.side;
                     out.y /= l.side;
                     if (l.sqrt){
                         out.w = out.w*out.w;
                         out.h = out.h*out.h;
                     }
                     float iou  = box_iou(out, truth);
                     //iou = 0;
                     float rmse = box_rmse(out, truth);
                     if(best_iou > 0 || iou > 0){
                         if(iou > best_iou){
                             best_iou = iou;
                             best_index = j;
                         }
                     }else{
                         if(rmse < best_rmse){
                             best_rmse = rmse;
                             best_index = j;
                         }
                     }
                 }
                 if(l.forced){
                     if(truth.w*truth.h < .1){
                         best_index = 1;
                     }else{
                         best_index = 0;
                     }
                 }
                 if(l.random && *(net.seen) < 64000){
                     best_index = rand()%l.n;
                 }
                 int box_index = index + locations*(l.classes + l.n) + (i*l.n + best_index) * l.coords;
                 int tbox_index = truth_index + 1 + l.classes;
                 box out = float_to_box(l.output + box_index, 1);
                 out.x /= l.side;
                 out.y /= l.side;
                 if (l.sqrt) {
                     out.w = out.w*out.w;
                     out.h = out.h*out.h;
                 }
                 float iou  = box_iou(out, truth);
                 //printf("%d,", best_index);
                 int p_index = index + locations*l.classes + i*l.n + best_index;
                 *(l.cost) -= l.noobject_scale * pow(l.output[p_index], 2);
                 *(l.cost) += l.object_scale * pow(1-l.output[p_index], 2);
                 avg_obj += l.output[p_index];
                 l.delta[p_index] = l.object_scale * (1.-l.output[p_index]);
                 if(l.rescore){
                     l.delta[p_index] = l.object_scale * (iou - l.output[p_index]);
                 }
                 l.delta[box_index+0] = l.coord_scale*(net.truth[tbox_index + 0] - l.output[box_index + 0]);
                 l.delta[box_index+1] = l.coord_scale*(net.truth[tbox_index + 1] - l.output[box_index + 1]);
                 l.delta[box_index+2] = l.coord_scale*(net.truth[tbox_index + 2] - l.output[box_index + 2]);
                 l.delta[box_index+3] = l.coord_scale*(net.truth[tbox_index + 3] - l.output[box_index + 3]);
                 if(l.sqrt){
                     l.delta[box_index+2] = l.coord_scale*(sqrt(net.truth[tbox_index + 2]) - l.output[box_index + 2]);
                     l.delta[box_index+3] = l.coord_scale*(sqrt(net.truth[tbox_index + 3]) - l.output[box_index + 3]);
                 }
                 *(l.cost) += pow(1-iou, 2);
                 avg_iou += iou;
                 ++count;
             }
         }
         if(0){
             float *costs = calloc(l.batch*locations*l.n, sizeof(float));
             for (b = 0; b < l.batch; ++b) {
                 int index = b*l.inputs;
                 for (i = 0; i < locations; ++i) {
                     for (j = 0; j < l.n; ++j) {
                         int p_index = index + locations*l.classes + i*l.n + j;
                         costs[b*locations*l.n + i*l.n + j] = l.delta[p_index]*l.delta[p_index];
                     }
                 }
             }
             int indexes[100];
             top_k(costs, l.batch*locations*l.n, 100, indexes);
             float cutoff = costs[indexes[99]];
             for (b = 0; b < l.batch; ++b) {
                 int index = b*l.inputs;
                 for (i = 0; i < locations; ++i) {
                     for (j = 0; j < l.n; ++j) {
                         int p_index = index + locations*l.classes + i*l.n + j;
                         if (l.delta[p_index]*l.delta[p_index] < cutoff) l.delta[p_index] = 0;
                     }
                 }
             }
             free(costs);
         }
         *(l.cost) = pow(mag_array(l.delta, l.outputs * l.batch), 2);
         printf("Detection Avg IOU: %f, Pos Cat: %f, All Cat: %f, Pos Obj: %f, Any Obj: %f, count: %d\n", avg_iou/count, avg_cat/count, avg_allcat/(count*l.classes), avg_obj/count, avg_anyobj/(l.batch*locations*l.n), count);
         //if(l.reorg) reorg(l.delta, l.w*l.h, size*l.n, l.batch, 0);
     }
 }
get_detection_boxes()
void get_detection_boxes (layer l, int w, int h, float thresh, float ** probs, box * boxes, int only_objectness)
Definition at line 224 of file detection_layer.c.
References layer::batch, layer::classes, layer::delta, forward_detection_layer(), box::h, layer::inputs, layer::n, layer::output, layer::outputs, layer::side, layer::sqrt, network::train, box::w, box::x, and box::y.
Referenced by test_coco(), test_yolo(), validate_coco(), validate_coco_recall(), validate_yolo(), and validate_yolo_recall().
 {
     int i,j,n;
     float *predictions = l.output;
     //int per_cell = 5*num+classes;
     for (i = 0; i < l.side*l.side; ++i){
         int row = i / l.side;
         int col = i % l.side;
         for(n = 0; n < l.n; ++n){
             int index = i*l.n + n;
             int p_index = l.side*l.side*l.classes + i*l.n + n;
             float scale = predictions[p_index];
             int box_index = l.side*l.side*(l.classes + l.n) + (i*l.n + n)*4;
             boxes[index].x = (predictions[box_index + 0] + col) / l.side * w;
             boxes[index].y = (predictions[box_index + 1] + row) / l.side * h;
             boxes[index].w = pow(predictions[box_index + 2], (l.sqrt?2:1)) * w;
             boxes[index].h = pow(predictions[box_index + 3], (l.sqrt?2:1)) * h;
             for(j = 0; j < l.classes; ++j){
                 int class_index = i*l.classes;
                 float prob = scale*predictions[class_index+j];
                 probs[index][j] = (prob > thresh) ? prob : 0;
             }
             if(only_objectness){
                 probs[index][0] = scale;
             }
         }
     }
 }
make_detection_layer()
detection_layer make_detection_layer (int batch, int inputs, int n, int side, int classes, int coords, int rescore)
Definition at line 13 of file detection_layer.c.
References layer::backward, backward_detection_layer(), layer::backward_gpu, layer::batch, layer::classes, layer::coords, layer::cost, layer::delta, DETECTION, layer::forward, forward_detection_layer(), layer::forward_gpu, layer::h, layer::inputs, layer::n, layer::output, layer::outputs, layer::rescore, layer::side, layer::truths, layer::type, and layer::w.
Referenced by parse_detection().
 {
     detection_layer l = {0};
     l.type = DETECTION;
     l.n = n;
     l.batch = batch;
     l.inputs = inputs;
     l.classes = classes;
     l.coords = coords;
     l.rescore = rescore;
     l.side = side;
     l.w = side;
     l.h = side;
     assert(side*side*((1 + l.coords)*l.n + l.classes) == inputs);
     l.cost = calloc(1, sizeof(float));
     l.outputs = l.inputs;
     l.truths = l.side*l.side*(1+l.coords+l.classes);
     l.output = calloc(batch*l.outputs, sizeof(float));
     l.delta = calloc(batch*l.outputs, sizeof(float));
     l.forward = forward_detection_layer;
     l.backward = backward_detection_layer;
 #ifdef GPU
     l.forward_gpu = forward_detection_layer_gpu;
     l.backward_gpu = backward_detection_layer_gpu;
     l.output_gpu = cuda_make_array(l.output, batch*l.outputs);
     l.delta_gpu = cuda_make_array(l.delta, batch*l.outputs);
 #endif
     fprintf(stderr, "Detection Layer\n");
     srand(0);
     return l;
 }