Darknet: regressor.c File Reference
regressor.c File Reference
#include "network.h"
#include "utils.h"
#include "parser.h"
#include "option_list.h"
#include "blas.h"
#include "assert.h"
#include "cuda.h"
#include <sys/time.h>
Functions
void train_regressor (char *datacfg, char *cfgfile, char *weightfile, int *gpus, int ngpus, int clear)
void predict_regressor (char *cfgfile, char *weightfile, char *filename)
void demo_regressor (char *datacfg, char *cfgfile, char *weightfile, int cam_index, const char *filename)
void run_regressor (int argc, char **argv)
Function Documentation
demo_regressor()
void demo_regressor (char * datacfg, char * cfgfile, char * weightfile, int cam_index, const char * filename)
Definition at line 160 of file regressor.c.
References image::data, error(), free_image(), network::h, letterbox_image(), load_weights(), network_predict(), parse_network_cfg(), set_batch_network(), show_image(), and network::w.
Referenced by run_regressor().
 {
 #ifdef OPENCV
     printf("Regressor Demo\n");
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     CvCapture * cap;
     if(filename){
         cap = cvCaptureFromFile(filename);
     }else{
         cap = cvCaptureFromCAM(cam_index);
     }
     if(!cap) error("Couldn't connect to webcam.\n");
     cvNamedWindow("Regressor", CV_WINDOW_NORMAL);
     cvResizeWindow("Regressor", 512, 512);
     float fps = 0;
     while(1){
         struct timeval tval_before, tval_after, tval_result;
         gettimeofday(&tval_before, NULL);
         image in = get_image_from_stream(cap);
         image in_s = letterbox_image(in, net.w, net.h);
         show_image(in, "Regressor");
         float *predictions = network_predict(net, in_s.data);
         printf("\033[2J");
         printf("\033[1;1H");
         printf("\nFPS:%.0f\n",fps);
         printf("People: %f\n", predictions[0]);
         free_image(in_s);
         free_image(in);
         cvWaitKey(10);
         gettimeofday(&tval_after, NULL);
         timersub(&tval_after, &tval_before, &tval_result);
         float curr = 1000000.f/((long int)tval_result.tv_usec);
         fps = .9*fps + .1*curr;
     }
 #endif
 }
predict_regressor()
void predict_regressor (char * cfgfile, char * weightfile, char * filename)
Definition at line 123 of file regressor.c.
References image::data, free_image(), network::h, letterbox_image(), load_image_color(), load_weights(), network_predict(), parse_network_cfg(), sec(), set_batch_network(), and network::w.
Referenced by run_regressor().
 {
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     clock_t time;
     char buff[256];
     char *input = buff;
     while(1){
         if(filename){
             strncpy(input, filename, 256);
         }else{
             printf("Enter Image Path: ");
             fflush(stdout);
             input = fgets(input, 256, stdin);
             if(!input) return;
             strtok(input, "\n");
         }
         image im = load_image_color(input, 0, 0);
         image sized = letterbox_image(im, net.w, net.h);
         float *X = sized.data;
         time=clock();
         float *predictions = network_predict(net, X);
         printf("Predicted: %f\n", predictions[0]);
         printf("%s: Predicted in %f seconds.\n", input, sec(clock()-time));
         free_image(im);
         free_image(sized);
         if (filename) break;
     }
 }
run_regressor()
void run_regressor (int argc, char ** argv)
Definition at line 214 of file regressor.c.
References demo_regressor(), find_arg(), find_char_arg(), find_int_arg(), gpu_index, predict_regressor(), and train_regressor().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *gpu_list = find_char_arg(argc, argv, "-gpus", 0);
     int *gpus = 0;
     int gpu = 0;
     int ngpus = 0;
     if(gpu_list){
         printf("%s\n", gpu_list);
         int len = strlen(gpu_list);
         ngpus = 1;
         int i;
         for(i = 0; i < len; ++i){
             if (gpu_list[i] == ',') ++ngpus;
         }
         gpus = calloc(ngpus, sizeof(int));
         for(i = 0; i < ngpus; ++i){
             gpus[i] = atoi(gpu_list);
             gpu_list = strchr(gpu_list, ',')+1;
         }
     } else {
         gpu = gpu_index;
         gpus = &gpu;
         ngpus = 1;
     }
     int cam_index = find_int_arg(argc, argv, "-c", 0);
     int clear = find_arg(argc, argv, "-clear");
     char *data = argv[3];
     char *cfg = argv[4];
     char *weights = (argc > 5) ? argv[5] : 0;
     char *filename = (argc > 6) ? argv[6]: 0;
     if(0==strcmp(argv[2], "test")) predict_regressor(data, cfg, weights);
     else if(0==strcmp(argv[2], "train")) train_regressor(data, cfg, weights, gpus, ngpus, clear);
     else if(0==strcmp(argv[2], "demo")) demo_regressor(data, cfg, weights, cam_index, filename);
 }
train_regressor()
void train_regressor (char * datacfg, char * cfgfile, char * weightfile, int * gpus, int ngpus, int clear)
Definition at line 10 of file regressor.c.
References network::angle, load_args::angle, network::aspect, load_args::aspect, basecfg(), network::batch, load_args::d, network::decay, network::exposure, load_args::exposure, free_data(), free_list(), free_network(), free_ptrs(), get_current_batch(), get_current_rate(), get_paths(), load_args::h, network::h, network::hue, load_args::hue, network::learning_rate, list_to_array(), load_data(), load_thread(), load_weights(), load_args::m, load_args::max, network::max_batches, network::max_crop, load_args::min, network::min_crop, network::momentum, load_args::n, option_find_str(), parse_network_cfg(), load_args::paths, read_data_cfg(), REGRESSION_DATA, network::saturation, load_args::saturation, save_weights(), sec(), network::seen, list::size, load_args::size, network::subdivisions, load_args::threads, train_network(), load_args::type, load_args::w, and network::w.
Referenced by run_regressor().
 {
     int i;
     float avg_loss = -1;
     char *base = basecfg(cfgfile);
     printf("%s\n", base);
     printf("%d\n", ngpus);
     network *nets = calloc(ngpus, sizeof(network));
     srand(time(0));
     int seed = rand();
     for(i = 0; i < ngpus; ++i){
         srand(seed);
 #ifdef GPU
         cuda_set_device(gpus[i]);
 #endif
         nets[i] = parse_network_cfg(cfgfile);
         if(weightfile){
             load_weights(&nets[i], weightfile);
         }
         if(clear) *nets[i].seen = 0;
         nets[i].learning_rate *= ngpus;
     }
     srand(time(0));
     network net = nets[0];
     int imgs = net.batch * net.subdivisions * ngpus;
     printf("Learning Rate: %g, Momentum: %g, Decay: %g\n", net.learning_rate, net.momentum, net.decay);
     list *options = read_data_cfg(datacfg);
     char *backup_directory = option_find_str(options, "backup", "/backup/");
     char *train_list = option_find_str(options, "train", "data/train.list");
     list *plist = get_paths(train_list);
     char **paths = (char **)list_to_array(plist);
     printf("%d\n", plist->size);
     int N = plist->size;
     clock_t time;
     load_args args = {0};
     args.w = net.w;
     args.h = net.h;
     args.threads = 32;
     args.min = net.min_crop;
     args.max = net.max_crop;
     args.angle = net.angle;
     args.aspect = net.aspect;
     args.exposure = net.exposure;
     args.saturation = net.saturation;
     args.hue = net.hue;
     args.size = net.w;
     args.paths = paths;
     args.n = imgs;
     args.m = N;
     args.type = REGRESSION_DATA;
     data train;
     data buffer;
     pthread_t load_thread;
     args.d = &buffer;
     load_thread = load_data(args);
     int epoch = (*net.seen)/N;
     while(get_current_batch(net) < net.max_batches || net.max_batches == 0){
         time=clock();
         pthread_join(load_thread, 0);
         train = buffer;
         load_thread = load_data(args);
         printf("Loaded: %lf seconds\n", sec(clock()-time));
         time=clock();
         float loss = 0;
 #ifdef GPU
         if(ngpus == 1){
             loss = train_network(net, train);
         } else {
             loss = train_networks(nets, ngpus, train, 4);
         }
 #else
         loss = train_network(net, train);
 #endif
         if(avg_loss == -1) avg_loss = loss;
         avg_loss = avg_loss*.9 + loss*.1;
         printf("%d, %.3f: %f, %f avg, %f rate, %lf seconds, %d images\n", get_current_batch(net), (float)(*net.seen)/N, loss, avg_loss, get_current_rate(net), sec(clock()-time), *net.seen);
         free_data(train);
         if(*net.seen/N > epoch){
             epoch = *net.seen/N;
             char buff[256];
             sprintf(buff, "%s/%s_%d.weights",backup_directory,base, epoch);
             save_weights(net, buff);
         }
         if(get_current_batch(net)%100 == 0){
             char buff[256];
             sprintf(buff, "%s/%s.backup",backup_directory,base);
             save_weights(net, buff);
         }
     }
     char buff[256];
     sprintf(buff, "%s/%s.weights", backup_directory, base);
     save_weights(net, buff);
     free_network(net);
     free_ptrs((void**)paths, plist->size);
     free_list(plist);
     free(base);
 }