Darknet: dice.c File Reference
dice.c File Reference
#include "network.h"
#include "utils.h"
#include "parser.h"
Functions
void train_dice (char *cfgfile, char *weightfile)
void validate_dice (char *filename, char *weightfile)
void test_dice (char *cfgfile, char *weightfile, char *filename)
void run_dice (int argc, char **argv)
Variables
char * dice_labels [] = {"face1","face2","face3","face4","face5","face6"}
Function Documentation
run_dice()
void run_dice (int argc, char ** argv)
Definition at line 104 of file dice.c.
References test_dice(), train_dice(), and validate_dice().
Referenced by main().
 {
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *cfg = argv[3];
     char *weights = (argc > 4) ? argv[4] : 0;
     char *filename = (argc > 5) ? argv[5]: 0;
     if(0==strcmp(argv[2], "test")) test_dice(cfg, weights, filename);
     else if(0==strcmp(argv[2], "train")) train_dice(cfg, weights);
     else if(0==strcmp(argv[2], "valid")) validate_dice(cfg, weights);
 }
test_dice()
void test_dice (char * cfgfile, char * weightfile, char * filename)
Definition at line 68 of file dice.c.
References image::data, dice_labels, free_image(), network::h, load_image_color(), load_weights(), network_predict(), parse_network_cfg(), set_batch_network(), top_predictions(), and network::w.
Referenced by run_dice().
 {
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     int i = 0;
     char **names = dice_labels;
     char buff[256];
     char *input = buff;
     int indexes[6];
     while(1){
         if(filename){
             strncpy(input, filename, 256);
         }else{
             printf("Enter Image Path: ");
             fflush(stdout);
             input = fgets(input, 256, stdin);
             if(!input) return;
             strtok(input, "\n");
         }
         image im = load_image_color(input, net.w, net.h);
         float *X = im.data;
         float *predictions = network_predict(net, X);
         top_predictions(net, 6, indexes);
         for(i = 0; i < 6; ++i){
             int index = indexes[i];
             printf("%s: %f\n", names[index], predictions[index]);
         }
         free_image(im);
         if (filename) break;
     }
 }
train_dice()
void train_dice (char * cfgfile, char * weightfile)
Definition at line 7 of file dice.c.
References basecfg(), network::decay, dice_labels, free_data(), get_paths(), network::h, network::learning_rate, list_to_array(), load_data_old(), load_weights(), network::momentum, parse_network_cfg(), save_weights(), sec(), network::seen, list::size, train_network(), and network::w.
Referenced by run_dice().
 {
     srand(time(0));
     float avg_loss = -1;
     char *base = basecfg(cfgfile);
     char *backup_directory = "/home/pjreddie/backup/";
     printf("%s\n", base);
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     printf("Learning Rate: %g, Momentum: %g, Decay: %g\n", net.learning_rate, net.momentum, net.decay);
     int imgs = 1024;
     int i = *net.seen/imgs;
     char **labels = dice_labels;
     list *plist = get_paths("data/dice/dice.train.list");
     char **paths = (char **)list_to_array(plist);
     printf("%d\n", plist->size);
     clock_t time;
     while(1){
         ++i;
         time=clock();
         data train = load_data_old(paths, imgs, plist->size, labels, 6, net.w, net.h);
         printf("Loaded: %lf seconds\n", sec(clock()-time));
         time=clock();
         float loss = train_network(net, train);
         if(avg_loss == -1) avg_loss = loss;
         avg_loss = avg_loss*.9 + loss*.1;
         printf("%d: %f, %f avg, %lf seconds, %d images\n", i, loss, avg_loss, sec(clock()-time), *net.seen);
         free_data(train);
         if((i % 100) == 0) net.learning_rate *= .1;
         if(i%100==0){
             char buff[256];
             sprintf(buff, "%s/%s_%d.weights",backup_directory,base, i);
             save_weights(net, buff);
         }
     }
 }
validate_dice()
void validate_dice (char * filename, char * weightfile)
Definition at line 47 of file dice.c.
References dice_labels, free_data(), free_list(), get_paths(), network::h, list_to_array(), load_data_old(), load_weights(), network_accuracies(), parse_network_cfg(), list::size, and network::w.
Referenced by run_dice().
 {
     network net = parse_network_cfg(filename);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     srand(time(0));
     char **labels = dice_labels;
     list *plist = get_paths("data/dice/dice.val.list");
     char **paths = (char **)list_to_array(plist);
     int m = plist->size;
     free_list(plist);
     data val = load_data_old(paths, m, 0, labels, 6, net.w, net.h);
     float *acc = network_accuracies(net, val, 2);
     printf("Validation Accuracy: %f, %d images\n", acc[0], m);
     free_data(val);
 }
Variable Documentation
dice_labels
char* dice_labels[] = {"face1","face2","face3","face4","face5","face6"}
Definition at line 5 of file dice.c.
Referenced by test_dice(), train_dice(), and validate_dice().