Darknet: detector.c File Reference
detector.c File Reference
#include "network.h"
#include "region_layer.h"
#include "cost_layer.h"
#include "utils.h"
#include "parser.h"
#include "box.h"
#include "demo.h"
#include "option_list.h"
#include "blas.h"
Functions
void train_detector (char *datacfg, char *cfgfile, char *weightfile, int *gpus, int ngpus, int clear)
static int get_coco_image_id (char *filename)
static void print_cocos (FILE *fp, char *image_path, box *boxes, float **probs, int num_boxes, int classes, int w, int h)
void print_detector_detections (FILE **fps, char *id, box *boxes, float **probs, int total, int classes, int w, int h)
void print_imagenet_detections (FILE *fp, int id, box *boxes, float **probs, int total, int classes, int w, int h)
void validate_detector_flip (char *datacfg, char *cfgfile, char *weightfile, char *outfile)
void validate_detector (char *datacfg, char *cfgfile, char *weightfile, char *outfile)
void validate_detector_recall (char *cfgfile, char *weightfile)
void test_detector (char *datacfg, char *cfgfile, char *weightfile, char *filename, float thresh, float hier_thresh, char *outfile, int fullscreen)
void run_detector (int argc, char **argv)
Variables
static int coco_ids [] = {1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,67,70,72,73,74,75,76,77,78,79,80,81,82,84,85,86,87,88,89,90}
Function Documentation
get_coco_image_id()
static int get_coco_image_id (char * filename) static
Definition at line 172 of file detector.c.
Referenced by print_cocos().
 {
     char *p = strrchr(filename, '_');
     return atoi(p+1);
 }
print_cocos()
static void print_cocos (FILE * fp, char * image_path, box * boxes, float ** probs, int num_boxes, int classes, int w, int h) static
Definition at line 178 of file detector.c.
References coco_ids, get_coco_image_id(), box::h, box::w, box::x, and box::y.
Referenced by validate_detector(), and validate_detector_flip().
 {
     int i, j;
     int image_id = get_coco_image_id(image_path);
     for(i = 0; i < num_boxes; ++i){
         float xmin = boxes[i].x - boxes[i].w/2.;
         float xmax = boxes[i].x + boxes[i].w/2.;
         float ymin = boxes[i].y - boxes[i].h/2.;
         float ymax = boxes[i].y + boxes[i].h/2.;
         if (xmin < 0) xmin = 0;
         if (ymin < 0) ymin = 0;
         if (xmax > w) xmax = w;
         if (ymax > h) ymax = h;
         float bx = xmin;
         float by = ymin;
         float bw = xmax - xmin;
         float bh = ymax - ymin;
         for(j = 0; j < classes; ++j){
             if (probs[i][j]) fprintf(fp, "{\"image_id\":%d, \"category_id\":%d, \"bbox\":[%f, %f, %f, %f], \"score\":%f},\n", image_id, coco_ids[j], bx, by, bw, bh, probs[i][j]);
         }
     }
 }
print_detector_detections()
void print_detector_detections (FILE ** fps, char * id, box * boxes, float ** probs, int total, int classes, int w, int h)
Definition at line 204 of file detector.c.
References box::h, box::w, box::x, and box::y.
Referenced by validate_detector(), and validate_detector_flip().
 {
     int i, j;
     for(i = 0; i < total; ++i){
         float xmin = boxes[i].x - boxes[i].w/2. + 1;
         float xmax = boxes[i].x + boxes[i].w/2. + 1;
         float ymin = boxes[i].y - boxes[i].h/2. + 1;
         float ymax = boxes[i].y + boxes[i].h/2. + 1;
         if (xmin < 1) xmin = 1;
         if (ymin < 1) ymin = 1;
         if (xmax > w) xmax = w;
         if (ymax > h) ymax = h;
         for(j = 0; j < classes; ++j){
             if (probs[i][j]) fprintf(fps[j], "%s %f %f %f %f %f\n", id, probs[i][j],
                     xmin, ymin, xmax, ymax);
         }
     }
 }
print_imagenet_detections()
void print_imagenet_detections (FILE * fp, int id, box * boxes, float ** probs, int total, int classes, int w, int h)
Definition at line 225 of file detector.c.
References box::h, box::w, box::x, and box::y.
Referenced by validate_detector(), and validate_detector_flip().
 {
     int i, j;
     for(i = 0; i < total; ++i){
         float xmin = boxes[i].x - boxes[i].w/2.;
         float xmax = boxes[i].x + boxes[i].w/2.;
         float ymin = boxes[i].y - boxes[i].h/2.;
         float ymax = boxes[i].y + boxes[i].h/2.;
         if (xmin < 0) xmin = 0;
         if (ymin < 0) ymin = 0;
         if (xmax > w) xmax = w;
         if (ymax > h) ymax = h;
         for(j = 0; j < classes; ++j){
             int class = j;
             if (probs[i][class]) fprintf(fp, "%d %d %f %f %f %f %f\n", id, j+1, probs[i][class],
                     xmin, ymin, xmax, ymax);
         }
     }
 }
run_detector()
void run_detector (int argc, char ** argv)
Definition at line 663 of file detector.c.
References demo(), find_arg(), find_char_arg(), find_float_arg(), find_int_arg(), get_labels(), gpu_index, option_find_int(), option_find_str(), read_data_cfg(), test_detector(), train_detector(), validate_detector(), validate_detector_flip(), and validate_detector_recall().
Referenced by main().
 {
     char *prefix = find_char_arg(argc, argv, "-prefix", 0);
     float thresh = find_float_arg(argc, argv, "-thresh", .24);
     float hier_thresh = find_float_arg(argc, argv, "-hier", .5);
     int cam_index = find_int_arg(argc, argv, "-c", 0);
     int frame_skip = find_int_arg(argc, argv, "-s", 0);
     int avg = find_int_arg(argc, argv, "-avg", 3);
     if(argc < 4){
         fprintf(stderr, "usage: %s %s [train/test/valid] [cfg] [weights (optional)]\n", argv[0], argv[1]);
         return;
     }
     char *gpu_list = find_char_arg(argc, argv, "-gpus", 0);
     char *outfile = find_char_arg(argc, argv, "-out", 0);
     int *gpus = 0;
     int gpu = 0;
     int ngpus = 0;
     if(gpu_list){
         printf("%s\n", gpu_list);
         int len = strlen(gpu_list);
         ngpus = 1;
         int i;
         for(i = 0; i < len; ++i){
             if (gpu_list[i] == ',') ++ngpus;
         }
         gpus = calloc(ngpus, sizeof(int));
         for(i = 0; i < ngpus; ++i){
             gpus[i] = atoi(gpu_list);
             gpu_list = strchr(gpu_list, ',')+1;
         }
     } else {
         gpu = gpu_index;
         gpus = &gpu;
         ngpus = 1;
     }
     int clear = find_arg(argc, argv, "-clear");
     int fullscreen = find_arg(argc, argv, "-fullscreen");
     int width = find_int_arg(argc, argv, "-w", 0);
     int height = find_int_arg(argc, argv, "-h", 0);
     int fps = find_int_arg(argc, argv, "-fps", 0);
     char *datacfg = argv[3];
     char *cfg = argv[4];
     char *weights = (argc > 5) ? argv[5] : 0;
     char *filename = (argc > 6) ? argv[6]: 0;
     if(0==strcmp(argv[2], "test")) test_detector(datacfg, cfg, weights, filename, thresh, hier_thresh, outfile, fullscreen);
     else if(0==strcmp(argv[2], "train")) train_detector(datacfg, cfg, weights, gpus, ngpus, clear);
     else if(0==strcmp(argv[2], "valid")) validate_detector(datacfg, cfg, weights, outfile);
     else if(0==strcmp(argv[2], "valid2")) validate_detector_flip(datacfg, cfg, weights, outfile);
     else if(0==strcmp(argv[2], "recall")) validate_detector_recall(cfg, weights);
     else if(0==strcmp(argv[2], "demo")) {
         list *options = read_data_cfg(datacfg);
         int classes = option_find_int(options, "classes", 20);
         char *name_list = option_find_str(options, "names", "data/names.list");
         char **names = get_labels(name_list);
         demo(cfg, weights, thresh, cam_index, filename, names, classes, frame_skip, prefix, avg, hier_thresh, width, height, fps, fullscreen);
     }
 }
test_detector()
void test_detector (char * datacfg, char * cfgfile, char * weightfile, char * filename, float thresh, float hier_thresh, char * outfile, int fullscreen)
Definition at line 591 of file detector.c.
References layer::classes, image::data, do_nms_obj(), draw_detections(), free_image(), free_ptrs(), get_labels(), get_region_boxes(), image::h, network::h, layer::h, network::layers, letterbox_image(), load_alphabet(), load_image_color(), load_weights(), network::n, layer::n, network_predict(), option_find_str(), parse_network_cfg(), read_data_cfg(), save_image(), sec(), set_batch_network(), show_image(), image::w, network::w, and layer::w.
Referenced by main(), and run_detector().
 {
     list *options = read_data_cfg(datacfg);
     char *name_list = option_find_str(options, "names", "data/names.list");
     char **names = get_labels(name_list);
     image **alphabet = load_alphabet();
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     srand(2222222);
     clock_t time;
     char buff[256];
     char *input = buff;
     int j;
     float nms=.4;
     while(1){
         if(filename){
             strncpy(input, filename, 256);
         } else {
             printf("Enter Image Path: ");
             fflush(stdout);
             input = fgets(input, 256, stdin);
             if(!input) return;
             strtok(input, "\n");
         }
         image im = load_image_color(input,0,0);
         image sized = letterbox_image(im, net.w, net.h);
         //image sized = resize_image(im, net.w, net.h);
         //image sized2 = resize_max(im, net.w);
         //image sized = crop_image(sized2, -((net.w - sized2.w)/2), -((net.h - sized2.h)/2), net.w, net.h);
         //resize_network(&net, sized.w, sized.h);
         layer l = net.layers[net.n-1];
         box *boxes = calloc(l.w*l.h*l.n, sizeof(box));
         float **probs = calloc(l.w*l.h*l.n, sizeof(float *));
         for(j = 0; j < l.w*l.h*l.n; ++j) probs[j] = calloc(l.classes + 1, sizeof(float *));
         float *X = sized.data;
         time=clock();
         network_predict(net, X);
         printf("%s: Predicted in %f seconds.\n", input, sec(clock()-time));
         get_region_boxes(l, im.w, im.h, net.w, net.h, thresh, probs, boxes, 0, 0, hier_thresh, 1);
         if (nms) do_nms_obj(boxes, probs, l.w*l.h*l.n, l.classes, nms);
         //else if (nms) do_nms_sort(boxes, probs, l.w*l.h*l.n, l.classes, nms);
         draw_detections(im, l.w*l.h*l.n, thresh, boxes, probs, names, alphabet, l.classes);
         if(outfile){
             save_image(im, outfile);
         }
         else{
             save_image(im, "predictions");
 #ifdef OPENCV
             cvNamedWindow("predictions", CV_WINDOW_NORMAL);
             if(fullscreen){
                 cvSetWindowProperty("predictions", CV_WND_PROP_FULLSCREEN, CV_WINDOW_FULLSCREEN);
             }
             show_image(im, "predictions");
             cvWaitKey(0);
             cvDestroyAllWindows();
 #endif
         }
         free_image(im);
         free_image(sized);
         free(boxes);
         free_ptrs((void **)probs, l.w*l.h*l.n);
         if (filename) break;
     }
 }
train_detector()
void train_detector (char * datacfg, char * cfgfile, char * weightfile, int * gpus, int ngpus, int clear)
Definition at line 13 of file detector.c.
References network::angle, load_args::angle, basecfg(), network::batch, load_args::classes, layer::classes, load_args::d, network::decay, DETECTION_DATA, network::exposure, load_args::exposure, free_data(), get_current_batch(), get_current_rate(), get_paths(), load_args::h, network::h, network::hue, load_args::hue, load_args::jitter, layer::jitter, network::layers, network::learning_rate, list_to_array(), load_data(), load_thread(), load_weights(), load_args::m, network::max_batches, layer::max_boxes, network::momentum, network::n, load_args::n, load_args::num_boxes, option_find_str(), parse_network_cfg(), load_args::paths, layer::random, read_data_cfg(), resize_network(), network::saturation, load_args::saturation, save_weights(), sec(), network::seen, list::size, network::subdivisions, load_args::threads, train_network(), load_args::type, load_args::w, and network::w.
Referenced by run_detector().
 {
     list *options = read_data_cfg(datacfg);
     char *train_images = option_find_str(options, "train", "data/train.list");
     char *backup_directory = option_find_str(options, "backup", "/backup/");
     srand(time(0));
     char *base = basecfg(cfgfile);
     printf("%s\n", base);
     float avg_loss = -1;
     network *nets = calloc(ngpus, sizeof(network));
     srand(time(0));
     int seed = rand();
     int i;
     for(i = 0; i < ngpus; ++i){
         srand(seed);
 #ifdef GPU
         cuda_set_device(gpus[i]);
 #endif
         nets[i] = parse_network_cfg(cfgfile);
         if(weightfile){
             load_weights(&nets[i], weightfile);
         }
         if(clear) *nets[i].seen = 0;
         nets[i].learning_rate *= ngpus;
     }
     srand(time(0));
     network net = nets[0];
     int imgs = net.batch * net.subdivisions * ngpus;
     printf("Learning Rate: %g, Momentum: %g, Decay: %g\n", net.learning_rate, net.momentum, net.decay);
     data train, buffer;
     layer l = net.layers[net.n - 1];
     int classes = l.classes;
     float jitter = l.jitter;
     list *plist = get_paths(train_images);
     //int N = plist->size;
     char **paths = (char **)list_to_array(plist);
     load_args args = {0};
     args.w = net.w;
     args.h = net.h;
     args.paths = paths;
     args.n = imgs;
     args.m = plist->size;
     args.classes = classes;
     args.jitter = jitter;
     args.num_boxes = l.max_boxes;
     args.d = &buffer;
     args.type = DETECTION_DATA;
     args.threads = 8;
     args.angle = net.angle;
     args.exposure = net.exposure;
     args.saturation = net.saturation;
     args.hue = net.hue;
     pthread_t load_thread = load_data(args);
     clock_t time;
     int count = 0;
     //while(i*imgs < N*120){
     while(get_current_batch(net) < net.max_batches){
         if(l.random && count++%10 == 0){
             printf("Resizing\n");
             int dim = (rand() % 10 + 10) * 32;
             if (get_current_batch(net)+200 > net.max_batches) dim = 608;
             //int dim = (rand() % 4 + 16) * 32;
             printf("%d\n", dim);
             args.w = dim;
             args.h = dim;
             pthread_join(load_thread, 0);
             train = buffer;
             free_data(train);
             load_thread = load_data(args);
             for(i = 0; i < ngpus; ++i){
                 resize_network(nets + i, dim, dim);
             }
             net = nets[0];
         }
         time=clock();
         pthread_join(load_thread, 0);
         train = buffer;
         load_thread = load_data(args);
         /*
         int k;
         for(k = 0; k < l.max_boxes; ++k){
             box b = float_to_box(train.y.vals[10] + 1 + k*5);
             if(!b.x) break;
             printf("loaded: %f %f %f %f\n", b.x, b.y, b.w, b.h);
         }
         */
         /*
         int zz;
         for(zz = 0; zz < train.X.cols; ++zz){
             image im = float_to_image(net.w, net.h, 3, train.X.vals[zz]);
             int k;
             for(k = 0; k < l.max_boxes; ++k){
                 box b = float_to_box(train.y.vals[zz] + k*5);
                 printf("%f %f %f %f\n", b.x, b.y, b.w, b.h);
                 draw_bbox(im, b, 1, 1,0,0);
             }
             show_image(im, "truth11");
             cvWaitKey(0);
             save_image(im, "truth11");
         }
         */
         printf("Loaded: %lf seconds\n", sec(clock()-time));
         time=clock();
         float loss = 0;
 #ifdef GPU
         if(ngpus == 1){
             loss = train_network(net, train);
         } else {
             loss = train_networks(nets, ngpus, train, 4);
         }
 #else
         loss = train_network(net, train);
 #endif
         if (avg_loss < 0) avg_loss = loss;
         avg_loss = avg_loss*.9 + loss*.1;
         i = get_current_batch(net);
         printf("%d: %f, %f avg, %f rate, %lf seconds, %d images\n", get_current_batch(net), loss, avg_loss, get_current_rate(net), sec(clock()-time), i*imgs);
         if(i%1000==0){
 #ifdef GPU
             if(ngpus != 1) sync_nets(nets, ngpus, 0);
 #endif
             char buff[256];
             sprintf(buff, "%s/%s.backup", backup_directory, base);
             save_weights(net, buff);
         }
         if(i%10000==0 || (i < 1000 && i%100 == 0)){
 #ifdef GPU
             if(ngpus != 1) sync_nets(nets, ngpus, 0);
 #endif
             char buff[256];
             sprintf(buff, "%s/%s_%d.weights", backup_directory, base, i);
             save_weights(net, buff);
         }
         free_data(train);
     }
 #ifdef GPU
     if(ngpus != 1) sync_nets(nets, ngpus, 0);
 #endif
     char buff[256];
     sprintf(buff, "%s/%s_final.weights", backup_directory, base);
     save_weights(net, buff);
 }
validate_detector()
void validate_detector (char * datacfg, char * cfgfile, char * weightfile, char * outfile)
Definition at line 383 of file detector.c.
References basecfg(), layer::classes, image::data, network::decay, do_nms_sort(), free_image(), get_labels(), get_paths(), get_region_boxes(), image::h, load_args::h, network::h, layer::h, load_args::im, network::layers, network::learning_rate, LETTERBOX_DATA, list_to_array(), load_data_in_thread(), load_weights(), network::momentum, network::n, layer::n, network_predict(), option_find_str(), parse_network_cfg(), load_args::path, print_cocos(), print_detector_detections(), print_imagenet_detections(), read_data_cfg(), read_map(), load_args::resized, set_batch_network(), list::size, load_args::type, image::w, load_args::w, network::w, and layer::w.
Referenced by run_detector().
 {
     int j;
     list *options = read_data_cfg(datacfg);
     char *valid_images = option_find_str(options, "valid", "data/train.list");
     char *name_list = option_find_str(options, "names", "data/names.list");
     char *prefix = option_find_str(options, "results", "results");
     char **names = get_labels(name_list);
     char *mapf = option_find_str(options, "map", 0);
     int *map = 0;
     if (mapf) map = read_map(mapf);
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     fprintf(stderr, "Learning Rate: %g, Momentum: %g, Decay: %g\n", net.learning_rate, net.momentum, net.decay);
     srand(time(0));
     list *plist = get_paths(valid_images);
     char **paths = (char **)list_to_array(plist);
     layer l = net.layers[net.n-1];
     int classes = l.classes;
     char buff[1024];
     char *type = option_find_str(options, "eval", "voc");
     FILE *fp = 0;
     FILE **fps = 0;
     int coco = 0;
     int imagenet = 0;
     if(0==strcmp(type, "coco")){
         if(!outfile) outfile = "coco_results";
         snprintf(buff, 1024, "%s/%s.json", prefix, outfile);
         fp = fopen(buff, "w");
         fprintf(fp, "[\n");
         coco = 1;
     } else if(0==strcmp(type, "imagenet")){
         if(!outfile) outfile = "imagenet-detection";
         snprintf(buff, 1024, "%s/%s.txt", prefix, outfile);
         fp = fopen(buff, "w");
         imagenet = 1;
         classes = 200;
     } else {
         if(!outfile) outfile = "comp4_det_test_";
         fps = calloc(classes, sizeof(FILE *));
         for(j = 0; j < classes; ++j){
             snprintf(buff, 1024, "%s/%s%s.txt", prefix, outfile, names[j]);
             fps[j] = fopen(buff, "w");
         }
     }
     box *boxes = calloc(l.w*l.h*l.n, sizeof(box));
     float **probs = calloc(l.w*l.h*l.n, sizeof(float *));
     for(j = 0; j < l.w*l.h*l.n; ++j) probs[j] = calloc(classes+1, sizeof(float *));
     int m = plist->size;
     int i=0;
     int t;
     float thresh = .005;
     float nms = .45;
     int nthreads = 4;
     image *val = calloc(nthreads, sizeof(image));
     image *val_resized = calloc(nthreads, sizeof(image));
     image *buf = calloc(nthreads, sizeof(image));
     image *buf_resized = calloc(nthreads, sizeof(image));
     pthread_t *thr = calloc(nthreads, sizeof(pthread_t));
     load_args args = {0};
     args.w = net.w;
     args.h = net.h;
     //args.type = IMAGE_DATA;
     args.type = LETTERBOX_DATA;
     for(t = 0; t < nthreads; ++t){
         args.path = paths[i+t];
         args.im = &buf[t];
         args.resized = &buf_resized[t];
         thr[t] = load_data_in_thread(args);
     }
     time_t start = time(0);
     for(i = nthreads; i < m+nthreads; i += nthreads){
         fprintf(stderr, "%d\n", i);
         for(t = 0; t < nthreads && i+t-nthreads < m; ++t){
             pthread_join(thr[t], 0);
             val[t] = buf[t];
             val_resized[t] = buf_resized[t];
         }
         for(t = 0; t < nthreads && i+t < m; ++t){
             args.path = paths[i+t];
             args.im = &buf[t];
             args.resized = &buf_resized[t];
             thr[t] = load_data_in_thread(args);
         }
         for(t = 0; t < nthreads && i+t-nthreads < m; ++t){
             char *path = paths[i+t-nthreads];
             char *id = basecfg(path);
             float *X = val_resized[t].data;
             network_predict(net, X);
             int w = val[t].w;
             int h = val[t].h;
             get_region_boxes(l, w, h, net.w, net.h, thresh, probs, boxes, 0, map, .5, 0);
             if (nms) do_nms_sort(boxes, probs, l.w*l.h*l.n, classes, nms);
             if (coco){
                 print_cocos(fp, path, boxes, probs, l.w*l.h*l.n, classes, w, h);
             } else if (imagenet){
                 print_imagenet_detections(fp, i+t-nthreads+1, boxes, probs, l.w*l.h*l.n, classes, w, h);
             } else {
                 print_detector_detections(fps, id, boxes, probs, l.w*l.h*l.n, classes, w, h);
             }
             free(id);
             free_image(val[t]);
             free_image(val_resized[t]);
         }
     }
     for(j = 0; j < classes; ++j){
         if(fps) fclose(fps[j]);
     }
     if(coco){
         fseek(fp, -2, SEEK_CUR);
         fprintf(fp, "\n]\n");
         fclose(fp);
     }
     fprintf(stderr, "Total Detection Time: %f Seconds\n", (double)(time(0) - start));
 }
validate_detector_flip()
void validate_detector_flip (char * datacfg, char * cfgfile, char * weightfile, char * outfile)
Definition at line 247 of file detector.c.
References basecfg(), network::c, layer::classes, copy_cpu(), image::data, network::decay, do_nms_sort(), flip_image(), free_image(), get_labels(), get_paths(), get_region_boxes(), image::h, load_args::h, network::h, layer::h, load_args::im, network::layers, network::learning_rate, LETTERBOX_DATA, list_to_array(), load_data_in_thread(), load_weights(), make_image(), network::momentum, network::n, layer::n, network_predict(), option_find_str(), parse_network_cfg(), load_args::path, print_cocos(), print_detector_detections(), print_imagenet_detections(), read_data_cfg(), read_map(), load_args::resized, set_batch_network(), list::size, load_args::type, image::w, load_args::w, network::w, and layer::w.
Referenced by run_detector().
 {
     int j;
     list *options = read_data_cfg(datacfg);
     char *valid_images = option_find_str(options, "valid", "data/train.list");
     char *name_list = option_find_str(options, "names", "data/names.list");
     char *prefix = option_find_str(options, "results", "results");
     char **names = get_labels(name_list);
     char *mapf = option_find_str(options, "map", 0);
     int *map = 0;
     if (mapf) map = read_map(mapf);
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 2);
     fprintf(stderr, "Learning Rate: %g, Momentum: %g, Decay: %g\n", net.learning_rate, net.momentum, net.decay);
     srand(time(0));
     list *plist = get_paths(valid_images);
     char **paths = (char **)list_to_array(plist);
     layer l = net.layers[net.n-1];
     int classes = l.classes;
     char buff[1024];
     char *type = option_find_str(options, "eval", "voc");
     FILE *fp = 0;
     FILE **fps = 0;
     int coco = 0;
     int imagenet = 0;
     if(0==strcmp(type, "coco")){
         if(!outfile) outfile = "coco_results";
         snprintf(buff, 1024, "%s/%s.json", prefix, outfile);
         fp = fopen(buff, "w");
         fprintf(fp, "[\n");
         coco = 1;
     } else if(0==strcmp(type, "imagenet")){
         if(!outfile) outfile = "imagenet-detection";
         snprintf(buff, 1024, "%s/%s.txt", prefix, outfile);
         fp = fopen(buff, "w");
         imagenet = 1;
         classes = 200;
     } else {
         if(!outfile) outfile = "comp4_det_test_";
         fps = calloc(classes, sizeof(FILE *));
         for(j = 0; j < classes; ++j){
             snprintf(buff, 1024, "%s/%s%s.txt", prefix, outfile, names[j]);
             fps[j] = fopen(buff, "w");
         }
     }
     box *boxes = calloc(l.w*l.h*l.n, sizeof(box));
     float **probs = calloc(l.w*l.h*l.n, sizeof(float *));
     for(j = 0; j < l.w*l.h*l.n; ++j) probs[j] = calloc(classes+1, sizeof(float *));
     int m = plist->size;
     int i=0;
     int t;
     float thresh = .005;
     float nms = .45;
     int nthreads = 4;
     image *val = calloc(nthreads, sizeof(image));
     image *val_resized = calloc(nthreads, sizeof(image));
     image *buf = calloc(nthreads, sizeof(image));
     image *buf_resized = calloc(nthreads, sizeof(image));
     pthread_t *thr = calloc(nthreads, sizeof(pthread_t));
     image input = make_image(net.w, net.h, net.c*2);
     load_args args = {0};
     args.w = net.w;
     args.h = net.h;
     //args.type = IMAGE_DATA;
     args.type = LETTERBOX_DATA;
     for(t = 0; t < nthreads; ++t){
         args.path = paths[i+t];
         args.im = &buf[t];
         args.resized = &buf_resized[t];
         thr[t] = load_data_in_thread(args);
     }
     time_t start = time(0);
     for(i = nthreads; i < m+nthreads; i += nthreads){
         fprintf(stderr, "%d\n", i);
         for(t = 0; t < nthreads && i+t-nthreads < m; ++t){
             pthread_join(thr[t], 0);
             val[t] = buf[t];
             val_resized[t] = buf_resized[t];
         }
         for(t = 0; t < nthreads && i+t < m; ++t){
             args.path = paths[i+t];
             args.im = &buf[t];
             args.resized = &buf_resized[t];
             thr[t] = load_data_in_thread(args);
         }
         for(t = 0; t < nthreads && i+t-nthreads < m; ++t){
             char *path = paths[i+t-nthreads];
             char *id = basecfg(path);
             copy_cpu(net.w*net.h*net.c, val_resized[t].data, 1, input.data, 1);
             flip_image(val_resized[t]);
             copy_cpu(net.w*net.h*net.c, val_resized[t].data, 1, input.data + net.w*net.h*net.c, 1);
             network_predict(net, input.data);
             int w = val[t].w;
             int h = val[t].h;
             get_region_boxes(l, w, h, net.w, net.h, thresh, probs, boxes, 0, map, .5, 0);
             if (nms) do_nms_sort(boxes, probs, l.w*l.h*l.n, classes, nms);
             if (coco){
                 print_cocos(fp, path, boxes, probs, l.w*l.h*l.n, classes, w, h);
             } else if (imagenet){
                 print_imagenet_detections(fp, i+t-nthreads+1, boxes, probs, l.w*l.h*l.n, classes, w, h);
             } else {
                 print_detector_detections(fps, id, boxes, probs, l.w*l.h*l.n, classes, w, h);
             }
             free(id);
             free_image(val[t]);
             free_image(val_resized[t]);
         }
     }
     for(j = 0; j < classes; ++j){
         if(fps) fclose(fps[j]);
     }
     if(coco){
         fseek(fp, -2, SEEK_CUR);
         fprintf(fp, "\n]\n");
         fclose(fp);
     }
     fprintf(stderr, "Total Detection Time: %f Seconds\n", (double)(time(0) - start));
 }
validate_detector_recall()
void validate_detector_recall (char * cfgfile, char * weightfile)
Definition at line 513 of file detector.c.
References basecfg(), box_iou(), layer::classes, image::data, network::decay, do_nms(), find_replace(), free_image(), get_paths(), get_region_boxes(), image::h, network::h, layer::h, box_label::h, network::layers, network::learning_rate, list_to_array(), load_image_color(), load_weights(), network::momentum, network::n, layer::n, network_predict(), parse_network_cfg(), read_boxes(), resize_image(), set_batch_network(), list::size, image::w, network::w, layer::w, box_label::w, box_label::x, and box_label::y.
Referenced by run_detector().
 {
     network net = parse_network_cfg(cfgfile);
     if(weightfile){
         load_weights(&net, weightfile);
     }
     set_batch_network(&net, 1);
     fprintf(stderr, "Learning Rate: %g, Momentum: %g, Decay: %g\n", net.learning_rate, net.momentum, net.decay);
     srand(time(0));
     list *plist = get_paths("data/voc.2007.test");
     char **paths = (char **)list_to_array(plist);
     layer l = net.layers[net.n-1];
     int classes = l.classes;
     int j, k;
     box *boxes = calloc(l.w*l.h*l.n, sizeof(box));
     float **probs = calloc(l.w*l.h*l.n, sizeof(float *));
     for(j = 0; j < l.w*l.h*l.n; ++j) probs[j] = calloc(classes+1, sizeof(float *));
     int m = plist->size;
     int i=0;
     float thresh = .001;
     float iou_thresh = .5;
     float nms = .4;
     int total = 0;
     int correct = 0;
     int proposals = 0;
     float avg_iou = 0;
     for(i = 0; i < m; ++i){
         char *path = paths[i];
         image orig = load_image_color(path, 0, 0);
         image sized = resize_image(orig, net.w, net.h);
         char *id = basecfg(path);
         network_predict(net, sized.data);
         get_region_boxes(l, sized.w, sized.h, net.w, net.h, thresh, probs, boxes, 1, 0, .5, 1);
         if (nms) do_nms(boxes, probs, l.w*l.h*l.n, 1, nms);
         char labelpath[4096];
         find_replace(path, "images", "labels", labelpath);
         find_replace(labelpath, "JPEGImages", "labels", labelpath);
         find_replace(labelpath, ".jpg", ".txt", labelpath);
         find_replace(labelpath, ".JPEG", ".txt", labelpath);
         int num_labels = 0;
         box_label *truth = read_boxes(labelpath, &num_labels);
         for(k = 0; k < l.w*l.h*l.n; ++k){
             if(probs[k][0] > thresh){
                 ++proposals;
             }
         }
         for (j = 0; j < num_labels; ++j) {
             ++total;
             box t = {truth[j].x, truth[j].y, truth[j].w, truth[j].h};
             float best_iou = 0;
             for(k = 0; k < l.w*l.h*l.n; ++k){
                 float iou = box_iou(boxes[k], t);
                 if(probs[k][0] > thresh && iou > best_iou){
                     best_iou = iou;
                 }
             }
             avg_iou += best_iou;
             if(best_iou > iou_thresh){
                 ++correct;
             }
         }
         fprintf(stderr, "%5d %5d %5d\tRPs/Img: %.2f\tIOU: %.2f%%\tRecall:%.2f%%\n", i, correct, total, (float)proposals/(i+1), avg_iou*100/total, 100.*correct/total);
         free(id);
         free_image(orig);
         free_image(sized);
     }
 }
Variable Documentation
coco_ids
int coco_ids[] = {1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,67,70,72,73,74,75,76,77,78,79,80,81,82,84,85,86,87,88,89,90} static
Definition at line 11 of file detector.c.
Referenced by print_cocos().