Darknet: gru_layer.h File Reference
gru_layer.h File Reference
#include "activations.h"
#include "layer.h"
#include "network.h"
Functions
layer make_gru_layer (int batch, int inputs, int outputs, int steps, int batch_normalize)
void forward_gru_layer (layer l, network net)
void backward_gru_layer (layer l, network net)
void update_gru_layer (layer l, int batch, float learning_rate, float momentum, float decay)
Function Documentation
backward_gru_layer()
void backward_gru_layer (layer l, network net)
Definition at line 203 of file gru_layer.c.
References layer::batch, increment_layer(), layer::input_h_layer, layer::input_r_layer, layer::input_z_layer, layer::inputs, LOGISTIC, layer::outputs, layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, layer::steps, TANH, and network::train.
Referenced by make_gru_layer().
 {
 }
forward_gru_layer()
void forward_gru_layer (layer l, network net)
Definition at line 127 of file gru_layer.c.
References activate_array(), axpy_cpu(), layer::batch, copy_cpu(), layer::delta, fill_cpu(), layer::forgot_state, forward_connected_layer(), layer::h_cpu, increment_layer(), network::input, layer::input_h_layer, layer::input_r_layer, layer::input_z_layer, layer::inputs, LOGISTIC, mul_cpu(), layer::output, layer::outputs, layer::prev_state, layer::r_cpu, layer::state, layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, layer::steps, TANH, network::train, weighted_sum_cpu(), and layer::z_cpu.
Referenced by make_gru_layer().
 {
     network s = net;
     s.train = net.train;
     int i;
     layer input_z_layer = *(l.input_z_layer);
     layer input_r_layer = *(l.input_r_layer);
     layer input_h_layer = *(l.input_h_layer);
     layer state_z_layer = *(l.state_z_layer);
     layer state_r_layer = *(l.state_r_layer);
     layer state_h_layer = *(l.state_h_layer);
     fill_cpu(l.outputs * l.batch * l.steps, 0, input_z_layer.delta, 1);
     fill_cpu(l.outputs * l.batch * l.steps, 0, input_r_layer.delta, 1);
     fill_cpu(l.outputs * l.batch * l.steps, 0, input_h_layer.delta, 1);
     fill_cpu(l.outputs * l.batch * l.steps, 0, state_z_layer.delta, 1);
     fill_cpu(l.outputs * l.batch * l.steps, 0, state_r_layer.delta, 1);
     fill_cpu(l.outputs * l.batch * l.steps, 0, state_h_layer.delta, 1);
     if(net.train) {
         fill_cpu(l.outputs * l.batch * l.steps, 0, l.delta, 1);
         copy_cpu(l.outputs*l.batch, l.state, 1, l.prev_state, 1);
     }
     for (i = 0; i < l.steps; ++i) {
         s.input = l.state;
         forward_connected_layer(state_z_layer, s);
         forward_connected_layer(state_r_layer, s);
         s.input = net.input;
         forward_connected_layer(input_z_layer, s);
         forward_connected_layer(input_r_layer, s);
         forward_connected_layer(input_h_layer, s);
         copy_cpu(l.outputs*l.batch, input_z_layer.output, 1, l.z_cpu, 1);
         axpy_cpu(l.outputs*l.batch, 1, state_z_layer.output, 1, l.z_cpu, 1);
         copy_cpu(l.outputs*l.batch, input_r_layer.output, 1, l.r_cpu, 1);
         axpy_cpu(l.outputs*l.batch, 1, state_r_layer.output, 1, l.r_cpu, 1);
         activate_array(l.z_cpu, l.outputs*l.batch, LOGISTIC);
         activate_array(l.r_cpu, l.outputs*l.batch, LOGISTIC);
         copy_cpu(l.outputs*l.batch, l.state, 1, l.forgot_state, 1);
         mul_cpu(l.outputs*l.batch, l.r_cpu, 1, l.forgot_state, 1);
         s.input = l.forgot_state;
         forward_connected_layer(state_h_layer, s);
         copy_cpu(l.outputs*l.batch, input_h_layer.output, 1, l.h_cpu, 1);
         axpy_cpu(l.outputs*l.batch, 1, state_h_layer.output, 1, l.h_cpu, 1);
         #ifdef USET
         activate_array(l.h_cpu, l.outputs*l.batch, TANH);
         #else
         activate_array(l.h_cpu, l.outputs*l.batch, LOGISTIC);
         #endif
         weighted_sum_cpu(l.state, l.h_cpu, l.z_cpu, l.outputs*l.batch, l.output);
         copy_cpu(l.outputs*l.batch, l.output, 1, l.state, 1);
         net.input += l.inputs*l.batch;
         l.output += l.outputs*l.batch;
         increment_layer(&input_z_layer, 1);
         increment_layer(&input_r_layer, 1);
         increment_layer(&input_h_layer, 1);
         increment_layer(&state_z_layer, 1);
         increment_layer(&state_r_layer, 1);
         increment_layer(&state_h_layer, 1);
     }
 }
make_gru_layer()
layer make_gru_layer (int batch, int inputs, int outputs, int steps, int batch_normalize)
Definition at line 29 of file gru_layer.c.
References layer::backward, layer::backward_gpu, backward_gru_layer(), layer::batch, layer::batch_normalize, layer::delta, layer::forgot_delta, layer::forgot_state, layer::forward, layer::forward_gpu, forward_gru_layer(), GRU, layer::h_cpu, layer::input_h_layer, layer::input_r_layer, layer::input_z_layer, layer::inputs, LINEAR, make_connected_layer(), layer::out_c, layer::out_h, layer::out_w, layer::output, layer::outputs, layer::prev_state, layer::r_cpu, layer::state, layer::state_h_layer, layer::state_r_layer, layer::state_z_layer, layer::steps, layer::type, layer::update, layer::update_gpu, update_gru_layer(), and layer::z_cpu.
Referenced by parse_gru().
 {
     fprintf(stderr, "GRU Layer: %d inputs, %d outputs\n", inputs, outputs);
     batch = batch / steps;
     layer l = {0};
     l.batch = batch;
     l.type = GRU;
     l.steps = steps;
     l.inputs = inputs;
     l.input_z_layer = malloc(sizeof(layer));
     fprintf(stderr, "\t\t");
     *(l.input_z_layer) = make_connected_layer(batch*steps, inputs, outputs, LINEAR, batch_normalize);
     l.input_z_layer->batch = batch;
     l.state_z_layer = malloc(sizeof(layer));
     fprintf(stderr, "\t\t");
     *(l.state_z_layer) = make_connected_layer(batch*steps, outputs, outputs, LINEAR, batch_normalize);
     l.state_z_layer->batch = batch;
     l.input_r_layer = malloc(sizeof(layer));
     fprintf(stderr, "\t\t");
     *(l.input_r_layer) = make_connected_layer(batch*steps, inputs, outputs, LINEAR, batch_normalize);
     l.input_r_layer->batch = batch;
     l.state_r_layer = malloc(sizeof(layer));
     fprintf(stderr, "\t\t");
     *(l.state_r_layer) = make_connected_layer(batch*steps, outputs, outputs, LINEAR, batch_normalize);
     l.state_r_layer->batch = batch;
     l.input_h_layer = malloc(sizeof(layer));
     fprintf(stderr, "\t\t");
     *(l.input_h_layer) = make_connected_layer(batch*steps, inputs, outputs, LINEAR, batch_normalize);
     l.input_h_layer->batch = batch;
     l.state_h_layer = malloc(sizeof(layer));
     fprintf(stderr, "\t\t");
     *(l.state_h_layer) = make_connected_layer(batch*steps, outputs, outputs, LINEAR, batch_normalize);
     l.state_h_layer->batch = batch;
 #ifdef CUDNN
         cudnnSetTensor4dDescriptor(l.input_z_layer->dstTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, batch, l.input_z_layer->out_c, l.input_z_layer->out_h, l.input_z_layer->out_w);
         cudnnSetTensor4dDescriptor(l.input_h_layer->dstTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, batch, l.input_h_layer->out_c, l.input_h_layer->out_h, l.input_h_layer->out_w);
         cudnnSetTensor4dDescriptor(l.input_r_layer->dstTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, batch, l.input_r_layer->out_c, l.input_r_layer->out_h, l.input_r_layer->out_w);
         cudnnSetTensor4dDescriptor(l.state_z_layer->dstTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, batch, l.state_z_layer->out_c, l.state_z_layer->out_h, l.state_z_layer->out_w);
         cudnnSetTensor4dDescriptor(l.state_h_layer->dstTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, batch, l.state_h_layer->out_c, l.state_h_layer->out_h, l.state_h_layer->out_w);
         cudnnSetTensor4dDescriptor(l.state_r_layer->dstTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_FLOAT, batch, l.state_r_layer->out_c, l.state_r_layer->out_h, l.state_r_layer->out_w);
 #endif
     l.batch_normalize = batch_normalize;
     l.outputs = outputs;
     l.output = calloc(outputs*batch*steps, sizeof(float));
     l.delta = calloc(outputs*batch*steps, sizeof(float));
     l.state = calloc(outputs*batch, sizeof(float));
     l.prev_state = calloc(outputs*batch, sizeof(float));
     l.forgot_state = calloc(outputs*batch, sizeof(float));
     l.forgot_delta = calloc(outputs*batch, sizeof(float));
     l.r_cpu = calloc(outputs*batch, sizeof(float));
     l.z_cpu = calloc(outputs*batch, sizeof(float));
     l.h_cpu = calloc(outputs*batch, sizeof(float));
     l.forward = forward_gru_layer;
     l.backward = backward_gru_layer;
     l.update = update_gru_layer;
 #ifdef GPU
     l.forward_gpu = forward_gru_layer_gpu;
     l.backward_gpu = backward_gru_layer_gpu;
     l.update_gpu = update_gru_layer_gpu;
     l.forgot_state_gpu = cuda_make_array(l.output, batch*outputs);
     l.forgot_delta_gpu = cuda_make_array(l.output, batch*outputs);
     l.prev_state_gpu = cuda_make_array(l.output, batch*outputs);
     l.state_gpu = cuda_make_array(l.output, batch*outputs);
     l.output_gpu = cuda_make_array(l.output, batch*outputs*steps);
     l.delta_gpu = cuda_make_array(l.delta, batch*outputs*steps);
     l.r_gpu = cuda_make_array(l.output_gpu, batch*outputs);
     l.z_gpu = cuda_make_array(l.output_gpu, batch*outputs);
     l.h_gpu = cuda_make_array(l.output_gpu, batch*outputs);
 #endif
     return l;
 }
update_gru_layer()
void update_gru_layer (layer l, int batch, float learning_rate, float momentum, float decay)
Definition at line 120 of file gru_layer.c.
References layer::input_layer, layer::output_layer, layer::self_layer, and update_connected_layer().
Referenced by make_gru_layer().
 {
     update_connected_layer(*(l.input_layer), batch, learning_rate, momentum, decay);
     update_connected_layer(*(l.self_layer), batch, learning_rate, momentum, decay);
     update_connected_layer(*(l.output_layer), batch, learning_rate, momentum, decay);
 }